### ISSUE TITLE
Bots do not change the fuelrods on exosuits

### ISSUE THREAD

**Issue by itchyOwl** [FakeFishGames/Barotrauma#10917]
The ticket is based on the comment on #10273.

> Bots do not change the batteries on exosuits, which prevents all movement when empty now as opposed to a huge slowdown, bots have no text callout for this if empty, and even if having spare batteries do not attempt to change them stranding the AI silently (and given the speed of these suits) possibly off-camera.

I think the bots should be able to switch the batteries, if they have any on their inventory. Also would add a new line of dialogue when they are out of batteries (could possibly be used elsewhere too).

**Comment by Regalis11** [comment]
Related: https://github.com/Regalis11/Barotrauma/issues/13131

**Comment by Regalis11** [comment]
Related conversation: https://github.com/FakeFishGames/Barotrauma/discussions/13867

**Comment by Rokvach** [comment]
Tested, working correctly. Can be merged and closed.
