### ISSUE TITLE
Enter Password prompt appears twice (once to join, again once in lobby). Clicking cancel disconnects the player from the lobby

### ISSUE THREAD

**Issue by Wheatley1001** [FakeFishGames/Barotrauma#11071]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

Title is description. Not entirely sure what causes this issue but it has happened to several players roughly four times in total. Image below for visual reference.

![image](https://user-images.githubusercontent.com/105495756/215242797-2c767d7d-9c95-40e3-865a-8611eff171ef.png)

### Bug prevalence

Happens regularly

### Version

Faction/endgame test branch

### Which operating system did you encounter this bug on?

Windows

**Comment by Vykn** [comment]
Just to add: this isn't factions specific. I personally experience this in the majority of lobbies that I connect to.
It's possible that this is related to the connection to the server - I mostly connect to EU/NA servers from Australia and get roughly 300-350 ping. I've not played on enough lower ping servers to confirm any greater or lesser frequency, though, so this is speculation.

**Comment by NilanthAnimosus** [comment]
Tested against 1.0.16.0

Unable to reliably reproduce, but potentially may help to reproduce it occasionally (around once per 4-8 connects):

1. Debug build dedicated server with password active
2. give server commands such as simulatedloss 0.1 and simulatedlatency 0.35 0.05 (Or other numbers, this is what I used)
3. run multiple clients - about 2-4 for faster attempts and disconnects, I had some disappear (Debug assert for 
4. Copy and paste the password into the join box when connecting via localhost
5. if issue doesn't appear, disconnect and try to connect as fast as possible. If it occurs its usually within 1/10th to 3/10th's of a second of the first password box closing.


https://github.com/Regalis11/Barotrauma/assets/29177976/a0a7b78b-bb9c-4099-9e93-0de2ec3e393c

**Comment by juanjp600** [comment]
Should be fixed in https://github.com/Regalis11/Barotrauma-development/commit/38e65e96fc0a61c32729deb4a002e88c9ae82bc1

**Comment by NilanthAnimosus** [comment]
Tested against fix/ros-fixes-march07 commit https://github.com/Regalis11/Barotrauma-development/commit/c6e903d786366fd1cfa2c4d199e60ae4fcd5a24d, no issues found, closing.

fix appears to work, could no longer replicate and have not seen this in any testing, if it does show up again the ticket can always be reopened but this appears to be resolved for the next update.
