### ISSUE TITLE
Harpoons breaking ragdolls

### ISSUE THREAD

**Issue by ubertpendragon** [FakeFishGames/Barotrauma#11133]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

Sticking a harpoon into a Mudraptor broke its ragdoll

https://user-images.githubusercontent.com/73229309/216417917-27d460fa-0f5c-4b8d-a3fb-17ac46c57cfa.mp4

https://user-images.githubusercontent.com/73229309/216419110-54aebe30-8e08-4a42-9864-9543a6e6eb20.mp4

### Reproduction steps

Load up an abandoned outpost and start blasting harpoons at Mudraptors.
The harpoon must stick to the fleshy parts

### Bug prevalence

Happens every now and then

### Version

Faction/endgame test branch

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment]
Potentially addressed in https://github.com/FakeFishGames/Barotrauma-development/commit/7c4255b8db864ace035157d664eae64480bf601c?

**Comment by Rokvach** [comment]
Tested, working correctly. Can be merged and closed.

**Comment by itchyOwl** [comment]
Closing the ticket, as it's potentially fixed. Let's reopen, if it's not.
