### ISSUE TITLE
Affliction Overrides only working when applied in specific order

### ISSUE THREAD

**Issue by UnhappyWithMyUsername** [FakeFishGames/Barotrauma#11427]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [X] My issue happened while using mods.

### What happened?

When creating a mod that overrides afflictions from a different mod, the original mod where the afflictions are from can't be enabled if the overriding mod is enabled first as it throws "duplicate affliction" errors.
So you have to enable the original mod that doesn't contain affliction overrides first and then you can enable the mod that overrides those afflictions. This also doesn't allow to enable both mods simultaneously unless saved in a mod list. I know this isn't really that big of a deal, but I can already see the complains in the comments when I push this update to the workshop version. People will constantly report these errors as they refuse to read descriptions or help threads.

In this case I added the waste infection affliction + all of the items and particles required for it to work from Barotraumatic Creature Pack into DynamicEuropa and set them to override. If I have DynamicEuropa enabled, I can't enable the Barotraumatic Creature Pack so I have to disable DynamicEuropa first, hit apply, then add the Barotraumatic Creature Pack first, hit apply again or else it won't work, and then I can add DynamicEuropa without issues. Saving and loading it as a mod list while both mods are enabled seems to work fine.

**EDIT:** _Restarting the game does sometimes also throw the error if both mods are enabled and disables the original mod. Also sometimes happens when trying to load it via mod list._

Here are some screenshots.
Error when trying to enable Barotraumatic Creature Pack due to affliction being initialised by DynamicEuropa overrides first:
![Affliction Error](https://user-images.githubusercontent.com/74098498/222433939-2fc636b4-da71-4131-b0a4-a6989dc4ab52.png)

Works fine if Barotraumatic Creature Pack was enabled (and applied) first, before enabling DynamicEuropa:
![Screenshot 2023-03-02 133111](https://user-images.githubusercontent.com/74098498/222435068-a1aacd70-c85e-4349-98f7-a9a49f5be250.png)

### Reproduction steps

1. Create a mod with afflictions from a different mod and set those to override.
2. Try to either enable both mods at the same time or the overriding one first and then the original affliction mod.
3. Error.

Alternatively:
1. Download "DynamicEuropa", "Barotraumatic" and "Barotraumatic Creature Pack"
2. Try to enable all at the same time or "DynamicEuropa" first and then "Barotraumatic" + "Barotraumatic Creature Pack".
3. Error.

### Bug prevalence

Happens every time I play

### Version

Faction/endgame test branch

### -

Actually happens in every game version.

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment]
Thank you for the report!

I wouldn't really consider this a bug. In order to override some existing content, that content needs to exist (i.e. the load order needs to be correct, loading the base content before the mods that override them).

While it might be possible to try to automatically adjust the load order based on the overrides, that seems like a potentially huge can of worms: for example, what'd happen if there's multiple mods that override the content? What if there are actual duplicate identifiers in the override hierarchy?

I think we could consider adding a clearer error message (maybe in message box instead of the debug console) that makes it easier to figure out what's causing these errors and to adjust the load order accordingly though.

**Comment by UnhappyWithMyUsername** [comment]
Yes that sounds good!
I think a message explaining that the load order needs to be adjusted might be a good idea and may spare users some time trying to figure it out what's going on and then reporting it as a bug on the mod page.

**Comment by Regalis11** [comment]
Addressed in https://github.com/FakeFishGames/Barotrauma-development/commit/e73c37a3141a3752b6051c4ae1caaf0f5f407975 by making the error message more descriptive (mentioning which content packages the conflicting afflictions are in, an advising the user the adjust the mod load order).
