### ISSUE TITLE
Wrecks with missing hulls/drones can spawn in walls

### ISSUE THREAD

**Issue by PanmanS** [FakeFishGames/Barotrauma#11486]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [X] My issue happened while using mods.

### What happened?

First and fore-most - this issue was reported earlier and I've seen report but couldn't find it again, so I decided to post it again!

Main problem: Wreck which has empty/non-hulled space can spawn in way that this part will be embeded into wall! Same goes for wrecks with drones (they spawn in wall)!

![image](https://user-images.githubusercontent.com/42521948/224566936-f77ed430-44c4-4599-b672-1c7688405242.png)
![image](https://user-images.githubusercontent.com/42521948/224567184-dc7eee9f-7600-461f-9640-5479a74b518c.png)

### Reproduction steps

1. use this wreck
[dugong.zip](https://github.com/Regalis11/Barotrauma/files/10951768/dugong.zip)
2. go in level editor
3. select any suitable small biome like europan ridge
5. set wreck's spawnrate to something like 10-20 per level to maximize chances of this thing appearing (otherwise there is no real reproduce since it is pure luck based)
6. enjoy the view of wreck stuck between small caverns

### Bug prevalence

Happens regularly

### Version

0.21.6.0

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment]
Thank you for the report!

Does this cause some kind of issues (is there some reason you'd need to be able to reach those "non-hulled" parts)? Imo it actually looks better that the sub is partially inside the wall like this, instead of balancing on a single point touching the wall.

**Comment by PanmanS** [comment]
> Thank you for the report!
> 
> Does this cause some kind of issues (is there some reason you'd need to be able to reach those "non-hulled" parts)? Imo it actually looks better that the sub is partially inside the wall like this, instead of balancing on a single point touching the wall.

well it all looks cool until you have dugong that is half in ice


in my mod, new wrecks for barotrauma, there is dugong version (7 iirc) that has breached part unhulled for lighting and boyancy reasons removed, but armor still has a hull and that will cause armor spawn in wall with all of it's loot forever in wall

or same sub i've sent above has an issue of drone (second part of it), spawning inside wall, again making loot area unreachable which if i had there logbook, would soft lock game

**Comment by ubertpendragon** [comment]
Note that since hulls take priority over level walls and actually allow you to move inside, it's possible considering allowing wrecks to spawn partly encased in walls.

![image](https://user-images.githubusercontent.com/73229309/229161335-331cf8ec-78cd-4c0e-90fe-e3e954e52625.png)

The problem is with the unhulled parts

**Comment by Rokvach** [comment]
This (PR) seems to have caused quite a few issues, wrecks and beacon stations spawning inside walls or not spawning at all.

I wrote a separate ticket for the inside wall spawning, can be closed if not seen necessary. 
[Wreck spawned inside a wall](https://github.com/Regalis11/Barotrauma/issues/13263)

Info on wrecks not spawning, its very common so easiet might be to just load up beacon missions on multiplayer mission mode. 

![image](https://github.com/Regalis11/Barotrauma/assets/7299826/4cae0056-6d1a-43e0-b52b-bf9bf97f6dbd)
![image](https://github.com/Regalis11/Barotrauma/assets/7299826/cd3c01f1-b989-435c-9b93-cba9a8ec4409)

Also might be related but I encountered a end beacon station on beacon mission mode

![image](https://github.com/Regalis11/Barotrauma/assets/7299826/1065c412-2461-40ad-901e-0d04fc90073e)
![image](https://github.com/Regalis11/Barotrauma/assets/7299826/280291ac-8857-4ce7-bbb4-301ef7c9c9fb)

**Comment by ubertpendragon** [comment]
![image](https://github.com/Regalis11/Barotrauma/assets/73229309/40e1d57a-165b-40b5-b11e-6c30cca6c82e)
