### ISSUE TITLE
High inventory scale causes overlap when opening another human's inventory

### ISSUE THREAD

**Issue by demiurgeQuantified** [FakeFishGames/Barotrauma#11482]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

When using a high inventory scale setting, opening another human's inventory causes the two inventories to overlap, making it difficult to confiscate items or arrest prisoners. The issue is much worse when using a higher HUD scale, as this moves the target inventory to make room for the larger chat menu. Especially frustrating is that though the target's inventory renders on top, all mouse input on overlapping areas goes through to the player's inventory.
At 125% inventory scale:
![image](https://user-images.githubusercontent.com/8355611/224465193-e26687ab-4932-46f6-bf48-560664effda7.png)
At 125% inventory and hud scale:
![image](https://user-images.githubusercontent.com/8355611/224465300-6ea63019-7407-4980-93d9-638c9c27160f.png)

A possible solution would be to move one of the inventories above the other. Another would be to hide the chat menu during this situation: the nature of the issue is that at this scale, especially when HUD scale is increased too, there simply isn't enough horizontal space for the chat menu and both inventories.

### Reproduction steps

1.This issue happens to me at 1080p - it's possible that it might not happen at all resolutions, especially those with wider aspect ratios
2. Start any gamemode, with a bot for ease of testing
3. Set your inventory scale to a high setting, or combine higher hud and inventory scales
4. Grab the bot, and notice the overlap between your inventories

### Bug prevalence

Happens every time I play

### Version

Faction/endgame test branch

### Which operating system did you encounter this bug on?

Windows

**Comment by itchyOwl** [comment]
A simple solution would be to limit the inventory scale on smaller resolutions.
