### ISSUE TITLE
Settings UI: mod thumbnail/icon disappears

### ISSUE THREAD

**Issue by kagalaxy** [FakeFishGames/Barotrauma#11510]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

While I was view details of a mod then I pressed a button on the top to the tab called "INSTALLED MODS" in Mods. The mod's thumbnail (or icon preferably) has dissapeared. It also caused an "Apply" button at the bottom to be active again. This bug wasn't for a specific mod it works on ANY MOD with ANY VERSION. After also pressing an apply button nothing much was happening.
![001](https://user-images.githubusercontent.com/98905327/225017228-068fda6f-b33c-4f91-a528-eb735a431f7c.jpg)

### Reproduction steps

1. In the main menu, go to the mods.
2. Have atleast any mod installed which has it's own icon present later on.
3. Press right mouse button on the mod at the modlist and select "View details".
4. After more details appearing press upper tab in this window called "INSTALLED MODS".

### Bug prevalence

Happens everytime

### Version

v1.0.7.0

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment]
Fixed in https://github.com/FakeFishGames/Barotrauma-development/commit/9f9f9830f3bc1ede11052fcc1441e4c4f32ea082
