### ISSUE TITLE
Constant Client Freezing - Unplayable

### ISSUE THREAD

**Issue by HotRossBuns** [FakeFishGames/Barotrauma#11523]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

Constant Client Freezing - Main Menu Relentless Issues.
I can boot the title up to the main menu. After waiting approximately 1 minute or so, the client will freeze and become entirely unresponsive.

Trying to Choose the majority of the options on the main menu before the 1 minute mark will cause the client to freeze in the same manor.

*Edit* After testing again, I managed to get a new game to start, spamming through the options as quickly as possible, and was able to get a game started. Then, after 15 seconds of being in a station, the game froze.
Looking to see if I got any new crash logs from this, nothing, unfortunately.

Having the Task Manager open, I can't see any odd behavior, It should be noted that Barotrauma is not listed as "Not Responding" as far as my OS is concerned, but it remains locked up and frozen all the same.

Haven't had any issues like this before, I have no mods enabled/installed. Other than very few custom subs I myself have made via the Sub Editor, Save files, Player profile etc, I don't believe there are any custom files or additions I have made.

I have reinstalled the game and have the same issues, All of the server logs I have available are from last year, Since I can't even get into a game, the in game logs are seemingly useless in this instance.

The in game console says nothing out of the usual.

I don't seem to be getting a certain type of crash/report or anything of that nature, I will happily post such a log if I can be directed to its approximate location.

My system specs are the following:

Windows 10
Intel(R) Core(TM) i7-9700K CPU @ 3.60GHz
16 Gigs of Ram
Nividia 1660 Ti

Video of the issue: https://www.youtube.com/watch?v=TF8kohSCyII&ab_channel=HotRossBuns

### Reproduction steps

1. Launch Barotrauma through Steam
2. Wait 60 seconds for the game to freeze

### Bug prevalence

Happens every time I play

### Version

Other

### -

as far back as build v0.17.12.0

### Which operating system did you encounter this bug on?

Windows

### Relevant error messages and crash reports

```shell
I have reinstalled the game and have the same issues, All of the server logs I have available are from last year, Since I can't even get into a game, the in game logs are seemingly useless in this instance.

The in game console says nothing out of the usual.

I don't seem to be getting a certain type of crash/report or anything of that nature, I will happily post such a log if I can be directed to its approximate location.
```

**Comment by HotRossBuns** [comment]
Found a Band-Aid solution, by myself, of course. But I am far from the only person with this problem: 
https://www.reddit.com/r/Barotrauma/comments/zgykf4/game_randomly_started_freezing/

**Comment by Regalis11** [comment]
Thank you for the report!

We still haven't been able to reproduce diagnose the issue at our end, but there seems to be a valuable clue in that video you posted: it looks like the game's frozen until the blue changelog notification pops up at the top-right corner of the screen. My guess would be that downloading that data changelog data from the server is taking a long time for some reason and causing the game to become unresponsive. I'll do some more debugging to diagnose this further, and hopefully we can get this issue sorted out soon. Sorry for the inconvenience!

**Comment by HotRossBuns** [comment]
**Thank you for very much for saying so.** It took 2 years of waiting to get so much as an acknowledgement as to my suffering, Its a shame it came after all this frustration, but I sincerely thank you for the gesture, here are the other posts indicating the same exact problem, though I fear there is little you will be able to learn additionally. 

However, I have further information you will take interest in: https://www.youtube.com/watch?v=fnJ92EkE0LM&ab_channel=HotRossBuns

I believe the freeze occurs regardless of where you are in the game, about 60 seconds in.   

[https://steamcommunity.com/app/602960/discussions/1/3363650131513392350/](steam://openurl/https://steamcommunity.com/app/602960/discussions/1/3363650131513392350/)

[https://steamcommunity.com/app/602960/discussions/1/3720566578373164927/](steam://openurl/https://steamcommunity.com/app/602960/discussions/1/3720566578373164927/)

[https://steamcommunity.com/app/602960/discussions/1/3274689286956551047/](steam://openurl/https://steamcommunity.com/app/602960/discussions/1/3274689286956551047/)

[https://steamcommunity.com/app/602960/discussions/1/2845669419702172678/](steam://openurl/https://steamcommunity.com/app/602960/discussions/1/2845669419702172678/)

[https://steamcommunity.com/app/602960/discussions/1/6006138415312613425/](steam://openurl/https://steamcommunity.com/app/602960/discussions/1/6006138415312613425/)

[https://steamcommunity.com/app/602960/discussions/1/3423313148358545118/](steam://openurl/https://steamcommunity.com/app/602960/discussions/1/3423313148358545118/)

**Comment by Zipliks** [comment]
Same problem, but after ~2 minutes of `freeze and become entirely unresponsive.` the game "unfreezes" and continues to work normally.
This only happens at startup after ~30 seconds.

Windows 22H2 19045.2006
Intel(R) Core(TM) i7-5820K CPU @ 3.30GHz
16.0 GB RAM
GTX 1080
Both the game and system are on SSD

**Comment by Regalis11** [comment]
@Zipliks thank you for the information! Have you tried the workaround I mentioned above (disabling the remote content in the main menu)? If you could give that a test and let us know whether it helps or not, it'd help us a lot in figuring out whether we're on the right track when it comes to diagnosing and fixing the issue.

**Comment by Zipliks** [comment]
@Regalis11, I assume the only config is `config_player.xml`. If so, it didn't help, unfortunately.
The game still freezes.

But it seems to freeze for a shorter time now, I can record a video demo with and without `remoteContentUrl=""`.
The animated background is quite helpful to determine the state of the game.

**Comment by Zipliks** [comment]
> @Regalis11, I assume the only config is `config_player.xml`. If so, it didn't help, unfortunately. The game still freezes.
> 
> But it seems to freeze for a shorter time now, I can record a video demo with and without `remoteContentUrl=""`. The animated background is quite helpful to determine the state of the game.

My current [config_player.txt](https://github.com/Regalis11/Barotrauma/files/11870293/config_player.txt)
The game freezes at the moment these 3 panels appear on the screen: 
![image](https://github.com/Regalis11/Barotrauma/assets/4831847/a2bfb96a-6db3-48d8-a755-d8252a964d02)

**Comment by NilanthAnimosus** [comment]
Your config contains this line:
remotemainmenucontenturl="https://www.barotraumagame.com/gamedata/"

to try to see what happens change the line so the link is removed like so:
remotemainmenucontenturl=""

Looking at the code, it should have been the above line, and not remoteContentUrl="" being added.
Not sure if you edited the correct line, when it works you should see the blue boxes not appear at all I think.

**Comment by Regalis11** [comment]
Thank you for the help in trying to disagnose this! Could you please try the following config file? It sets remotemainmenucontenturl to empty, and should make the changelogs and unstable notification disappear from the main menu. And hopefully get rid of the freeze, if those are what is causing the freeze.

[config_player.txt](https://github.com/Regalis11/Barotrauma/files/11881068/config_player.txt)

**Comment by Zipliks** [comment]
@Regalis11 I've been waiting for ~5 minutes, no freezes. `Host server` option was disabled (if it was unintended). I guess it worked 🤔

**Comment by NilanthAnimosus** [comment]
Thanks for helping and trying this out!

Just a note though, but that config files extension ends in .txt instead of .xml (github doesn't let us upload most file types)

From when I tried this myself, the changelogs shouldn't appear on the screen, but it is also peculiar its only 5 seconds now?, so just making sure you correctly replaced the config file here by renaming or copying the contents over?

If you dragged and dropped into the folder without the extension rename - in in case it wouldn't work.

It also should not effect the host server button either way normally (that is more up to steam being connected to the steam servers, which today was tuesday when they often in my experience momentary go offline in some regions).

Here I've zipped up the same config file but as an XML (if you want to drag and drop the contents of this zip into your game and you previously did not copy the contents of the text file or rename the extension):
[config_player.zip](https://github.com/Regalis11/Barotrauma/files/11887527/config_player.zip)

**Comment by Zipliks** [comment]
Ok, now with a fresh game installation:

Test 1:
Original `config_player.xml` (SHA1: `449b295b0437105f6562f7a6c3941d7288ed2253`)
Changelogs appeared after: ~39 seconds.
Time before the game freezes: ~3 seconds
Game freezed for ~29 seconds.

Test 2:
Archived `config_player.xml` (SHA1: `33c46af05314eba878f4a87b72e4dc162593e3bd`)
Changelogs appeared after ~40 seconds.
Time before the game freezes: ~4 seconds
Game freezed for: ~43 seconds.

Test 3:
VPN is On (I've randomly found it somehow helps with the game freezes)
Original `config_player.xml` (SHA1: `449b295b0437105f6562f7a6c3941d7288ed2253`)
Changelogs appeared after ~1 second.
Time before the game freezes: ~1 minute.
Game **did not** freeze.

Test 4:
VPN is On (I've randomly found it somehow helps with the game freezes)
Archived `config_player.xml` (SHA1: `33c46af05314eba878f4a87b72e4dc162593e3bd`)
Changelogs appeared after 1 second.
Time before the game freezes: ~2 seconds (too fast to determine)
Game freezed for: ~3 seconds


Specs:
Operating System: Windows 10 Pro x64 (2009 build 19045)
Motherboard: ASUSTeK COMPUTER INC. SABERTOOTH X99
CPU: Intel(R) Core(TM) i7-5820K CPU @ 3.30GHz
GPU: NVIDIA GeForce GTX 1080, 8 GB
Display: BenQ GL2460BenQ EX2510S @165 (1920 x 1080)
RAM: 16 GB
Storages:
C: 223 GB [KINGSTON SV300S37A240G]
D: 1863 GB [ST2000DX001-1NS164]
E: 465 GB [Samsung SSD 970 EVO Plus 500GB]
H: 223 GB [PH6-CE240-L1] SSD
USB: connected – 12 (media storages – 0)
PC works: 0 days, 0 hours, 44 minutes, 11 seconds
Download speed: ≈ 524.12 Mbps
average ping ≈ 18 ms

Image of config file location and extension:
![image](https://github.com/Regalis11/Barotrauma/assets/4831847/bc4aa2ae-9001-4313-ba52-723830865ebd)

`Host server` button was not affected at all.
Asked my friends to do the same: changelog blue boxes appear with both the original and modified configs.

If there's anything else I could do to help, I'd love to.
