### ISSUE TITLE
Outpost Doctor can't heal "twin"(?) bot in single player campaign

### ISSUE THREAD

**Issue by Greggho** [FakeFishGames/Barotrauma#11654]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

Somehow I got two NPCs hirelings that share the same internal ID or something, this causes issues with the Outpost Doctor (only issue I've seen so far)

### Reproduction steps

See attached save - try to heal PC 'Randi "Rude"' via Outpost Doctor, you'll see the wacky behavior

[Boatmurder.zip](https://github.com/Regalis11/Barotrauma/files/11068250/Boatmurder.zip)

Issue description/history:
Somehow I have two submariners that have the same name/appearance (internal ID/seed?). These are distinguished by nicknames, both first names are "Randi".
I don't recall which outpost I hired them but could have been the same outpost, very likely in different turns of the game - you can see so because one guy has a lot less experience. This is Randy "Rude" (because he's rude, yes, I'm a genius, sue me)

Said newer guy seems to share the Outpost Doctor UI for the older "twin" (Randi "Quickshot"):
Whenever I try to treat the newer guy "Rude", he shows the afflictions of his twin.
If I treat new guy "Rude", his twin actually gets treated and "Rude" still has his afflictions, and now don't even show the treatment buttons over him (as if he were his older twin lol). Seems like the price is equivalent to his afflictions though - I might be wrong...
If I treat the older twin, "Quickshot", only he gets treated, the younger twin, "Rude" gets zilch
If I treat EVERYONE, (I'm fairly certain) I **PAY** for "Rude"  treatment prices as well, but his afflictions don't go away and the "Treat All" button greys out (he's usually really banged up because of this feedback loop)

Save in an outpost attached, should be easy to reproduce.

### Bug prevalence

Happens every time I play

### Version

v1.0.8.0

### Which operating system did you encounter this bug on?

Windows

### Relevant error messages and crash reports

```shell
other than the weird behavior, no error/crash messages
```

**Comment by itchyOwl** [comment]
Happens probably because the characters are identified by a hash based on the name and the appearance info. Not sure, but I don't think we should create characters with the same names. Should also do something to prevent twins, e.g. check if another character with the same hash is found, and if so, regenerate or modify the appearance/name. However, we can't force this on player characters -> might need to do something else to identify the characters, like a combination of Info.GetIdentifier() and Character.ID (non-persistent). Or just generate a truly unique and persisten id for each character info.

would be better to use actually unique (and persistent) identifiers for the characters.

**Comment by Regalis11** [comment]
Fixed in https://github.com/FakeFishGames/Barotrauma-development/commit/637ea83ebd87922de01ead92e7700b2f124a1469

**Comment by Jasontti** [comment]
Tested the fix in: https://github.com/FakeFishGames/Barotrauma-development/pull/5227/commits/4fdcf9f98ce0224ad92e34d25711764600c82139

Tested in SP and MP
Tried with the save provided
Tested normal gameplay and healing between rounds
Checked hiring roster in multiple outposts

Could not recreate the situation with 2 exactly same bots
Tried to trigger events that spawn hireable npcs and many times with spawn command

No issues found
Closing ticket as completed
