### ISSUE TITLE
Decoy depth charges are too fast for monsters

### ISSUE THREAD

**Issue by ubertpendragon** [FakeFishGames/Barotrauma#11788]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

Decoy depth charges are too fast for monsters to catch up. 
They have a launchimpulse property, which means they do not slow down after being shot. 
Coupled with their density, they're just really fast

    <Body width="128" height="85" density="15" />
    <Projectile characterusable="false" launchimpulse="5.0">

Remove launchimpulse from the depth charge and add it to the tube itself, adjust density for sinking speed.

https://user-images.githubusercontent.com/73229309/230783962-43f52e97-5db7-434b-b94b-852d74fb4be6.mp4

Unstable (v1.1.4.0)

**Comment by Udrakan** [comment]
Result for moloch, from #11786
https://user-images.githubusercontent.com/59519434/230784898-b2430313-3fd1-4e28-8ff9-6d3ffd2b5ceb.mp4

**Comment by Regalis11** [comment]
> They have a launchimpulse property, which means they do not slow down after being shot.
> Remove launchimpulse from the depth charge and add it to the tube itself

Does this actually change the velocity at which the depth charge is launched? If it does, that seems like a bug in itself. The "final" launch impulse is simply the sum of the launch impulses of the projectile and the turret, so it should make no difference which the impulse is defined in.

**Comment by ubertpendragon** [comment]
> > They have a launchimpulse property, which means they do not slow down after being shot.
> 
> > Remove launchimpulse from the depth charge and add it to the tube itself
> 
> Does this actually change the velocity at which the depth charge is launched? If it does, that seems like a bug in itself. The "final" launch impulse is simply the sum of the launch impulses of the projectile and the turret, so it should make no difference which the impulse is defined in.

I assumed putting impulse on the projectile keeps it moving forward while putting it on the launcher was only an initial impulse but I'm probably wrong then.

Density would be the only factor?

**Comment by BlackMoons** [comment]
Would like to add, it seems if you put a depth charge into a loader via the sub editor, it does not behave the same as if you put it into the loader ingame

**Comment by BlackMoons** [comment]
Impulse determines its initial speed in the direction the depth charge launcher is aiming (its turret direction, not rotation, it has the same pie thing that turrets do), density determines if it accelerates, de-accelerates/stops or starts to float up again.

**Comment by BlackMoons** [comment]
After some tests, Launch impulse 10, density 10.2 produces a very nice decoy depth charge that fires out about 30 meters then slows down slightly for monsters to catch up to it.

**Comment by BlackMoons** [comment]
Here is a mod featuring 10.4 density depth charges if you want to see how they would behave: https://steamcommunity.com/sharedfiles/filedetails/?id=3319277391

Also some 9.6 density floating depth charges for distracting things above you, because why not?

**Comment by Regalis11** [comment]
Merged, closing
