### ISSUE TITLE
Defense Bots Don't Go Up

### ISSUE THREAD

**Issue by sylos** [FakeFishGames/Barotrauma#11793]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

Defense Bots don't go up ladders.  I made some defense bots and they end up gathering at the bottom of a Typhon attack tier 2 sub, multiplayer game.  They can't follow me up ladders.

### Reproduction steps

1. Be in multiplayer campaign started just pre-1.0
2. Buy typhon attack sub post 1.0
3. Build defense bots
4. Watch as they eventually collect inside bottom crew quarters

### Bug prevalence

Happens regularly

### Version

v1.0.8.0

### Which operating system did you encounter this bug on?

Windows

**Comment by HeatedWafflez** [comment]
> Thanks for the report! It's a known issue due to some technical issues that I didn't have time to dig into. As a workaround, you can carry it.

This isn't directly related to this ticket, but I just want to emphasize that the defense bots are incredibly difficult to utilize and they're just plain and simple awful.
-They seem to hardly follow you or are painfully slow at it outside the sub.
-They target entities that you wouldn't want them to such as prisoners or the huskified storage container.
-Dragging them is incredibly slow.

I'm hoping that it gets more love and that pet/companion entities can be ordered around like normal crew members (of course only to the person it's attached to?).

I might be missing the point that the defense bot is intended to reside only in the sub but currently it seems their functionality and capabilities are so mediocre they're more of a chore to handle even in this function.

**Comment by itchyOwl** [comment]
Fixed in FakeFishGames/Barotrauma-development#5553.

**Comment by Rokvach** [comment]
Tested, working correctly. Can be merged and closed.
