### ISSUE TITLE
[Sub Editor] Lights Randomly Don't Cast Shadows*

### ISSUE THREAD

**Issue by VaelophisNyx** [FakeFishGames/Barotrauma#12389]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

To clarify the title, sometimes any light placed in a room, set to cast shadows, will simply **refuse** to cast shadows at all unless it has its range increased (or decreased) to another arbitrary number. This small room in the photo below requires a light set to range 1200, otherwise the light completely ignores the walls

![Screenshot_2](https://github.com/Regalis11/Barotrauma/assets/1534478/76810ffc-2354-4510-b460-f62b1ff4c600)
![Screenshot_3](https://github.com/Regalis11/Barotrauma/assets/1534478/46208742-a556-41b1-8bad-d04160cdf252)

Best I can tell this may be a small-room issue, but I have had this occur in a large room as well. I can't think of any particular direct causes however. Reproduction steps are the best I have to go on.
Edit:
It appears this does stem slightly from light positioning, moving the pictured light left 2 grid spaces fixes it. However, I do believe this behavior is a bug worth figuring out. Additionally reducing the range after moving it reintroduces the bug

### Reproduction steps

1. Build a submarine
2. Place a light
3. Set the light to Cast Shadows and On
4. Move it into a room and test if the light behaves
5. If it does not, adjust the range up or down until it suddenly behaves

### Bug prevalence

Happens regularly

### Single player or multiplayer?

Other

### -

Sub Editor, possibly affects singleplayer/multiplayer. Untested.

### Version

v1.0.21.0

### Which operating system did you encounter this bug on?

Windows

**Comment by VaelophisNyx** [comment]
so a friend and I may have pinned down why? Seems to be related to having no hulls at all, then adding a light. Once a hull is added it still won't fix it, but if you save & reload the sub, it fixes it. Maybe it's got something to do with physics body generation? IDK how the light code works

**Comment by VaelophisNyx** [comment]
Additionally shifting the entire submarine in the editor can move around the problem locations, even to other lights

**Comment by Regalis11** [comment]
Might've been addressed by the changes in https://github.com/FakeFishGames/Barotrauma-development/pull/5372 (PR in our private repo), which fixed [Lamp Causes Light Leak Through Hatches After Open & Close](https://github.com/FakeFishGames/Barotrauma/issues/12087) and [Opened hatches/doors do not cast shadow when closed](https://github.com/FakeFishGames/Barotrauma/issues/14065). Moving to QA for a re-test

**Comment by Regalis11** [comment]
Tested, could no longer repro the issue with either of the described repro steps.
