### ISSUE TITLE
pirate ships acting like trampolines

### ISSUE THREAD

**Issue by LePiromano** [FakeFishGames/Barotrauma#12434]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

fell into a pirate ship and started bouncing
https://github.com/Regalis11/Barotrauma/assets/55637865/d71f9f18-1a16-4c97-b65d-0dd8e8675d18

### Reproduction steps

flood the pirate shit and crash land it somewhere
flood your own ship and fall on top of the pirate ship
bounce

### Bug prevalence

Happens regularly

### Single player or multiplayer?

Single player

### Version

Unstable (v1.1.3.0)

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment]
I unfortunately could not find a way to reproduce this. 
https://github.com/Regalis11/Barotrauma/assets/14351070/cdd497e9-e49b-484b-b062-adea4d29ab26

Could be that it requires the submarine to hit the one below it in some specific way, maybe a weapon or some specific wall pieces first? Unfortunately the clip is so dark it's hard to see what exactly is going on there or which submarine it is. :/

**Comment by xolophreny** [comment]
Got something potentially similar happening in the editor - spawned a Selkie on top of a Kastrull, punctured its ballast slightly. It falls on the Kastrull, the Kastrull gets pushed down a bit, but the Selkie rebounds back up with more force than it fell with. Kastrull was in manual steering mode, so it probably didn't try to move upwards by itself

https://github.com/Regalis11/Barotrauma/assets/41170402/679b194b-a5de-4590-845f-524dbc79e2f4

**Comment by Regalis11** [comment]
No known steps to repro, closing
