### ISSUE TITLE
Labels tags sent by Wi-Fi component in chat are not formatted.

### ISSUE THREAD

**Issue by HMilix** [FakeFishGames/Barotrauma#12448]
Hi,

I don't know if it's a bug or a missing feature.
When you try to send in the chat a label tag like `label.engine1` (which give `Engine #1` in a text display for example) via a Wi-Fi component, the text is not formatted, it sends `label.engine1` and not `Engine #1`.

If you want to reproduce, just 
set a Memory Component with your tag label, put the "signal_out" in the "set_output" of a Signal Check Component,
link a button in the "signal_in" of the Signal Check Component
and send the "signal_out" in a Wifi component (with "Link to Chat" on, of course.)
Like this image:
![image_2023-08-01_211938149](https://github.com/Regalis11/Barotrauma/assets/67100013/b78986c7-a53c-4fb1-8335-4cf639ac6865)

And it will send this result:
![image_2023-08-01_212610084](https://github.com/Regalis11/Barotrauma/assets/67100013/d7799b3a-f96d-4d65-ae34-71d6e2e78dcb)

There's anyway to fix this?

Tested in 1.0.21.0.

Have a good day.

**Comment by itchyOwl** [comment]
Seems like a bug to me.

**Comment by HMilix** [comment]
Tested with the 1.1.18.0, still doesn't work. (Me sad :c)
