### ISSUE TITLE
Sound effects sometimes not playing in multiplayer (shotgun)

### ISSUE THREAD

**Issue by itchyOwl** [FakeFishGames/Barotrauma#12510]
Shotgun sounds aren't always audible in a multiplayer game. Haven't debugged it so I don't know if they are playing at all or just being muffled out too much or something. But I've now encountered the issue at least twice in a multiplayer session when firing a shotgun. I doubt it's due to any recent changes, because the last time was months ago, but can't be sure.

Possibly affects other effects too. Could be related to #11142.

Last time encountered the issue in v1.1.7.0 (very-unstable-unstable, steam build).

QA: just keep an eye one the issue and report any findings here.

**Comment by Rokvach** [comment]
Just testing this by loading into a multiplayer round and firing a shotgun underwater did make a sound

I feel like this is caused by the sound channels being full and some other sounds having a higher priority than the shotgun, especially during very hectic gameplay.

**Comment by itchyOwl** [comment]
Yeah I suspected the same, though we should make sure it doesn't happen on sounds like that. It felt really broken.

**Comment by NilanthAnimosus** [comment]
The same issues from #12511 appears to be one cause of this issue, On the last round other clients will not hear the sounds as well as not seeing the projectile trail. its unknown if this is the main cause however.

**Comment by Regalis11** [comment]
No known steps to repro. Potentially caused by https://github.com/FakeFishGames/Barotrauma/issues/12511
