### ISSUE TITLE
Issue with the repair (stuck when attempting to repair)

### ISSUE THREAD

**Issue by DropUrKeybd** [FakeFishGames/Barotrauma#12585]
I encountered an issue while repairing the coilgun loader. It appears to be an endless repairing process with no progress. My character is stuck in that position, and no matter where I go, the game always tries to return me to this place. I am also attaching a video demonstrating the error.

https://github.com/Regalis11/Barotrauma/assets/103832952/9f1779c3-c5f5-4327-8ddc-9b704ba99741

**Comment by abemaden** [comment]
Had the same issue here ---> https://github.com/Regalis11/Barotrauma/issues/12524
Apparently it should have been fixed, but it seems to persist. 
The character doesn't glitch out as much anymore, and when clicking the quick time event to repair it seems to repair very slowly now instead of not repairing at all.

**Comment by Rokvach** [comment]
I haven't been able to reproduce this issue so far

**Comment by NilanthAnimosus** [comment]
Gave this some testing and was also unable to reproduce the issue.

I have tried several hunches on the version this issue appeared (1.1.8.0 unstable), such as old version submarines (Before ammo indicator lights were added), Purchasing new turrets (As in the video that loader is by default empty on a typhon), moving the character away from repairs, moving location as an AI is part way through repair, water damage, damage via explosions, removing the tool as you repair, switching between item and repair interface, Holding a screwdriver while repairing, Spamming the stop and start of repairs, repairing next round in the outpost, Buying outpost repairs then trying to repair current or next round. I essentially ran out of ideas.

If this is easily reproducable on one of your save files that it occurs regularly on, could you upload said saves?

If not, is there anything you did during the round that could contribute to this that perhaps seemed odd, or even a server log of said session if a server?

**Comment by Regalis11** [comment]
No known steps to repro, closing
