### ISSUE TITLE
A non-host player closes the game，If he goes online again, all items will disappear.

### ISSUE THREAD

**Issue by Kaze2018** [FakeFishGames/Barotrauma#12593]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

If a non-host player puts on diving suits and closes the game, death will be triggered. If he goes online again, all items will disappear.

### Reproduction steps

1.Non-host players put on diving suits
2.Non-host players close the game,but host player still online
3.wait until non-host completely dead （the username in the upper left corner will disappear）
4.host player save and exit the game
5.Next time hostplayer start a server
6.Non-host players get ready and get into game
7.All the items in the backpack of the non-host player when they logged out last time are all missing

### Bug prevalence

Happens every time I play

### Single player or multiplayer?

Multiplayer hosted using a dedicated server

### Version

v1.0.21.0

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment]
Thank you for the report!

I'm not entirely sure if I understood the issue correctly, but to me it does not seem like a bug. If you die, you lose your items.

**Comment by Regalis11** [comment]
No known steps to repro, closing
