### ISSUE TITLE
[Unstable 1.1.11.0] bots cannot defend themselves while holding a Cargo Scooter in their hands

### ISSUE THREAD

**Issue by 0n1ime** [FakeFishGames/Barotrauma#12668]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

Bots cannot defend themselves while holding a Cargo Scooter in their hands, despite the fact that they have weapons in their inventory. 
Also, they cannot accept an order to fight intruders while holding a Cargo Scooter in their hans.
They can't drop a Cargo Scooter, eliminate an enemy, and even more so pick up a Cargo Scooter again. Therefore, a possible solution may be to allow bots to put a Cargo Scooter in the Toolbelt Slot.
![fight intrufers order](https://github.com/Regalis11/Barotrauma/assets/143577687/81367ff8-14af-4a6c-9c5e-4337f3407f0b)

### Reproduction steps

1. Start submarine editor
2. Open eny submarine and put a Cargo Scoter on the floor or in any cabinet
3. Start submarine testing
4. Order the bot to prepare for expedition
5. Bot picked up a Cargo Scooter
6. Order the bot to follow you outside the submarine
7. Сreate an any hostile little creature next to the bot with the console command
8. Bot will run away from the creature without trying to fight it while having a weapon in the inventory
![Ateck order](https://github.com/Regalis11/Barotrauma/assets/143577687/6958c1f1-1d21-48e8-8cfd-3d8bf7d01bab)

### Bug prevalence

Happens every time I play

### Single player or multiplayer?

Single player

### Version

Other

### -

Unstable 1.1.11.0

### Which operating system did you encounter this bug on?

Windows

**Comment by itchyOwl** [comment]
> Therefore, a possible solution may be to allow bots to put a Cargo Scooter in the Toolbelt Slot.

No. We don't bots be able to do different things than the players. I think the bots should just drop the scooter or alternatively flee like not being able to find a weapon. Not sure which would be better (or less annoying).

**Comment by itchyOwl** [comment]
Also they should probably not automatically take cargo scooters, at least not when there's regular scooters around,

**Comment by 0n1ime** [comment]
I tested the same situation, but the bot had a Metal Crate in his hands, the bot also does not attack the enemy, it cannot drop a Metal Crate to draw a weapon. He also answers "negative, no way" to the order to fight intruders. Bots don't know what to do when they have any large object in their hands and when they can't put it in their inventory. All this happens when bots are outside the submarine. At this stage, it is better not to give them such items in their hands .
