### ISSUE TITLE
Submarine equality check failed when host transitions too fast after loading in

### ISSUE THREAD

**Issue by Rokvach** [FakeFishGames/Barotrauma#12699]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

Clients can disconnect from a server if the host starts a new round before any of the other clients have loaded in yet. 

![image](https://github.com/Regalis11/Barotrauma/assets/7299826/4e89c9bb-85a3-4449-a0a5-876a42375180)

### Reproduction steps

1. Play with multiple non-local clients
2. Leave outpost
3. Dock back into outpost
4. As soon as outpost loads in load a new round
5. Clients who were still loading into the outpost should disconnect once the next level is loaded. 

### Bug prevalence

Happens regularly

### Single player or multiplayer?

Multiplayer hosted from the in-game menu (= using a listen server)

### Version

Unstable (v1.1.10.0)

### Which operating system did you encounter this bug on?

Windows

**Comment by Rokvach** [comment]
Can be reproduced quite easily nowadays by running two clients with the "multiclienttestmode" command enabled and then using  "teleportsub endoutpost" command as soon as you get access to the conole on a level which has a outpost at the end so the round ends immediately after using the command.

**Comment by Jasontti** [comment]
Testing notes: https://github.com/FakeFishGames/Barotrauma-development/pull/4961#issuecomment-2556606531
Closing ticket as completed
