### ISSUE TITLE
Bots prefer PUCS over abyss suits below 6000m

### ISSUE THREAD

**Issue by SomeRandomNoobKekeke** [FakeFishGames/Barotrauma#12704]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

[so they can't repair hull below 6000m and just die](https://www.youtube.com/watch?v=cP3t0qMdY7A)

![20230922122657_1](https://github.com/Regalis11/Barotrauma/assets/122838333/f962f90c-5fb3-4fa5-8a4f-d9577dcff0c7)
if there are no pucs on board then they take abyss suits as they should
### Reproduction steps

take [this](https://drive.google.com/file/d/1ALCRaUSFCjRkOtZZD3B7FQrrqGS65FJs/view) save, it's singleplayer, full vanila
or just find another deep enough place in hydrothermal wastes

teleport sub below 6000m
make sure bots have pucs and access to abyss suits
drill a hole and watch bots trying to fix it in pucs

### Bug prevalence

Happens every time I play

### Single player or multiplayer?

Single player

### Version

v1.0.21.0

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/41fe92d25e88630d3d355af7c4dbe8c17895e5c1
