### ISSUE TITLE
Naval Architect achievement triggered with only 10 hours total in game

### ISSUE THREAD

**Issue by Finxx1** [FakeFishGames/Barotrauma#12711]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

When messing around in the submarine editor, clicking test gave me the achievement.
![image](https://github.com/Regalis11/Barotrauma/assets/46616745/f69dcc97-b897-4edc-a500-08e776cb6963)

### Reproduction steps

1. Select "Submarine Editor" on the main menu
2. Open "Dugong" (other Vanilla submarines might work too, but I can't remove the achievement to test.)
3. Click the "Test" button
4. Achievement should trigger.

### Bug prevalence

Just once

### Single player or multiplayer?

Other

### -

Submarine Editor

### Version

v1.0.21.0

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment]
Thank you for the report! We unfortunately haven't been able to reproduce the issue - it doesn't seem to happen consistently, so it most likely requires some more specific circumstances to occur. I've added some extra debug logging in https://github.com/Regalis11/Barotrauma-development/commit/bcb886babb3bb298f0717be31338be40e3efb156 (commit in our private repo) to hopefully help us diagnose the problem.

**Comment by Jasontti** [comment]
I'll leave this one open still, as there is no functional changes, but might become relevant when more information is gathered.
