### ISSUE TITLE
Issue with Reactor GUI: Making the reactor Holdable spawns an invisible GUI that doesn't allow the player to interact with anything inside, no way of removing it

### ISSUE THREAD

**Issue by ZliKeksic328** [FakeFishGames/Barotrauma#12719]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [X] My issue happened while using mods.

### What happened?

So, I was making a mod for a carry-able reactor, it was going smoothly until I ran into an issue that I couldn't fix, as well as some other mod developrers: The reactor spawns an invisible GUI when being carried, and there's no known way of dealing with the issue.

The invisible GUI prevents the player from moving when they have their mouse inside said GUI, prevents the player from interacting with objects inside said GUI, ans prevents placement of the reactor.

![Screenshot (428)](https://github.com/Regalis11/Barotrauma/assets/88772947/eb4b3d05-0417-49ca-87be-c0c8c0a1bbcc)
![Screenshot (434)](https://github.com/Regalis11/Barotrauma/assets/88772947/13f79717-afc8-4628-9995-108af4ca7d8b)
https://clipchamp.com/watch/BYls56oybsL

### Reproduction steps

1. Spawn the reactor in Submarine editor
2. Reactor works fine
3. Detatch said reactor
4. The invisible GUI spawns when the reactor is carried
5. The GUI interrupts actions and movement

### Bug prevalence

Happens regularly

### Single player or multiplayer?

Happens in both single player and multiplayer

### Version

v1.0.21.0

### Which operating system did you encounter this bug on?

Windows

### Relevant error messages and crash reports

```shell
No errors.
```

**Comment by Jasontti** [comment]
[Boiler.zip](https://github.com/Regalis11/Barotrauma/files/12730095/Boiler.zip)
Stripped down localmod in question for testing

**Comment by Regalis11** [comment]
Thank you for the report! Fixed in https://github.com/Regalis11/Barotrauma-development/commit/bf71a4a907a847abfb374005c603bdc16e33c823 (commit in our private repo).

**Comment by Jasontti** [comment]
Tested in: https://github.com/Regalis11/Barotrauma-development/pull/4510/commits/b873d70553cc05e59c9a530f187089ba9e907972

Fix works and character can move while holding reactor now.

This could be causing GUI issue of linked elements not being visible ie. status monitor when operating navigation terminal or cabinet, when operating fabricator (item in linked cabinets are still accessible to fabricator).

![2023-11-24_11-14](https://github.com/Regalis11/Barotrauma/assets/8488224/aab36489-f114-4f65-b97f-fea46a382a8b)

**Comment by Regalis11** [comment]
@Jasontti I'm not sure I understand the issue, in what situation can that happen? What's happening in the screenshot?

**Comment by Jasontti** [comment]
Tested in: https://github.com/FakeFishGames/Barotrauma-development/pull/4710/commits/f8f41d156d567714b014cc07b7bd677ebe89f8f9

Tested with the example mod and vanilla placeables, like circuitbox, components and pumps

Example mod UI works. You can use it attached and walk with it detached, but mod itself has some other issues.

No issues with vanilla content found.
Closing ticket
