### ISSUE TITLE
"changes to your character will be applied when the round ends" notification is shown in lobby

### ISSUE THREAD

**Issue by Rokvach** [FakeFishGames/Barotrauma#12798]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

![image](https://github.com/Regalis11/Barotrauma/assets/7299826/a29ee559-76cc-41ea-b2ea-294772125197)

### Reproduction steps

1. Start a multiplayer round
2. Return to lobby
3. Notice the notification

### Bug prevalence

Happens every time I play

### Single player or multiplayer?

Multiplayer hosted from the in-game menu (= using a listen server)

### Version

Other

### -

release/traitor-update Commit: https://github.com/Regalis11/Barotrauma-development/commit/88d5b069d60135c3dc0f96d83f55709cfe433788

### Which operating system did you encounter this bug on?

Windows

**Comment by Rokvach** [comment]
Tested, working correctly. Can be merged and closed.

**Comment by Regalis11** [comment]
Seems to have resurfaced with the server lobby rework, reopened

**Comment by Regalis11** [comment]
Fixed in https://github.com/FakeFishGames/Barotrauma-development/commit/eb674313935c0894e783043d76e3ee8a1059e1ad
