### ISSUE TITLE
Factions modding bugs and grievances

### ISSUE THREAD

**Issue by ubertpendragon** [FakeFishGames/Barotrauma#12790]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

A list of things that are either bugged or missing, relating to modding factions in the game.
Disscussed among modders, will add more

Simple mod for testing all of these issues:

[Truehuskfaction.zip](https://github.com/Regalis11/Barotrauma/files/12883411/Truehuskfaction.zip)

# BUGS

**-AI breaks in non-faction affiliated outposts** 
If a location of the outpost type isn't affiliated with a faction, the AI partially shuts down. NPCs with `behavior="Patrol"` wont patrol properly, others won't try to repair, get stuck in place or behave strangely #12789

**-Items break in non-faction affiliated outposts** 
Items like junction boxes will degrade, when they don't in regular outposts. I'm not sure what logic regular outposts are using, but the machines do not degrade there

**-Assigned outpost team does not assign a team**
When assigning `outpostteam="huskcult" ` in Locationtypes, the outpost will not in fact be assigned the husk faction

```xml
  <huskchurch
    identifier="huskchurch"
    replaceinradiation="Abandoned"
    namefile="%Moddir%/Text/HusklocationNames.txt,%Moddir%/Text/HuskcityNames.txt"
    outpostteam="huskcult"  
```

No faction
![image](https://github.com/Regalis11/Barotrauma/assets/73229309/4486bfd4-ec50-4ab2-bef3-b28df884703a)

Assigned faction
![image](https://github.com/Regalis11/Barotrauma/assets/73229309/ce615f4c-ef08-4b03-aeab-eac3d3479174)

# FEATURES

**-Cannot set multiple opposing factions**
Opposingfaction determines negative reputation gains when gaining positive reputation with one faction. But you cannot set multiple factions as opposign, even though it would make sense for one fully "hostile" faction
`opposingfaction="coalition,separatists"`

### Version

v1.0.21.0

### Reproduction steps

Boot up a campaign with the mod
Dock to a husk outpost
Watch the AI
Watch items degrade

**Comment by Regalis11** [comment]
> When assigning outpostteam="huskcult"  in Locationtypes, the outpost will not in fact be assigned the husk faction

I think this is a misunderstanding of what the outpost team property does: teams aren't the same thing as factions, valid teams are None (enemies), Team1 (player team), Team2 (second player team, hostile to Team1), FriendlyNPC (self-explanatory).

**Comment by Regalis11** [comment]
It also seems the issue here is that the outpost does not belong to the faction (in fact it doesn't seem to belong to any faction). So I would argue the AI issue isn't a bug: the NPCs aren't in their own outpost, but a random outpost that doesn't belong to anyone, so they should not be repairing it or patrolling around it.

**Comment by Regalis11** [comment]
> Items break in non-faction affiliated outposts

By default, items don't deteriorate in friendly outposts. I think the issue here is that the outpost isn't friendly (as it doesn't belong to anyone).

**Comment by ubertpendragon** [comment]
Thanks for the quick reply

> I think this is a misunderstanding of what the outpost team property does: teams aren't the same thing as factions, valid teams are None (enemies), Team1 (player team), Team2 (second player team, hostile to Team1), FriendlyNPC (self-explanatory).

The crux of the problem is that there's no easy way to assign a certain faction to a certain location (typically a set of outposts)


Typically I wanted husks to have their own outpost types, outside of regular vanilla outposts, but I ended up making a "neutral" location with husk NPCs in Outpostgenerationparameters

Otherwise the husk-specific outposts would've been taken over by coalition/separatists using `controlledoutpostpercentage`, and vanilla outposts by husks

**Comment by Regalis11** [comment]
Yeah, currently there isn't a way to tie a faction to a specific location type. Outposts are assigned to factions randomly, and the look of the outpost is modified to fit the faction. Being able to force the faction based on the location type seems like it'd make adding custom factions much easier though, I think we'll need to add support for that.

**Comment by Regalis11** [comment]
Implemented in https://github.com/Regalis11/Barotrauma-development/commit/ad86d3f676dd6e9fbb4534b86a0386acc2a36c19
