### ISSUE TITLE
Players can bypass OuterClothes+InnerClothes lock in wearable items

### ISSUE THREAD

**Issue by Alpharius-30-milenium** [FakeFishGames/Barotrauma#12793]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [X] My issue happened while using mods.

### What happened?

So, I getting some reports when people say that they can use 2 slot armor in 1 slot sometimes.

### Reproduction steps

1. wear item that takes 2 slots
2. wear diving mask with oxygen tank in it
3. put item from one of the slots in oxygen tank that is contained in diving mask
4. wear anything you want in free slot
5. [or watch the pinned video] https://youtu.be/CAr2QDXjkaw

### Bug prevalence

Happens regularly

### Single player or multiplayer?

Happens in both single player and multiplayer

### Version

v1.0.21.0

### Which operating system did you encounter this bug on?

Windows

**Comment by itchyOwl** [comment]
The repro steps needs confirmation, moving to QA investigates.

**Comment by Rokvach** [comment]
Tested in version 1.1.18.1 using the Barotrauma 40K mod https://steamcommunity.com/sharedfiles/filedetails/?id=2610181908

I was able to reproduce this issue using the "Sororitas power armor" with the same steps as shown on the video. 

Moving to Bugfixes
