### ISSUE TITLE
crawleroutbreak event lacks spawnpoints in Research module + mod support

### ISSUE THREAD

**Issue by ubertpendragon** [FakeFishGames/Barotrauma#12799]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

Very simple request to add a spawnpoint with a tag in Research moduels for event/mod support if you want to spawn monsters in these rooms

![image](https://github.com/Regalis11/Barotrauma/assets/73229309/6eb4144c-1208-430d-8f7c-213226fe6ca9)
![image](https://github.com/Regalis11/Barotrauma/assets/73229309/5709b0bd-c6cb-4c77-86cb-74674958bd28)

Additionally crawleroutbreak event could use this
![image](https://github.com/Regalis11/Barotrauma/assets/73229309/21b7c46f-b2eb-4e1b-bb91-c54e3f212f3f)

**Crawlers spawn using the crew spawnpoints** instead of the actual containement room, monster specific spawnpoint would help

![image](https://github.com/Regalis11/Barotrauma/assets/73229309/6ca2a0d2-a5fe-4b91-9e55-403ca780f9a5)
![image](https://github.com/Regalis11/Barotrauma/assets/73229309/521bb87b-0b16-429d-9d58-5e0e7a467d22)

I'm not familiar with event system but I assume it'd be possible to either break or open the door somehow.

### Version

v1.0.21.0

**Comment by ubertpendragon** [comment]
Note that crawleroutbreak also happens in colonies, but these modules don't have "containement" areas so it feels like crawlers just happened out of nowhere 

_maybe_
![image](https://github.com/Regalis11/Barotrauma/assets/73229309/769d02f4-997e-4058-b921-fe6bbec19da8)

**Comment by ubertpendragon** [comment]
Note that I submitted those changes as part of PR

https://github.com/FakeFishGames/Barotrauma/pull/12906

**Comment by Jasontti** [comment]
Tested in: https://github.com/FakeFishGames/Barotrauma-development/pull/4592/commits/740d82c6f74956cdda620c199f5516f53abb4ab5

Tested as part of larger event PR: https://github.com/FakeFishGames/Barotrauma-development/pull/4592

No issues found
Closing ticket
