### ISSUE TITLE
Attacks set with TargetType="Character" cannot damage items (flares)

### ISSUE THREAD

**Issue by ubertpendragon** [FakeFishGames/Barotrauma#12802]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [X] My issue happened while using mods.

### What happened?

If an creature attack is set with `TargetType="Character"`, it cannot damage item despite having `itemdamage`

This means it wont be able to break a flare with its attack unless it has a `TargetType="Structure"` and will be forever distracted by it

### Reproduction steps

1. Throw a flare
2. Spawn a hammerheadspawn

or

1. Throw a flare
2. Spawn a crawler
3. Breaks flare

4. Change `TargetType="Structure"` to `TargetType="Character" ` in CrawlerDefaultRagdoll.xml at line 84
5. Crawler cannot break flare any more

### Version

v1.0.21.0

**Comment by itchyOwl** [comment]
Yep, it has to use TargetType="Structure", which in practice means "anything but characters". Or "Any", which accepts any targets. There's legacy reasons for this: back in the days the only items monsters could attack were doors. Obviously that's not the case anymore. And we could consider changing it, but would have to evaluate how much if would affect existing content.

**Comment by itchyOwl** [comment]
Fixed in FakeFishGames/Barotrauma-development#5558. You can now also target items. Having TargetType="Structure" still includes items, so effectively it's the same as TargetType="Structure,Item", but you can now have TargetType="Item", which doesn't target walls or doors (although they are technically items).

**Comment by ubertpendragon** [comment]
Nice
