### ISSUE TITLE
Ammoboxes cannot fall out of submarine?

### ISSUE THREAD

**Issue by PanmanS** [FakeFishGames/Barotrauma#12826]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

So Im not sure if it was deliberate or unconscious design decision, but items like crates, metalboxes or even exosuits dont fall out of submarine, while diving suits do??
![image](https://github.com/Regalis11/Barotrauma/assets/42521948/1aba922d-a855-4b17-95a8-50bd1cd6ac2c)

Wouldn't it be more interesting if everything fell out?

### Reproduction steps

1. load sub editor on berrilia and go to ballast (can be any sub)
2. `explosion 200 0 0 2000000000 0 0 0` entire ballast and make sure you can swim through
3. spawn ammoboxes, diving suits, exosuits and metal crates!

### Bug prevalence

Happens every time I play

### Single player or multiplayer?

Single player

### Version

v1.0.21.0

### Which operating system did you encounter this bug on?

Windows

**Comment by itchyOwl** [comment]
The repro steps needs confirmation, moving to QA investigates.

**Comment by PanmanS** [comment]
Anything I can do?

**Comment by Regalis11** [comment]
Fixed in https://github.com/FakeFishGames/Barotrauma-development/commit/eb1f9d960cff847e7b9b910584f4eda199ac47f8

**Comment by Jasontti** [comment]
Tested in: https://github.com/FakeFishGames/Barotrauma-development/pull/4885/commits/81bd083265f04308815030a2de307ff5eeee9f84

Tested by dropping in and out of the sub most items

No issues found
Closing ticket
