### ISSUE TITLE
Crewmodule_01 lacks mudraptorspawnvent tag on its vents

### ISSUE THREAD

**Issue by ubertpendragon** [FakeFishGames/Barotrauma#12867]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

The event `soundinthevent` uses a specific tag to trigger

Crew Modules 02 and 03 have vents with the tag `mudraptorspawnvent`, but not Crewmodule_01, which makes the event rarer than it should be

![image](https://github.com/Regalis11/Barotrauma/assets/73229309/3f6c8513-818c-4a77-8dd0-e10687f1d28d)

I'm not sure if there are more modules that use or should use this

### Version

v1.1.18.1 (Treacherous Tides)

**Comment by ubertpendragon** [comment]
There are a only 2 more modules with this tag as well (engineering and husk), but combined with https://github.com/Regalis11/Barotrauma/issues/12868 the event is hard to trigger

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/6f676587f7fe9cb9ced289ecb514a04fdb675468

**Comment by Jasontti** [comment]
Tested in: https://github.com/FakeFishGames/Barotrauma-development/pull/4592/commits/740d82c6f74956cdda620c199f5516f53abb4ab5

Tested as part of larger event PR: https://github.com/FakeFishGames/Barotrauma-development/pull/4592

No issues found
Closing ticket
