### ISSUE TITLE
Game doesn't recognize correct audio output device

### ISSUE THREAD

**Issue by Isamylov** [FakeFishGames/Barotrauma#12877]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

I have a speakers and headphones. Sometimes I want to play using speakers, sometimes using headphones. Normally - all games can recognize what output device I'm using, but barotrauma simply remember output device in own settings, which sometimes incomfortable. Please consider to read the current OS output device settings and auto determine the game audio output.

### Reproduction steps

1. Set output device in game as speakers.
2. Quit.
3. Set windows audio output as headphones.
4. Run the game.
5. The game will use it's own output device settings instead of autodetect.

### Bug prevalence

Happens every time I play

### Single player or multiplayer?

Other

### Version

v1.1.18.1 (Treacherous Tides)

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment]
Closing in favor of the new "general audio device issues" ticket: https://github.com/FakeFishGames/Barotrauma/issues/13430
