### ISSUE TITLE
Special character keys on non-QWERTY layout can't be used as keybind

### ISSUE THREAD

**Issue by Reewn** [FakeFishGames/Barotrauma#12882]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

Special character keys such as [ ² ] on the [AZERTY layout](https://en.wikipedia.org/wiki/AZERTY#/media/File:KB_France.svg) can't be used as keybind (where ` is), or [ é ] on the [BÉPO layout](https://en.wikipedia.org/wiki/B%C3%89PO#/media/File:KB_French_Dvorak_b%C3%A9po_simplifi%C3%A9.svg) (where W is). Trying to do so bind the action to the "None" key instead, which makes the action unusable. This has been tested on both Linux and Windows.

These special characters are not listed in the [Key Enum definition](https://learn.microsoft.com/en-us/dotnet/api/system.windows.input.key?view=windowsdesktop-7.0), so I guess it will return "None" by default. Note that special characters can still be bound if they are on the Numeric row from [ 1 ] to [ 0 ]. It seems the key position overrides the character, in this case (_e.g._ 'é' can be used with the AZERTY layout).

Probably related issue: #3133 

### Reproduction steps

1. Run the game
2. Set the keyboard layout to AZERTY
3. Open Settings > Controls
4. Bind an action to the [ ² ] key ([ ` ] in QWERTY) or any special character that isn't on the Numeric row.

The keybind should be "None". Using the action in a game should do nothing either.

### Bug prevalence

Happens every time I play

### Single player or multiplayer?

Happens outside single player or multiplayer game modes (e.g. game launches on startup, something broken in the main menu)

### Version

v1.1.18.1 (Treacherous Tides)

### Which operating system did you encounter this bug on?

Linux

**Comment by Regalis11** [comment]
Thank you for the report! This seems to be [a known issue in MonoGame](https://github.com/MonoGame/MonoGame/issues/5715). I implemented a workaround to this now in our private repo (https://github.com/Regalis11/Barotrauma-development/commit/4b888ad0d0f21b7aae69b73ddc46f6d248fe7245), mapping the keys to what they correspond to on a US layout (which isn't exactly correct, but should allow setting them as keybinds).
