### ISSUE TITLE
Wiring snaps to grid corners while in play, components snap to grid centers in play and in editor. 

### ISSUE THREAD

**Issue by nomnivore1** [FakeFishGames/Barotrauma#12910]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

Item placement in game and in the editor now matches, but wires still snap to the offset grid positions. 
![BaroGrid](https://github.com/Regalis11/Barotrauma/assets/48558380/adbc4881-265f-465d-a521-8a4d812b1a49)

### Reproduction steps

1. open a submarine in the editor 
2. place relays on the grid in the editor, 
3. place wires and a screwdriver where they will be accessible in play
4. press "test" button
5. attempt to run a wire from one relay to another, following the grid orientation
6. the wire nodes will snap to the corners of the grid, while the relays are placed at the grid square centers

### Bug prevalence

Happens regularly

### Single player or multiplayer?

Other

### -

Found in the editor, have not taken to singleplayer or multiplayer to test. 

### Version

v1.1.18.1 (Treacherous Tides)

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/342dfbf470be4c442f3a59e04dc262279a6cc025

**Comment by Rokvach** [comment]
Moving back to todo, the sub editor uses a 5 point system where you can align the wire to the sides and the center, I feel like we should also have it this way ingame. Also wires leaving devices would be nice if they were aligned to the grid as well rather than just to the center of the device.

**Comment by Rokvach** [comment]
Tested, working correctly, can be merged and closed.
