### ISSUE TITLE
An error concerned with adding sub in editor.

### ISSUE THREAD

**Issue by LUKA46B** [FakeFishGames/Barotrauma#12952]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

When you add a submarine while did not link it to the main submarine's dock,it would report an error saying that sth went wrong when initializing that sub for having no position.AND,it would be unable to spawn that same sub in the eidtor as if it no longer exist.

By the way,the Chinese translators missed the adding description of the engineers' talent ‘Submarine Of Things’ about circuit boxes.

### Reproduction steps

1.enter the sub editor
2.load a sub
3.add a "sub sub"(haha)  using "add submarine" without linking it to the main sub
4.test
5.An error reported,saying that sth went wrong when initializing that sub for having no position.
6.try spawn another "subsub" using "spawnsub"
7.could not find the subsub(even when the subsub is the sameone to mainsub) in this testing round.

### Bug prevalence

Happens every time I play

### Single player or multiplayer?

Single player

### Version

v1.1.19.3 (Treacherous Tides Hotfix 2)

### Which operating system did you encounter this bug on?

Windows

**Comment by LUKA46B** [comment]
Thank u for reply.I tried testing this issue for few more times(in the version unstable 1.2.1.0),and found this issue is related to the language setting.


For language such as French,German,English,it just happens like what you'd described,which however behaves differently when in Chinese,Japanese,Korean,even Russian.
(we are now convinced this would be an&nbsp;imperialism bug)
I guess there may be sth&nbsp; wrong with unicode or some other thing.=/


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Regalis11/Barotrauma"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年11月18日(星期六) 凌晨0:18
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [Regalis11/Barotrauma] An error concerned with adding sub in editor. (Issue #12952)





 
Thank you for the report and sorry for taking so long to get back to you!
 
I'm not sure if I understood the steps correctly, because I was unable to fully reproduce the issue. I tried adding an unlinked Selkie to the vanilla Selkie, started the test mode, got the console error, and then attempted to spawn another Selkie using "spawnsub selkie cursor", and it spawned with no issues.
 
Did you try spawning the sub in the actual editor, or in the test mode? And did I understand correctly that the "main sub", the "sub sub" and the one you're trying to spawn using console commands are all the same submarine?

**Comment by Regalis11** [comment]
I would argue that the described behavior is not a bug: if you're playing in Russian, you need to enter the name of the submarine is Russian.

Addressed this regardless (commit in our private repo: https://github.com/FakeFishGames/Barotrauma-development/commit/9dd79ece163ac910af44550c07a5b2b9c528173c). Now both the localized and non-localized name are accepted.
