### ISSUE TITLE
Auto-Injector Headset and PUCS healing item priority when using H (Health) menu

### ISSUE THREAD

**Issue by Oxmaster** [FakeFishGames/Barotrauma#12951]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

Auto-Injector Headset has too high of a priority when healing with H menu, same with PUCS.

When wearing "Medic's Fatigues" / "Doctor's Uniform" or having them in inventory with morphine and not having any morphine in inventory, the Auto-Injector Headset takes priority when healing with H menu.

Main issue is with bots; when giving "Medical Doctor" bots "Medic's Fatigues" with 8 morphine and "Auto-Injector Headset" with 1 morphine, when they heal other bots or players, they use morphine from their Auto-Injector Headset first.

Short video showing healing priority with different combinations.
https://youtu.be/O9N7iKfLgJ4

In my opinion; "PUCS" should be last when healing (it's an item that is often dropped) after that the "Auto-Injector Headset", and then the rest.

### Reproduction steps

1. Equip "Medic's Fatigues" / "Doctor's Uniform" with morphine inside
2. Equip "Auto-Injector Headset" with morphine inside
3. Use H menu to heal affliction
4. Observe the priority from which item will the medicine be applied.

### Bug prevalence

Happens every time I play

### Single player or multiplayer?

Single player

### Version

v1.1.19.3 (Treacherous Tides Hotfix 2)

### Which operating system did you encounter this bug on?

Windows

**Comment by Jasontti** [comment]
Tested in: https://github.com/Regalis11/Barotrauma-development/pull/4633/commits/ed5cec0cfbf72ca298d1b4e272755efbbcd67783

Bots now use healing items from largest inventory.

Spotted one inconsistency
Now when manually using H menu, it highlights items in fatigues, but uses item from auto-injector instead

![image](https://github.com/Regalis11/Barotrauma/assets/8488224/f566c4cd-f9b4-4e9e-9806-7f0d3980dbaf)

1. Have saline in fatigues and auto-injector
2. giveaffliction bloodloss 50 "favourite bot"
3. Use healing menus buttons to heal
4. Saline from auto-injector is used

**Comment by Jasontti** [comment]
Tested in: https://github.com/FakeFishGames/Barotrauma-development/pull/4633/commits/bd659eab3585e83a795adec9dca97867b3feed8c

No issues found
Closing ticket
