### ISSUE TITLE
Mining minerals mission description has an error in reward percentage again

### ISSUE THREAD

**Issue by pavel4win** [FakeFishGames/Barotrauma#12964]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [X] My issue happened while using mods.

### What happened?

Translation error fixed earlier appears again.

![2023-10-31_14-27-29 (2)](https://github.com/Regalis11/Barotrauma/assets/47295383/de111861-79e2-42e3-a834-406bb3581a74)

[Mining minerals mission description has an error in reward percentage](https://github.com/Regalis11/Barotrauma/issues/11221)

We receive 75% as a reward and 25% is taken from us.
But description assumes that we receive 25% as a reward and 75% will be taken from us.

It would be correct to write: "вы должны передать нам 25%" (you must give us 25%)
or "наша доля - 25%" (our share is 25%)
or "Мы заберем 25% добычи". (We'll take 25% of the mined minerals.)

### Reproduction steps

1. Get any mining minerals mission
2. Choose russian language
3. Take a look on its description. The description has error.

### Bug prevalence

Happens every time I play

### Single player or multiplayer?

Happens in both single player and multiplayer

### Version

v1.1.19.3 (Treacherous Tides Hotfix 2)

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/9c7f2c95d6f0fa20c322b56a6da4c7a614b9537b

**Comment by Rokvach** [comment]
Tested, no issues. Closing.

**Comment by pavel4win** [comment]
This translation error still not corrected!

**Comment by Regalis11** [comment]
Which missions is it specifically? To me it seems like all of them use "Вы должны предоставить [handoverpercentage]" in Russian, is that not correct?

**Comment by Regalis11** [comment]
...Ah, nvm. The changes I did to the lines have been reverted for some reason, need to redo the fix. :/

**Comment by Regalis11** [comment]
Fixed again. Let's verify the fix is still there when we import the localization kit the next time. https://github.com/Regalis11/Barotrauma-development/commit/cc74ab13f29c19948cff19c84b73010f11a80c0d

**Comment by Regalis11** [comment]
Should be fixed for real now, fix coming up in the next update!
