### ISSUE TITLE
Creatures still have trouble targeting affliction-given tags

### ISSUE THREAD

**Issue by myrukun** [FakeFishGames/Barotrauma#12977]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [X] My issue happened while using mods.

### What happened?

Creature AI often ignores targets with a given tag from an affliction, for instance, SCP-096 will only attack characters with the "shyguy_target" tag which is given from an affliction.

I saw a post was made about this bug about a year ago, and even after being fixed it still happens.

![image_2023-11-06_015332566](https://github.com/Regalis11/Barotrauma/assets/72015194/88ed3f47-9978-45bf-a0b3-f213c6f0d90a)

[relevantxml.txt](https://github.com/Regalis11/Barotrauma/files/13265063/relevantxml.txt)

### Reproduction steps

1. Create a custom creature that targets a custom tag
2. Give a character that custom tag through a modded affliction
3. Watch the creature **not** target the character with the tag at all, and idle.

### Bug prevalence

Happens every time I play

### Single player or multiplayer?

Happens in both single player and multiplayer

### Version

v1.1.19.3 (Treacherous Tides Hotfix 2)

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment]
Insufficient information to address the issue, closing
