### ISSUE TITLE
NPC's idle in hull created between two docking ports

### ISSUE THREAD

**Issue by BlackMoons** [FakeFishGames/Barotrauma#12973]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [X] My issue happened while using mods.

### What happened?

NPC's seem to idle in the hull created where two docking ports join.

Or at least, many times after finishing some work inside my drone, the NPC's seem to idle, wandering back and forth in the exact docking port area. Once they get a new task, they freely leave indicating they are not 'stuck'.

Would suggest making sure that hull is created with 'avoid staying' flag set? 

### Reproduction steps

Have a sub where NPC's work in the drone (Patching a leak for example). Included is such a sub.

Let them finish work in the drone with no other tasks to do (Both airlocks are automatically set to 'avoid staying', and the rest of the drone is also set that way)

see NPC walk back and forth between drone airlock and hull between two docking ports.

Make a hole somewhere else. they leave and patch it just fine, so its not that they are 'stuck' so much as they.. just don't want to leave the most horrible place to hang out on the entire submarine that has no oxygen whatsoever (have I mentioned various NPC's have died in this drone mysteriously?)

[Bangkok 41.zip](https://github.com/Regalis11/Barotrauma/files/13258623/Bangkok.41.zip)

### Bug prevalence

Happens every now and then

### Single player or multiplayer?

Happens in both single player and multiplayer

### Version

v1.1.19.3 (Treacherous Tides Hotfix 2)

### Which operating system did you encounter this bug on?

Windows

**Comment by Jasontti** [comment]
Tested in: https://github.com/FakeFishGames/Barotrauma-development/pull/4627/commits/487b0e5491ecb75bd5a73ca7f516449dc8efd89f

Vertical docking ports are working fine
No issues found with anything in vanilla

Made horizontal docking ports and they seemed to work ok
Noting that horizontal docking ports are suspect of some jank on themselves

No issues found
Closing ticket
