### ISSUE TITLE
Steal clown crate from officer event ("censorship") is bugged

### ISSUE THREAD

**Issue by SoNickRND** [FakeFishGames/Barotrauma#12988]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

I got to the station chief first and took the usual missions.
Took the crate with honks, and nobody worried.
Get to clowns (and one guardian came with me)
Took a quest from the clown, and right after that guardian asked me why I took the crate.
I lied to him, and after that quest toaster said "sadly, you return empty-handed" (or like that)
But I still have the crate with honks In my hands! 
![image](https://github.com/Regalis11/Barotrauma/assets/125238/5637958c-b58b-4548-906b-dff376d8c162)

### Reproduction steps

I playing the campaign on easy.
I got to the station chief first and took the usual missions.
Took the crate with honks, and nobody worried.
Get to clowns (and one guardian came with me)
Took a quest from the clown, and right after that guardian asked me why I took the crate.
I lied to him, and after that quest toaster said "Sadly, you return empty-handed" (or like that)
But I still have the crate with honks In my hands! 
![image](https://github.com/Regalis11/Barotrauma/assets/125238/5637958c-b58b-4548-906b-dff376d8c162)

### Bug prevalence

Just once

### Single player or multiplayer?

Single player

### Version

v1.1.19.3 (Treacherous Tides Hotfix 2)

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/856e54f8f52b91dcbb9399f2a101c6bdf5bd082c (commit in our private repo).

Note for testing: this event is called 'censorship' and can be triggered using `triggerevent censorship`.

**Comment by Jasontti** [comment]
Tested in: https://github.com/FakeFishGames/Barotrauma-development/pull/4592/commits/740d82c6f74956cdda620c199f5516f53abb4ab5

Tested as part of larger event PR: https://github.com/FakeFishGames/Barotrauma-development/pull/4592

No issues found
Closing ticket
