### ISSUE TITLE
Flak Bolt won't spawn shrapnels indoors

### ISSUE THREAD

**Issue by zhu-rengong** [FakeFishGames/Barotrauma#12994]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

As the title said.

### Reproduction steps

1. Shoot Flak Bolt

### Bug prevalence

Just once

### Single player or multiplayer?

Multiplayer hosted using a dedicated server

### Version

v1.1.19.3 (Treacherous Tides Hotfix 2)

### Which operating system did you encounter this bug on?

Windows

**Comment by zhu-rengong** [comment]
Oh, I misjudged, I was blind.

**Comment by zhu-rengong** [comment]
I finally know why I want to open this issue. It seems that the moment Shrapnel is spawned in Air, it will be judged to be in the water.
You can add the following code to flakshrapnel's Projectile:
```xml
<StatusEffect type="OnActive" target="This">
   <Remove />
   <Conditional inwater="true" />
</StatusEffect>
```
When spawned indoors, it will be removed immediately.

**Comment by Jasontti** [comment]
Tested.
Shrapnel can be seen exiting the hull and when they are in water trails can be seen.
Could not discern any gameplay issue from this.
Closing ticket.

https://github.com/FakeFishGames/Barotrauma/assets/8488224/9b8d7fc3-efcb-46ab-b9c2-63f4f3497305
