### ISSUE TITLE
Why doesn't Event Manager work in test started from the submarine editor?

### ISSUE THREAD

**Issue by zhu-rengong** [FakeFishGames/Barotrauma#13010]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [X] My issue happened while using mods.

### What happened?

I'm modding some items, when trigger some events, they will register some scripted events but do nothing in test started from the sub editor.

### Reproduction steps

1. Make a mod with an item that can be used to register some scripted events, here're an example: https://github.com/Regalis11/Barotrauma/issues/12601
2. Start with the mod provided by the above example in test started from the submarine editor.
3. Open the console and type "spawnitem revolver_conversationaction100options inventory".
4. Shoot a revolver round
5. It should prompt you a dialog but it doesn't

### Bug prevalence

Happens every now and then

### Single player or multiplayer?

Single player

### Version

v1.1.19.3 (Treacherous Tides Hotfix 2)

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment]
Addressed in https://github.com/Regalis11/Barotrauma-development/commit/28d8f2ddea3fad698f8ea181f4ac38aaeaea594c

**Comment by Regalis11** [comment]
Tested, no issues found
