### ISSUE TITLE
Dedicated server steam authentication failed

### ISSUE THREAD

**Issue by mllightitup** [FakeFishGames/Barotrauma#13049]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

I'm trying to create my own dedicated server without mods. I used this step by step guide https://barotraumagame.com/wiki/Hosting_a_Dedicated_Server
Also for port forwarding I tried to use radmin vpn and hamachi.
The problem is clearly somewhere on the game side, as in any other games (project zomboid, minecraft, etc.) where you can create a dedicated server no problems occur.
After starting the server I can personally log in to the server using both local ip (localhost) and my public ip provided by hamachi or radmin vpn. But my friends get the error "Steam authentication failed" when trying to access the server. In the serversettings.xml file I tried to change the enableupnp and IsPublic parameter to true and false, but it doesn't work.

### Reproduction steps

1. Download radmin vpn
2. Create network
3. invite your friend
4. follow steps from official guide to host server(with steamcmd)
5. ask your friend to join server via your radmin ip

### Bug prevalence

Happens regularly

### Single player or multiplayer?

Multiplayer hosted using a dedicated server

### Version

v1.1.19.3 (Treacherous Tides Hotfix 2)

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment]
Thank you for the report! Which of the hosting methods listed in the wiki are you using? If you want to use Steam networking (and Steam authentication), you need to host it using SteamCMD.

**Comment by mllightitup** [comment]
> Thank you for the report! Which of the hosting methods listed in the wiki are you using? If you want to use Steam networking (and Steam authentication), you need to host it using SteamCMD.

I used steamcmd. If I understand correctly, it is impossible to create a server for a local network (created with programs like hamachi or radmin vpn). Let me clarify that I was able to create a server directly without any additional programs (by forwarding the ports in the router settings). Let me clarify that I was able to create a server directly without any additional programs (by forwarding ports in the router settings), as I have a normal public ip, but some people due to provider restrictions have Private IPv4 addresses(https://en.wikipedia.org/wiki/Private_network) and do not have such an opportunity as I do, and are forced to use such programs

**Comment by mllightitup** [comment]
If necessary I can record a video of exactly what I do and what results I get.

**Comment by FOHADER** [comment]
DId you solve the problem?

**Comment by mllightitup** [comment]
> DId you solve the problem?

No. This can only be bypassed by TRUE port forwarding through a router and having a public ip from the ISP.
In the situation when such vpn services are used, steam tries to communicate for authentication or something like that with external resources via hamachi or radmin vpn ip address. And since it is a private and closed local network between people, it can't go outside of it and address public ips. I think it works something like this, but maybe I'm wrong

**Comment by mllightitup** [comment]
This will probably result in people on the same LAN, with the internet turned off, not being able to join each other anyway due to steam trying to check something. Even if they are sitting near each other and connected to the same wifi

**Comment by Rein-chan** [comment]
With the release of version v1.1.18.0 (Treacherous Tides (19 oct 2023)) this problem appeared and still causes a lot of inconvenience to people. you have known this for more than three months. please provide a solution.

**Comment by Regalis11** [comment]
I now (finally) looked into this more closely. Back in older versions of the game (way before 1.0) it used to be possible to remove the Steam authentication requirement by setting the value RequireSteamAuthentication to "false" in the server settings. This functionality seems to have gotten lost at some point during the years.

I've now readded this functionality ([commit in our private repo](https://github.com/FakeFishGames/Barotrauma-development/commit/5e1ec5a5725fd24ee5f66c14597cc1f2d6aa1d57)), so once that change goes out, it should be possible to get the server working without a connection to Steam by adding RequireAuthentication="false" to the server config file.

Sorry for the inconvenience, and sorry for taking so long to address this!

**Comment by mllightitup** [comment]
> I now (finally) looked into this more closely. Back in older versions of the game (way before 1.0) it used to be possible to remove the Steam authentication requirement by setting the value RequireSteamAuthentication to "false" in the server settings. This functionality seems to have gotten lost at some point during the years.
> 
> I've now readded this functionality ([commit in our private repo](https://github.com/FakeFishGames/Barotrauma-development/commit/5e1ec5a5725fd24ee5f66c14597cc1f2d6aa1d57)), so once that change goes out, it should be possible to get the server working without a connection to Steam by adding RequireAuthentication="false" to the server config file.
> 
> Sorry for the inconvenience, and sorry for taking so long to address this!

Is this fix coming out with the "Blood in the water" update?

**Comment by Regalis11** [comment]
Unfortunately not, I was implemented so close to the release that we didn't have time to get it tested in time for the update. :/ But most likely in the next update!

**Comment by NilanthAnimosus** [comment]
This should be in the next update (likely the next unstable too!), closing as resolved.
