### ISSUE TITLE
`RequireAimToUse` is forced true when an item has `RangedWeapon` component

### ISSUE THREAD

**Issue by BiffW** [FakeFishGames/Barotrauma#13050]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [X] My issue happened while using mods.

### What happened?

While trying to create a weapon mod that can shoot and activate something special when not aiming. I discovered this behavior hard-coded.
It seems to be related to [these code](https://github.com/Regalis11/Barotrauma/blob/71b710641b6b3df60d03adf0dab772b6f5def528/Barotrauma/BarotraumaShared/SharedSource/Items/Components/Holdable/RangedWeapon.cs#L132C18-L132C33).

### Reproduction steps

1. create a modded glowstick by adding a `RangedWeapon` component to it
3. the glow stick can no longer be activated without aiming

### Bug prevalence

Happens every time I play

### Single player or multiplayer?

Single player

### Version

v1.1.19.3 (Treacherous Tides Hotfix 2)

### Which operating system did you encounter this bug on?

Windows

**Comment by BiffW** [comment]
It would make more sense to make it a property of `ItemComponent` instead of `Item`.

**Comment by itchyOwl** [comment]
Tested, working correctly.
