### ISSUE TITLE
Sonar issues (mountains and entrances not displayed correctly)

### ISSUE THREAD

**Issue by Vykn** [FakeFishGames/Barotrauma#13061]
### What happened?

Two issues, somewhat related -

- When ascending near abyss mountains, any terrain higher than the submarine does not appear on active sonar. Most prominent in Europan Ridge levels, which have a very steep mountain.

https://github.com/Regalis11/Barotrauma/assets/37850646/02f21de6-ef4d-414a-ae05-16ab52ed8477

- Some structures are not shown correctly. Very notable in the EndOutpost_Entrance - you can't actually see the entrances unless you're at a very specific angle, but happens in regular ruins as well.

https://github.com/Regalis11/Barotrauma/assets/37850646/93f3d54b-0953-44ec-bc69-33bd2586eed7

https://github.com/Regalis11/Barotrauma/assets/37850646/b898a634-ee14-42d8-a5c3-b7f8b24b91f5

https://github.com/Regalis11/Barotrauma/assets/37850646/48139795-dfb7-43a7-9502-417e9504c65f

It was expected that the sonar should show what is actually there.

### Reproduction steps

1. Go to the level editor and load a Europan Ridge level, teleport the sub down the the bottom of the abyss
2. Ascend while next to the mountain with active sonar on
3. Observe that part of the mountain does not appear

1. Go to the submarine editor and load the EndOutpost_Entrance.
2. Observe that the sonar does not show what the structure looks like

### Version

Both stable (v1.1.19.3) and unstable (v1.2.1.0)

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/pull/4673

**Comment by Jasontti** [comment]
Tested in: https://github.com/FakeFishGames/Barotrauma-development/pull/4673/commits/e7e97d0a860524aed3465074c163bf159230933e

Tested cases mentioned by Vyk, no issues.

New issue:
Ice spires and floating island don't show up in radar.
Sometimes you get a small blip of spire and it then vanishes.

Picture of floating island:
![2024-01-26_16-54](https://github.com/FakeFishGames/Barotrauma/assets/8488224/cc65efd9-9d2f-408f-8318-1b59c1bd9254)

**Comment by Regalis11** [comment]
Fixed in https://github.com/FakeFishGames/Barotrauma-development/pull/4673/commits/1050bbdb4de045e5834881f097dd57fe1f476f1f

**Comment by Jasontti** [comment]
Tested in: https://github.com/FakeFishGames/Barotrauma-development/pull/4673/commits/1050bbdb4de045e5834881f097dd57fe1f476f1f

Spires and floating islands work

It looks like wall rendering in sonar is now referencing inside walls

![baro-sonar-issue2](https://github.com/FakeFishGames/Barotrauma/assets/8488224/a0aed240-c767-4e09-a4c2-128120f884cf)
![baro-sonar-issue3](https://github.com/FakeFishGames/Barotrauma/assets/8488224/698ca2d6-5b0f-4efb-bc0a-557bd9c72d0e)

**Comment by Jasontti** [comment]
Tested again: https://github.com/FakeFishGames/Barotrauma-development/pull/4673/commits/d3290010ab432e9dd6a41e01ad07c6931ced2c2b

No issues found
Closing ticket
