### ISSUE TITLE
Error in the number of items on the submarine during the sale

### ISSUE THREAD

**Issue by DyadkaRuslan** [FakeFishGames/Barotrauma#13060]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

I'm starting a campaign without mods for dugongs. I approach the dealer as an engineer, 18 revolver cartridges are indicated in the "submarine" tab. And there are only 12 of them. The "sell" tab lists 5 screwdrivers and wrenches, although there are only 3 of them at the beginning.

### Reproduction steps

![20231119195417_1](https://github.com/Regalis11/Barotrauma/assets/83873243/91bd0a78-1493-419f-91e9-8fe704e7e36b)
![20231119195424_1](https://github.com/Regalis11/Barotrauma/assets/83873243/cc385595-679d-4698-a7b9-0f64a5749498)
[Save.zip](https://github.com/Regalis11/Barotrauma/files/13403921/Save.zip)

### Bug prevalence

Happens every now and then

### Single player or multiplayer?

Single player

### Version

v1.1.19.3 (Treacherous Tides Hotfix 2)

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment]
The value at the bottom is how many items you own in total, not the number of items in the submarine. I wonder if there's been some mistranslation here that makes it less clear in Russian? In English the top value says "Submarine" and the bottom one "Owned".

**Comment by DyadkaRuslan** [comment]
In the upper screenshot, the first value is a submarine, and the second is in the inventory. And the second one is not correct, because we have 12 rounds in total, not 18

**Comment by pavel4win** [comment]
I see this bug in every game. And I created a similar topic myself. 

https://github.com/Regalis11/Barotrauma/issues/12712

It feels like some of my items are being counted twice. However, if you save the game and load it, the quantity error usually disappears for some time. It’s as if there is some kind of temporary variable that not have been reset properly and it distorts the counter.

**Comment by Regalis11** [comment]
@pavel4win discovered a way to reproduce this (see https://github.com/Regalis11/Barotrauma/issues/13281).

Should be fixed in https://github.com/Regalis11/Barotrauma-development/commit/deeaa0f3557e9b6762ce35f42be85dc9f83e8ca8 (commit in our private repo).

**Comment by Rokvach** [comment]
Tested, working correctly. Can be merged and closed.
