### ISSUE TITLE
Autopilot to destination from abyss doesn't manage to go there

### ISSUE THREAD

**Issue by JeroonBosch** [FakeFishGames/Barotrauma#13077]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

Fought a Charybdis in the abyss, set a bot to autopilot me to the destination.

### Reproduction steps

1. Campaign in 3rd biome (theaphoticplateau, level seed LpqJ1YYP) with Winterhalter
2. Descend to the abyss, fought a charybdis but shouldn't matter if you fight or not
3. Get to the bottom of the abyss, away from any paths (as seen on debugai)
4. Submarine navigates to sidepath but no further, see screenshots
![image](https://github.com/Regalis11/Barotrauma/assets/8641689/033bd464-25e6-4cab-8d2c-63e39c06eb45)
![image](https://github.com/Regalis11/Barotrauma/assets/8641689/e0f70c2a-dc1a-4720-87ff-98124ebe9f6d)

Save:
[Testcase_Lategame.zip](https://github.com/Regalis11/Barotrauma/files/13451245/Testcase_Lategame.zip)

### Bug prevalence

Just once

### Single player or multiplayer?

Single player

### Version

v1.2.1.0 (Unstable)

### -

fix/big-monsters-through-wall branch

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment]
I'm afraid I couldn't find a way to repro this. Seems that the level I'm getting when loading this save isn't the same as in the screenshots. Tested in v1.2.1.0 (Unstable) and https://github.com/FakeFishGames/Barotrauma-development/commit/3927e98 (commit on the fix/big-monsters-through-wall branch the day this ticket was created).

**Comment by Regalis11** [comment]
No known steps to repro, closing
