### ISSUE TITLE
Flamer issue

### ISSUE THREAD

**Issue by EebleSheembl** [FakeFishGames/Barotrauma#13099]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

Flamer doesn't work and fuel is upside-down while facing left 

### Reproduction steps

Be in unstable
get a flamer with fuel
face to the left
use it

### Bug prevalence

Happens every time I play

### Single player or multiplayer?

Single player

### Version

v1.2.3.0 (Unstable)

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment]
Thank you for the report! The mirrored tank is a [known issue](https://github.com/Regalis11/Barotrauma/issues/13083), and we've got a fix coming up for that one in the next unstable build.

I couldn't find any other issues with the flamer though, could you describe how exactly it doesn't work? Does it just not do anything?

**Comment by Regalis11** [comment]
Insufficient information to address the issue, closing
