### ISSUE TITLE
(Unstable) Player Direction and Click Placement Not Working

### ISSUE THREAD

**Issue by Dathomerian554** [FakeFishGames/Barotrauma#13112]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

I'm not exactly sure how many bugs are being reported here, but at least two.  
First, unstable version 1.2.4.0 has an issue where the character cannot change direction (unless you click on say a steel cabinet, which will change the character's direction to whether the mouse is on the left or right).  This issue does not seem to be affecting bots, but severely impacts a real player.  
Second, it has become nearly impossible to click on specific items in the sub, such as doors.  For some reason it is obsessed with being locked onto one item (such as something on the floor or even in-sub lighting).  
The error message provided below happened when I attempted to place a text display inside my sub.  However I couldn't accomplish this simple task because of the fact that selecting specific things (even in the grid for placing items on the sub) is currently extremely difficult if not impossible.  

### Reproduction steps

https://github.com/Regalis11/Barotrauma/assets/144430175/11f2e4f8-3a64-4501-b17c-24011096665f

1. Open Barotrauma Campaign.
2. Move Character left and right, noticing character does not change direction.
3. Click on an item, such as a door, noticing it is extremely difficult to select said item.

### Bug prevalence

Happens every time I play

### Single player or multiplayer?

Single player

### Version

Other

### -

1.2.4.0

### Which operating system did you encounter this bug on?

MacOS

### Relevant error messages and crash reports

```shell
Attempted to move the item Text Display to an invalid position ([X:NaN Y:NaN])
	at System.Environment.get_StackTrace()
	at Barotrauma.Item.SetTransform(Vector2 simPosition, Single rotation, Boolean findNewHull, Boolean
setPrevTransform) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Items\Item.cs:line 1502
	at Barotrauma.Items.Components.Holdable.Use(Single deltaTime, Character character) in
<DEV>\Barotrauma\BarotraumaShared\SharedSource\Items\Components\Holdable\Holdable.cs:line 758
	at Barotrauma.Item.Use(Single deltaTime, Character user, Limb targetLimb, Entity useTarget, Character
userForOnUsedEvent) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Items\Item.cs:line 3077
	at Barotrauma.Character.Control(Single deltaTime, Camera cam) in
<DEV>\Barotrauma\BarotraumaShared\SharedSource\Characters\Character.cs:line 2223
	at Barotrauma.Character.Update(Single deltaTime, Camera cam) in
<DEV>\Barotrauma\BarotraumaShared\SharedSource\Characters\Character.cs:line 3366
	at Barotrauma.AlCharacter.Update(Single deltaTime, Camera cam) in
<DEV>\Barotrauma/BarotraumaShared/SharedSource/Characters/AlCharacter.cs:line 38
	at Barotrauma.Character.UpdateAll(Single deltaTime, Camera cam) in
<DEV>\Barotrauma\BarotraumaShared\SharedSource\Characters\Character.cs:line 3138
	at Barotrauma.GameScreen.Update(Double deltaTime) in
<DEV>\Barotrauma\BarotraumaShared\SharedSource\Screens\GameScreen.cs:line 185
	at Barotrauma.GameMain.Update(GameTime gameTime) in
<DEV>\Barotrauma\BarotraumaClient\ClientSource\GameMain.cs:line 855
	at Microsoft.Xna.Framework.Game.DoUpdate(Game Time game Time) in
<DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 651
	at Microsoft.Xna.Framework.Game.Tick() in
<DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 500
	at Microsoft.Xna.Framework.SdlGamePlatform.RunLoop() in
<DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\SDL\SDLGamePlatform.cs:line 93
	at Microsoft.Xna.Framework.Game.Run(GameRunBehavior runBehavior) in
<DEV>\Libraries\MonoGame.Framework\5rc\MonoGame.Framework\Game.cs:line 397
	at Microsoft.Xna.Framework.Game.Run() in
<DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 367
	at Barotrauma.Program.Main(String[] args) in
<DEV>\Barotrauma\BarotraumaClient\ClientSource\Program.cs:line 58
```

**Comment by Dathomerian554** [comment]
What's strange is it does not seem to be occurring anymore on my end either, even though I made sure to quit the game several times before to double check it was an issue.  I am not using any mods.  I'm still wondering why I got that error message though.

**Comment by Regalis11** [comment]
No known steps to repro, closing
