### ISSUE TITLE
beacon station shows as inactive when moving to an empty node

### ISSUE THREAD

**Issue by JeroonBosch** [FakeFishGames/Barotrauma#13128]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

Beacon station still shows as inactive when moving to an empty node and opening the map.
The "Mission complete" and rewards of any missions (including beacon station mission) only show after selecting a new location from the empty node. Thus opening the map still shows an inactive beacon station, giving the impression the mission isn't done yet.

### Reproduction steps

1. Play a campaign
2. Activate a beacon station on a route where it ends in an empty node
3. At the end of the level, open the map. Notice how the beacon station still shows inactive
4. Select next destination, notice getting a reward for the beacon station and it showing correctly as active only from the next time you open the map.

### Bug prevalence

Happens every time I play

### Single player or multiplayer?

Happens in both single player and multiplayer

### Version

v1.1.19.3 (Treacherous Tides Hotfix 2)

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment]
Does not seem to require an empty node, the icon just doesn't change until the round ends and the mission completes. Fixed in https://github.com/Regalis11/Barotrauma-development/commit/4d947508832af2ffbbd3cf9e4f3fc9befd827a56

**Comment by Jasontti** [comment]
Tested in: https://github.com/FakeFishGames/Barotrauma-development/pull/4760/commits/07da099e8527114ed52829c06731ece7b06ec4fd

Tested with steps above and with path ending in normal outpost

No issues found
Closing ticket
