### ISSUE TITLE
Stun baton stuck to my knees.

### ISSUE THREAD

**Issue by SoNickRND** [FakeFishGames/Barotrauma#13135]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

I bring some corpses to sub, loot 'em and baton stuck to my knees.
![image](https://github.com/Regalis11/Barotrauma/assets/125238/602d8dee-8c59-4584-add1-a2f8af6c9826)

### Reproduction steps

I bring some corpses to sub, loot 'em and baton stuck to my knees.
![image](https://github.com/Regalis11/Barotrauma/assets/125238/602d8dee-8c59-4584-add1-a2f8af6c9826)

### Bug prevalence

Just once

### Single player or multiplayer?

Single player

### Version

v1.1.19.3 (Treacherous Tides Hotfix 2)

### Which operating system did you encounter this bug on?

Windows

**Comment by SoNickRND** [comment]
I can pick it, but If I drop it, it stuck again, even if floor is clean

**Comment by Jasontti** [comment]
Thank you for your report, but could not reproduce this.
Closing this for now until more information or this happens again.
