### ISSUE TITLE
Action Type OnOpen/OnClose is works only for client

### ISSUE THREAD

**Issue by Fachoj** [FakeFishGames/Barotrauma#13144]
Make it work on server too, or add precautions in description of these action types in Enums.cs

**Comment by Fachoj** [comment]
[`243c7f9`](https://github.com/Regalis11/Barotrauma-development/commit/243c7f92e9689aa8055d1bab3311316b72911980) Fixed OnOpen and OnClose statuseffects not doin... - Regalis11

**Comment by Fachoj** [comment]
https://steamcommunity.com/sharedfiles/filedetails/?id=3111258795 
My mod with workaround

**Comment by NilanthAnimosus** [comment]
This has been fixed now (Where OnClose and OnOpen effects will trigger clientside and server side status effects) for an upcoming update. Closing.
