### ISSUE TITLE
W key gets stuck

### ISSUE THREAD

**Issue by GurnetGurnet** [FakeFishGames/Barotrauma#13143]
Whenever i tab in, or just randomly, it holds W until i press W again. This is very annoying and only works for W, it also only works in Barotrauma. It has previously never done this before and has now done this on multiple servers. It even does this when im in the chat box. Please fix, Bad Bug

**Comment by GurnetGurnet** [comment]
Scratch the E part, it does also work with E and does also force me to go up, while it still types W in chat

**Comment by GurnetGurnet** [comment]
An uninstall and reinstall has not fixed it.

**Comment by GurnetGurnet** [comment]
Now it works sometimes outside of barotrauma, *seemingly* when switching from the game window to anything else, it only presses the w key twice when i alt-tab into barotrauma and only once when i alt-tab out.

**Comment by Regalis11** [comment]
Thank you for the report!

> Now it works sometimes outside of barotrauma, seemingly when switching from the game window to anything else, it only presses the w key twice when i alt-tab into barotrauma and only once when i alt-tab out.

If the issue occurs outside barotrauma too, to me this sounds like it might be an issue with your keyboard or system.

**Comment by Regalis11** [comment]
No known steps to repro, seems probable that this is an issue with the user's keyboard or system since it happens outside barotrauma too.
