### ISSUE TITLE
Lights turn on slowly, but only the first time they are turned on

### ISSUE THREAD

**Issue by mygamingaccount** [FakeFishGames/Barotrauma#13159]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

If there is a light that is off at the start of the round, then when you switch it on, it will glow brighter slowly.

But every subsequent time you switch it off or on it happens instantly.

I believe this is unintended.

[lights.webm](https://github.com/Regalis11/Barotrauma/assets/68995233/dadd3750-f587-4c02-b4e1-96ee9da23944)

### Reproduction steps

Editor
Add a light component
Add a button
Connect them
Test
Click

Expected: turning it on and off it does the same thing every time
Result: first time it turns on is special for some reason

### Bug prevalence

Happens every time I play

### Single player or multiplayer?

Single player

### Version

v1.2.6.0 (Winter Update)

### Which operating system did you encounter this bug on?

Linux

**Comment by Regalis11** [comment]
It seems the lights do this and play the "zapping" sounds the first time they're powered. This is such ancient code that I'm not 100% sure what the original intention was, but to me it seems like this is not a bug, but an intentional effect when the sub first powers up.
