### ISSUE TITLE
Mechanic Bot - No Diving Mask Available, small leak in ballast, aborts task

### ISSUE THREAD

**Issue by ODonnellBP** [FakeFishGames/Barotrauma#13167]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

If a bot assigned to Fix Leaks is alerted to a hull leak in an unpressurized ballast room and no diving masks are available, they will abort the task and go idle, despite the availability of diving SUITS.

If a small leak happens in a normal room, the bot will attend the task
If a large leak happens in a normal room and the room is pressurized, the bot will get an available diving suit and attend the task
If a small leak happens in a ballast room, the bot will say "Need to find a diving suit!", go find a diving mask and attend the task.  If there is no diving mask available, the bot will abort the task and go idle despite available diving suits.  If this leak in the ballast becomes large enough to pressurize the room the bot will then go get a diving suit and attend the task.

### Reproduction steps

1. start a campaign (or a test in custom)
2. collect and remove from bot's availability all diving masks
3. make sure diving suits are available
4. assign a bot with a welding torch the Fix Leaks task
5. create a small hole in the ballast (small enough the pump compensates and doesn't pressurize the room)

### Bug prevalence

Happens every time I play

### Single player or multiplayer?

Other

### -

It relates to bot activity, happens in single/multiplayer

### Version

v1.2.6.0 (Winter Update)

### Which operating system did you encounter this bug on?

Windows

**Comment by NilanthAnimosus** [comment]
Closing as tested and merged (should be fixed in the next update!)
