### ISSUE TITLE
Tooltip hover text does not update to new keybinds during same session

### ISSUE THREAD

**Issue by Arctodites** [FakeFishGames/Barotrauma#13169]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

The tooltip hover text for actions such as 'use,' heal,' or 'grab' does not update to reflect new keybinds during the same session of a game, either during a round or between rounds (at outposts), at least in singleplayer.  I have to close and relaunch the game before a refresh will take effect (playing via Steam on Windows 10 Home 64-bit (10.0, Build 19045) (19041.vb_release.191206-1406)).

### Reproduction steps

1.) start a singleplayer campaign game
2.) rebind one or more keys (e.g. 'grab' from [G] to [F])
3.) test to make sure that the new keybind has taken effect
4.) note that the tooltip hover text has not updated to the new keybind and will not refresh until one closes out of the game session

### Bug prevalence

Happens every time I play

### Single player or multiplayer?

Single player

### Version

v1.2.6.0 (Winter Update)

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/7942647740f3280a97cbd359772ea2c30a60dbda (commit in our private repo)
