### ISSUE TITLE
Mining spot unreachable

### ISSUE THREAD

**Issue by ohan2** [FakeFishGames/Barotrauma#13165]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

During a mission to mine Titanite ore, I couldn't find any path from the cave entrance to the ore location that's marked on the sonar. 
![Mineral deposit sealed off](https://github.com/Regalis11/Barotrauma/assets/22153954/ffcf2817-954a-47d3-9153-29e379dd0004)

This is the first time I've encountered this issue during ~50 hours of play time.

### Reproduction steps

1. Start singleplayer campain.
2. Keep playing mining missions until issue is encountered?

### Bug prevalence

Just once

### Single player or multiplayer?

Single player

### Version

v1.2.6.0 (Winter Update)

### Which operating system did you encounter this bug on?

Linux

**Comment by SomeRandomNoobKekeke** [comment]
This wall on the left looks like ice, couldn't you just drill it with plasma cutter?

**Comment by Regalis11** [comment]
Thank you for the report! Would you happen to have the save file available so we could give it a test?

**Comment by ohan2** [comment]
Hi, I think that's the case. I later came across a YouTube video showing
that the wall can be drilled through but I've already skipped the mission.
Thanks for the heads up. I haven't needed to drill through walls and I
don't recall being informed about this in the tutorial or tooltips, though
I could be wrong.

**Comment by Regalis11** [comment]
Insufficient information to address the issue, closing
