### ISSUE TITLE
the audio for the Aphotic plateau broke, and just started SPAMMING the message box

### ISSUE THREAD

**Issue by CanadianCanuck021** [FakeFishGames/Barotrauma#13176]
![Screenshot 2023-12-15 220428](https://github.com/Regalis11/Barotrauma/assets/153968508/503342ee-7632-4e33-9b57-d4b15a652751)
It just froze my game entirely
I have absolutely no idea how to give any information on this, so sorry if it doesnt help.

**Comment by Regalis11** [comment]
No known steps to repro, closing
