### ISSUE TITLE
CanTransfer doesn't work on junctionbox

### ISSUE THREAD

**Issue by iridescent-lightning** [FakeFishGames/Barotrauma#13184]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [X] My issue happened while using mods.

### What happened?

According to the source code (shared), the powertransfer should stop working if you assign false to cantransfer. However, it only turns off the light of the junctionbox, the power is still delivered. Is there something I did wrong?

### Reproduction steps

Either use lua or C# harmony to mode the codes, make CanTransfer = false; 
Nothing works intended. You can just copy the script and use it with Csforbarotrauma. (remove the check fuse part, that's mod content)

using System.Reflection;
using Barotrauma;
using Barotrauma.Items.Components;
using HarmonyLib;

using Microsoft.Xna.Framework;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Xml.Linq;

namespace PowerTransferMod
{
    class PowerTransferMod : IAssemblyPlugin
    {
        public Harmony harmony;
        
        private static Item fuse;
        private static ItemContainer itemContainer; 
        public void Initialize()
        {
            harmony = new Harmony("reactormod");

            harmony.Patch(
                original: typeof(PowerTransfer).GetMethod("Update"),
                pretfix: new HarmonyMethod(typeof(PowerTransferMod).GetMethod(nameof(Updateprefix)))
            );
            
        }

        public void OnLoadCompleted() { }
        public void PreInitPatching() { }

        public void Dispose()
        {
            harmony.UnpatchAll();
            harmony = null;
        }

        public static void Updateprefix(float deltaTime, Camera cam, PowerTransfer __instance)
        {
            PowerTransfer _ = __instance;
            itemContainer = _.item.GetComponent<ItemContainer>();
            if (itemContainer == null){return;}//this is important because it will crash the game if the item doesn't have an item container during the first frame of the game
            
            fuse = _.item.GetComponent<ItemContainer>().Inventory.GetItemAt(0) as Item;
            if (fuse == null || fuse.Condition <= 0)
            {
                _.CanTransfer = false;
                return;
            }
            else
            {
                _.CanTransfer = true;
            }
            
        }
    }
}

### Bug prevalence

Happens every time I play

### Single player or multiplayer?

Happens in both single player and multiplayer

### Version

v1.2.6.0 (Winter Update)

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment]
(Finally) merged the fix to our private repo, fix coming up in a future update
