### ISSUE TITLE
Mass fabricating items drop outside of fabricator due to no stacking (quality RNG)

### ISSUE THREAD

**Issue by ubertpendragon** [FakeFishGames/Barotrauma#13196]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

When mass fabricating items in the fabricator, some will drop outside because Items of different quality cannot stack.

![image](https://github.com/Regalis11/Barotrauma/assets/73229309/92321a39-cb20-4369-98fc-e030dea13dd5)
![image](https://github.com/Regalis11/Barotrauma/assets/73229309/680398bb-e6e2-4d01-99fa-ac90bd7b0813)

Either make quality items stack (which has its own problems) or remove crafting RNG?

### Reproduction steps

1. Fabricator with Sodium + Phosphorous
2. `setskill all 80`
3. Craft multiple UEX

### Version

v1.2.6.0 (Winter Update)

**Comment by mygamingaccount** [comment]
It's like the slot machines spitting out coins when you hit jackpot

**Comment by Regalis11** [comment]
This is intentional

**Comment by pavel4win** [comment]
It would be reasonable to design 4 cells for the fabricated goods at the fabricator, then all created  products will be distributed among them.

**Comment by Arctomachine** [comment]
Dropped items often clip through floor. They are impossible to pick up and soon disappear completely.
Solutions other than already proposed:
- increase output slots to 2
- allow outputting into container placed in input slots
- allow placing container into output slot
- add new slot specifically for output container to where stackable items go after craft

**Comment by JeroonBosch** [comment]
implemented in e6b62cc6dff8731fae0c2dac4f670b6b9c5c78b6

**Comment by Rokvach** [comment]
Tested, working correctly. Can be merged and closed.
