### ISSUE TITLE
Tinkered devices appear repairable but can't be repaired (repair threshold discrepancy)

### ISSUE THREAD

**Issue by MissPotato** [FakeFishGames/Barotrauma#13209]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

I took the tinkerer talent in a multiplayer server where I am a client. Buildings that I can repair past 100% will say repairable above when they are actually repairable.  For example, a pump will be at 85% health. The context menu will highlight"press e to repair" but when attempting to repair the building only the pump slider menu will appear. 

### Reproduction steps

1) Join multiplayer as mechanic
2) Pick the Tinkerer talent
3) Wait for building to get close to repairable %
4) Attempt to repair it, but menu doesn't appear

### Bug prevalence

Happens every time I play

### Single player or multiplayer?

Multiplayer hosted from the in-game menu (= using a listen server)

### Version

v1.2.7.0 (Winter Update hotfix)

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment]
Thank you for the report!

I'm not actually entirely sure this is a bug. The tinkerer talent allows you to repair past 100%, but it doesn't affect the threshold at which the item becomes repairable. The repair threshold for pumps for example is 80%, so to me it sounds like this is working as expected.

**Comment by MissPotato** [comment]
The bug is that the client incorrectly thinks that it can repair things
that are above the threshold. It seems to treat as if the threshold was
also increased by the talent.

In other words, the default action for a client holding a wrench when
attempting to interact with a building is to try and open the repair
minigame. The context menu displays as is the building is ready to be
repaired.

This means the only way for a player to actually know what they can repair
is to try and repair every building, or look at the electronics monitor and
know what every building's threshold is. As hovering over the building will
incorrectly display that it is ready to repair.

This is really easy to see by damaging a door, repairing it past 100%, the
slowly damaging the door and paying attention to when the context menu
incorrectly says you can repair it .

**Comment by Regalis11** [comment]
Thank you for the extra info, I think I got what the issue is now and fixed it in https://github.com/Regalis11/Barotrauma-development/commit/20fb2f3a803f98d8d5f5939064ccdebb0af2e33d (commit in our private repo).

Internal note for testing: this doesn't seem to be a multiplayer-specific issue, the same thing happens in single player too.
