### ISSUE TITLE
Projectiles can't Flip with weapons when it spawned or used by StatusEffect

### ISSUE THREAD

**Issue by MJJJJN11** [FakeFishGames/Barotrauma#13204]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [X] My issue happened while using mods.

### What happened?

    
    <Item identifier="TestGun" >
      <Holdable  >
        <StatusEffect type="OnUse" target="Contained" >
          <Use />
        </StatusEffect>
      </Holdable>
      <ItemContainer spawnwithid="TestBullet" >
        <Containable items="TestBullet" itempos="50,-2" rotation="0" />
      </ItemContainer>
    </Item>

    
    <Item identifier="TestGun" >
      <RangedWeapon >
        <StatusEffect type="OnUse" target="This" >
          <SpawnItem identifier="TestBullet" spawnposition="This" count="1" aimspread="0" rotationtype="Collider" rotation="0" />
        </StatusEffect>
      </RangedWeapon>
    </Item>

### Reproduction steps

Projectiles can't Flip with weapons if it **spawned** or **used** by StatusEffect.

https://github.com/Regalis11/Barotrauma/assets/149501175/8d98f428-75bc-46ef-afb2-9e970295448a

https://github.com/Regalis11/Barotrauma/assets/149501175/2905b210-7b7d-42f4-98ca-efee371d1308

### Bug prevalence

Happens every time I play

### Single player or multiplayer?

Single player

### Version

v1.2.6.0 (Winter Update)

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment]
Thank you for the report! Fixed in https://github.com/Regalis11/Barotrauma-development/commit/4c5f7c0b1aa36005170f74d0e56edc3b1f9ec4c0 (commit in our private repo)
