### ISSUE TITLE
Engineer tutorial objective list not properly registering return to automatic reactor control if done prior to objective list update

### ISSUE THREAD

**Issue by Nezumi-chan** [FakeFishGames/Barotrauma#13208]
### Disclaimers

- [x] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

When I switched back to automatic control after finishing the reactor tutorial segment of the Engineer tutorial,, but **before** I clicked the dialogue option to confirm those orders and the objective appeared on the list, the objective didn't get marked, and toggling it again still didn't mark it.. This seems to be purely cosmetic, as the tutorial did continue, and I was even able to complete it.

### Reproduction steps

1. Start the Roles tutorial. 
2. Continue until you get to the step where you are supposed to turn automatic control back on after finishing the manual control tutorial, but turn it on **before** you click the dialogue option confirming you understand you need to do so.
3. The objective will not be marked complete, though all other aspects of the tutorial work as intended.

### Bug prevalence

Happens every time I play

### Single player or multiplayer?

Single player

### Version

v1.2.7.0 (Winter Update hotfix)

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment]
Thank you for the report! Fixed in https://github.com/Regalis11/Barotrauma-development/commit/8286cdadc283b5a94154ef1eb27f7c84550bd59e (commit in our private repo)

**Comment by Rokvach** [comment]
Tested, working correctly. Can be merged and closed.
