### ISSUE TITLE
Diving suit lights shining out of a cabinet in the sub editor

### ISSUE THREAD

**Issue by Forch115** [FakeFishGames/Barotrauma#13217]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

After trying to put a diving suit in the closet, a headlamp appears
![Снимок экрана (544)](https://github.com/Regalis11/Barotrauma/assets/154619147/7d529b7c-3a13-463c-b4d8-e02bdafcfb43)

### Reproduction steps

1 Go to the submarine editor.
2 Place a cabinet for scuba gear (assembling this item also works).
3 Put any diving suit in the closet.
4 Turn on the light display.

### Bug prevalence

Happens regularly

### Single player or multiplayer?

Other

### -

 Submarine editor

### Version

v1.2.7.0 (Winter Update hotfix)

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/2c7d70453bd22da0beb2cabf4d62ada11f70a017 (commit in our private repo)

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
