### ISSUE TITLE
Clients wait indefinitely for mods on servers with AllowModDownloads disabled

### ISSUE THREAD

**Issue by cl0ck-byte** [FakeFishGames/Barotrauma#13211]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

https://github.com/Regalis11/Barotrauma/blob/8ea2b47889ede027c2214ce95f4f0d26b67ee450/Barotrauma/BarotraumaShared/SharedSource/Networking/ServerSettings.cs#L487-L491

https://github.com/Regalis11/Barotrauma/blob/8ea2b47889ede027c2214ce95f4f0d26b67ee450/Barotrauma/BarotraumaServer/ServerSource/Networking/FileTransfer/FileSender.cs#L410-L416

Currently, disabled mod uploads are handled in a weird way - client has no idea if server actually sends mods and the option for downloading mods off server is still visible despite server config. 

![pict00r](https://github.com/Regalis11/Barotrauma/assets/35605833/4c6d738a-f8c2-4201-bc2f-21e2a8c5c222)

For now, it just halts all uploads so clients wait indefinitely for server upload:

![pict00r2](https://github.com/Regalis11/Barotrauma/assets/35605833/b6ff36b5-7ac5-4d45-b922-9aae0dc3e52a)

Maybe server with `AllowModDownloads` disabled should send a message upon mod request, so that client will know about it? Players should be able to subscribe to mods instead of having to rejoin in order to fulfil requirements.

### Reproduction steps

`AllowModDownloads="False"` in server config XML
1. Start MP server
2. Client joins the server and requests mod download
3. Client receives nothing, waits indefinitely 

### Bug prevalence

Happens every time I play

### Single player or multiplayer?

Multiplayer hosted using a dedicated server

### Version

v1.2.7.0 (Winter Update hotfix)

### Which operating system did you encounter this bug on?

Windows

**Comment by NilanthAnimosus** [comment]
A fix has been made for this (https://github.com/FakeFishGames/Barotrauma-development/commit/2d14fd05d7b1ebd27ec5669f71a6fc660651de20 - But the details can't be seen as its in the private repo) though it reads:

"Fixed clients not getting notified in any way if the server they're trying to join doesn't allow sending mod files, causing the client to get stuck waiting indefinitely if they opt to download missing mods from the server. Now the client just gets the option to subscribe to the mods in the workshop or to cancel."

It will be included in the games code once its been tested by us, and then appear in the next patch.

**Comment by NilanthAnimosus** [comment]
If there is a mod missmatch the players would have to download from the servers, and should go through the same prompt in theory with only cancel being available. The joining player would still see which mod it is, and just needs to update their subscribed workshop mods then join the server.

There isn't really a workaround if their subscribed but to an earlier/later version, as they can't download the current version from the server if its disallowed. its unknown if their version is later or earlier, only that it mismatches. and downloading whatever is current on the workshop may not necessarily be the same files either.
