### ISSUE TITLE
Containers can be unintentionally placed behind cabinents

### ISSUE THREAD

**Issue by ng** [FakeFishGames/Barotrauma#13218]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

I have a container of genetic material that was automatically placed behind a cabinet in the Orca's medbay. I cannot access it even though the item locator shows it should exist.

### Reproduction steps

The container placement was automatic, so I'm not sure how to reproduce this. If I were to guess, it would be to board an Orca that has too much cargo, drop genetic material from inventory, order crew to clean up, then try to locate the container.

### Bug prevalence

Just once

### Single player or multiplayer?

Single player

### Version

v1.2.7.0 (Winter Update hotfix)

### Which operating system did you encounter this bug on?

Windows

**Comment by itchyOwl** [comment]
Need to find the repro steps.

**Comment by Regalis11** [comment]
I'm afraid there might not be enough information here for us to diagnose the issue. I'm at least not sure what "container" refers to here (what kind of a container?).
