### ISSUE TITLE
NPCs don't know how to deal with water pressure.

### ISSUE THREAD

**Issue by knightez12** [FakeFishGames/Barotrauma#13223]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

when submarines are  flooded npcs wil just swimming around and die from water pressure even though there are several room that are safe and not flooded.

### Reproduction steps

1.get hull breach
2.get flooded
3.npcs equip diving mask
4.npcs swim in circle
5.die

### Bug prevalence

Happens every now and then

### Single player or multiplayer?

Single player

### Version

v1.2.7.0 (Winter Update hotfix)

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment]
Thank you for the report!

Which submarine did this happen in? Did you notice it happening in some specific room? If this was in some custom submarine, it could possibly be that the waypoints haven't been properly set up or updated in the sub.

**Comment by knightez12** [comment]
All tier 1 subs or maybe other tier too but I don't take any passenger
after reaching Europa ridge

Also they will prioritize safe spot instead of diving suit too.

ในวันที่ อ. 26 ธ.ค. 2023 22:51 Joonas Rikkonen ***@***.***>
เขียนว่า:

**Comment by pavel4win** [comment]
The same thing happened to me yesterday in a single player game with mods (dynamic europa, etc.). Orca uboat. When the uboat was flooded, the NPCs swam wearing pressure masks until they died, although there were free diving suits nearby, they ignore it and did not put suits on.

**Comment by Jasontti** [comment]
There is something weird going in pathfinding.
Managed to get mechanic failing to exit ballast in humpback on video:

https://github.com/FakeFishGames/Barotrauma/assets/8488224/f2d88f7e-0cbd-4613-b40a-ace9f216972e

In other instance idle medic was swimming only in diving mask in fully flooded hull, also in humpback, feels like they don't properly evaluate the danger within the room they are idling in.

**Comment by itchyOwl** [comment]
@Jasontti, if you are on single player, please type "debugai" before recording or taking a screenshot.
