### ISSUE TITLE
Sub editor: Door gaps do not get included in group when group is copied and pasted

### ISSUE THREAD

**Issue by estebanthebad** [FakeFishGames/Barotrauma#13238]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported (searched for "gap group").
- [ ] My issue happened while using mods.

### What happened?

Sub editor.
When including a door and its gap in a group, the gap is not included in the group if the group is copied and then pasted.
Normally everything is included in the same group, if a group is copied and pasted.

![image](https://github.com/Regalis11/Barotrauma/assets/52369117/039dcdf4-b922-4d1b-a92d-2e1b84e10ee0)

### Reproduction steps

1. Sub editor
2. Enable view gaps
3. Place vanilla "Custom Door". Result: Door1 and gap1 are placed.
4. Select door and gap
5. Create group
6. Select group in group list
7. CTRL+C
8. CTRL+V, Result: Door2 and gap2 are placed.
9. Select group in group list. Result: Door1, gap1 and door2 are selected. Gap2 is not selected.
10. Drag group. Result: Door1, gap1 and door2 are moved. Gap2 is not moved.

### Bug prevalence

Happens every time I play

### Single player or multiplayer?

Happens outside single player or multiplayer game modes (e.g. game launches on startup, something broken in the main menu)

### Version

v1.2.7.0 (Winter Update hotfix)

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment]
Addressed in https://github.com/Regalis11/Barotrauma-development/commit/a3eddbbcd8ce03f052abb5ee9308e7e0898c6e12

**Comment by Jasontti** [comment]
Tested at the same time with: https://github.com/FakeFishGames/Barotrauma/issues/13253

Closing this ticket
