### ISSUE TITLE
MissionAction always selects the same mission even though there are several missions that match the tag

### ISSUE THREAD

**Issue by A2ur3** [FakeFishGames/Barotrauma#13234]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [X] My issue happened while using mods.

### What happened?

I made a custom outpost event where there will always be a commoner giving you four missions according to tag killswarm_set1, killswarm_set2, killswarm_set3 and killswarm_set4. I was not using other mods but every time I received same missions.
![ScriptedEvent](https://github.com/Regalis11/Barotrauma/assets/64390906/133dff6e-95e9-4bbd-ad77-efb7b0ab64ab)
![UnlockedMission1](https://github.com/Regalis11/Barotrauma/assets/64390906/7d4f4fbd-b5b2-457f-97a6-0536fd656b51)
![UnlockedMission2](https://github.com/Regalis11/Barotrauma/assets/64390906/2dbb55e1-a94a-4617-a7c5-a8067db52d25)

### Reproduction steps

1. download 
and enable [MissionAction Test.zip](https://githubfast.com/Regalis11/Barotrauma/files/13772608/MissionAction.Test.zip)
2. create a new save
3. go to outpost docking module and find the custom mission NPC
4. you get four mudraptor mission all the time

### Bug prevalence

Happens every time I play

### Single player or multiplayer?

Happens in both single player and multiplayer

### Version

v1.2.7.0 (Winter Update hotfix)

### Which operating system did you encounter this bug on?

Windows

**Comment by AzureNocte** [comment]
I've encountered this issue too, it seems that this happened regularly to modded missions with tags "killswarm_set1"/"killswarm_set2"/"killswarm_set3"/"killswarm_set4", the outpost manager will give you the same mission every time regardless of commonness.

**Comment by Regalis11** [comment]
@AzureNocte The fix is not yet included in the public version of the game. Sorry for the inconvenience!

**Comment by AzureNocte** [comment]
It's ok, as long as this issue will get fixed in future patches. Thanks!

**Comment by A2ur3** [comment]
the issue persists you still get same missions
