### ISSUE TITLE
Max Climb Angle acts very weird

### ISSUE THREAD

**Issue by ricky122122** [FakeFishGames/Barotrauma#13240]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

steep but short walls can damage and stun you
https://github.com/Regalis11/Barotrauma/assets/111702225/b0d789d2-d565-49db-ac77-121e42d5351f

shuttle shell a glass d has a weird hitbox with the ends having a steep angle causing you to get stuck on one side of them
https://github.com/Regalis11/Barotrauma/assets/111702225/990a847b-b2fc-4449-852d-b08366cecf0d

https://github.com/Regalis11/Barotrauma/assets/111702225/9ac66163-0add-48a1-92e5-f7997fdcd7ce

running past a short but steep wall seems to just chuck you at the ground
https://github.com/Regalis11/Barotrauma/assets/111702225/76be2976-70e4-436a-84c2-614a581147d5

also this new climbable angle thing should be a setting in the server settings or something alot of gamemodes use maps with small pieces of walls sticking out that are steep and now noone can pass them without trying to ragdoll over

### Reproduction steps

watch videos

### Bug prevalence

Happens every time I play

### Single player or multiplayer?

Happens in both single player and multiplayer

### Version

v1.2.7.0 (Winter Update hotfix)

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment]
Addressed the 1st issue in https://github.com/Regalis11/Barotrauma-development/commit/39dd77122ef0feae6cf867009d2f85a4b3bbb7ff. The 2nd seems to happen because there's a small gap between the walls' colliders the character can drop inside.

**Comment by SanderN8H** [comment]
Adding this here as it seems related: Other structures such as curved walls seem to be bugged as well. In previous versions it was possible to walk much further up curved walls. The current behavior seems overly limited (see added video). Any fix would be appreciated.

https://github.com/Regalis11/Barotrauma/assets/156925749/c1b25dbc-3b61-4157-b951-2a0d043817e1

**Comment by Rokvach** [comment]
Tested, working correctly. Can be merged and closed.
