### ISSUE TITLE
Rope pullsource behaves inconsistently in multiplayer

### ISSUE THREAD

**Issue by iridescent-lightning** [FakeFishGames/Barotrauma#13244]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [X] My issue happened while using mods.

### What happened?

Actually I'm pretty sure this bug had been reported. So I don't mind move it to the discussion. I figure it's pretty simple to re-enabled the pullsource feature by just removing the inwater condition and ragdolled condition in the source code. I'm curious why the rope pulling source behaves so badly in multiplayer?

### Reproduction steps

using harmony to make rope pullsource work at all conditions. Or use other method.
pullsource in multiplayer. 
character glitched to the sky.

### Bug prevalence

Happens every time I play

### Single player or multiplayer?

Multiplayer hosted using a dedicated server

### Version

Other

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment]
Thank you for the report!

I'm not entirely sure I understand the issue. What do you mean by the "pullsource feature" - applying a force to the character using the item using the `SourcePullForce` attribute?

There are some know issues with applying the force to the character when it's swimming or ragdolling, those should be addressed in https://github.com/Regalis11/Barotrauma-development/pull/4558 (PR in out private repo), so it could be the issue's already been addressed. That fix is unfortunately not yet available in any public build though.

**Comment by iridescent-lightning** [comment]
If you enabled the pullsource. And try to utilize it as a grapple in door. It works fine in single player but jitters so badly in multiplayer. I want to know why.

**Comment by Regalis11** [comment]
What do you mean by pullsource? How exactly do you enable it? There's no property with that name in the Rope component.

**Comment by iridescent-lightning** [comment]
Ah sorry, I meant SourcePullForce

**Comment by itchyOwl** [comment]
I think what he meant is that harpoon pull mechanics work unreliably. Our PR probably fixes some issues, but it still works worse in mp than in sp.

> It works fine in single player but jitters so badly in multiplayer.

Me too! :D

**Comment by Rokvach** [comment]
Tested, didn't notice anything strange, PR can be merged and closed.

**Comment by itchyOwl** [comment]
I think it's because the ragdoll can't keep up with the main collider that we apply the pull force to. Possibly fixed in FakeFishGames/Barotrauma-development#5132.

**Comment by Rokvach** [comment]
Tested, didn't see any issues with this. Working correctly, can be merged and closed.
