### ISSUE TITLE
"Politician" talent tree isn't translated

### ISSUE THREAD

**Issue by DieOrsons** [FakeFishGames/Barotrauma#13257]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

Captain talent branch "politician" is not translated in Russian. In Russian, the word is "Политик."

### Reproduction steps

1. Start game
2. Open captain talent tree
3. There is no translation of that word
![Screenshot_1](https://github.com/Regalis11/Barotrauma/assets/155447308/eeb0bac4-5cd7-43ce-b639-eebf4bfbba7d)

### Bug prevalence

Happens every time I play

### Single player or multiplayer?

Single player

### Version

v1.2.7.0 (Winter Update hotfix)

### Which operating system did you encounter this bug on?

Windows

### Relevant error messages and crash reports

```shell
I love your game
```

**Comment by Regalis11** [comment]
Addressed, fix coming up in the next update!
