### ISSUE TITLE
Sub editor: Item assemblies with entity groups confuse grouping features

### ISSUE THREAD

**Issue by estebanthebad** [FakeFishGames/Barotrauma#13253]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

When placing item assemblies which contain entity groups, these groups are lost (do not show up in the group list) - mostly. Except if the entity group contains a door and its gap. Then the grouping functionality shows some additional weird behavior.

### Reproduction steps for bug without door gap

1. Sub editor
2. Enable view gaps
3. Place vanilla "Fin patch 1" 2 times
4. Select both patches
5. Create group
6. Rename group to "patches"
7. Click group "patches" in group list to select it
8. Create item assembly named "IA test groups patches"
9. Exit sub editor
10. Enter sub editor
11. Open group list/menu
12. Place item assembly "IA test groups patches"
* Expected result: Group "patches" shows up in group list.
* Observed result: Group list stays empty.
13. Click anywhere on background to deselect placed entities.
14. Click "Create group"
* Expected result: Empty new group shows up in group list.
* Observed result: Same as expected.

### Reproduction steps for bug with door gap

1. Sub editor
2. Enable view gaps
3. Place vanilla "Custom door"
4. Select door and gap
5. Create group
6. Rename group to "door and gap"
7. Click group "door and gap" in group list to select it
8. Create item assembly named "IA test groups door"
9. Exit sub editor
10. Enter sub editor
11. Open group list/menu
12. Place item assembly "IA test groups door"
* Expected result: Group "door and gap" shows up in group list.
* Observed result: Group list stays empty.
13. Click anywhere on background to deselect placed entities.
14. Click "Create group"
* Expected result: Empty new group shows up in group list.
* Observed result: Two groups show up in group list: Group "door and gap" and "New group"
15. Select group "door and gap" in group list.
* Expected result: Door and gap get selected.
* Observed result: Door gets selected. Gap does not get selected.

### Bug prevalence

Happens every time I play

### Single player or multiplayer?

Happens outside single player or multiplayer game modes (e.g. game launches on startup, something broken in the main menu)

### -

Sub editor

### Version

v1.2.7.0 (Winter Update hotfix)

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment]
Thank you for the report! Fixed in https://github.com/Regalis11/Barotrauma-development/commit/28ea35f77ee0e1034202c58c904221e74229b7b9 (commit in our private repo)

**Comment by Jasontti** [comment]
Tested in: https://github.com/Regalis11/Barotrauma-development/pull/4805/commits/ad6e1505d4a9ae8b402b3a7a3df839657278de81

Issues:
Place item assembly "IA test groups patches"
 - Expected result: Group "patches" shows up in group list.
Could not get this to work with different variations.
Easily reproed without closing the editor

Select group "door and gap" in group list.
 - Expected result: Door and gap get selected.
Setting custom door in to a group and saving it as assembly succesfully creates group, but gap and door stay separated

Tested and works:
Click anywhere on background to deselect placed entities.
Click "Create group"
    Expected result: Empty new group shows up in group list.

**Comment by Regalis11** [comment]
Addressed in https://github.com/Regalis11/Barotrauma-development/pull/4805/commits/b079a8e8d48094984f2189c78431c982799272a5 and https://github.com/Regalis11/Barotrauma-development/pull/4805/commits/a3eddbbcd8ce03f052abb5ee9308e7e0898c6e12

**Comment by Jasontti** [comment]
Tested in: https://github.com/FakeFishGames/Barotrauma-development/pull/4805/commits/a3eddbbcd8ce03f052abb5ee9308e7e0898c6e12

No issues found
Closing ticket
