### ISSUE TITLE
If your game language is English, some simplified Chinese texts within character name and mission name won't display

### ISSUE THREAD

**Issue by A2ur3** [FakeFishGames/Barotrauma#13258]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

![characterName](https://github.com/Regalis11/Barotrauma/assets/64390906/75771d00-cae8-4405-8cf3-4840610412b7)
text "师" is missing
![englishmissionName](https://github.com/Regalis11/Barotrauma/assets/64390906/58b15d0d-f300-4dfc-b762-786f75e5bfb8)
![chinesemissionName](https://github.com/Regalis11/Barotrauma/assets/64390906/7da1e639-5e33-4c49-9e74-81329db61500)
text "为" is missing
seems this issue #11987 didn't fully addressed

### Reproduction steps

texts used in pictures above
character name "工程师"
mission name "成为希望的代价"

### Bug prevalence

Happens every time I play

### Single player or multiplayer?

Happens in both single player and multiplayer

### Version

v1.2.7.0 (Winter Update hotfix)

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment]
Thank you for the report! Fixed in https://github.com/Regalis11/Barotrauma-development/commit/646b1f9438f329b3c71aed2778149ed52c0b8b36

**Comment by Jasontti** [comment]
Tested in: https://github.com/FakeFishGames/Barotrauma-development/commit/0536608e0d9ce00243a9e1909a58106e7f869745

Created a test mission with "成为希望的代价" and character with "工程师"
Observed that all characters were visible in all the places where those were used

No issues found
Closing ticket
