### ISSUE TITLE
[Unstable] Map generation sometimes forces the coalition faction on the starting outpost

### ISSUE THREAD

**Issue by ubertpendragon** [FakeFishGames/Barotrauma#13250]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [X] My issue happened while using mods.

### What happened?

Husk faction is forced onto the huskchurch location type, but since this one spawned at the very first location, I assume the game forced coalition on it? 

![image](https://github.com/Regalis11/Barotrauma/assets/73229309/a0d21f27-f05d-461f-90d1-fa48ec8328c5)

![image](https://github.com/Regalis11/Barotrauma/assets/73229309/2988d06d-da22-4714-99fe-4bdb075723e9)

![image](https://github.com/Regalis11/Barotrauma/assets/73229309/1f435ca5-9f67-42d8-b00d-ac79e7fc0e9c)

The clown outpost (which appears and disappears) didnt get the coalition faction assigned

![image](https://github.com/Regalis11/Barotrauma/assets/73229309/9a0e2683-ce2e-4786-9f9b-a13d4f5c83a1)

Add a "biome 0" starter outpost (like the end outpost but in reverse)

### Reproduction steps

1. Add mod [Truehuskfaction.zip](https://github.com/Regalis11/Barotrauma/files/13810265/Truehuskfaction.zip)
2. Load save [Huskoutposttestie.zip](https://github.com/Regalis11/Barotrauma/files/13810266/Huskoutposttestie.zip)
3. Jump around using `togglecampaignteleport` the clown outpost should spawn

### Bug prevalence

Just once

### Single player or multiplayer?

Single player

### Version

Other

### -

Unstable

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/b6f322cca77d2ad83184f0625f317a0f4f778b84

**Comment by NilanthAnimosus** [comment]
Closing as tested, merged and to be included in the next update.

Notes:
Issues mentioned above are fixed and it is now possible to force factions in outposts with both faction/secondaryfaction="factionname", as well as using ="None" to force it to no faction for either one (IE. to stop clowns being assigned to a primary clowns only location, you would define the secondary faction as none)
