### ISSUE TITLE
[Unstable] Wreck spawned inside a wall

### ISSUE THREAD

**Issue by Rokvach** [FakeFishGames/Barotrauma#13263]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

![image](https://github.com/Regalis11/Barotrauma/assets/7299826/bd7d9639-fbfd-4369-bbe5-a9f689390445)
![image](https://github.com/Regalis11/Barotrauma/assets/7299826/19a40e72-3890-4645-a2e4-f37b31ee35ed)

### Reproduction steps

1. Load up level editor with the following info

Level type: plateaubasic
Seed: 9fEHuDJJ
Submarine: Dugong

### Bug prevalence

Just once

### Single player or multiplayer?

Other

### -

level editor

### Version

Other

### -

Testing branch: very-unstable-unstable-dec23

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment]
Probably related to https://github.com/Regalis11/Barotrauma-development/pull/4716

**Comment by Udrakan** [comment]
Encountered this today on Unstable myself. Save:
[Save 17.zip](https://github.com/Regalis11/Barotrauma/files/13850503/Save.17.zip)

**Comment by Rokvach** [comment]
Tested, working correctly. Can be merged and closed.
