### ISSUE TITLE
Wrecked Shuttle sprites are very different from non-wrecked shuttle pieces 

### ISSUE THREAD

**Issue by JeroonBosch** [FakeFishGames/Barotrauma#13264]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

Noticed while trying out the wreck converter.

![image](https://github.com/Regalis11/Barotrauma/assets/8641689/4ae12d6e-4032-4b70-ae8f-98c6e34706ba)

Some of the wreck pieces seem very outdated, and some shapes are not nearly the same as the non-wreck versions.
Additional note: while most pieces have a default scale of 0.5, most wreck shuttle pieces have a default scale of 1.0 so the wreck converting will mess those up.

The main issue is the vastly different styles though. The wreck versions have harder black lines and look clearly legacy. These items should then be moved to legacy items (as not to screw up old submarines) and new wrecked sprites can be added that match our current standards/style.

### Reproduction steps

1. Open sub editor, Barsuk
2. Use the new converttowreck command

### Bug prevalence

Happens every time I play

### Single player or multiplayer?

Happens in both single player and multiplayer

### Version

Other

### -

fix/wreck-converter

### Which operating system did you encounter this bug on?

Windows

**Comment by IiroEnges** [comment]
Demoted old sprite sheet to legacy, created new atlas for new wrecked sprites

**Comment by Rokvach** [comment]
Tested, didn't spot any issues can be merged and closed.
