### ISSUE TITLE
Reputation bar UI doesn't scale with min/max reputation settings

### ISSUE THREAD

**Issue by ubertpendragon** [FakeFishGames/Barotrauma#13260]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [X] My issue happened while using mods.

### What happened?

If you create or change a faction to have less than 100 reputation, the UI still reads as -100 to 100

![image](https://github.com/Regalis11/Barotrauma/assets/73229309/e2a4bcd1-a053-4430-bdd8-6ddcad52ef89)

 `minreputation="-20" maxreputation="20" `
 
 

### Reproduction steps

Change a faction reputation to 
 `minreputation="-20" maxreputation="20" `

### Bug prevalence

Just once

### Single player or multiplayer?

Single player

### Version

Other

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/1e80c1900cc04d10032cce549c846268f6c3606a
