### ISSUE TITLE
[Unstable] Top half of Dr. af Grann's outpost spawns inside the level ceiling

### ISSUE THREAD

**Issue by Udrakan** [FakeFishGames/Barotrauma#13275]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

Save: [Save 17.zip](https://github.com/Regalis11/Barotrauma/files/13851418/Save.17.zip)
Keep in mind this save CRASHES due to #13274. Potentially related to #13263 

To temporarily fix it, I changed this (line 97):
`<StatusEffect target="This" type="OnFailure" target="UseTarget" forceplaysounds="true">`

to this:
`<StatusEffect target="This" type="OnFailure" forceplaysounds="true">`

![image](https://github.com/Regalis11/Barotrauma/assets/59519434/b0bf73cb-8cfa-4260-9b52-bfd7f2d7f811)

### Reproduction steps

1. load save

### Bug prevalence

Just once

### Single player or multiplayer?

Single player

### Version

v1.2.7.0 (Winter Update hotfix)

### Which operating system did you encounter this bug on?

Windows

**Comment by ubertpendragon** [comment]
Any reason ceiling is drawn in front of submarines when level walls are drawn behind?

I can walk freely inside in both pictures, I just think it's cool to have outposts encased in terrain (forced outpost position in leveleditor)

![image](https://github.com/Regalis11/Barotrauma/assets/73229309/bb06a9e7-d620-45a9-8fb9-56b2ccdc2f48)

![image](https://github.com/Regalis11/Barotrauma/assets/73229309/a0bc7cec-007f-44a7-a171-cbec90a70bc8)
