### ISSUE TITLE
Inconsistent right click ui in sub editor (cannot open pumps and navigation console)

### ISSUE THREAD

**Issue by CometVoid** [FakeFishGames/Barotrauma#13278]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [X] My issue happened while using mods.

### What happened?

Right click > Open does not work on pumps or the navigation computer., whilst it does on batteries, containers, and reactor.
E hotkey still works

![image](https://github.com/Regalis11/Barotrauma/assets/80859724/d6a19f50-d514-462f-b3bc-6a74217cfba8)
Open greyed out on right click ui with a pump

![image](https://github.com/Regalis11/Barotrauma/assets/80859724/464b9b79-29f2-457f-9430-1313a07e2fd6)
Open not greyed out on a reactor

### Reproduction steps

1. Right click a pump

### Bug prevalence

Happens every time I play

### Single player or multiplayer?

Other

### -

Submarine Editor

### Version

Other

### -

V1.2.7.0, LuaCsForBarotrauma

### Which operating system did you encounter this bug on?

Linux

**Comment by CometVoid** [comment]
Astraltor in discord mentioned the commonality between the items that do work and ones that don't with right click > Open, is the ones that work all have an inventory.

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/f9c9466517a8fa1c0d2c8410bf210632069be83d

**Comment by Rokvach** [comment]
Tested, working correctly. Can be merged and closed.
