### ISSUE TITLE
Platforms don't have collision with items when placed outside of the submarine

### ISSUE THREAD

**Issue by NotWendy** [FakeFishGames/Barotrauma#13276]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

Platforms function differently depending on whether there is a hull box around them or not. When placed outside of a submarine, they not only lose collision with characters (which is reasonable), but also with items (which is sad).

This is unintuitive (why would items fall through the platform just because it's submerged in water?) and also prevents setups like the one in the screenshot below from being built. Instead of the platform acting as a place for divers to drop off loot without entering the submarine, it turns into a purely decorative piece.

![PlatformOutside](https://github.com/Regalis11/Barotrauma/assets/47554589/f1de2f8a-85e2-4bff-a0ad-a780287f775d)

### Reproduction steps

1. Place a platform in the submarine editor without adding a hull around it.
2. Drop an item onto the platform, be it a tool, a crate, or anything else.
3. Watch the item fall straight through the platform.

### Bug prevalence

Happens every time I play

### Single player or multiplayer?

Happens in both single player and multiplayer

### Version

v1.2.7.0 (Winter Update hotfix)

### Which operating system did you encounter this bug on?

Windows

**Comment by itchyOwl** [comment]
Not sure if this is something that should be fixed or not. If not -> close it, if yes, add a bug label.

**Comment by Regalis11** [comment]
In my opinion this doesn't seem worth addressing: it would be non-trivial to solve because it'd mean the submarine's external collider needs to consist of fixtures with different collision categories, and it'd complicate the collision detection logic somewhat (and incur some performance cost).
