### ISSUE TITLE
WaitForItemFabricatedAction doesn't care which items you fabricate

### ISSUE THREAD

**Issue by Regalis11** [FakeFishGames/Barotrauma#13287]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

WaitForItemFabricatedAction completely ignores ItemIdentifier, meaning actions using it always complete no matter what item the player fabricates. Seems to affect divinelabor, deepdiverducks and handcuffshortage traitor events.

### Reproduction steps

1. Start an MP round
2. `triggertraitorevent handcuffshortage`
3. Fabricate any 8 items, notice the objective completes

### Bug prevalence

Happens regularly

### Single player or multiplayer?

Multiplayer hosted from the in-game menu (= using a listen server)

### Version

v1.2.7.0 (Winter Update hotfix)

### Which operating system did you encounter this bug on?

Windows

**Comment by Rokvach** [comment]
Tested, working correctly. Can be merged and closed.
