### ISSUE TITLE
Bots get stuck in combat mode.

### ISSUE THREAD

**Issue by pavel4win** [FakeFishGames/Barotrauma#13285]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [X] My issue happened while using mods.

### What happened?

I can’t say exactly under what conditions this happens.
This happens when there are monsters outside near the hull of the boat.
Although there are no monsters inside the boat. I find that the bot is standing with a weapon in his hands.
The “battle” icon is lit in the team list.
The bot stands motionless with a weapon in his hands and does not exit the “battle” mode. And does not carry out any other orders until all orders are reset and given again.
I didn't notice this bug in earlier versions of the game.

![2024-01-09_13-39-29](https://github.com/Regalis11/Barotrauma/assets/47295383/708cceff-e53b-46ae-8775-e22dcb87ba28)

### Reproduction steps

I can't give exact steps for reproduction.

### Bug prevalence

Happens every now and then

### Single player or multiplayer?

Single player

### Version

v1.2.7.0 (Winter Update hotfix)

### Which operating system did you encounter this bug on?

Windows

**Comment by A2ur3** [comment]
caused by some mod creatures like overrode Hammerheadgold from barotraumatic creature pack
i dont know what they changed
