### ISSUE TITLE
Escaping Prisoners do not seek weapons.

### ISSUE THREAD

**Issue by NilanthAnimosus** [FakeFishGames/Barotrauma#13297]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

upon escaping the handcuffs, the prisoners only flee and pose no harm, as they appear to refuse to pickup weapons even if they are on the floor.

They will use weapons if placed onto their body (such as before handcuff removal or by knocking them out). it seems they just refuse to seek a weapon on the player submarine.

### Reproduction steps

1. Start/Load a campaign mission into the outpost
2. Unlockmission escort3
3. teleport submarine to end of level and lock it in place
4. wait for prisoners to free themselves or free the prisoners (both likely work)
5. Once their red names appear, in debugai it will show them as in combat, but they will only flee and never seek a weapon.

### Bug prevalence

Happens regularly

### Single player or multiplayer?

Single player

### Version

v1.2.8.0 (Winter Update hotfix 2)

### Which operating system did you encounter this bug on?

Windows

**Comment by itchyOwl** [comment]
Fixed in Regalis11/Barotrauma-development#4872.
