### ISSUE TITLE
Interactions with pets take priority over every other action

### ISSUE THREAD

**Issue by NotWendy** [FakeFishGames/Barotrauma#13292]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

When a pet is anywhere near you, the E button will _always_ be used to play with it, no matter what your mouse is currently hovering over.
Trying to repair a junction box and there's a psilotoad on the floor below it? You're petting the psilotoad.
Trying to fix the engine and your defense bot is in the same room as you? You've now completely forgotten about your job and are playing with the defense bot.

### Reproduction steps

1. Let a pet anywhere near a repairable device.
2. Try and repair the device by hovering your mouse over it and pressing E.
3. _Who's a good orange boy? You're a good orange boy!_

### Bug prevalence

Happens every time I play

### Single player or multiplayer?

Happens in both single player and multiplayer

### Version

v1.2.7.0 (Winter Update hotfix)

### Which operating system did you encounter this bug on?

Windows

**Comment by Udrakan** [comment]
This is very annoying when wiring too

**Comment by Regalis11** [comment]
Fixed in https://github.com/FakeFishGames/Barotrauma-development/commit/c4e2718d46d785601a8dee0c577d7143d9b90765
