### ISSUE TITLE
Unable to pick up a stun baton

### ISSUE THREAD

**Issue by A2ur3** [FakeFishGames/Barotrauma#13298]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

you can not pick stun baton up

### Reproduction steps

1. Spawn a stun baton
2. try to pick it up

### Bug prevalence

Happens every time I play

### Single player or multiplayer?

Happens in both single player and multiplayer

### Version

v1.2.8.0 (Winter Update hotfix 2)

### Which operating system did you encounter this bug on?

Windows

**Comment by marpul358** [comment]
Had this happen yesterday. Stun baton dropped by a dying outpost security officer and could not pick it up.

**Comment by kumilanka** [comment]
Confirmed: can spawn a stun baton and not pick it up. Bots can pick it up just fine, though.

**Comment by Jasontti** [comment]
Testes in: https://github.com/FakeFishGames/Barotrauma-development/pull/4848/commits/48a43df5c36e5fb23054c60d25ca267ee8274fe8

Tested that batons can be picked up by players and bots
Old functionality with bots switching batteries works also

No issues found
Closing ticket
