### ISSUE TITLE
Move faster while scooting and wearing backpack + exosuit

### ISSUE THREAD

**Issue by Vykn** [FakeFishGames/Barotrauma#13318]
Potential duplicate of #12673. I couldn't find the changes in the patch notes so I'm not sure if the fix has made it into stable, but it was closed 4 months ago and I have some additional info.

### What happened?

Putting on a backpack while wearing the exosuit makes you move much faster while using a scooter. Very strange behaviour; both items slow you down, yet wearing both is somehow faster than just wearing the exosuit.

Did a bunch of testing since I don't know enough about all the speed modifiers to do calculations

![image](https://github.com/Regalis11/Barotrauma/assets/37850646/1509dbb6-60ed-48f2-967b-11dd88be64d3)

Notably wearing exo + backpack is faster than just exo. The rest is more sensible, but the backpack does not reduce movement speed by 30% in most cases, though that was mentioned in the other issue. The speed modifiers aren't fully consistent, but that's not necessarily an issue in of itself. Maybe the above data is useful in determining if anything needs changing.

### Reproduction steps
1. Wear exosuit, use scooter, observe speed
2. Put on backpack, use scooter, observe speed is notably higher.

### Version

v1.2.8.0 (Winter Update hotfix 2)

**Comment by Regalis11** [comment]
Fixed in https://github.com/FakeFishGames/Barotrauma-development/commit/33ad391c54e9fc7d924e91833631dae73f5ea95b
