### ISSUE TITLE
New tracks mute main music at intensities below 25

### ISSUE THREAD

**Issue by SomeRandomNoobKekeke** [FakeFishGames/Barotrauma#13312]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

New tracks (Submarine Flooded - Extended, Monster Nearby - Extended) do not play at intensity <25 (they have intensityrange="25,75")
But they block main music leaving you in silence

This means all [fights with less than 7 crawlers](https://youtu.be/oaG8Hp-megg?feature=shared&t=109) , fixing any flooded beacon will be in silence

This sounds awful and it wasn't like that:

https://github.com/Regalis11/Barotrauma/assets/122838333/a84a6812-7f18-4b73-b272-14163a1b4af0

https://github.com/Regalis11/Barotrauma/assets/122838333/c6d2618c-fb9b-44e8-b867-2f5daecf03e8

https://github.com/Regalis11/Barotrauma/assets/122838333/02b08a45-ddb5-4498-a213-56758596fb8f

https://github.com/Regalis11/Barotrauma/assets/122838333/95fc4a0f-d0a6-47b0-bf06-0aac906e051b

### Reproduction steps

quickstart dugong 0
spawn crawler
listen

### Bug prevalence

Happens regularly

### Single player or multiplayer?

Single player

### Version

v1.2.8.0 (Winter Update hotfix 2)

### Which operating system did you encounter this bug on?

Windows

**Comment by SomeRandomNoobKekeke** [comment]
Monster Nearby - Extended.ogg starts playing only after you spawn 13 crawlers

**Comment by SomeRandomNoobKekeke** [comment]
Monster Nearby - Extended.ogg starts playing only after you spawn 13 crawlers

**Comment by SomeRandomNoobKekeke** [comment]
[Ok, i'll just fix it myself](https://steamcommunity.com/sharedfiles/filedetails/?id=3141544529)

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/0683bb15c5d9c46caa337a433eed0db8430bccaa

Fixed music stopping when under attack by monsters and the EventManager intensity is below 25 (i.e. when you're being attacked by some weak monsters). Happened because the minimum intensity of the monster clips was set to 25. Now we don't switch to the "monster" music types if there's no suitable music for the current intensity.

**Comment by SomeRandomNoobKekeke** [comment]
Note, there is an example of "good muting"
When you are in abyss and some abyss creature is nearby it stops main music but don't play intensity layers until it targets you
https://www.youtube.com/watch?v=kxdOkrxNIMk
It's probably not intended, and it wasn't like that in 1.0.21.0 but i think it's cool because:
- Is creepy: Imagine you are peacefully swimming in the abyss and suddenly calm music stops for unknown reason, and you won't found out why until you turn on the sonar
- Without music you can clearly hear distant roars of abyss creatures

The only problem is that the radius of this muting around abyss creatures is too big, it's like 5 roar radiuses when i think it should be near 1
