### ISSUE TITLE
Typhon Brig Oxygen bug

### ISSUE THREAD

**Issue by danielpcdesign** [FakeFishGames/Barotrauma#13319]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

While doing a prisoner transport mission I decidded to place all prisoner in the Brig on the Typhon submarine to avoid escapes later. After A few minutes I was notified that I had failed the mission and when I checked the brig, all prisoners were dead. Initially I thought it had something to do with me being too rough on them, so I restarted the mission and had the same problem. Again, I restarted and placed only one prisoner, thinking there might not be enough oxygen for all. Still, he died. I went into the editor thinking perhaps the vent was not connected ot that loose vents did not generate oxygen. However, everything looked fine. I looked up the issue and found out it has to do with room size. I decided to increase the ammount of oxygen in the sub editor but I am unsure if this made changes to the sub in my campaign file, because after testing even with only one prisoner, he died. This is not a big issue but is something that shouldn't happen on a vanilla submarine that every player has access to and that contaions a brig which is useless.

### Reproduction steps

1.Have any sort of campaign.
2.Buy a Typhon Submarine.
3. Place any character inside the brig.
4. Wait

### Bug prevalence

Happens regularly

### Single player or multiplayer?

Single player

### Version

v1.2.8.0 (Winter Update hotfix 2)

### Which operating system did you encounter this bug on?

Windows

**Comment by SomeRandomNoobKekeke** [comment]
in that room 1 vent provides ~95% of a person's oxygen requirement
So yes, give them masks or oxygenite shard
Nice idea to increase o2 gen production, also adding more vents would be an easy fix for this
No, it won't affect already purchased sub, you need to rebuy it

**Comment by marpul358** [comment]
Is this happening now because we cannot upgrade the oxygen generator anymore?

**Comment by Jasontti** [comment]
Tested in: https://github.com/FakeFishGames/Barotrauma-development/pull/4865/commits/6dc3d449d95a8300c0f37885f4e1c99c1430b5b6

Tested typhons brigg
Did couple shiplike hulls and managed to get not enough oxygen warning to trigger

No issues found
Closing ticket

**Comment by MAH69IK** [comment]
We've run into this problem too. Our tests showed that even 1 person suffocates in a closed brig.

@Jasontti I understand you were unable to replicate the problem? In that case maybe record a video?

**Comment by SomeRandomNoobKekeke** [comment]
@MAH69IK it will be implemented in next barotrauma update or maybe in unstable

**Comment by Jasontti** [comment]
@MAH69IK 
Yes, that was me testing the fix. I believe it's already in the unstable.
Seems like link to the fix is not here yet:
https://github.com/FakeFishGames/Barotrauma-development/pull/4865/commits/9a9713096d8d04071402a74256a08aa66b74ff23
