### ISSUE TITLE
Character still grabbing/interacting with modded container after closing its UI through other means

### ISSUE THREAD

**Issue by aoyamajia** [FakeFishGames/Barotrauma#13326]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [X] My issue happened while using mods.

### What happened?

Upon taking something from a container that requires another item to be equipped (e.g., #12669), the UI for the container closes (as though you have right clicked or walked sufficiently far away), but the character is still grabbing the container as though interacting with its UI open.
I would have expected my character to stop interacting with the item entirely once the UI closes.

### Reproduction steps

1. Run the example from #12669 in either singleplayer/multiplayer.
2. Take an item from the left or right crate shelf.
3. Notice how the character is still grabbing the crate shelf after the item UI closes. Selecting the crowbar while in this state lets you toggle displaying the shelf's UI.

### Bug prevalence

Happens every time I play

### Single player or multiplayer?

Happens in both single player and multiplayer

### Version

v1.2.9.0 (unstable)

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/c01638ae15777da17c5d02f80fe08fe450ae8e59
