### ISSUE TITLE
Rooms made out of multiple hulls always show 1 percent of water when flooded and repaired.

### ISSUE THREAD

**Issue by Smrtonosan** [FakeFishGames/Barotrauma#13322]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

When making my submarine I noticed that couple of rooms would never drain. Originally I thought the pumps were placed too high but after double checking that was not the issue, later I realized that it was only a problem in rooms made out of multiple hulls.

The issue is present on all submarines.
![Dugong](https://github.com/Regalis11/Barotrauma/assets/104994469/c79e2c4e-994d-4fcf-b388-62d148b75abd)
Dugong's engine room is made out of multiple hulls.
The issue seems to be due to water detector not detecting the last bit of water? As when I unwire the water detector from the small pump and set it to manually drain it will drain all of the water on the dugong engine room.

However on submarines like the azimuth, where the room doesn't have a small pump, it will always show 1% of water.
![Azimuth](https://github.com/Regalis11/Barotrauma/assets/104994469/a779bbf8-32b1-49ab-9b4e-5a0551a4832e)
Even if doors to adjacent rooms are open, hull that leads below is cut open, the duct block is open, it will always have 1% of water.

### Reproduction steps

1. Load Azimuth is submarine editor.
2. Switch to mechanic and cut open 1 hole in the roof of the command room.
3. After a bit of water get's in weld the hole closed.
4. Check the status monitor only to notice that the room has 1% of water despite there not being any holes.

### Bug prevalence

Happens every time I play

### Single player or multiplayer?

Single player

### Version

v1.2.8.0 (Winter Update hotfix 2)

### Which operating system did you encounter this bug on?

Windows

**Comment by Smrtonosan** [comment]
My apologies, the command room in azimuth is a hull overlap issue.

The dugong engine room though isn't, from what I can see, the same isn't the case on my custom submarine.

**Comment by Jasontti** [comment]
Tested in: https://github.com/FakeFishGames/Barotrauma-development/pull/4876/commits/d5252d0389e45089dc35f61e505bb8eb5137091e

Flooded couple subs and let them drain, azimuth, dugong and camel mainly

No issues found
Closing ticket
