### ISSUE TITLE
Switching to a bot with a recipe while fabricating the recipe cancels the fabrication

### ISSUE THREAD

**Issue by Vykn** [FakeFishGames/Barotrauma#13333]
### What happened?
Starting the fabrication of a recipe that is unlocked by a bot, followed by switching to the bot with the recipe cancels the fabrication. (Obviously only occurs in singleplayer)

https://github.com/Regalis11/Barotrauma/assets/37850646/186eae84-3e6c-4555-ae7b-6d103958f565

### Reproduction steps
1. give a recipe to an npc
2. using a different character, fabricate the recipe
3. switch to the bot with the recipe
4. observe that the fabrication has been cancelled

### Version
v1.2.8.0 (Winter Update hotfix 2) & v1.2.9.0 (unstable)

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/26dd79834dae7b1e6916ee07fa010a53b334552c

**Comment by Regalis11** [comment]
Merged, closing
