### ISSUE TITLE
getting away with station murder with no penalty via stun grenades

### ISSUE THREAD

**Issue by LePiromano** [FakeFishGames/Barotrauma#13338]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

using a stun grenade you can stun a security officer npc in a station and use their own cuffs, then you can put a welding fuel tank on their mask and place it on their face, this will kill them with no reputation loss as long as you don't place any of their items in your inventory during the interaction, plus the welding fuel mask is not damage directly applied by you so they don't even get pissed off
you can do this pretty much in a wide open space with people watching you do it and you will not lose any reputation
i only report this as an issue because it's the only remaining way i know to kill outpost ncps without any penalty
i can think of a couple ways to deal with this issue but one of them is making sec off npcs able to break out of cuffs

### Reproduction steps

go to an outpost
find an lonely guard or multiple guards in the same room
drop a stun nade
open their inventory, cuff them, bring a welding fuel tank and put it on their mask, and exchange their mask with their equipped helmet

### Bug prevalence

Happens every time I play

### Single player or multiplayer?

Single player

### Version

v1.2.9.0 (unstable)

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment]
To me it feels like the welding fuel tank kills are the main issue here, not the stun grenades. Addressed in https://github.com/FakeFishGames/Barotrauma-development/commit/04d4d8f2af8a4c426a6e21285a8893d1c2fe8add by making the character who put on the mask be considered the killer.

**Comment by LePiromano** [comment]
https://cdn.discordapp.com/attachments/668819422919524352/1223058336594006167/harvest.mp4?ex=661878d6&is=660603d6&hm=c4eb92ec7755af3ee056b9e279da54ec05ceca8e9b31ec20f00d32748f30ba12&

still possible in v1.4.0.0

**Comment by Regalis11** [comment]
@LePiromano the fix is not yet out.

**Comment by Rokvach** [comment]
Tested, working correctly. can be merged and closed.
