### ISSUE TITLE
Opening talent tree shows finished branches as locked

### ISSUE THREAD

**Issue by Sailtor** [FakeFishGames/Barotrauma#13332]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

When opening the talent menu after loading the game, talent branches that have already been finished displayed as locked if you have started the next branch.

Screenshots of this happening:
![20240121134605_1](https://github.com/Regalis11/Barotrauma/assets/17296454/351d8503-a49e-45fb-ac1e-610e600629c3)
![20240121134553_1](https://github.com/Regalis11/Barotrauma/assets/17296454/519c7d68-8c4d-4f3b-a289-f5b0f0902224)
![20240121134547_1](https://github.com/Regalis11/Barotrauma/assets/17296454/23ecc6cc-154e-41ab-baf3-006e74db78b5)
![20240121134543_1](https://github.com/Regalis11/Barotrauma/assets/17296454/388561fa-3f71-4168-a176-32bc3095b5b3)

### Reproduction steps

1. Start a singleplayer campaign
2. Finish one talent branch for any character
3. Get one skill out of any other branch
4. Save and exit
5. Load the game again

### Bug prevalence

Happens regularly

### Single player or multiplayer?

Single player

### Version

v1.2.8.0 (Winter Update hotfix 2)

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment]
Thank you for the report!

I'm not entirely sure I understand the issue. Do you mean that e.g. this branch is shown as locked?
![image](https://github.com/Regalis11/Barotrauma/assets/14351070/8363e1ab-720c-4c40-b6a5-9b84c19b1e50)

I don't see anything unusual in that pic: the selected talents are displayed correctly and the non-selected ones are correctly grayed out (as you can no longer select them).

**Comment by Sailtor** [comment]
Yes, that branch is what I think should look different. The talents in it displayed correctly but they have grey background and a lock icon in a right corner as if the talent hasn't been unlocked yet. But if you unlock all 3 branches all talents in them have a green background with a tick:
![20240122172052_1](https://github.com/Regalis11/Barotrauma/assets/17296454/ad150594-cb06-455a-a67a-4a46e901445b)
So maybe it would be nice to show unlocked branches like that before you unlock them all so you could better see what talents you unlocked. And also to show that talents from previous branch are still working. Like this, for example:
![screen](https://github.com/Regalis11/Barotrauma/assets/17296454/bbe1ae2a-960f-4a6e-97dc-35a874822fd8)

**Comment by Rokvach** [comment]
Tested, working correctly. Can be merged and closed.
