### ISSUE TITLE
Bots cannot hear order to use WiFi Turret with Circuit Box

### ISSUE THREAD

**Issue by Vuruul** [FakeFishGames/Barotrauma#13343]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

Bots cannot hear the order to man turrets when WiFi controls pass through a circuit box. It doesn't matter if both ends of the WiFi signal are in Circuit Boxes or just one - it happens either way. 

### Reproduction steps

1. Load your favorite sub with working guns in the editor.
2. Connect any periscope to its turret through WiFi and order a bot to man it (this will work).
3. Now connect any periscope to its turret through WiFi but this time put the WiFi components into a Circuit Box.
4. Order the bot to man the turret again (this does not work).
5. The bot will say "This character can't hear the order"
![image](https://github.com/FakeFishGames/Barotrauma/assets/157542043/4706a13b-73e9-4160-bb8b-3cc64cbd21c1)

### Bug prevalence

Happens every time I play

### Single player or multiplayer?

Other

### -

Submarine Editor

### Version

v1.2.8.0 (Winter Update hotfix 2)

### Which operating system did you encounter this bug on?

Windows

**Comment by Jasontti** [comment]
Tested the fix: https://github.com/FakeFishGames/Barotrauma-development/pull/4889/commits/edc14cac93678d8efeb5aecbd0960ac62d808c1b
Tested in: https://github.com/FakeFishGames/Barotrauma-development/pull/4889/commits/9c998ed69def501cf19065900f675d50595fb32a

Used our test sub and created test sub from remora and it's shuttle.

No issues found
Closing ticket
