### ISSUE TITLE
If use "Override" element in text file, label and roomname selection window will show nothing.

### ISSUE THREAD

**Issue by esirprus** [FakeFishGames/Barotrauma#13340]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [X] My issue happened while using mods.

### What happened?

I'm using neurotrauma mod and i noticed that roomname selection window shows nothing
![image](https://github.com/FakeFishGames/Barotrauma/assets/44423036/476b8ce3-f4c2-4c30-99a3-1e2367ea5a4f)
it should show something
![image](https://github.com/FakeFishGames/Barotrauma/assets/44423036/9f0c7f20-18aa-4ae1-9000-af68937ea32c)
if the game behaving correctly. Also label selection window shows nothing, not quite sure if there's more affected content out there, so plz check.

### Reproduction steps

I make a small mod for you devs to test, just:
1. download zip [roomtest.zip](https://github.com/FakeFishGames/Barotrauma/files/14026684/roomtest.zip)
2. enable the mod and see the roomname selection window
3. edit the text file and remove "Override" element and check the roomname selection window again

### Bug prevalence

Happens every time I play

### Single player or multiplayer?

Single player

### Version

v1.2.8.0 (Winter Update hotfix 2)

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment]
Fixed in https://github.com/FakeFishGames/Barotrauma-development/commit/5753fe7c93a391fb9ba614d3ecaa129478f19b4f (commit in our private repo)

**Comment by Jasontti** [comment]
Tested in: https://github.com/FakeFishGames/Barotrauma-development/pull/4887/commits/5753fe7c93a391fb9ba614d3ecaa129478f19b4f

Tested with the mod provided and with neurotrauma
Made quick custom sub
Loaded old and and checked that roomnames have not changed
tested in SP and MP to see if everything is ok in status monitor

No issues found
Closing ticket
