### ISSUE TITLE
Lead Duplication

### ISSUE THREAD

**Issue by TheWanderingMaw** [FakeFishGames/Barotrauma#13344]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

Purchasing Lead from the basic merchant at an outpost, I purchased the maximum amount. Each time, 4 would be removed from the vendor's inventory, so I would buy max again, and this kept going until I had over 200 Lead. This also happened when trying to sell the lead from my sub. This happened when I tried to purchase it directly to my inventory, I did not have it delivered to my sub. One of my crew did order some to the sub prior to my shopping.

### Reproduction steps

1. Start Multiplayer campaign
2. Head to an outpost regular Merchant (not arms dealer, engineering merchant, etc.)
3. Purchase some Lead to the sub
4. Have another player purchase the full stock of lead to their inventory
5. Merchant's stock should go down by 4
6. Try selling lead from sub to same merchant, more lead should start spawning in your inventory

### Bug prevalence

Just once

### Single player or multiplayer?

Multiplayer hosted from the in-game menu (= using a listen server)

### Version

v1.2.8.0 (Winter Update hotfix 2)

### Which operating system did you encounter this bug on?

Windows

**Comment by NilanthAnimosus** [comment]
Closing as fixed and tested and should be resolved in a future update
