### ISSUE TITLE
Clown Exo Suit (Funbringer 3000) is missing "diving" tag

### ISSUE THREAD

**Issue by Max112358** [FakeFishGames/Barotrauma#13342]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [x] My issue happened while using mods.

### What happened?

The clown exo suit, unlike every other form of breathing device, is missing the "diving" tag. The normal exo suit has it so I'm guessing this is a mistake. It does have the "deepdiving" tag though.

<img width="119" alt="image" src="https://github.com/FakeFishGames/Barotrauma/assets/97316904/fb53e625-1016-473e-87c6-da1d2068d098">

### Reproduction steps

Check the item tag list for "clownexosuit"
See that diving is not on the list.

### Bug prevalence

Happens every now and then

### Single player or multiplayer?

Multiplayer hosted from the in-game menu (= using a listen server)

### Version

v1.2.8.0 (Winter Update hotfix 2)

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment]
Why should it have that tag?

**Comment by Max112358** [comment]
Because you are breathing from it? I had a mod that looks for items tagged with "diving" and it doesn't work for this particular item. Why does the normal exosuit have it?

**Comment by Regalis11** [comment]
That tag doesn't seem to have much effect on anything in the vanilla game, so I was wondering if I'm missing something or if there's some common use for it in mods. I guess it makes some sense that it's not technically diving gear, as "lore-wise" it seems like something designed to be used indoors (with the banana peel cannon and all), but I suppose it'd be more consistent if it was tagged the same way as the other suits.

**Comment by Regalis11** [comment]
Added in https://github.com/FakeFishGames/Barotrauma-development/commit/3b1ec253a74b24eed96eb63ee5f03a5ff8975536 (commit in our private repo)

**Comment by Max112358** [comment]
I use it as a way of finding breathing devices. Listing them all out in an array would be brittle because they change all the time. However as long as new ones get the diving tag I can find them no matter how the game changes. It makes for less maintenance in my mods.
