### ISSUE TITLE
Fabricator allows making item without all materials if recipe has same material in multiple slots

### ISSUE THREAD

**Issue by marpul358** [FakeFishGames/Barotrauma#13346]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

For example Assault Rifle Magazine requires the following five items:
- magnesium
- steel bar OR titanium
- steel bar OR uranium OR titanium
- copper or zinc
- steel bar
But just by placing magnesium, zinc/copper and a single (1) steel bar in the fabricator slot (or having it in toolbelt or attached storage locker) enables the create button and pressing it makes the wanted item. This seems to be possible with any recipe that allows the same material, steel bar in the above example, to be used in multiple slots.

### Reproduction steps

1. Have 1 steel bar, 1 magnesium, 1 copper in toolbelt (or fabricator slot or attached storage)
2. Open fabricator and search and select the assault rifle magazine recipe
3. Press create
4. Fabricator should produce 1 assault rifle magazine even though it was missing 2 of the required materials count

### Bug prevalence

Happens every time I play

### Single player or multiplayer?

Single player

### Version

v1.2.8.0 (Winter Update hotfix 2)

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment]
Thank you for the report! Fixed in https://github.com/FakeFishGames/Barotrauma-development/commit/bc54740ace45cda49d1b37ac9cba96c16718842d (commit in our private repo)
