### ISSUE TITLE
"OnSpawn" cannot set item condition or quality

### ISSUE THREAD

**Issue by esirprus** [FakeFishGames/Barotrauma#13349]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

I searched vanilla content and found "bloodsamplevial" won't spawn at 0 condition
```xml
  <Item name="" identifier="bloodsamplevial" 
...
      <StatusEffect type="OnSpawn" target="this" condition="0" setvalue="true" />
...
```
Seems “Onspawn” and play sound works good？

### Reproduction steps

1. type "spawnitem bloodsamplevial inventory" in console
2. see the condition

### Bug prevalence

Happens every time I play

### Single player or multiplayer?

Single player

### Version

v1.2.8.0 (Winter Update hotfix 2)

### Which operating system did you encounter this bug on?

Windows

### Relevant error messages and crash reports

extra info:
On TraitorEvent i see
```xml
...
      <StatusEffectAction targettag="vial">
        <StatusEffect Condition="0" setvalue="true" />
      </StatusEffectAction>
...
```
maybe that's the reason it spawns at 0 condition in TraitorEvent.

**Comment by Regalis11** [comment]
Fixed in https://github.com/FakeFishGames/Barotrauma-development/commit/c6c3f889f514dc268a2c78230a2415dea94653b1

**Comment by Regalis11** [comment]
(Finally) merged the fix to our private repo, fix coming up in a future update
