### ISSUE TITLE
Door backgrounds are too deep

### ISSUE THREAD

**Issue by ubertpendragon** [FakeFishGames/Barotrauma#13353]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

Door foreground sprite is at 0.510 depth
Door background sprite is at 0.890 depth
Door buttons are at 0.750 depth

The depth discrepancy means items just show through the door background like wires and you have no room to control the door depth

![image](https://github.com/FakeFishGames/Barotrauma/assets/73229309/225d812c-7292-45c3-9ac1-191c8550e4b2)

I'll open a PR

### Version

v1.2.8.0 (Winter Update hotfix 2)

**Comment by Regalis11** [comment]
I'm not sure I understand the issue here. It's intended that wires and other items are rendered in front of the background: the background is supposed to be the frame of the door, attached to a wall, so an item would be in front of it.

**Comment by ubertpendragon** [comment]
Basically there's a delta of 410 depth between foreground and background **which leaves no room for depth fine tuning**

If you want to hide the wires behind the background (some people do some people dont) you can't change door depth. 
If you mess with wall depth for decoration and reach 0.880 the wall will render in front of the door.

 0.490 puts the *whole door* including background in front of characters, so you can't reduce depth at all. 
 
 
 The compromise I found was to keep foreground at 0.510 and background at 0.610 so you can increase door depth if you want wires to show through the background.

**Comment by ubertpendragon** [comment]
https://github.com/FakeFishGames/Barotrauma/pull/13354

**Comment by ubertpendragon** [comment]
Will leave PR open

**Comment by Regalis11** [comment]
I'm afraid the PR cannot be used in it's current form, I think we do need some kind of backwards compatibility logic if we're going to change the sprite depths. If you're not planning on implementing that in the PR, I think it could be closed too (and we may look into it at some point in the future!).
