### ISSUE TITLE
'damagedbyrepairtools="true"' doesn't work without  damagedbyprojectiles or damagedbymeleeweapons... except on doors

### ISSUE THREAD

**Issue by ubertpendragon** [FakeFishGames/Barotrauma#13356]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

If you use 'damagedbyrepairtools="true"' alone on items that arent doors, they can't be damaged by repair tools. 
They need `damagedbyprojectiles="true"` or `damagedbymeleeweapons="true"` to actually get damaged by repair tools

Doors ONLY use this and get damaged just fine.
`  <Item name="" identifier="aliendoor" category="Alien" Tags="alien,door,aliendoor,weldable" damagedbyrepairtools="true" scale="0.5">`

### Reproduction steps

1. Remove `damagedbyprojectiles="true"` or `damagedbymeleeweapons="true"` from crawleregg
2.   `<Item name="" identifier="crawleregg" hideinmenus="true" health="20" damagedbyexplosions="true"  damagedbyrepairtools="true" category="Misc" spritecolor="199,253,172,255" scale="0.5" impactsoundtag="impact_soft">`
3. spawn a crawler egg via console
4. try to use plasma cutter on it

### Bug prevalence

Happens every time I play

### Single player or multiplayer?

Single player

### Version

v1.2.8.0 (Winter Update hotfix 2)

### Which operating system did you encounter this bug on?

Windows

**Comment by Jasontti** [comment]
Tested in: https://github.com/FakeFishGames/Barotrauma-development/pull/4901/commits/97b5b4a8308aa48e595ce8ed2b4ce252dcb2a5f6

Tested with steps provided, works.
Tested that normally damaging things work too.
Went around and tested that other things take damage from guns, turrets, welder and plasma cutter.

No issues found, closing ticket as resolved
