### ISSUE TITLE
Ladders don't respect "remove if linked" properties for outpost modules

### ISSUE THREAD

**Issue by ubertpendragon** [FakeFishGames/Barotrauma#13358]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

Ladders linked to doors in outpost modules do not respect the "remove (or appear) if linked" property if either one of the top or bottom doors is connected to another module

In green: APPEARS when hatch is connected
In red: REMOVED when hatch is connected

![image](https://github.com/FakeFishGames/Barotrauma/assets/73229309/808c377f-498a-46e5-87c0-3b043977435b)

You can see the decorative fin following the rule but not ladders

![image](https://github.com/FakeFishGames/Barotrauma/assets/73229309/59284ed8-eb5b-4920-ba8e-3e9e069bbc06)

### Version

v1.2.8.0 (Winter Update hotfix 2)

**Comment by Regalis11** [comment]
This is intentional: the outpost generator doesn't allow auto-removing ladders if the gap gets connected to another module. I'm not sure what that behavior would be needed for, in what kind of a setup do you want the ladder to be removed if the gap leads to another module?

**Comment by ubertpendragon** [comment]
The green ladders are supposed to be removed if the gap is NOT connected, but it doesn't do that.

If either the top/bottom gaps are connected, the top/bottom ladders appear regardless if their own gap is connected


Compare the behavior of the colored fins to the ladders in the picture

**Comment by Regalis11** [comment]
>The green ladders are supposed to be removed if the gap is NOT connected (or only appear if it IS connected), but it doesn't do that.

Well, arguably they are not, that's not what the setting says. When you enable it, it removes the entity if the door is in use, but it doesn't say disabling it removes the entity in the opposite case. But yeah, the behavior of ladders is inconsistent with how other types of entities work, so I suppose we could change it.

**Comment by ubertpendragon** [comment]
In the second picture ladders should behave like the fins but they don't

**Comment by Regalis11** [comment]
Should they? As said, the outpost generator doesn't allow auto-removing ladders if the gap gets connected to another module That would prevent you from using the ladder to move between the modules. And the property only says the entity should get removed when the door is in use, but not that it should also get removed if it's set to false and the doors is _not_ in use.

**Comment by ubertpendragon** [comment]
Yes, if links don't affect ladders you end up with ladders always present leaving to nowhere 

Note that it happens if either one of the top/bottom gaps are in use, but if none are in use (left/right gaps are used) the ladders don't generate (as they should)

**Comment by Regalis11** [comment]
Merged, closing
