### ISSUE TITLE
StatusEffect type nearbyitems and it's targeting

### ISSUE THREAD

**Issue by Alpharius-30-milenium** [FakeFishGames/Barotrauma#13363]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [X] My issue happened while using mods.

### What happened?

So, it's modding problem mostly since if you use target nearbyitems in status effect it start to work very weirdly. Example: you have limb that is executing status effect with target nearbyitems every 10 seconds and should target certain IDs but I find out that it still target all items, including contained items (I find it out when character with that limb passed container full of stuff and fps dropped drastically). Also for some reason any status type except always won't work if you target nearby items (it was tested on InWater/NotInWater and on OnOpen/OnClose)

### Reproduction steps

In my example it was:
1. Create custom husk and add all necessary appendages
2. Create custom afflictions for each appendage
3. Launch MP game
4. Install implants with these appendages on multiple characters
5. See the fps drops time to time when status effect happens

I will also leave file with character and item prefabs because I'm not the best at explaining such things
[HumanPriest.zip](https://github.com/FakeFishGames/Barotrauma/files/14087382/HumanPriest.zip)

### Bug prevalence

Happens every time I play

### Single player or multiplayer?

Happens in both single player and multiplayer

### Version

v1.2.8.0 (Winter Update hotfix 2)

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment]
@kobango 

It does not need to search the distance between each item, but from the entity executing the status effect to each item. That's a time complexity of O(n), not O(n^2). It's also worth noting that there are quite a lot of optimizations in that method, and it can actually rule out quite a lot of the items without having to calculate the distance.

**Comment by Regalis11** [comment]
I had a look at this now, and I'm not entirely sure I was able to reproduce the issue. The provided mod doesn't seem usable as-is, so I had to do some modifications to it (adding a filelist.xml and changing the folder structure a bit) to get it to load. Here's that modified version: [HumanPriest.zip](https://github.com/FakeFishGames/Barotrauma/files/14109514/HumanPriest.zip)

I still couldn't quite figure out which items or afflictions I'm supposed to use to reproduce the issue though, could you give any pointers?

Regardless, I found one issue that could potentially be behind the issue. It seems status effects defined in limbs will try to find the targets for the effect every frame regardless of the interval at which the status effect executes, which probably explains the performance hit. Fixed that in https://github.com/FakeFishGames/Barotrauma-development/commit/d864ed62afb42aee01a5086824be13fd86c40d68 (commit in our private repo).

**Comment by Alpharius-30-milenium** [comment]
> Regardless, I found one issue that could potentially be behind the issue. It seems status effects defined in limbs will try to find the targets for the effect every frame regardless of the interval at which the status effect executes, which probably explains the performance hit.

Well, that was the main issue

**Comment by NilanthAnimosus** [comment]
Closing as tested (and fix works).

Note on caveats: if you use the existing status effects in your mod it will still have the same performance issues, as the conditionals will stop the status effect from triggering - thus not triggering the interval delay (causing it to need to re-check the target items each update against the conditional).

When the statuseffect does trigger and goes on cooldown to the interval it won't have to scan items anymore, so you might want to make it always trigger without the conditional, and check after it has been applied to the items. not sure on the best method to this (an explosion status effect perhaps that applies an effect?), but still worth noting.
