### ISSUE TITLE
Equip the item with "DecorativeSprite" cause the decorative sprite highlighted.

### ISSUE THREAD

**Issue by esirprus** [FakeFishGames/Barotrauma#13367]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [X] My issue happened while using mods.

### What happened?

just tryed to make a mod gun that can spin when reload. And find the sprite highlighing when equipping.

https://github.com/FakeFishGames/Barotrauma/assets/44423036/9711d455-f22a-4161-9ea8-83b4cb3500ad

![image](https://github.com/FakeFishGames/Barotrauma/assets/44423036/0401e577-1916-41dd-9020-f5684557ab04)
![image](https://github.com/FakeFishGames/Barotrauma/assets/44423036/f316ea20-6b3b-485f-ab67-f47a11671b2e)

### Reproduction steps

1.download the mod 
[DecorativeSprite_test.zip](https://github.com/FakeFishGames/Barotrauma/files/14121812/DecorativeSprite_test.zip)
2.equip the gun
3.drop the gun to the ground
4.check the difference of the sprite

### Bug prevalence

Happens every time I play

### Single player or multiplayer?

Single player

### Version

v1.2.8.0 (Winter Update hotfix 2)

### Which operating system did you encounter this bug on?

Windows

**Comment by esirprus** [comment]
additional: vanilla item magnetic suspension crate is effected by this issue
![image](https://github.com/FakeFishGames/Barotrauma/assets/44423036/ccdfb586-d634-4ddc-8fbc-63c311285ac9)
![image](https://github.com/FakeFishGames/Barotrauma/assets/44423036/93a76a88-31b5-440e-ad36-8f5fca5ebb35)
![image](https://github.com/FakeFishGames/Barotrauma/assets/44423036/cb1348d2-4066-40f8-b585-d462c00d7264)
![image](https://github.com/FakeFishGames/Barotrauma/assets/44423036/116b4902-fcbf-477f-acf6-1e78eb0a1b5e)

**Comment by Regalis11** [comment]
Fixed in https://github.com/FakeFishGames/Barotrauma-development/commit/69d59c091b67ea482c5aa2dd5e9126f5b14226b5

**Comment by Rokvach** [comment]
Tested, working correctly. Can be merged and closed.
