### ISSUE TITLE
Unidirectional Playback Error in Engine.UpdateAnimation method @ lines 134-142 in ClientSource?

### ISSUE THREAD

**Issue by jigardi** [FakeFishGames/Barotrauma#13364]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

NB: Although I found the bug while modding, I have not ticked the "My issue happened while using mods" checkbox, since the error is with vanilla code affecting all `<Engine>` elements.

I've traced the bug to a few lines in this file:

https://github.com/FakeFishGames/Barotrauma/blob/05398cc56cca028801789d9563616f2a582e563f/Barotrauma/BarotraumaClient/ClientSource/Items/Components/Machines/Engine.cs

-and more specifically this function:

```cs
partial void UpdateAnimation(float deltaTime)
        {
            if (propellerSprite == null) { return; }
            spriteIndex += (force / 100.0f) * AnimSpeed * deltaTime;
            if (spriteIndex < 0)
            {
                spriteIndex = propellerSprite.FrameCount;
            }
            if (spriteIndex >= propellerSprite.FrameCount)
            {
                spriteIndex = 0.0f;
            }
        }
```

The error is with these lines exactly:
```cs
if (spriteIndex < 0)
            {
                spriteIndex = propellerSprite.FrameCount;
            }
if (spriteIndex >= propellerSprite.FrameCount)
            {
                spriteIndex = 0.0f;
            }
```
At first glance these seem reasonable, since they keep the `spriteIndex` from going out of bounds, but in praxis they are nonsensical as they incorrectly set the `spriteIndex` from an animation standpoint.

The function, as is, only works as "intended", while the `force` value is positive, and when the `AnimSpeed` value is very low and also positive. 

For any negative values the function will visually fail almost immediately, as it keeps yielding a minimum `spriteIndex` i.e. `0` or a maximum `spriteIndex` i.e. `FrameCount`, as correctly defined in Spritesheet.cs:

https://github.com/FakeFishGames/Barotrauma/blob/05398cc56cca028801789d9563616f2a582e563f/Barotrauma/BarotraumaShared/SharedSource/Sprite/SpriteSheet.cs

The problem is that this causes the `spriteIndex` value to clamp, when it should actually wrap instead.

(I suppose it would also "work" if both values were simultaneously negative, but in that case I suspect the animation would only play "incorrectly" when reversing the submarine, and get stuck when attempting to move forward.)

The solution should be simple enough, perhaps something like this will suffice:

```cs
partial void UpdateAnimation(float deltaTime)
        {
            if (propellerSprite == null) { return; }
            spriteIndex += (force / 100.0f) * AnimSpeed * deltaTime;
            if (spriteIndex < 0)
            {
                spriteIndex = propellerSprite.FrameCount - Math.Abs(spriteIndex) % propellerSprite.FrameCount;
            }
            else
            {
                spriteIndex = spriteIndex % propellerSprite.FrameCount;
            }
        }
```

Looks like `spriteIndex` is a float, so perhaps a final clamp() is necessary to avoid an out of bounds error, but I'm not sure about that.

PS: I'd also strongly recommend giving modders access to a generalized `<SpriteSheet>` element, with rudimentary controls.
Otherwise people will be forced to chuck in `<Engine> `elements all over the place, or use rows and rows of `<BrokenSprite>` elements in conjunction with unnecessarily janky `<StatusEffect>` logic, in order to play custom animations - but perhaps that's what was hinted at in the blogpost earlier this month? : P

### Reproduction steps

1. Add a correctly configured `<propellersprite`> element inside of an `<Engine>` element.
2. Reverse the Engine(Manually or Automatically doesn't matter, result is the same as the problem lies downstream). 
3. The propellersprite visually stops updating, as it is continually fed the maximum or minimum frame index, rather than the correct one within range.(?)

### Bug prevalence

Happens every time I play

### Single player or multiplayer?

Happens in both single player and multiplayer

### Version

Other

### -

Should happen in all versions as far as I can tell. But I've only tested it fully in Unstable v1. 2.10.0

### Which operating system did you encounter this bug on?

Windows

### Relevant error messages and crash reports

```shell
Causes no crashing or error messages, since the function in question is bounded correctly. However the function is logically unsound for half of its possible input values i.e. all negative numbers; and will therefore fail to visually update the `<propellersprite>` it is responsible for.
```

**Comment by jigardi** [comment]
Edit: Fixed some typos and markup mistakes.

**Comment by Regalis11** [comment]
Thank you for the report and for taking the time to diagnose the issue. :) Your proposed solution looks correct to me, and based on a quick test, seems to work with no issues. Fixed in our private repo now (https://github.com/FakeFishGames/Barotrauma-development/commit/0c33f71dc420453d968c0a958a5b77cea42b7905), but it will take a while before the fix makes it to the public version.

**Comment by jigardi** [comment]
> Thank you for the report and for taking the time to diagnose the issue. :) Your proposed solution looks correct to me, and based on a quick test, seems to work with no issues. Fixed in our private repo now (https://github.com/FakeFishGames/Barotrauma-development/commit/0c33f71dc420453d968c0a958a5b77cea42b7905), but it will take a while before the fix makes it to the public version.

Huzzah! Ø__^
Glad I could help!
