### ISSUE TITLE
"Indestructible" structure parameter not saved when placed in editor

### ISSUE THREAD

**Issue by ubertpendragon** [FakeFishGames/Barotrauma#13365]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

If you set in a structure's xml `indestructible="true"`, the structure won't be checked as indestructible by default when placed in the sub editor

```xml 
 <Wall name="Rock Cave Wall (Horizontal)" identifier="de-rockcavewallhorizontalstraight" descriptionidentifier="exteriorshell" subcategory="cavedeco" body="true" castshadow="true" health="999999999" bodyheight="40" bodyoffset="0,0" resizehorizontal="true" indestructible="true">
```

![image](https://github.com/FakeFishGames/Barotrauma/assets/73229309/915b3042-41a6-4539-84d9-a11a1a823a09)

### Reproduction steps

1 Add `indestructible="true"' to a wall properties in structureprefabs.xml

2 Place said wall in editor

### Bug prevalence

Just once

### Single player or multiplayer?

Single player

### Version

v1.2.10.0 (unstable)

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment]
Fixed in https://github.com/FakeFishGames/Barotrauma-development/commit/4d8204befed4dbc1eed446794ebbdac9d569ad4c

**Comment by Regalis11** [comment]
Merged, coming up in a future update
