### ISSUE TITLE
Create a saved data with no crew by firing crew and killing the remaining character

### ISSUE THREAD

**Issue by kaedepon** [FakeFishGames/Barotrauma#13374]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

"HR Manager" and the suicide of a crew member will create a saved data with no crew member.
The save data is loaded, the game is immediately over because there is no crew.
I think It is not good that a player can control fired crew until the game is reloaded.

### Reproduction steps

1. Start a single player campaign.
2. Access a "HR Manager".
3. Fire a "Engineer" and "Mechanic".
4. Suicide a "Captain" (eg.suffocation, dive the sea naked, etc)
5. Save and quit or leave an outpost.
6. It makes for cool saved data.

### Bug prevalence

Happens every time I play

### Single player or multiplayer?

Single player

### Version

v1.2.8.0 (Winter Update hotfix 2)

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment]
Thank you for the report! Fixed in https://github.com/FakeFishGames/Barotrauma-development/commit/4f6b50c413ce2cc0b35333e8dc3eaa1dde27f6a9 (commit in our private repo)

**Comment by Rokvach** [comment]
Tested, working correctly. Can be merged and closed.
