### ISSUE TITLE
[Unstable] Selecting Holographic Display item crashes the game (SerializableEntityEditor.CreateStringField)

### ISSUE THREAD

**Issue by ubertpendragon** [FakeFishGames/Barotrauma#13378]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

Place this in sub editor and select it

![image](https://github.com/FakeFishGames/Barotrauma/assets/73229309/abb5e6ed-a76b-4482-96a6-4afec9ebe989)

[crashreport (39).log](https://github.com/FakeFishGames/Barotrauma/files/14144715/crashreport.39.log)

Other items of the same type (decorative with light component) also crash the game 
![image](https://github.com/FakeFishGames/Barotrauma/assets/73229309/8543b70a-6396-4a24-bc02-11b6eb31d3d6)

### Version

v1.2.10.0 (unstable)

**Comment by Jasontti** [comment]
Tested in: https://github.com/FakeFishGames/Barotrauma-development/pull/4912/commits/852fa888ee05649332efc6ccefafd2b8b279de26

Placed all affected monitors and holograms
Gave them tags
Tested in SP and MP

No issues found
Closing ticket
