### ISSUE TITLE
[Modding] CopyEntityDir appears to be non functional

### ISSUE THREAD

**Issue by SydWad** [FakeFishGames/Barotrauma#13372]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [X] My issue happened while using mods.

### What happened?

CopyEntityDir="" appears to not be functional in any context i have tried to use it in.
There are no errors in the log.

ParticleEmitter.cs
`[Editable, Serialize(true, IsPropertySaveable.Yes, description: "Should the entity heading direction be applied to the particle rotation? Only affects after flipping the texture and when CopyEntityAngle is true.")]`
`public bool CopyEntityDir { get; set; }`
![Untitled](https://github.com/FakeFishGames/Barotrauma/assets/106110714/841c5a5a-870c-4652-873d-38288be11b96)

In this context i am trying to make a tracer trail that follows the physics item regardless of the angle of the item. Have the tracer follow the path of motion of the item.
`<ParticleEmitter particle="chainguntrail" particlespersecond="50" CopyEntityAngle="true" CopyEntityDir="true" colormultiplier="255,80,80,200" />`

[I will provide a dummy item on the workshop using it as well.
Mod name: ParticleEmitter Test
Item name: ParticleEmitter Test](https://steamcommunity.com/sharedfiles/filedetails/?id=3152318422)

I have scoured the base game and workshop to find any context of it in use when set to "true" but in the very rare few where it appeared the tracer still did not follow path of motion and appeared to just be used in a case of uninformed copying of existing code. I have also tried many sorts of combinations with the function to see if it requires angle or velocity info along with it, but no luck.

### Reproduction steps

Reproduction:
Just simply attempt to use the CopyEntityDir function on a particle emitter such as in the mod provided.

### Bug prevalence

Happens every time I play

### Single player or multiplayer?

Happens in both single player and multiplayer

### Version

v1.2.8.0 (Winter Update hotfix 2)

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment]
Thank you for the report!

Looking at the screenshot, to me the property appears to be working as intended. The description is worded in a pretty confusing way though: the "heading direction" does not mean the direction the item is moving in, but the direction it's facing (i.e. whether it's being flipped horizontally, like when you aim a tool to the left).

Since the sprites in this case look like they're symmetrical and would look the same regardless of the direction they're facing, both screenshots look correct.

**Comment by SydWad** [comment]
> Thank you for the report!
> 
> Looking at the screenshot, to me the property appears to be working as intended. The description is worded in a pretty confusing way though: the "heading direction" does not mean the direction the item is moving in, but the direction it's facing (i.e. whether it's being flipped horizontally, like when you aim a tool to the left).
> 
> Since the sprites in this case look like they're symmetrical and would look the same regardless of the direction they're facing, both screenshots look correct.

If that is the intended feature I’m rather disappointed that there is no way to produce the effect I was intending and thought this would provide…

**Comment by Regalis11** [comment]
Yeah, it'd definitely be useful to have some way to make the particles rotate to the direction of the movement. I think we can look into adding a setting for that! Sorry for the inconvenience.
