### ISSUE TITLE
[Unstable] Infection from afflictions affects other limbs and % chance is excessively high

### ISSUE THREAD

**Issue by ubertpendragon** [FakeFishGames/Barotrauma#13376]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

Infection spreads to limbs that are not the one that is bleeding/burnt. 

Change
`      <StatusEffect target="Character" interval="1" disabledeltatime="true" ConditionalComparison="And">`

to
`      <StatusEffect target="Limb" interval="1" disabledeltatime="true" ConditionalComparison="And">`

Also the chance of affliction appearing is way higher than the numbers suggest 

30 seconds later
![image](https://github.com/FakeFishGames/Barotrauma/assets/73229309/c1dd8172-fc01-44e9-945b-ed21179a68e0)

### Reproduction steps

Give yourself 30 bleeding via console
`giveaffliction bleeding 30 "Arthur Sykes" torso`

Infection everywhere

### Bug prevalence

Happens every time I play

### Single player or multiplayer?

Single player

### Version

v1.2.10.0 (unstable)

### Which operating system did you encounter this bug on?

Windows

**Comment by JeroonBosch** [comment]
As a sidenote, for performance reasons we might want to prevent the probability from being checked all the time.

For example: No change for further infection if the limb already has infection.

**Comment by Jasontti** [comment]
Tested in: https://github.com/FakeFishGames/Barotrauma-development/pull/4928/commits/fa2b0076af55f94c87d29d1714ef5574bb60cccd
Part of PR: https://github.com/FakeFishGames/Barotrauma-development/pull/4928

No issues found
Closing ticket
