### ISSUE TITLE
Submarine switches another at Natural Formation by Using Submarine Switch Terminal in the Passageways.

### ISSUE THREAD

**Issue by kaedepon** [FakeFishGames/Barotrauma#13389]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

Using the Submarine Switch Terminal in the Passageways, the submarine switches at the goal or return.
It feels strange as ambience that the submarine switches when arriving at Natural Formation.
How do they get and switch submarines at Natural Formation ?
I think If not necessary, Submarine Switch Terminal should only be installed at outposts.

### Reproduction steps

1. Leaving the outpost toward Natural Formation.
2. Access Submarine Switch Terminal in the starting point. (do not docking.)
3. Switch submarine another.
4. Goal to the destination.
5. Submarine switch another at Natural Formation.

----

Figure of Step 2
![image](https://github.com/FakeFishGames/Barotrauma/assets/47914478/b09f5efb-0b95-425a-920f-84d85f60c1eb)

### Bug prevalence

Happens every time I play

### Single player or multiplayer?

Happens in both single player and multiplayer

### Version

v1.2.8.0 (Winter Update hotfix 2)

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment]
Fixed in https://github.com/FakeFishGames/Barotrauma-development/pull/4932, closing
