### ISSUE TITLE
Backpacks speed modifier still doesn't stack with diving suits

### ISSUE THREAD

**Issue by Vykn** [FakeFishGames/Barotrauma#13384]
The issue from https://github.com/FakeFishGames/Barotrauma/issues/12673 has been moved from one speed modifier that doesn't stack to another speed modifier that doesn't stack. 

Diving suits use `SpeedMultiplier` statuseffect, which doesn't stack with any speed modifier, not even itself. So changing backpacks from `SpeedMultiplier` to `StatValue MovementSpeed` hasn't changed anything.
It still doesn't stack with diving suits, and wearing a backpack + any suit is the same speed as just wearing a backpack - that is, wearing a combat suit + backpack is the same speed as abyss suit + backpack, because it just takes the greatest negative speed modifier.

Related - using an oxygenite tank in a slipsuit doesn't give any speed boost, since the speed modifier from the suit doesn't stack with the modifier from the oxygenite. It has been said before that speed modifiers are generally not supposed to stack (and most of them don't), though this case feels like it could go either way. 
For comparison, a combat suit normally swims at 2.1m/s, and a slip at 3.0m/s. But with oxygenite tanks, combat swims at 2.7m/s, and a slipsuit still at 3.0m/s.

**Comment by Regalis11** [comment]
This is actually how the modifier is intended to work: it takes the greatest negative modifier. While it's maybe a little strange, I think making all the multipliers stack might lead to other kinds of issues: it'd make it very difficult to configure all the potential speed multipliers in a way that doesn't lead to some combinations giving you a very low or very high speed multiplier (which tends to break the animations, as they aren't configured to work right with an arbitrarily low or high movement speed).

>So changing backpacks from SpeedMultiplier to StatValue MovementSpeed hasn't changed anything.

It did: previously it was possible to negate the -30% penalty from a backpack by wearing a suit that gives you a smaller penalty, now the largest penalty is applied instead.
