### ISSUE TITLE
IPV6 not work?

### ISSUE THREAD

**Issue by yunkuangao** [FakeFishGames/Barotrauma#13387]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

When I connect using ipv6 it prompts:
```
Failed to start the client {Oops - no IPV6 support yet?}
```

### Reproduction steps

1. Join a multiplayer server
2. Use direct join and fill in the corresponding domain name

### Bug prevalence

Happens every time I play

### Single player or multiplayer?

Multiplayer hosted using a dedicated server

### Version

v1.2.8.0 (Winter Update hotfix 2)

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment]
Thank you for the report!

Internal note: this seems to be coming from the Facepunch.Steamworks (the method `NetAddress.From`). Seems like the library doesn't fully support IPv6 addresses?

**Comment by yunkuangao** [comment]
So,do I need to provide corresponding logs and other information?

**Comment by Regalis11** [comment]
No need, I think we can try to diagnose this with the information you've provided. Thanks and sorry for the inconvenience!

**Comment by Regalis11** [comment]
We've now addressed this in our private repo, the fix should be coming into the unstable version in the near future. :)
