### ISSUE TITLE
DockingModule_02_Colony lacks decorations for Clowns

### ISSUE THREAD

**Issue by ubertpendragon** [FakeFishGames/Barotrauma#13385]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

DockingModule_02_Colony lacks decorations for Clowns, such as background walls. If Clown Haven generates using this docking module, it will look very odd

Comparison

![image](https://github.com/FakeFishGames/Barotrauma/assets/73229309/561a8a57-17f0-42b7-9d87-7cb575152eca)
![image](https://github.com/FakeFishGames/Barotrauma/assets/73229309/3259b6ef-202c-4b12-bbc8-70391d8753a9)

### Reproduction steps

a

### Bug prevalence

Just once

### Single player or multiplayer?

Single player

### Version

v1.2.8.0 (Winter Update hotfix 2)

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment]
These are actually clown decoration:
![image](https://github.com/FakeFishGames/Barotrauma/assets/14351070/8fba2de9-b53c-434a-af18-bc9d61f703ba)

While I agree there could be more decoration to make it even more obviously clown-themed, I wouldn't really consider this a bug, nor an important thing to address: I think the clown decoration in all of the other modules makes it pretty clearly a clown-themed outpost even if the decoration in the docking module isn't as over-the-top as in the other docking module variant.

**Comment by ubertpendragon** [comment]
![image](https://github.com/FakeFishGames/Barotrauma/assets/73229309/12a92330-c921-4d75-aea5-ae01246a1d2a)
