### ISSUE TITLE
[Unstable] PUCS has slightly higher speed boost from oxygenite

### ISSUE THREAD

**Issue by Vykn** [FakeFishGames/Barotrauma#13383]
### What happened?
Most diving items, when containing an oxygenite tank, give a 20% speed boost. PUCS has a 30% speed boost instead. Not entirely sure whether this is intentional, but it seems pretty out of place.

### Version
v1.2.10.0 (unstable)

**Comment by Regalis11** [comment]
Fixed in https://github.com/FakeFishGames/Barotrauma-development/commit/d749e60935e32c6c4df8a42547f5b3d163a4798a

**Comment by Jasontti** [comment]
Tested in: https://github.com/FakeFishGames/Barotrauma-development/pull/4936/commits/9afd93d36b4f1aeed356fa9ac6ee657dbcad9690

No issues found
Closing ticket
