### ISSUE TITLE
[Unstable] PUCS beeps in low oxygen even if not being worn

### ISSUE THREAD

**Issue by Vykn** [FakeFishGames/Barotrauma#13381]
### What happened?

If in the ocean or in a hull with no oxygen, if a PUCS does not have a tank inside it, it will beep. Even if on the ground or being held in the hands.

### Version
v1.2.10.0 (unstable)

**Comment by Regalis11** [comment]
Fixed in https://github.com/FakeFishGames/Barotrauma-development/commit/df08b22d9ff141b52f62f75a402ff6b15c9f6c74

**Comment by Jasontti** [comment]
Tested in: https://github.com/FakeFishGames/Barotrauma-development/pull/4936/commits/9afd93d36b4f1aeed356fa9ac6ee657dbcad9690

No issues found
Closing ticket
