### ISSUE TITLE
Sprite of logbooks is too deep

### ISSUE THREAD

**Issue by SomeRandomNoobKekeke** [FakeFishGames/Barotrauma#13393]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

Logbooks (handheldterminal) have sprite depth 0.8

![Screenshot_1](https://github.com/FakeFishGames/Barotrauma/assets/122838333/57af9150-7568-447a-9229-2fab65bece9c)
Which is deeper than many things, here's a little azimuth on logbook storage for example

![azimuth](https://github.com/FakeFishGames/Barotrauma/assets/122838333/64cf7bbd-6c9f-47a9-ad39-1f22a21b0800)

As you can see if you drop it near reactor, fabricator, deconstructor, engine, depth charge loader, turret loader, ladder
it will be lost

Why not give these things spritedepth 0.55 like for any other tool?

### Reproduction steps

Find important log
Accidentally drop it
Oh no, it's lost

### Bug prevalence

Happens every time I play

### Single player or multiplayer?

Single player

### Version

v1.2.8.0 (Winter Update hotfix 2)

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment]
Fixed in https://github.com/FakeFishGames/Barotrauma-development/commit/4e8febafaaa0d6036fa7969852d8413ef91aa813 (commit in our private repo)
