### ISSUE TITLE
Affliction's final strength is miscalculated in StatusEffect

### ISSUE THREAD

**Issue by zhu-rengong** [FakeFishGames/Barotrauma#13397]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [X] My issue happened while using mods.

### What happened?

Take HMG as an example
**Select this part of the code:**
```xml
<StatusEffect type="OnUse" target="Character" disabledeltatime="true" comparison="and">
    <Conditional skillrequirement="true" weapons="lt 75" />
    <Conditional recoilstabilized="lte 0" />
    <Affliction identifier="stun" strength="0.1" />
</StatusEffect>
<StatusEffect type="OnUse" target="Character" disabledeltatime="true" comparison="and">
    <Conditional skillrequirement="true" weapons="lt 50" />
    <Conditional recoilstabilized="lte 0" />
    <Affliction identifier="stun" strength="0.25" />
</StatusEffect>
<StatusEffect type="OnUse" target="Character" disabledeltatime="true" comparison="and">
    <Conditional skillrequirement="true" weapons="lt 25" />
    <Conditional recoilstabilized="lte 0" />
    <Affliction identifier="stun" strength="0.75" />
</StatusEffect>
```
**Change it to:**
```xml
<StatusEffect type="OnUse" target="Character" disabledeltatime="true">
    <Affliction identifier="bloodloss" strength="10" />
</StatusEffect>
```

Then whenever you fire with hmg you will get 10% Bloodloss
But actually, after the first fire, you get 20% Bloodloss each time

Similarly, if I change the 10% bloodloss to 5% Burn
Then after the first fire, all your limbs will get 15% Burn

### Reproduction steps

Follow the above **What happened?** to make a modified hmg

### Bug prevalence

Happens every now and then

### Single player or multiplayer?

Multiplayer hosted from the in-game menu (= using a listen server)

### Version

v1.2.8.0 (Winter Update hotfix 2)

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment]
Thank you for the report! I gave this a test, and I don't there's actually a bug here. The strength of the affliction seems to be correct: when I fire once, it's 10, and after the second shot, it's 20 and so on. I think you're probably confusing the vitality loss caused by the bloodloss with the strength of the bloodloss. These don't scale linearly: at low strengths, blood loss doesn't affect vitality much, which is why you see a larger jump in the vitality loss when you fire the gun multiple times.

**Comment by zhu-rengong** [comment]
Oh, you are right, I mistakenly thought that the number I saw in the health ui represented strength, but it actually represented vitality decreasement.
