### ISSUE TITLE
Custom Characters that are in the crews team can't be seen on the player list (slugcat)

### ISSUE THREAD

**Issue by kleiner-sentry** [FakeFishGames/Barotrauma#13394]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [X] My issue happened while using mods.

### What happened?

I use a custom lua script very similar to the [Playable Mudraptor mod](https://steamcommunity.com/sharedfiles/filedetails/?id=2852819097&searchtext=playable), and anytime there's a custom character in my team even when I'm playing as the custom character, I'm unable to see the character on the playerlist. This is a problem because it causes problems relating to switching characters in singleplayer, managing talents in singleplayer and multiplayer, and managing money and players in multiplayer. I've attempted to call CrewManager.AddCharacter in lua, but It wouldn't work even if i use hook.call on it. According to EvilFactory, it's not possible to include non-humans into the playerlist.

Additionally, because I use a script that automatically replaces humans with the custom character--like in the Playable mudraptors mod--and assigns it to the player's team, and gives it the proper job, I've noticed its behavior is different between Singleplayer games and Multiplayer games. In singleplayer, anytime you start a new round, the characters are deleted and remade, and a duplicate is also created (and immediately deleted by the script). This also means all inventory data is lost between rounds. If you were to play as the custom character and start a new round, you'd be kicked to a human player. In multiplayer, anyone who isn't playing as the custom character and start a new round, they will loose all data, becoming a regular character (and also getting immediately deleted by the script). Multiplayer is the only mode in which you can play as a custom character, but is also the one mode where you can't have bots.

I understand if you don't want to fix this issue, as this is a modding problem. However If you do fix these problems, it will make it significantly easier to make playable custom species a thing. I'd expect an influx of mods and interest later down the road if these were to be fixed. If you want to experiment yourself, I'll leave my mod here.

[Playable Slugcat.zip](https://github.com/FakeFishGames/Barotrauma/files/14156439/Playable.Slugcat.zip)

### Reproduction steps

1. start multiplayer with the mod (you need lua)
2. set your job to a slugcat and start a campaign, and spawn some more slugcats.
3. start a new round, and all bots except you should be deleted. (the console will say so)
4. Start a singleplayer game and spawn some more slugcats. control one if you like.
5. Start a new round
6. All the slugcats you spawned should have a different color, and no inventory. Additionally if you were playing as a slugcat, you would have been sent to a human the moment the round started.

### Bug prevalence

Happens every time I play

### Single player or multiplayer?

Happens in both single player and multiplayer

### Version

v1.2.8.0 (Winter Update hotfix 2)

### Which operating system did you encounter this bug on?

Windows

**Comment by Abkim27** [comment]
I think that those mods work by spawning character(like player mudraptor) in and "deleting" your human character, so it's maybe the problem simular to the problem with characters that "braindead" being revived and not showing up in crew list

**Comment by Regalis11** [comment]
Addressed in https://github.com/FakeFishGames/Barotrauma-development/pull/5024 (PR in our private repo)

> I think that those mods work by spawning character(like player mudraptor) in and "deleting" your human character, so it's maybe the problem simular to the problem with characters that "braindead" being revived and not showing up in crew list

The issue actually has to do with the character not having CharacterInfo as described above. :) That should be fixed now, by allowing non-human characters to have CharacterInfo as well.

**Comment by kleiner-sentry** [comment]
is there a way to replace the human character with a custom character without using lua jank? or perhaps override how the game spawns players?

**Comment by Jasontti** [comment]
Fix tested.
Tested with modified slugcat test mod that doesn't require lua, it's not possible to run lua in our test builds.
Tested with the steps above.
More comprehensive testing notes in our private repo: https://github.com/FakeFishGames/Barotrauma-development/pull/5024

No issues found.
Closing ticket as completed.
