### ISSUE TITLE
Fix Spawn Point error

### ISSUE THREAD

**Issue by Myrik25** [FakeFishGames/Barotrauma#13399]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

During the campaign, when you do a personnel transport mission it will spawn Cultists, Clowns, etc. on the Assistant Spawn Point instead of Any, Commoner, etc.

### Reproduction steps

Try running the campaign and do various personnel transport missions with an Assistant spawn in a separate area than the Common, Any, etc. 

### Bug prevalence

Happens regularly

### Single player or multiplayer?

Happens in both single player and multiplayer

### -

During in Single or Multi-Player Campaign

### Version

v1.2.8.0 (Winter Update hotfix 2)

### -

During in Single or Multi-Player Campaign

### Which operating system did you encounter this bug on?

Windows

### Relevant error messages and crash reports

```shell
During in Single or Multi-Player Campaign
```

**Comment by Regalis11** [comment]
Thank you for the report!

This is not a bug. The clowns and cultists in the escort missions seem to be assistants, so they spawn at assistant spawnpoints.
