### ISSUE TITLE
[Modding] Lists in sub / level editors are randomized (it's annoying)

### ISSUE THREAD

**Issue by ubertpendragon** [FakeFishGames/Barotrauma#13398]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

All lists are sorted in a somewhat random fashion which makes finding things extra tedious.

It doesn't reflect the sorting of Locationtypes.xml, Outpostgenerationparameters.xml either, and seems to be randomized each time you launch the game.

Any sorting would help greatly

![image](https://github.com/FakeFishGames/Barotrauma/assets/73229309/92f61e1f-2bce-469b-8cc0-7ce280d172bb)
![image](https://github.com/FakeFishGames/Barotrauma/assets/73229309/b601390e-738d-43ac-993e-ba6fb80920db)

Level editor
![image](https://github.com/FakeFishGames/Barotrauma/assets/73229309/3829f5d1-9ab3-4112-bf1a-846cb55ad33e)

### Version

v1.2.8.0 (Winter Update hotfix 2)

**Comment by Regalis11** [comment]
Fixed in https://github.com/FakeFishGames/Barotrauma-development/pull/4938, closing
