### ISSUE TITLE
Icebergs and Ice Spikes taking lower damage from Piercing Coilgun and other projectiles/hitscan with maxtargets 2+

### ISSUE THREAD

**Issue by Draconis13** [FakeFishGames/Barotrauma#13407]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

Ammo that hits a target more than once such a Vanilla gameplay Coilgun Piercing when it hits ice is stopped and does not hit the ice a second time reducing its damage as it cannot be hit multiple times by the piercing projectile/hitscan 

### Reproduction steps

tested in single and multiplayer with vanilla piercing ammo and also with a mod that  that adds autocannons and firearms with 2 and 3 targets to hit on different ammo projectiles/hitscan and they can only hit the ice spike/berg once as it is considered a single target. 

### Bug prevalence

Happens every time I play

### Single player or multiplayer?

Happens in both single player and multiplayer

### Version

v1.2.8.0 (Winter Update hotfix 2)

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment]
Thank you for the report! I would not really consider this a bug: the piercing ammo can hit multiple targets, but as you said, the ice spire is just one target and wont take any "extra damage". I think this also makes sense logically: a projectile that's effective at penetrating targets most likely wouldn't be that good for destroying big chunks of ice.

**Comment by Draconis13** [comment]
That is fair I guess. For the autocannons I wanted them to deal damage as they needed to pass through multiple hitboxes instead of doing large amounts of damage to a single limb,  Similar issue with other weapons. I am looking for the ID of icebergs and icespires so I can make a small explosion effect so they do the intended damage to ice.
