### ISSUE TITLE
Traitor mission: Firing Blanks uncompletable in a submarine with no coilgun

### ISSUE THREAD

**Issue by hammyhamm-bugs** [FakeFishGames/Barotrauma#13400]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [X] My issue happened while using mods.

### What happened?

Gained the traitor mission: Firing blanks, when the submarine we are on has no coilgun to load ammunition into.

Quest should be modified to allow for chaingun, laser as an option rather than just coilgun

### Reproduction steps

1. be in a submarine without a coilgun
2. get a traitor mission firing blanks
3. be unable to complete mission

### Bug prevalence

Happens regularly

### Single player or multiplayer?

Multiplayer hosted from the in-game menu (= using a listen server)

### Version

v1.2.8.0 (Winter Update hotfix 2)

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment]
Thank you for the report!

I was unable to find a way to reproduce the issue. The event should only trigger if the submarine has a coilgun loader, and that seemed to work correctly in my test (the event was ruled out from being selected for the level when I was playing on a sub with no coilgun).

I wonder if it could be that the submarine you encountered this in has a coilgun loader somewhere, despite not having a coilgun?

**Comment by Regalis11** [comment]
No known steps to repro, closing
