### ISSUE TITLE
MeleeWeapon does not specify the target component when creating EntityEvent

### ISSUE THREAD

**Issue by zhu-rengong** [FakeFishGames/Barotrauma#13405]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

As the title said, check the following code:
https://github.com/FakeFishGames/Barotrauma/blob/0c433eb187b20f4bd24a1919b478529b387ee0bf/Barotrauma/BarotraumaShared/SharedSource/Items/Components/Holdable/MeleeWeapon.cs#L477-L478
It will cause async on the client side
Should change it to:
```csharp
server.CreateEntityEvent(item, new Item.ApplyStatusEffectEventData(conditionalActionType, targetItemComponent: this, targetCharacter, targetLimb, useTarget: targetEntity));
server.CreateEntityEvent(item, new Item.ApplyStatusEffectEventData(ActionType.OnUse, targetItemComponent: this, targetCharacter, targetLimb, useTarget: targetEntity));
```

### Reproduction steps

1. Subscribe the mod(OTFX): https://steamcommunity.com/sharedfiles/filedetails/?id=2986787106
2. Host a server and start game
3. Enter cheat code: spawnitem otfx_assaultrifle2 inventory
4. Double click RMB to switch attack mode for using its melee weapon
5. Melee attack at something, you will notice your screen is shaking
6. Shaking will not happen in single player mode

https://github.com/FakeFishGames/Barotrauma/assets/73634685/4f27760b-0172-44db-ab3d-283e48ccb687

### Bug prevalence

Happens every now and then

### Single player or multiplayer?

Multiplayer hosted from the in-game menu (= using a listen server)

### Version

v1.2.8.0 (Winter Update hotfix 2)

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment]
Fixed in https://github.com/FakeFishGames/Barotrauma-development/commit/538899695494acc73730df348723572791cfdd90

**Comment by Regalis11** [comment]
Merged, closing
