### ISSUE TITLE
Cabinet sorting bug

### ISSUE THREAD

**Issue by SomeRandomNoobKekeke** [FakeFishGames/Barotrauma#13402]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

Sorting in cabinets with some specific items constantly rearranges backpacks 

https://github.com/FakeFishGames/Barotrauma/assets/122838333/4e10d79e-4bce-481f-9249-fdae0ff24ca0

It's surprisingly hard to find a set of items that can cause this
So i just extracted a cabinet from my sub to an [item assembly](https://steamcommunity.com/sharedfiles/filedetails/?id=3155310490)

The language is english if it matters
Note that silicon also jumping in loops
Also works with duffle bags
I couldn't reproduce it with suitcases

### Reproduction steps

Take this [item assembly](https://steamcommunity.com/sharedfiles/filedetails/?id=3155310490)
Place it somewhere in sub editor
Press sort button
You don't even need to run test

### Bug prevalence

Happens regularly

### Single player or multiplayer?

Single player

### Version

v1.2.8.0 (Winter Update hotfix 2)

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment]
Fixed in https://github.com/FakeFishGames/Barotrauma-development/pull/4929
