### ISSUE TITLE
Create a saved data with no crew before displaying result of lose

### ISSUE THREAD

**Issue by kaedepon** [FakeFishGames/Barotrauma#13404]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

This is a different method than #13374 .
After lose a game, save before the result is displayed.

### Reproduction steps

1. Start a single player campaign.
2. Kill all crews.
3. After kill the last crew, "Save and quit" before the result is displayed.
4. It makes for cool saved data.

----
Figure of Step 3
![step3](https://github.com/FakeFishGames/Barotrauma/assets/47914478/ac6e8283-e336-4215-9011-d171771650cd)

### Bug prevalence

Happens every time I play

### Single player or multiplayer?

Single player

### Version

v1.2.8.0 (Winter Update hotfix 2)

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment]
Thank you for the report! Fixed in https://github.com/FakeFishGames/Barotrauma-development/commit/5ffa145f9052fea6ac8c8236030923a6abcc057e (commit in our private repo)

**Comment by Rokvach** [comment]
Tested, working correctly. Can be merged and closed.
