### ISSUE TITLE
Unable to dock in campaign (outpost spawned too close to level wall)

### ISSUE THREAD

**Issue by Alpharius-30-milenium** [FakeFishGames/Barotrauma#13401]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [X] My issue happened while using mods.

### What happened?

*I did not managed to find any mentions of this problem but I think it might be a duplicate since problem isn't insignificant.

Docking module sometimes spawn too close to level wall making it impossible to dock if sub is big/have docking not in the left edge

### Reproduction steps

To be honest, it happens completely randomly without any pattern and only proofs of bug I have are screenshots of people complaining about it.
![image](https://github.com/FakeFishGames/Barotrauma/assets/60311003/f036fd31-4514-4ccc-86b7-4ad598d45386)
![image](https://github.com/FakeFishGames/Barotrauma/assets/60311003/b4dfc672-3cfb-46e0-8462-ad7cb5ab77e6)
![image](https://github.com/FakeFishGames/Barotrauma/assets/60311003/028e6424-31ed-4402-a451-0144cea9d5b1)
![image](https://github.com/FakeFishGames/Barotrauma/assets/60311003/a42872ca-0453-4a26-abb3-669eeae8d7e7)

### Bug prevalence

Happens regularly

### Single player or multiplayer?

Happens in both single player and multiplayer

### Version

v1.2.8.0 (Winter Update hotfix 2)

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment]
Insufficient information to address the issue, closing
