### ISSUE TITLE
[Unstable] Tooltip of autosort buttons stopped working, icons unclear

### ISSUE THREAD

**Issue by JeroonBosch** [FakeFishGames/Barotrauma#13411]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

![image](https://github.com/FakeFishGames/Barotrauma/assets/8641689/9de7366a-bcef-4c19-bbc4-0a9b8bdc846d)
I had no idea what these buttons do anymore, when the tooltip disappeared. The icons are not very clear actually. The left icon looks like 'duplicate' and the right icon like 'list'. 

A better icon may be:
![image](https://github.com/FakeFishGames/Barotrauma/assets/8641689/25e325bc-70e2-4054-a274-209fa6ab83c9)

The other button was merging stacks I believe, so an icon like these would maybe suit better?
![image](https://github.com/FakeFishGames/Barotrauma/assets/8641689/34fbf188-0bfa-480f-a3a9-7f829c8d7e35)
or
![image](https://github.com/FakeFishGames/Barotrauma/assets/8641689/f89d8d07-c383-4c98-9a0b-80d3eaab44ce)

### Reproduction steps

1. Hover over the sorting buttons

### Bug prevalence

Just once

### Single player or multiplayer?

Multiplayer hosted from the in-game menu (= using a listen server)

### Version

v1.2.10.0 (unstable)

### Which operating system did you encounter this bug on?

Windows

**Comment by JeroonBosch** [comment]
@NamAnhLe also commented the location of the buttons doesn't make so much sense, it looks more like it affects the pop-up window rather than the contents (which I agree with)

Quick mock-up:
![image](https://github.com/FakeFishGames/Barotrauma/assets/8641689/f094ee3e-f8cb-4f56-a020-93f16aa9f786)

**Comment by NamAnhLe** [comment]
Icon pushed and implemented. Need further work from a programmer to move the icons inside the box.

**Comment by Rokvach** [comment]
Tested, working correctly. Can be merged and closed.
