### ISSUE TITLE
Docking to pirate submarine may have ladder blocking issue

### ISSUE THREAD

**Issue by marpul358** [FakeFishGames/Barotrauma#13410]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

Player Typhon 1 ventral aft docking to a Pirate Typhon 2 dorsal docking port. Climbing up from the Pirate Typhon 2 docking port ladder's left side you get stuck when you reach the Typhon 1 ladders BUT when climbing up from the ladder's right side it sort of yoinks you up to the Typhon 1 ladder and you can climb all the way up.

Not sure if it's a "bug" exactly but pretty sure it is not an intended feature?

Could the mirroring of the Pirate submarine be part of the issue?

Only tested with player docking a Typhon 1 on a Pirate Typhon 2.

### Reproduction steps

1. Player has Typhon 1
2. Pirate submarine is Typhon 2
3. Dock Typhon 1 to Typhon 2 so that the Typhon 2 is the one on the bottom
4. Try to climb up from the Typhon 2 ladder's left side meaning the player character is looking to the right when climbing up
5. Player character gets stuck when trying to climb all the way up to the Typhon 1

### Bug prevalence

Happens every time I play

### Single player or multiplayer?

Single player

### Version

v1.2.8.0 (Winter Update hotfix 2)

### Which operating system did you encounter this bug on?

Windows

**Comment by Jasontti** [comment]
Was able to reproduce this in pvp mode. Typhon for coalition and Typhon 2 for separatists.
![2024-11-27_11-57](https://github.com/user-attachments/assets/1d560336-54a5-4829-94fa-6932bdf71937)

**Comment by Regalis11** [comment]
Fixed in https://github.com/FakeFishGames/Barotrauma-development/commit/8426da42e0ae9cedda2527d70c6d374c2aab86bf
