### ISSUE TITLE
Merchants request goods that are not craftable

### ISSUE THREAD

**Issue by marpul358** [FakeFishGames/Barotrauma#13418]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

Merchant requested goods had Dementonite Crowbar which is not craftable (obtainable?) anymore. Merchants should not request goods that are not craftable or at least obtainable anymore (without console commands). Probably the other dementonite tools are also included. If items are deprecated or made unobtainable steps should include to remove them merchant requested goods list.

### Reproduction steps

Merchant requested goods contained an uncraftable (unobtainable?) item. No idea how to reproduce sensibly if requested goods are RNG.

### Bug prevalence

Just once

### Single player or multiplayer?

Single player

### Version

v1.2.8.0 (Winter Update hotfix 2)

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment]
Fixed in https://github.com/FakeFishGames/Barotrauma-development/commit/74d92eb1696f026b32d971cbab89b0227bcd6861 (commit in our private repo)
