### ISSUE TITLE
The game crashes after console command "quit" in lobby (server was on the same computer)

### ISSUE THREAD

**Issue by pavel4win** [FakeFishGames/Barotrauma#13421]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [X] My issue happened while using mods.

### What happened?

The game not only quits but crashes after console command "quit" in lobby

[crashreport (40).log](https://github.com/FakeFishGames/Barotrauma/files/14236508/crashreport.40.log)

### Reproduction steps

1. create server
2. In lobby press F3 and give console command quit
3. game quits with crash, crash report attached.

### Bug prevalence

Just once

### Single player or multiplayer?

Multiplayer hosted from the in-game menu (= using a listen server)

### Version

v1.2.8.0 (Winter Update hotfix 2)

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment]
This is the expected behavior: the "quit" console command shuts down the server executable, which causes an ungraceful disconnect.
