### ISSUE TITLE
Typo in geneticmaterialhammerhead's description

### ISSUE THREAD

**Issue by Herbalicious** [FakeFishGames/Barotrauma#13423]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

The description for Hammerhead Genetic Material reads:
`Allows the subject to to do [value]% more damage with melee weapons.` 
when it should be:
`Allows the subject to do [value]% more damage with melee weapons.`

### Reproduction steps

Obtain a Hammerhead Genetic Material item and look at the description.

### Bug prevalence

Happens every time I play

### Single player or multiplayer?

Happens in both single player and multiplayer

### Version

v1.2.8.0 (Winter Update hotfix 2)

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment]
Fixed in https://github.com/FakeFishGames/Barotrauma-development/commit/cc72bc63e8abdcf068d8137b6ce179dd32408c03 (commit in our private repo)
