### ISSUE TITLE
Items glitch out and make clang sounds when stuck inside hull

### ISSUE THREAD

**Issue by kleiner-sentry** [FakeFishGames/Barotrauma#13432]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [X] My issue happened while using mods.

### What happened?

It seems that when an item is stuck inside a wall in multiplayer, and the submarine moves around, the faster the item moves and glitches. you can still grab the glitched item through the wall though. seems to be a server-client desync issue, because the glitch is visible and audible to everyone
![20240214185459_1](https://github.com/FakeFishGames/Barotrauma/assets/5957082/243143f2-fc4d-4680-850d-c56397595fb8)

### Reproduction steps

1. cut a hole in the wall
2. drop an item into the hole while it's flooded
3. when it's inside the wall repair the wall
4. move the sub around and hear a constant clang sound

### Bug prevalence

Happens regularly

### Single player or multiplayer?

Multiplayer hosted from the in-game menu (= using a listen server)

### Version

v1.2.8.0 (Winter Update hotfix 2)

### Which operating system did you encounter this bug on?

Windows

**Comment by NotWendy** [comment]
Happens all the time to me too. Pretty much every other round something gets stuck in the floor, and ammo boxes are most prone to it due to being stored on the floor often.
Only happens with external hulls, I have to note. The item gets stuck on the edge of the hull box, between the room and the ocean outside.
If the items aren't cut out of the wall and moved somewhere safe, they will sometimes disappear entirely when the round ends.

**Comment by Regalis11** [comment]
Most likely related to https://github.com/FakeFishGames/Barotrauma/issues/12826, potentially fixed in https://github.com/FakeFishGames/Barotrauma-development/pull/4885 (PR in our private repo).

> Fixed some items falling through holes in walls. Didn't affect all items: the item got teleported outside the sub when it left the sub, and depending on the shape of the collider, it'd either get stuck on the sub's external collider or keep falling. 

> Now items collide with the extra physics body we generate on damaged walls for repair tools to be able to hit the wall.

**Comment by Jasontti** [comment]
Tested in: https://github.com/FakeFishGames/Barotrauma-development/pull/4885/commits/81bd083265f04308815030a2de307ff5eeee9f84

Tested by dropping in and out of the sub most items
Sub fully destroyed and then repaired had no difference

No issues found
Closing ticket
