### ISSUE TITLE
[Modding] Compatibility of module flags/location issues (Abandoned Outpost/Cities)

### ISSUE THREAD

**Issue by ubertpendragon** [FakeFishGames/Barotrauma#13437]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [X] My issue happened while using mods.

### What happened?

Consider a campaign using the following

Vanilla modules
Mod A adds modules
Mod B adds location types (example: "camp", a small military outpost)

For maximum compatibility, you want mod A modules to spawn in any possible mod, so logically you'd pick the "Any" option right?

![image](https://github.com/FakeFishGames/Barotrauma/assets/73229309/f0d8fb1d-c104-4c2b-85e3-a532fc449a31)

**The problem is that if you use "Any" with the "vanilla" module flags _(AdminModule, CrewModule...)_, these modules will spawn in Abandoned Outposts and Cities. The ANY option is currently unuseable because it breaks Abandoned Outposts (and Cities in a lesser way)**

![image](https://github.com/FakeFishGames/Barotrauma/assets/73229309/1d3c7113-1136-41f0-b159-e739f5d9c73f)

**Abandoned Outposts and Cities are the two vanilla "special" outpost types, so they should use special flags:
AdminCity, AdminAbandoned....**

This would improve mod compatibility: mod A just uses "Any", and mod B doesn't have to do extra compatibility mods to benefit from mod A's content

### Version

v1.2.8.0 (Winter Update hotfix 2)

**Comment by ubertpendragon** [comment]
Also be careful because some events use Targetmoduletype which I believe uses module *flags* so changing the airlock module of the city to AirlockCity might make those events not trigger? We couldnt figure it out yesterday

![image](https://github.com/FakeFishGames/Barotrauma/assets/73229309/c385c7e6-179f-44e8-9e78-5f65b313cfe4)

**Comment by Jasontti** [comment]
Tested in: https://github.com/FakeFishGames/Barotrauma-development/pull/4996/commits/27da37ba7a2caec51865da8e854147f590aafb2f

Tested in vanilla and with DE
Tested also that events trigger properly
Could not spot any issues
Closing ticket
