### ISSUE TITLE
Affiliation talent behaviour multiple faction equal reputation

### ISSUE THREAD

**Issue by marpul358** [FakeFishGames/Barotrauma#13433]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

Talent description says:
_Affiliated faction: The faction you have the highest reputation with._

If you have multiple factions with equally high reputation no faction is affiliated. Not sure if this is actually intended to work like this or is it an oversight when multiple factions are considered.

If it is intentional that only a single faction can ever be affiliated with then I guess it is working as intended.
Else should it not treat equally high reputation among factions as all of them being affiliated?

### Reproduction steps

Captain with Politician talent tree talents that give affiliation bonuses. Have all four factions at max reputation of 100. No faction is affiliated.

### Bug prevalence

Happens every time I play

### Single player or multiplayer?

Single player

### Version

v1.2.8.0 (Winter Update hotfix 2)

### Which operating system did you encounter this bug on?

Windows

**Comment by JeroonBosch** [comment]
If you have multiple factions you're equally high reputation with, then none of them really are the one "faction you have the highest reputation with."
The tree is designed around affiliating with one faction, and allows the bonuses to be strong because of that. So yea, this is intended.
