### ISSUE TITLE
Minor issue: technical text appearing in fabricator (colored text not working)

### ISSUE THREAD

**Issue by Alpharius-30-milenium** [FakeFishGames/Barotrauma#13441]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [X] My issue happened while using mods.

### What happened?

Basically if item have some kind of custom text aka hints in it's description for some reason in fabricator you'll see code fragments of the description

### Reproduction steps

1. Add custom description like: "‖color:gui.orange‖HINT‖end‖:"
2. Launch game
3. open fabricator
4. Profit
![image](https://github.com/FakeFishGames/Barotrauma/assets/60311003/9dc758a8-a192-4671-9185-3ec24aed227b)
![image](https://github.com/FakeFishGames/Barotrauma/assets/60311003/e8a7bbce-eab8-480b-87cb-e970039dac4f)

### Bug prevalence

Happens every time I play

### Single player or multiplayer?

Happens in both single player and multiplayer

### Version

v1.2.8.0 (Winter Update hotfix 2)

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment]
Fixed in https://github.com/FakeFishGames/Barotrauma-development/commit/a1708a05ae08da1ebe60241466d6054feeaad2b5 (commit in our private repo)
