### ISSUE TITLE
Diving masks users still use hull oxygen even if their mask is providing them with oxygen

### ISSUE THREAD

**Issue by Sharp-Shark** [FakeFishGames/Barotrauma#13447]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [X] My issue happened while using mods.

### What happened?

    To begin with I got to say I figured this by doing `cl_lua print(Character.Controlled.UseHullOxygen)` so I have clientside lua installed and enabled. But that was the only mod I had, so there is no overriding of the diving mask at all.

    Whenever a character is wearing a diving mask that is providing them with oxygen they still have `UseHullOxygen` equal to `true`. I assume this means a character who is breathing the oxygen from a diving mask would still use the oxygen from a room, which doesn't make a lot of sense.

    For PUCS it makes sense to leave as is since they don't degrade the O2 tanks if the player is in a hull with oxygen, but diving masks degrade their O2 tank and still have `UseHullOxygen` be equal to `true` when it should equal `false`.

    To fix this all that would be required is a simple XML change for `divingmask` and `clowndivingmask`. PUCS already has logical `UseHullOxygen`, Broken Diving Suit is fine too and all other diving suits (regular, disposable, abyssal, combat and slipsuit) are aswell.

### Reproduction steps

Just wear a diving mask with an oxygen tank inside that has a condition above 0 and you'll see that `UseHullOxygen` is still equal to `true`.

### Bug prevalence

Happens every time I play

### Single player or multiplayer?

Happens in both single player and multiplayer

### Version

v1.2.8.0 (Winter Update hotfix 2)

### Which operating system did you encounter this bug on?

Windows

### Relevant error messages and crash reports

```shell
None.
```

**Comment by Regalis11** [comment]
Fixed in https://github.com/FakeFishGames/Barotrauma-development/commit/263bf5a79dec23c65c30714887bdee41cbb26b3a (commit in our private repo)

**Comment by Jasontti** [comment]
Tested in: https://github.com/FakeFishGames/Barotrauma-development/pull/4936/commits/9afd93d36b4f1aeed356fa9ac6ee657dbcad9690

No issues found
Closing ticket
