### ISSUE TITLE
Pressing download from workshop sends me to the menu and back to the server without downloading

### ISSUE THREAD

**Issue by EebleSheembl** [FakeFishGames/Barotrauma#13445]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [X] My issue happened while using mods.

### What happened?

In some servers i join i press the workshop subscribe button only for it to send me to the main menu and back to the server without downloading

### Reproduction steps

Genuinely no idea i think it might just be by chance 

### Bug prevalence

Happens every now and then

### Single player or multiplayer?

Multiplayer hosted from the in-game menu (= using a listen server)

### Version

v1.2.8.0 (Winter Update hotfix 2)

### Which operating system did you encounter this bug on?

Windows

**Comment by itchyOwl** [comment]
I'm sorry for the incovenience. Unfortunately there's not enough information in the ticket to fix the issue. I'll close it for now. Let's re-open it, if there's any steps to repro.
