### ISSUE TITLE
criteria humanprefabidentifier works weirdly

### ISSUE THREAD

**Issue by Alpharius-30-milenium** [FakeFishGames/Barotrauma#13448]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [X] My issue happened while using mods.

### What happened?

For some reason criteria humanprefabidentifier work for raptor owner (the only reference in code for it) and not work on characters that are in the player's team

### Reproduction steps

Make character prefab (like aunt Dorris)
Make event that triggers after you hired the character
Add as a criteria humanprefabidentifier:[created character]
See that it not finding it for some reason

As you can see from screenshots required character is existing but event won't go further

![image](https://github.com/FakeFishGames/Barotrauma/assets/60311003/98f399cf-6554-4953-83d8-4c8faa826c81)
![image](https://github.com/FakeFishGames/Barotrauma/assets/60311003/9ab34049-e612-4226-a193-a02f7f2965bb)
![image](https://github.com/FakeFishGames/Barotrauma/assets/60311003/b798f7f8-236e-4026-84a4-d8ff6560f5e6)
![image](https://github.com/FakeFishGames/Barotrauma/assets/60311003/81d787bb-f132-4da1-abb2-c88c2524929b)

### Bug prevalence

Happens every time I play

### Single player or multiplayer?

Happens in both single player and multiplayer

### Version

v1.2.8.0 (Winter Update hotfix 2)

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment]
It seems the issue here was the NPC lost the reference to the prefab when hired to the crew (in a sense making them no longer instances of that prefab). Fixed in https://github.com/FakeFishGames/Barotrauma-development/commit/9114293a1d54f10bfb15db6b06b216ab85da51d4
