### ISSUE TITLE
Random character remove event on mid round.

### ISSUE THREAD

**Issue by esirprus** [FakeFishGames/Barotrauma#13459]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [X] My issue happened while using mods.

### What happened?

after a short freeze and with "Warning event count very high", many players(or characters?) are removed without log info. And seems the remove event is not for a circular range.
here's a video
https://github.com/FakeFishGames/Barotrauma/assets/44423036/60016a33-dbe4-4d7b-876c-66e38294da0c
log here
![2 NUP`$MQ MXJ8IP LJM4WF](https://github.com/FakeFishGames/Barotrauma/assets/44423036/ff00e6fa-c19a-43d7-b719-de4431bce73b)
client console error (from other player, full error info may missing)
 
![M2FB4VEP4B~VWIPU1C0~U{X](https://github.com/FakeFishGames/Barotrauma/assets/44423036/7c045c62-31de-4f71-a0b6-68fedbaff7ea)
![59K6YZ`FWYO83~VBE8P}ZS0](https://github.com/FakeFishGames/Barotrauma/assets/44423036/dce8785c-d78c-4ab8-9030-14c6a3b81898)

### Reproduction steps

Dont know how to reproduce, seems happens randomly.
If this is caused by mod, maybe looping "RemoveCharacter" in mods and check its behaviour. Or anything else? Please tell me if you devs know more.
If this is caused by game itself, what information can I give?
Since the player-hosted servers are not hosted by me, may won't be able to give information in time, sorry.

### Bug prevalence

Happens every now and then

### Single player or multiplayer?

Multiplayer hosted from the in-game menu (= using a listen server)

### Version

v1.2.8.0 (Winter Update hotfix 2)

### Which operating system did you encounter this bug on?

Windows

### Relevant error messages and crash reports

modlist here
[2024-02-22 LIST SHIT FIX .txt](https://github.com/FakeFishGames/Barotrauma/files/14367750/2024-02-22.LIST.SHIT.FIX.txt)

**Comment by Regalis11** [comment]
Thank you for the report!

I'm afraid this looks like an issue caused by mods: the line numbers in the error message don't correspond to the line numbers in the vanilla code, so there must be some kind of code modifications at play here. There's probably not much we can do to address the issue I'm afraid. :/

**Comment by esirprus** [comment]
thanks for the answer! i will check if some mods cause this

**Comment by Regalis11** [comment]
To elaborate a bit on what I suspect is happening here: some kind of an item is trying to apply a status effect to the character whose inventory it's inside, but that character has been removed already (which should also remove the item and stop it from trying to apply those effects). I think some mod is removing the character in some incorrect way that bypasses things like removing the items in the inventory too. We've had some reports about mods doing stuff like this before: [here's one recent example](https://github.com/FakeFishGames/Barotrauma/issues/13450) (in that case the mod in question was Neurotrauma, but afaik the Performance Fix mod does things like this too).

**Comment by esirprus** [comment]
as i know if neurotrauma run in single player it will remove item or spawn item without using entityspawner(that's why we see those issue happened on singleplayer), like code
```Lua
function HF.RemoveItem(item)
    if item == nil or item.Removed then return end
    
    if SERVER then
        -- use server remove method
        Entity.Spawner.AddEntityToRemoveQueue(item)
    else
        -- use client remove method
        item.Remove()
    end
```

but the key in this issue is "**character** is removed", and the game don't crash, only poped up error on client.
so i think your explanation just explained why client has console error, but that's not the key point

**Comment by esirprus** [comment]
@Regalis11 sorry for the ping, but I'm happy we found the reason, but not like you said, they are simple xml mods, this is an oversight of "inherit".
part of A:
```xml
<StatusEffect type="OnActive" duration="5" target="NearbyCharacters" targets="human" range="500" camerashake="5" setvalue="true" stackable="false">
    <Affliction identifier="hallucinatingshortduration" strength="3" />
    <TriggerEvent identifier="clownhaven_progress" />
    <sound file="Content/Items/JobGear/Clown/ClownExosuitHorn.ogg" type="OnUse" range="500.0" loop="true" />
</StatusEffect>
```
part of B
```xml
<StatusEffect type="OnDeath" target="This" disabledeltatime="true" stackable="false" delay="400">
      <RemoveCharacter />
</StatusEffect>
```
and the mods write A is inherited of B
so finally the SE in A will finally be (i guess)
```xml
<StatusEffect…>
    <RemoveCharacter />
    <Affliction identifier="hallucinatingshortduration" strength="3" />
    <TriggerEvent identifier="clownhaven_progress" />
    <sound file="Content/Items/JobGear/Clown/ClownExosuitHorn.ogg" type="OnUse" range="500.0" loop="true" />
</StatusEffect>
```
I'm not good at programming, but I can guess why our conclusion (the issue was caused by lua mod) was wrong. The server use "Lua For Barotrauma" as executable, so if some error happens on server side, it will point to the Lua For Barotrauma's code, not vanilla code, even the error was caused by vanilla part. And so do the client.
