### ISSUE TITLE
Problems with autointeractwithcontained="true" in sub editor

### ISSUE THREAD

**Issue by ubertpendragon** [FakeFishGames/Barotrauma#13454]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

Two issues:

* When you try to wire an item that uses  _autointeractwithcontained="true"_ in the sub editor, it grabs the item

![image](https://github.com/FakeFishGames/Barotrauma/assets/73229309/b639b60d-11e1-4f20-9beb-63fab80e6f62)

* Cannot open the inventory by pressing E like other containers.

As a side note, it would be nice if weapon holders and fire extinguisher holders had this function 😉 

### Reproduction steps

1. Place artifact holder
2. Place artifact in artifact holder
3. Try to press E to open inventory
4. Go in wiring mode and try to wire it

### Version

v1.2.8.0 (Winter Update hotfix 2)

**Comment by Regalis11** [comment]
Addressed in https://github.com/FakeFishGames/Barotrauma-development/commit/68e4fa4d07aba609ee1c91554f27aac100453675
