### ISSUE TITLE
Water editing doesn't work while in freecam

### ISSUE THREAD

**Issue by BeanyBoi69** [FakeFishGames/Barotrauma#13451]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

Using the water editor (water command) whilst in freecam only has some minor clientside effects, like pushing characters around.

### Reproduction steps

1. Enable water editing
2. Enter freecam
3. Increase/decrease water amount
4. Watch it vanish

### Bug prevalence

Happens every time I play

### Single player or multiplayer?

Multiplayer hosted from the in-game menu (= using a listen server)

### Version

v1.2.8.0 (Winter Update hotfix 2)

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment]
Fixed in https://github.com/FakeFishGames/Barotrauma-development/commit/0f5c430c3955f6e0d0c8e6611cc7ee093022c856
