### ISSUE TITLE
Revenge Squad only lasts 60 seconds

### ISSUE THREAD

**Issue by Kiwibaum** [FakeFishGames/Barotrauma#13466]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

Revenge squad only lasts 60 seconds cause while the talent gives 120 of the affliction correctly the affliction itself has a maxstrength 60, duration 60 and the Effect of it is only defined up to a maxstrength of 60. 
I did confirm this with a timer.

### Reproduction steps

Always active. 
1, Go to Content/Talents/Assistant/AfflictionsAssistant.xml
2. Search for revengesquad
3. Behold the cruelty of maxstrength="60", duration="60", Effect/maxstrength="60"

### Bug prevalence

Happens every time I play

### Single player or multiplayer?

Happens in both single player and multiplayer

### Version

v1.2.12.0 (unstable)

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment]
Fixed in https://github.com/FakeFishGames/Barotrauma-development/commit/148f6ea5418947ba06988a4a85896af66c8344ab (commit in our private repo)
