### ISSUE TITLE
UNSTABLE: Exosuit Stun-Resistance labeled twice.

### ISSUE THREAD

**Issue by MarkCringan** [FakeFishGames/Barotrauma#13463]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

Exosuit stats list "-75% Stun" twice

![image-1](https://github.com/FakeFishGames/Barotrauma/assets/115203569/c166984a-0495-4fb1-b49e-52a7d824772c)

### Reproduction steps

1. Spawn in an exosuit.
2. Stun is there twice

### Bug prevalence

Just once

### Single player or multiplayer?

Single player

### Version

v1.2.12.0 (unstable)

### Which operating system did you encounter this bug on?

Windows

### Relevant error messages and crash reports

```shell
T
```

**Comment by Regalis11** [comment]
Fixed in https://github.com/FakeFishGames/Barotrauma-development/commit/d79a96ca15c57f9f70cd3a2240b07d264388cd71 (commit in our private repo)
