### ISSUE TITLE
Remora - walking from shuttle to main sub isn't possible (need to run)

### ISSUE THREAD

**Issue by JeroonBosch** [FakeFishGames/Barotrauma#13470]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

![image](https://github.com/FakeFishGames/Barotrauma/assets/8641689/9e2b7c50-a3c5-4bc4-b4fa-a82c6abea857)
Apparently this is buggy

### Reproduction steps

1. Load remora
2. Go into the shuttle
3. Walk (not run/sprint back)
4. Notice you cannot
5. Notice running also takes some effort

### Bug prevalence

Happens regularly

### Single player or multiplayer?

Happens in both single player and multiplayer

### Version

v1.2.8.0 (Winter Update hotfix 2)

### Which operating system did you encounter this bug on?

Windows

**Comment by Rokvach** [comment]
Tested, working correctly. Can be merged and closed.
