### ISSUE TITLE
Incorrect crush depth for pirates and shuttles

### ISSUE THREAD

**Issue by SomeRandomNoobKekeke** [FakeFishGames/Barotrauma#13477]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

Real crush depth for pirates and shuttles is less than what is displayed on nav terminal
In fact you will be crushed the moment you receive "approaching crush depth" warning

https://github.com/FakeFishGames/Barotrauma/assets/122838333/e37888a8-a505-4a30-b177-1c2b1466da0c

I believe this is happening because you set crush depth only for submarine [here](https://github.com/FakeFishGames/Barotrauma/blob/master/Barotrauma/BarotraumaShared/SharedSource/Networking/RespawnManager.cs#L91) and [here](https://github.com/FakeFishGames/Barotrauma/blob/master/Barotrauma/BarotraumaShared/SharedSource/Events/Missions/PirateMission.cs#L265)
But according to [this](https://github.com/FakeFishGames/Barotrauma/blob/master/Barotrauma/BarotraumaShared/SharedSource/Map/SubmarineBody.cs#L623) walls are damaged based on their individual crush depths

I think you can just additionally set crush depth to all sub walls, i tried that in my mods, i think it works fine

### Reproduction steps

take this save [Pirate test.zip](https://github.com/FakeFishGames/Barotrauma/files/14392055/Pirate.test.zip)
(or just start new campaign, buy 2 hull upgrades, go to 3rd biome and unlock some pirate mission)
Control pirate captain
steer your ship into the abyss

I couldn't test that with shuttle because you need at least one friend or round will just end with your death

Also would be nice if you add some commands like to teleport any sub, not just main, or to spawn shuttle, or to prevent round from ending
### Bug prevalence

Happens every time I play

### Single player or multiplayer?

Single player

### Version

v1.2.8.0 (Winter Update hotfix 2)

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment]
Thank you for the report!

> I believe this is happening because you set crush depth for them like [this](https://github.com/FakeFishGames/Barotrauma/blob/master/Barotrauma/BarotraumaShared/SharedSource/Networking/RespawnManager.cs#L91) and [this](https://github.com/FakeFishGames/Barotrauma/blob/master/Barotrauma/BarotraumaShared/SharedSource/Events/Missions/PirateMission.cs#L265)
> But according to [this](https://github.com/FakeFishGames/Barotrauma/blob/master/Barotrauma/BarotraumaShared/SharedSource/Map/SubmarineBody.cs#L623) walls are damaged based on their individual crush depths

I take it you didn't take a look at what the RealWorldCrushDepth property does? It simply just sets all of the walls' crush depths to the specified value. So in the vanilla game, the crush depth of all the walls is the same as the crush depth of the submarine. So, in you mod it isn't necessary to go through all the walls, you can just set the sub's crush depth.

>Do you really need that logic?

No, it's not used for anything in the vanilla game. But changing it would require some refactoring to the submarine upgrade system, and I would be surprised if there weren't mods that make use of this functionality for something.
