### ISSUE TITLE
Rotated objects don't mirror correctly in pvp

### ISSUE THREAD

**Issue by Vykn** [FakeFishGames/Barotrauma#13476]
If an item that can't be mirrrored in the sub editor (for example railgun shell racks or crate shelves) has some rotation, then if it is used in a sub v sub mission (pvp or in modded campaign pirate submarines) it will be flipped the wrong way.

An example in my beloved diagugong;

What it looks like in the normal sub:
![image](https://github.com/FakeFishGames/Barotrauma/assets/37850646/5d8b0730-55b0-48d5-94fb-6ea2c82e95b8)

What it looks like in the flipped sub:
![image](https://github.com/FakeFishGames/Barotrauma/assets/37850646/7f1ac742-d1c7-49ea-8e71-ee2c73fecf7f)

### Reproduction steps:
1. Get a submarine with an item that can't be mirrored, and give the item some rotation
2. Load the submarine in a sub v sub multiplayer mission
3. Observe that in the flipped sub, these items are rotated incorrectly

Attached is the .sub file for the diagugong if whoever is testing this would like to use it

[Diagugong.zip](https://github.com/FakeFishGames/Barotrauma/files/14391803/Diagugong.zip)

### Version
Occurred in (Unstable ROS) 1.2.12.0, but I'm quite sure this would occur on (Stable) 1.2.8.0 as well

**Comment by Rokvach** [comment]
Tested, working correctly. Can be merged and closed.
