### ISSUE TITLE
Able to grab opposing team npcs in sub v sub mode

### ISSUE THREAD

**Issue by Vykn** [FakeFishGames/Barotrauma#13472]
### What happened?

In sub v sub pvp multiplayer mode, if you find an npc that is on the opposing team, you can grab them and access their inventory as if they were part of your crew. Not likely to happen often, but very abusable if you swim up to them and take off their suit while in high pressure.

### Reproduction steps
1. Host a sub v sub match and ensure there are npc crew on board
2. Find an enemy npc crew member and take their stuff

### Version
Occurred in (Unstable ROS) 1.2.12.0, but I'm quite sure this would occur on (Stable) 1.2.8.0 as well

**Comment by giists** [comment]
No issues found, closing.
