### ISSUE TITLE
[Unstable] Mudraptor shell error message

### ISSUE THREAD

**Issue by ubertpendragon** [FakeFishGames/Barotrauma#13473]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

The wearable mudraptor armor

![image](https://github.com/FakeFishGames/Barotrauma/assets/73229309/760c3ba6-c989-4e3b-a300-e1229cdc20ef)

### Reproduction steps

.

### Bug prevalence

Just once

### Single player or multiplayer?

Single player

### Version

v1.2.12.0 (unstable)

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment]
Fixed in https://github.com/FakeFishGames/Barotrauma-development/commit/57d5fc0b10b1ae2ff0b925a70ef5cd75476997aa (commit in our private repo)
