### ISSUE TITLE
[Unstable] Custom modules flags send false error messages 

### ISSUE THREAD

**Issue by ubertpendragon** [FakeFishGames/Barotrauma#13488]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [X] My issue happened while using mods.

### What happened?

Outposts using custom module flags send error messages even though the outpost generates properly

![image](https://github.com/FakeFishGames/Barotrauma/assets/73229309/d16d38fa-1c85-4c8d-bf6e-4be657935c7c)

Docking and Main modules
![image](https://github.com/FakeFishGames/Barotrauma/assets/73229309/821ccd41-39aa-45b2-acd3-86131d6e8cbe)

### Version

v1.2.12.0 (unstable)

**Comment by Regalis11** [comment]
Steps to repro pls?

**Comment by ubertpendragon** [comment]
![image](https://github.com/FakeFishGames/Barotrauma/assets/73229309/bc8113a5-b32b-4a87-9b08-e897596230cf)
another example

**Comment by Jasontti** [comment]
Tested in: https://github.com/FakeFishGames/Barotrauma-development/pull/5010/commits/049c97819bcb6787d338dd93823268a55a15982f

Created custom outpost module with allowed location type as "any"
Tested in level editor and didn't get any errors
Tested in SP campaign with no errors also

Closing ticket
