### ISSUE TITLE
Shrapnels spawned by falk bolt will ignore collisions with the user

### ISSUE THREAD

**Issue by zhu-rengong** [FakeFishGames/Barotrauma#13480]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

I checked the source code and found the reason, no matter what, they always ignore user:
https://github.com/FakeFishGames/Barotrauma/blob/bff194d1abfd8f1662eecf3aab1d4e37e5cc79e4/Barotrauma/BarotraumaShared/SharedSource/StatusEffects/StatusEffect.cs#L2143-L2144

Test video:
https://github.com/FakeFishGames/Barotrauma/assets/73634685/41f77859-8f3f-4e9f-b073-1045e43d1e89
I fired the flak bolt at myself, the spawned shrapnels passed me and hit the human behind me
Then I fired the flak bolt at a human, but the spawned shrapnels did not pass the human.

### Reproduction steps

1. control flak cannon and shoot a flak bolt at yourself

### Bug prevalence

Happens every now and then

### Single player or multiplayer?

Single player

### Version

v1.2.8.0 (Winter Update hotfix 2)

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment]
Fixed in https://github.com/FakeFishGames/Barotrauma-development/commit/84e87b4b755b7185a3355f6eaea6589b03dddd7b
