### ISSUE TITLE
Items with melee component after being used to attack lose collision with platforms

### ISSUE THREAD

**Issue by Sharp-Shark** [FakeFishGames/Barotrauma#13483]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [x] My issue happened while using mods.

### What happened?

Tested with a modded item, a wrench and a crowbar (I noticed the issue whilst creating the modded item, then I disabled all my mods and went to test to see if the bug also occurred in vanilla). Inside sub editor I opened Camel, grabbed my melee weapon, dropped it whilst on top of a platform and it fell and stood on top of the platform (which is the expected behavior). I grabbed it, whacked the air and when I dropped it, it fell right through the platform. After using it, it seems to have permanently lost collision with platforms. Just aiming but not whacking will not disable its collision against platforms.

### Reproduction steps

1. Open sub editor
2. Enter test mode
3. Become mechanic
4. Whack wrench (doesn't need to hit anything, just hitting the air works)
5. Drop it whilst standing on top of a platform
6. Watch as it falls right pass it

### Bug prevalence

Happens every time I play

### Single player or multiplayer?

Happens in both single player and multiplayer

### Version

v1.2.8.0 (Winter Update hotfix 2)
v1.4.4.1 (Blood in the Water Uodate)

### Which operating system did you encounter this bug on?

Windows

### Relevant error messages and crash reports

```shell
None.
```

**Comment by kumilanka** [comment]
Tested fix, works:
https://gyazo.com/ee93d2cdb7ff61e385e785b07cce234e

**Comment by Sharp-Shark** [comment]
Simply incredible. Truly a B-Day for all barotrauma players (Barodev-Day).
🙏🙏🙏🙏
