### ISSUE TITLE
[Unstable] Sounds trying to play before level is loaded + error message spam

### ISSUE THREAD

**Issue by ubertpendragon** [FakeFishGames/Barotrauma#13489]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

When you load a level the console will get spammed with error messages for these:

![image](https://github.com/FakeFishGames/Barotrauma/assets/73229309/e3964d06-85bc-49f7-8b51-6a60217ef43a)

### Reproduction steps

Load any level in Leveleditor multiple times

### Bug prevalence

Happens regularly

### Single player or multiplayer?

Single player

### Version

v1.2.12.0 (unstable)

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment]
This has been fixed in our private repo (private commit: https://github.com/FakeFishGames/Barotrauma-development/pull/4989/commits/122e36d9de11dfca614e57ca7cb54c5f84cc6daa), the fix is coming out in the next unstable build. :)

**Comment by Regalis11** [comment]
Nvm, still seems to occur in the latest build

**Comment by Jasontti** [comment]
Tested in: https://github.com/FakeFishGames/Barotrauma-development/pull/5010/commits/049c97819bcb6787d338dd93823268a55a15982f

You can still occasionally these errors in level editor and SP campaign mode.
Level editor settings: outpostlevel, military outpost
Campaign: starting outpost

**Comment by Jasontti** [comment]
Tested again: https://github.com/FakeFishGames/Barotrauma-development/pull/5010/commits/bc234772918a891bcf91f2650d2a32f9a4673622

Generated levels in debug and release builds

No issues found
Closing ticket
