### ISSUE TITLE
[Unstable] Error in "Infiltration" event

### ISSUE THREAD

**Issue by ubertpendragon** [FakeFishGames/Barotrauma#13481]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

![image](https://github.com/FakeFishGames/Barotrauma/assets/73229309/15b78c47-729f-47da-8cb8-1b0ba6080090)

You can delete that line:
`<SpawnAction itemidentifier="bikehorn" targetinventory="clownhonker" targettag="bikehorn1" />`

I added this line in case it was possible to make clowns use bike horns via NPCOperateAction but since it's not possible I forgot to remove it

### Version
Unstable

**Comment by Regalis11** [comment]
Fixed in https://github.com/FakeFishGames/Barotrauma-development/commit/454fc25a5e595c1f25bdf90239a3b96fa081e000
