### ISSUE TITLE
Is "TriggerComponent" in item different from "Trigger" in LevelObject?

### ISSUE THREAD

**Issue by AzureNocte** [FakeFishGames/Barotrauma#13484]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [X] My issue happened while using mods.

### What happened?

I was making a modded creature, my intention was its attack has a chance to cause submarine to be infected ballast flora.
So I made an emitter, it has subelement:

`<Trigger triggeredby="Submarine" radius="800" infectidentifier="ballastflora" infectionchance="0.1" />`

But when I tested, It just did nothing.

So I wound like to know  Is "TriggerComponent" in item different from "Trigger" in LevelObject? 
If so, could you make TriggerComponent contain "infectidentifier" and "infectionchance", and make these two attributes function as well?
(Sorry I'm using issue report to ask this, though it is obviously not a bug...)

files here:
[alienitems.zip](https://github.com/FakeFishGames/Barotrauma/files/14397950/alienitems.zip)

### Reproduction steps

1. Enter sub editor
2. Type console command: spawnitem blightemitter cursor
3. Observe

### Bug prevalence

Happens every time I play

### Single player or multiplayer?

Single player

### Version

v1.2.8.0 (Winter Update hotfix 2)

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment]
These are two entirely different things, Triggers in levelobjects unfortunately don't support infecting with ballast flora.
