### ISSUE TITLE
[Unstable] Explosivemishap doesn't kill the NPCs

### ISSUE THREAD

**Issue by ubertpendragon** [FakeFishGames/Barotrauma#13491]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

Explosion is too weak, text says NPCs die

![image](https://github.com/FakeFishGames/Barotrauma/assets/73229309/e43bdc00-3854-4e6a-9fd6-db437f0d73fd)

### Version

v1.2.8.0 (Winter Update hotfix 2)

**Comment by Jasontti** [comment]
Testing notes: https://github.com/FakeFishGames/Barotrauma-development/pull/5009
AfflictionAction was malformed.
To inform about this in the future "log an error if AfflictionAction does not define the affliction." was added in:
https://github.com/FakeFishGames/Barotrauma-development/pull/5009/commits/92458b8f3f693b4f91f095328082436e64a3422e

Closing as completed
