### ISSUE TITLE
Salt Bulbs explode in water without delay

### ISSUE THREAD

**Issue by SomeRandomNoobKekeke** [FakeFishGames/Barotrauma#13496]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

[The wiki says](https://barotraumagame.com/wiki/Salt_Bulb) that I have 3 seconds to realize my mistake and pick it up

https://github.com/FakeFishGames/Barotrauma/assets/122838333/8d967983-e9de-4d2a-b7b3-e8a6d0eff3e9

### Reproduction steps

Drop a salt bulb fruit in the water

### Bug prevalence

Happens every time I play

### Single player or multiplayer?

Single player

### Version

v1.2.8.0 (Winter Update hotfix 2)

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment]
The information in the wiki seems to be incorrect. I don't see any indication in the xml or the change history that they were ever intended to explode with a 3 second delay.
