### ISSUE TITLE
[Unstable] Explosive Mishap error message

### ISSUE THREAD

**Issue by ubertpendragon** [FakeFishGames/Barotrauma#13490]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

Statuseffect target not defined (the event still works)

![image](https://github.com/FakeFishGames/Barotrauma/assets/73229309/6f81856a-b158-4391-87d8-5705bf31d51f)

### Reproduction steps

`triggerevent Explosivemishap`

### Bug prevalence

Just once

### Single player or multiplayer?

Single player

### Version

v1.2.12.0 (unstable)

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment]
Fixed in https://github.com/FakeFishGames/Barotrauma-development/commit/74df31f0791f921018ffea00859203c1ca50f5ca
