### ISSUE TITLE
Transferring saves (Steam to Epic or vice versa) retains player information only for steam users

### ISSUE THREAD

**Issue by UbiAnomaly** [FakeFishGames/Barotrauma#13494]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

When loading a save from the Steam edition of the game on the Epic version, player data won't be assigned since the game uses steam IDs to identify who is who. It works correctly for players on Steam using crossplay, however. Likewise, a campaign created on the Epic Games store version will not retain player information of the host (potentially other players on Epic, can't verify). This could foreseeably be an issue for players wanting to swap platforms with an ongoing campaign.

### Reproduction steps

1) Host a multiplayer server from the Epic or Steam version of the game
2) Create a campaign, load into it and then alter your inventory in any way (drop an item etc)
3) Load the same campaign from the other launcher
4) Inventory is now reset

### Bug prevalence

Happens every time I play

### Single player or multiplayer?

Multiplayer hosted from the in-game menu (= using a listen server)

### Version

v1.2.12.0 (unstable)

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment]
Thank you for the report!

I'm not entirely sure I'd consider this a bug, or even an issue we should address. If you own the game on some account in the Epic store, and also in Steam, there's no way for the game to know that these accounts belong to the same player nor that the servers should let both accounts control the same character. The only exception is Steam clients using crossplay - when you've linked your accounts, the server can tell they both belong to you.

While we could potentially work around this by something like creating and maintaining our account system, to me it seem like it'd vastly complicate things and be more inconvenient for players, and I feel like it might not be worth it to address such a rare use case (I'm having a hard time thinking of why someone would want to purchase the game on both stores and swap campaign saves between them).
