### ISSUE TITLE
Tutorial instructs to close windows with Aim rather than Close

### ISSUE THREAD

**Issue by ilmarilahti** [FakeFishGames/Barotrauma#13507]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

I've remapped Aim to F away from RMB, since I'm using a buttonless trackpad and holding the "RMB" (two finger press on my laptop) messes with being able to properly aim with the mouse. Close is still on RMB (which works correctly). However, the tutorial suggests closing dialog boxes with F.

A guess is that Aim and Close used to be the same thing in the past, and the tutorial hasn't been updated since separating them.

### Reproduction steps

1. Remap Aim to something other than RMB.
2. Play tutorial (I think this came up with the captain profession tutorial at least, could be elsewhere too)
3. ???
4. Profit

### Bug prevalence

Just once

### Single player or multiplayer?

Single player

### Version

v1.2.8.0 (Winter Update hotfix 2)

### Which operating system did you encounter this bug on?

MacOS

**Comment by Regalis11** [comment]
Fixed in https://github.com/FakeFishGames/Barotrauma-development/commit/aacfa4dfca69d637004151141e36294045d84631. Pushed straight to the release branch, imo this is such a trivial fix it doesn't need to go through the usual review/QA process.
