### ISSUE TITLE
"Name contains illegal symbols" warning when launching the game for the first time

### ISSUE THREAD

**Issue by Regalis11** [FakeFishGames/Barotrauma#13501]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

The "Name contains illegal symbols" warning pops up when you launch the game for the first time. Or more specifically, when your desired player name hasn't been added to the config file yet.

### Reproduction steps

1. Remove config_player.xml or delete "playername" from it to simulate starting the game for the first time
2. Launch the game

### Bug prevalence

Happens every now and then

### Single player or multiplayer?

Other

### Version

v1.2.12.0 (unstable)

### Which operating system did you encounter this bug on?

Windows

**Comment by Rokvach** [comment]
Tested, working correctly. Can be merged and closed.
