### ISSUE TITLE
Separatist Exterior Part Sprite Bleed

### ISSUE THREAD

**Issue by brand175** [FakeFishGames/Barotrauma#13512]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

Sprite bleed on the top part. 
![Barotrauma Screenshot 2024 03 06 - 13 10 43 64](https://github.com/FakeFishGames/Barotrauma/assets/20964160/d5597275-93a9-4f13-9514-0243ff81fadb)

### Reproduction steps

Open Sub Editor
Select Part
Zoom in close to the top middle of the fin

### Bug prevalence

Happens every time I play

### Single player or multiplayer?

Other

### -

Any

### Version

v1.2.8.0 (Winter Update hotfix 2)

### Which operating system did you encounter this bug on?

Windows

**Comment by Rokvach** [comment]
Tested, no issues. Can be merged and closed.
