### ISSUE TITLE
Basic Platform Sprite and wrecked Bleed

### ISSUE THREAD

**Issue by brand175** [FakeFishGames/Barotrauma#13514]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

Sprite bleed on bottom part of platform basic. The wrecked one has skid patterns floating on the top (hard to see)
![Barotrauma Screenshot 2024 03 06 - 14 05 05 37](https://github.com/FakeFishGames/Barotrauma/assets/20964160/d370d60a-f1a3-4a54-998d-b81363f38ca0)

### Reproduction steps

Open sub editor

### Bug prevalence

Happens every time I play

### Single player or multiplayer?

Happens in both single player and multiplayer

### Version

v1.2.8.0 (Winter Update hotfix 2)

### Which operating system did you encounter this bug on?

Windows

**Comment by Rokvach** [comment]
Tested, no issues. Closing.
