### ISSUE TITLE
[Unstable] Voice chat speech bubble not switching colors when switching between radio and local.

### ISSUE THREAD

**Issue by HeatedWafflez** [FakeFishGames/Barotrauma#13522]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

As mentioned in the title. The speech bubble will stay the color of the voice chat mode you first talked in even when switching to radio or local. This is entirely visual and it still does switch but it can be quite disorientating as the bubble serves as a convenient visual indicator compared to looking at the bottom left of your screen.

https://github.com/FakeFishGames/Barotrauma/assets/51425624/2c0b7676-ae3c-4ed4-9057-3dd1d0b64d03

In stable this works correctly however. Can't post the clip because even though the clip is short I can't compress it below 10MB :/

### Reproduction steps

1. Start speaking in local or radio chat.
2. Switch to either while still speaking OR while the speech bubble is still visible after you've stopped speaking.
3. Speak again if following the latter on the previous instruction.

### Bug prevalence

Happens every time I play

### Single player or multiplayer?

Multiplayer hosted from the in-game menu (= using a listen server)

### Version

v1.2.13.0 (unstable)

### Which operating system did you encounter this bug on?

Windows

### Relevant error messages and crash reports

```shell
where the olaf at
```

**Comment by Regalis11** [comment]
Fixed in https://github.com/FakeFishGames/Barotrauma-development/commit/24ae1726263c71247d9821f2170335a5d2f03580

> where the olaf at

He's still working with us, just focusing on our unannounced new project nowadays. :)

**Comment by Rokvach** [comment]
Tested, working c orrectly. Can be merged and closed.
