### ISSUE TITLE
Create new character on outpost causes inventory loss/character reset

### ISSUE THREAD

**Issue by UnhappyWithMyUsername** [FakeFishGames/Barotrauma#13527]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### The Issue:
When dying in an outpost level type and creating a new character, your new character will spawn it, but will completely reset (spawn in as new again) after undocking from the outpost, causing you to lose all items you had in your inventory from that round. A video example can be found below. (We and especially the editor may have had a little too much fun)
https://youtu.be/_LGQGKwY2JI?si=yhEKxCLmDg0KMD7s

### My guess for the cause:
I believe this happens because the outpost level type immediatly forces you into the respawn queue after death occured without asking instead of an opt-in system like in the LocationConnection type.
This process might cause the server to associate the client with its previous character, but loads it in with the data of the newly created one, thinking it is the old character since the respawn queue was already entered before the "create new" button was pressed.

Now the client is in a state where the character is seen as the old character by the server that should be replaced with a new character, despite the character having the new data already and thus is replaced by another new character in the next round which causes the inventory loss.

### Potential fix:
Use the same opt-in system for respawning on the Outpost level type as it is used in the LocationConnetion type instead of forcing a respawn.
Also perhaps disable the "Create New" button when the client opted into the respawn queue with a notification to opt out of it before attempting to create a new character to prevent this bug potentially also happening in LocationConnection types?

### Reproduction steps

1. Start a multiplayer game.
2. Kill your character and create a new one.
3. After respawning as your new character, collect some items.
4. Undock from the outpost.
5. Observe your inventory (Or rather entire character) being reset after loading in.

### Bug prevalence

Happens every time I play

### Single player or multiplayer?

Multiplayer hosted using a dedicated server

### Version

v1.2.8.0 (Winter Update hotfix 2)

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment]
Fixed in https://github.com/FakeFishGames/Barotrauma-development/commit/7e5ae6ec006075507020b5302b26bc567a8091aa
