### ISSUE TITLE
2 Different Cultist Robes being sold 

### ISSUE THREAD

**Issue by EebleSheembl** [FakeFishGames/Barotrauma#13528]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

in the Church Merchant theres two selections of Cultist Robes and i dont mean Zealot

### Reproduction steps

1 Go to Church Merchant
2 Cultist robes for sale

### Bug prevalence

Happens every time I play

### Single player or multiplayer?

Happens in both single player and multiplayer

### Version

v1.2.8.0 (Winter Update hotfix 2)

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment]
Fixed in https://github.com/FakeFishGames/Barotrauma-development/commit/f7f25e3586dc14ae88ad41944f92ce0080e6f7ca
