### ISSUE TITLE
Language settings not saving if no other config option is modified (Client name / resolution etc)

### ISSUE THREAD

**Issue by NilanthAnimosus** [FakeFishGames/Barotrauma#13532]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

When choosing the first-launch language (IE. english), if you immediately quit the game after without any other config setting changes (IE, resolution or serverlist name change), it will prompt to ask again the users language as it does not appear to save the changes initially on selection.

it appears when the config file first generates. language is set to "None" but not saved on choosing the language immediately (and another change is required for that).

### Reproduction steps

1. Remove config_player.xml and serversettings.xml (this one probably unnecessary).
2. validate game files
3. Launch and choose a language
4. Quit the game without touching anything else
5. launch the game and find the language selection.

### Bug prevalence

Happens every time I play

### Single player or multiplayer?

Happens outside single player or multiplayer game modes (e.g. game launches on startup, something broken in the main menu)

### Version

v1.2.8.0 (Winter Update hotfix 2)

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment]
Fixed in https://github.com/FakeFishGames/Barotrauma-development/pull/5053
