### ISSUE TITLE
Portable pump UI blinks when you pick it in multiplayer

### ISSUE THREAD

**Issue by zhu-rengong** [FakeFishGames/Barotrauma#13531]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

As the title said.
https://github.com/FakeFishGames/Barotrauma/assets/73634685/2acb57f7-4d55-4f5a-ad7d-17a93a72aa4b

### Reproduction steps

1. Host a server
2. Pick portable pump

### Bug prevalence

Happens every now and then

### Single player or multiplayer?

Multiplayer hosted from the in-game menu (= using a listen server)

### Version

v1.2.8.0 (Winter Update hotfix 2)

### Which operating system did you encounter this bug on?

Windows

**Comment by zhu-rengong** [comment]
I found the following code that modifies the Holdable's DisplayMsg and PickKey:
https://github.com/FakeFishGames/Barotrauma/blob/3b722fae594d298f7a3b9812adac7b9f991be2dd/Barotrauma/BarotraumaShared/SharedSource/Items/Components/Holdable/Holdable.cs#L671-L672
https://github.com/FakeFishGames/Barotrauma/blob/3b722fae594d298f7a3b9812adac7b9f991be2dd/Barotrauma/BarotraumaShared/SharedSource/Items/Components/Holdable/Holdable.cs#L650-L651
Although I don't know why it does this, if they are removed, the bug will be fixed and the picking shortcut keys and prompts will not be confused.

**Comment by itchyOwl** [comment]
Can confirm the issue and the steps to repro.

**Comment by Jasontti** [comment]
Testing notes: https://github.com/FakeFishGames/Barotrauma-development/pull/5092#issuecomment-2134483192
No issues found.
Closing ticket as completed.
