### ISSUE TITLE
Beacon Stations: Bandits alert each other in combat

### ISSUE THREAD

**Issue by Regalis11** [FakeFishGames/Barotrauma#13530]
Split from: https://github.com/FakeFishGames/Barotrauma-development/issues/4967

I would like for bandits on Beacon Stations to be a bit more clever in their defenses:

- When they're fighting they alert their allies.
- Gunshots or other noise should alert them.

**Comment by Jasontti** [comment]
Testing notes: https://github.com/FakeFishGames/Barotrauma-development/pull/5199#issuecomment-2097749958
No issues found
Closing ticket as completed
