### ISSUE TITLE
Sonar monitor doesn't have a light

### ISSUE THREAD

**Issue by ubertpendragon** [FakeFishGames/Barotrauma#13539]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

The sonar monitor doesn't have a light unlike the navigation terminal

![image](https://github.com/FakeFishGames/Barotrauma/assets/73229309/134770f7-9dae-4381-af99-52be1bc090d5)

Add this inside Sonar in the xml

```xml
      <LightComponent range="10.0" lightcolor="255,255,255,0" powerconsumption="5" IsOn="true" castshadows="false" alphablend="false" allowingameediting="false">
        <Upgrade gameversion="0.9.600.0" lightcolor="255,255,255,0"/>
        <sprite texture="Content/Items/Command/navigatorLights.png" depth="0.025" sourcerect="0,0,384,212" origin="0.5,0.5" alpha="1.0" />
      </LightComponent>
      <LightComponent range="10.0" lightcolor="255,255,255,0" powerconsumption="5" IsOn="true" castshadows="false" alphablend="false" blinkfrequency="1" allowingameediting="false">
        <Upgrade gameversion="0.9.600.0" lightcolor="255,255,255,0"/>
        <sprite texture="Content/Items/Command/navigatorLights.png" depth="0.025" sourcerect="400,0,384,212" origin="0.5,0.5" alpha="1.0" />
      </LightComponent>
```

### Version

v1.2.8.0 (Winter Update hotfix 2)

**Comment by Regalis11** [comment]
Addressed in https://github.com/FakeFishGames/Barotrauma-development/commit/c48603a7fbe72ccedc461b3bce8f4cd14542010b
