### ISSUE TITLE
Bots pick up active flares/glowsticks and put them in containers when cleaning up

### ISSUE THREAD

**Issue by NotWendy** [FakeFishGames/Barotrauma#13546]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

If a player lights up a flare and puts it on the ground in the submarine, idle bots will treat that flare as trash that shouldn't be on the floor, and will put it into the nearest storage cabinet, where it'll continue losing durability without providing light.

Sometimes the player might want to light up their submarine with flares or glowsticks, so it's best for bots to ignore the flare until it has lost all durability, and not treat it as an item that should be cleaned up.

### Reproduction steps

1. Load any submarine and have some idle bots around.
2. Light up a flare, drop it on the floor.
3. Watch one of the bots pick up the flare and stash it away in a cabinet.

### Bug prevalence

Happens every time I play

### Single player or multiplayer?

Happens in both single player and multiplayer

### Version

v1.2.8.0 (Winter Update hotfix 2)

### Which operating system did you encounter this bug on?

Windows

**Comment by Rokvach** [comment]
Tested, working correctly. Can be merged and closed.
