### ISSUE TITLE
(Unstable) Outpost Generation placing a a small room with an oxygen generator instead of an outpost module

### ISSUE THREAD

**Issue by EllieVx** [FakeFishGames/Barotrauma#13541]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

The outpost module at the end of the level didn't load correctly, a small room with an oxygen generator has taken it's place instead.
![image](https://github.com/FakeFishGames/Barotrauma/assets/110141171/baed5229-440e-4ec3-b2e1-f019c07f0c95)

### Reproduction steps

I'm not exactly too sure how this happened, it's a vanilla campaign run that I just started. this happened when I played the game normally for the first time, I used cheats to teleport to the end of the level the second time and it's the same small room with the oxygen generator. This has only happened twice.
![image](https://github.com/FakeFishGames/Barotrauma/assets/110141171/910da9ad-8315-4579-91f8-d3080457467c)
[Unstable Campaign.zip](https://github.com/FakeFishGames/Barotrauma/files/14576000/Unstable.Campaign.zip)

### Bug prevalence

Happens every now and then

### Single player or multiplayer?

Single player

### Version

v1.2.13.0 (unstable)

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment]
Thank you for the report! I'm fairly sure this outpost module is not from the vanilla game, are you sure you're not using any mods? And haven't created any custom outpost modules in the submarine editor?

**Comment by Regalis11** [comment]
I suspect this might be one of those custom submarine mods then, they might include some outpost modules as well.

**Comment by EllieVx** [comment]
I believe they're all my submarines, but I could be wrong. I've only downloaded one custom sub in the past but it's modded so it should be disabled

**Comment by Regalis11** [comment]
Thank you for the extra info. I gave the provided save a test, but unfortunately I don't see that kind of an outpost module (as said, I believe that module is not present anywhere in the vanilla files). You seem to have some kind of content packages enabled that sound like they could include this sort of a module, could it perhaps be "door test"?

![image](https://github.com/FakeFishGames/Barotrauma/assets/14351070/9cd5b028-ba5a-42aa-b0bd-226dd2d30982)

**Comment by EllieVx** [comment]
I opened the game and found the door test, it is indeed an outpost module.
![image](https://github.com/FakeFishGames/Barotrauma/assets/110141171/a5333d13-f5f0-4757-9477-82737ca05383)

**Comment by Regalis11** [comment]
Glad we found the issue. :) Disabling the mod that contains that module should take care of the problem.

**Comment by EllieVx** [comment]
alrighty, thanks!
