### ISSUE TITLE
Purchasing ID cards and receiving them immediately results in blank ID card

### ISSUE THREAD

**Issue by HawkinsThe71st** [FakeFishGames/Barotrauma#13545]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

Purchasing an ID card from a merchant and picking the option to get the item immediately produces a blank ID card instead of one belonging to the person who bought the ID card.
Card purchased with "Get the items now" option:
![image](https://github.com/FakeFishGames/Barotrauma/assets/115734437/7fc4bb51-42a4-49af-93d6-bbdbf2e3e53f)
Card purchased with submarine delivery (after undocking):
![image](https://github.com/FakeFishGames/Barotrauma/assets/115734437/db3de100-47df-4e07-82cb-a3c51e6a8cbe)

### Reproduction steps

1. Buy an ID card with immediate delivery option

### Bug prevalence

Happens regularly

### Single player or multiplayer?

Single player

### Version

v1.2.8.0 (Winter Update hotfix 2)

### Which operating system did you encounter this bug on?

Windows

**Comment by Jasontti** [comment]
Tested the fix in: https://github.com/FakeFishGames/Barotrauma-development/pull/5228/commits/d56c44d6a4e42f3942abccb05246b28a686cad32

Tested in SP and MP
Bought ID cards, one instantly and one delivered
Bought other things
Did a cargo mission

No issues found
Closing ticket as completed
