### ISSUE TITLE
[Modding] Vanilla hallways still generate in modded outposts

### ISSUE THREAD

**Issue by ubertpendragon** [FakeFishGames/Barotrauma#13547]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [X] My issue happened while using mods.

### What happened?

Vanilla hallways will force themselves on modded outposts, no matter if you specify allowed location types. 

![image](https://github.com/FakeFishGames/Barotrauma/assets/73229309/f6cacbfd-eb30-4ddd-8a89-6bbf87e4310f)

Here the hallway has `allowedlocationtypes` defined to the intended locations:
![image](https://github.com/FakeFishGames/Barotrauma/assets/73229309/2cf2c99a-a5b5-44b4-a91f-62ae6dd42ac7)

I assume this is the relevant part of the code that says modules configured with locations/flags should take priority:

https://github.com/FakeFishGames/Barotrauma/blob/3b722fae594d298f7a3b9812adac7b9f991be2dd/Barotrauma/BarotraumaShared/SharedSource/Map/Outposts/OutpostGenerator.cs#L882
https://github.com/FakeFishGames/Barotrauma/blob/3b722fae594d298f7a3b9812adac7b9f991be2dd/Barotrauma/BarotraumaShared/SharedSource/Map/Outposts/OutpostGenerator.cs#L1212

We had a LENGTHY discussion on the modding discord about the workarounds to prevent this (reference to https://github.com/FakeFishGames/Barotrauma/pull/7281) and it's either bugged or unintuitive

![image](https://github.com/FakeFishGames/Barotrauma/assets/73229309/623888c9-e15d-4a23-bca7-58f1af841872)

### Possible Solutions:
**Set all vanilla hallways to 0 commonness (currently 10). In theory they should still generate if there are no other options, but this should prevent them from generating at custom locations if custom hallways are set up.**

I've tested this by modifying vanilla files and got no error. Rolled a bunch of vanilla and modded outposts, no issues there so it should be the simplest solution

### Version

Unstable

**Comment by ubertpendragon** [comment]
The mod:

[#DELocalHuskModIntegrated.zip](https://github.com/FakeFishGames/Barotrauma/files/14593926/DELocalHuskModIntegrated.zip)

1 Go to `leveleditor`
2 Generate coldcavernsoutpost + miningoutpost a bunch of times
3 Increase hallway length if needed
![image](https://github.com/FakeFishGames/Barotrauma/assets/73229309/cd9cc0a9-34d8-48a3-94a7-6f3a4afd915a)

**Comment by Jasontti** [comment]
Tested in: https://github.com/FakeFishGames/Barotrauma-development/pull/4996/commits/27da37ba7a2caec51865da8e854147f590aafb2f

Tested in vanilla and with DE
Vanilla hallways did not generate on lair outposts anymore

No issues found
Closing ticket
