### ISSUE TITLE
adrenaline now completely overshadows liquid oxygenite

### ISSUE THREAD

**Issue by LePiromano** [FakeFishGames/Barotrauma#13549]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [X] My issue happened while using mods.

### What happened?

the new adrenaline rush effect not only keeps you conscious in critical health but also prevents you from losing oxygen and lets you breathe while critical, i believe the whole point of liquid oxygenite was to help in a situation like that, but now with adrenaline you can do that and also keep someone in the fight, maybe either make it so adrenaline rush doesn't allow you to breathe while critical, or buff liquid oxygenite to be a better version of adrenaline? it's been an underpowered drug for years anyway

you also can't use liquid oxygenite to heal someone via syringe gun because it acts like a fuckin grenade launcher

### Reproduction steps

110 lacerations on someone
wait for oxygen damage to be 80
use adrenaline
heals back up
same situation
use liquid oxygenite
~~patient blows up~~
don't use a syringe gun
also heals back up, but almost feels slower

### Bug prevalence

Happens every time I play

### Single player or multiplayer?

Happens in both single player and multiplayer

### Version

v1.2.13.0 (unstable)

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment]
Thank you for the report!

I think you're overlooking the fact that it has other uses: it can be used as an ingredient for oxygenite tanks and as an explosive. It's not really even a drug, but a toxic chemical (even though it has some niche medical uses too), so we don't feel it needs to be on part with adrenaline.
