### ISSUE TITLE
Sprite Bleed Vent & Panel

### ISSUE THREAD

**Issue by brand175** [FakeFishGames/Barotrauma#13548]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

![Barotrauma Screenshot 2024 03 13 - 14 45 02 03](https://github.com/FakeFishGames/Barotrauma/assets/20964160/99b94866-1598-4da8-92a8-105f0b8b1ff3)

![Barotrauma Screenshot 2024 03 13 - 14 48 16 27](https://github.com/FakeFishGames/Barotrauma/assets/20964160/b170e335-4f60-4770-b4d3-b2fcabeeaa9d)

### Reproduction steps

Open sub editor

### Bug prevalence

Happens every time I play

### Single player or multiplayer?

Single player

### Version

v1.2.8.0 (Winter Update hotfix 2)

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment]
Fixed in https://github.com/FakeFishGames/Barotrauma-development/commit/8365f4152cff349e17bd0b45f6d32f43d53fbb75

**Comment by Rokvach** [comment]
Tested, no issues. Closing.
