### ISSUE TITLE
[Modding] Schrodinger's sprite

### ISSUE THREAD

**Issue by Alpharius-30-milenium** [FakeFishGames/Barotrauma#13542]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [X] My issue happened while using mods.

### What happened?

Well, console spamming every damn round that game "can't" find sprite of come creatures but game finds and draws the sprite perfectly (no missing limbs on model, no errors when you spawn creature manually). As you will see on screenshots, creature is perfectly visible but when you load into the round game spams errors

### Reproduction steps

1. Create creature via character editor
2. (?)
3. It might start spamming about missing sprite in console (for some reason it did not happening right away after creature is added to the mod)
![Screenshot_1](https://github.com/FakeFishGames/Barotrauma/assets/60311003/cb5a9dbb-2683-4eaa-9b8e-f4bc52ba1fb5)
![Screenshot_2](https://github.com/FakeFishGames/Barotrauma/assets/60311003/3b6324bd-826b-4429-a864-baa9c71c8f74)
I will send the folder with the creature from example.
[HuskMarine.zip](https://github.com/FakeFishGames/Barotrauma/files/14576347/HuskMarine.zip)

### Bug prevalence

Happens every time I play

### Single player or multiplayer?

Happens in both single player and multiplayer

### Version

v1.2.8.0 (Winter Update hotfix 2)

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment]
I believe this is the same issue as https://github.com/FakeFishGames/Barotrauma/issues/13408 (it doesn't just apply to the "gore sprites", but preloading all sprites from modded characters). Should be fixed for the upcoming update. Sorry for the inconvenience!

**Comment by Alpharius-30-milenium** [comment]
Well, partly it is true but this certain problem isn't "few patches" ago, this bug I've seen even 2 years ago but in that time I wasn't reporting/suggesting anything.

**Comment by Regalis11** [comment]
To my knowledge it's not a recent issue, but has been an issue ever since the "preloading" was implemented (which was several years ago).
