### ISSUE TITLE
shooting at walls with adrenaline from a syringe gun causes an error

### ISSUE THREAD

**Issue by LePiromano** [FakeFishGames/Barotrauma#13550]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [X] My issue happened while using mods.

### What happened?

shot an inner wall with adrenaline from a syringe and an error popped up
![image](https://github.com/FakeFishGames/Barotrauma/assets/55637865/1db0e849-61a9-48d9-8dda-466c63b8560a)
idk if other drugs have the issue

### Reproduction steps

grab a syringe gun
load with adrenaline
shoot down to the floor you're standing on

### Bug prevalence

Happens every time I play

### Single player or multiplayer?

Single player

### Version

v1.2.13.0 (unstable)

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment]
Fixed in https://github.com/FakeFishGames/Barotrauma-development/commit/fdf8dd9dadd4bb830295faeafee8a4b5979b2417

**Comment by Rokvach** [comment]
Tested, working correctly. Can be merged and closed.
