### ISSUE TITLE
when getting an item delivered and then buying the same item to get right away it doesnt get given to you even tho the delivered item still gets delivered

### ISSUE THREAD

**Issue by EebleSheembl** [FakeFishGames/Barotrauma#13552]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

https://github.com/FakeFishGames/Barotrauma/assets/152429881/19f77c30-3148-451e-8096-cbf79f499ea1

### Reproduction steps

get one item delivered to sub
buy the same item and get it now
you wont get the item now but the item will still be delivered

### Bug prevalence

Happens every time I play

### Single player or multiplayer?

Multiplayer hosted from the in-game menu (= using a listen server)

### Version

v1.2.8.0 (Winter Update hotfix 2)

### Which operating system did you encounter this bug on?

Windows

**Comment by EebleSheembl** [comment]
very low quality due to it having to be less than 10 mb

**Comment by Regalis11** [comment]
Thank you for the report! I'm fairly sure this is caused by the same bug as [Lead Duplication](https://github.com/FakeFishGames/Barotrauma/issues/13344#top), but I think we'll need to test and verify.
