### ISSUE TITLE
[Unstable] Beacon Station 4 cant be entered without breaking the hatch

### ISSUE THREAD

**Issue by ubertpendragon** [FakeFishGames/Barotrauma#13567]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

Beacon Station 4s cant be entered without breaking the hatch because the hatch only opens if the water is drained. 
You need power to the pump to drain the water so you see where this is going

**Fastest Solution: remove all the circuit/wires and use 2 buttoned hatches, if someone wants to get in/out they'll open/close it manually anyway**.

![image](https://github.com/FakeFishGames/Barotrauma/assets/73229309/f7fdde7d-8f3a-43d2-9017-5d601aba484f)

### Version

v1.2.13.0 (unstable)

**Comment by Jasontti** [comment]
Tested in: https://github.com/FakeFishGames/Barotrauma-development/pull/5071/commits/b700498e265c75269d27b9b78b8d505324db734e

No issues found
Closing ticket
