### ISSUE TITLE
 DockingModule_02_Colony lacks decorations for Clowns 

### ISSUE THREAD

**Issue by ubertpendragon** [FakeFishGames/Barotrauma#13570]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

https://github.com/FakeFishGames/Barotrauma/issues/13385

![image](https://github.com/FakeFishGames/Barotrauma/assets/73229309/1d3decbc-38f7-4ce4-94d7-2732e81f7839)

### Reproduction steps

.

### Bug prevalence

Just once

### Single player or multiplayer?

Single player

### Version

v1.2.8.0 (Winter Update hotfix 2)

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment]
Fixed in https://github.com/FakeFishGames/Barotrauma-development/commit/08dadadaa35b4a226c46aef8bf264db99ac3d3ae
