### ISSUE TITLE
Ultimate Jest mission will be marked as failed even after being completed

### ISSUE THREAD

**Issue by ubertpendragon** [FakeFishGames/Barotrauma#13571]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

Ultimate Jest mission will be marked as failed even after being completed

The event has been correctly turned into a clown outpost and the clown quest still progresses

![image](https://github.com/FakeFishGames/Barotrauma/assets/73229309/8f797a19-7f53-4f7f-9feb-140bfb6b2a85)
![image](https://github.com/FakeFishGames/Barotrauma/assets/73229309/a6b85379-400e-4e7a-93a0-6940fa405a40)

### Reproduction steps

Do the quest in MP idk

### Bug prevalence

Just once

### Single player or multiplayer?

Multiplayer hosted from the in-game menu (= using a listen server)

### Version

v1.2.8.0 (Winter Update hotfix 2)

### Which operating system did you encounter this bug on?

Windows

**Comment by Wheatley1001** [comment]
It's important to note that checking the mission menu in the tab screen showed the mission as completed.
![image](https://github.com/FakeFishGames/Barotrauma/assets/105495756/865adee9-b705-4fe8-8943-e19794c614ec)

The outpost, when you redock to it immediately upon completion of the "failed" mission, will retain its old name despite changing faction ownership. 
![image](https://github.com/FakeFishGames/Barotrauma/assets/105495756/9df5c8ff-1680-4b12-8481-afe55eae6acb)

This naming inconsistency was fixed later on, although I cannot identify when.

**Comment by Jasontti** [comment]
Tested in: https://github.com/FakeFishGames/Barotrauma-development/pull/5080/commits/9e128e3f7377768899621c515d64f6d3ce13c73a

Tested in campaign and mission mode with mission that use campaign metadata and that not
Tested the path of the bikehorn questline once by metadata manipulation and once normally with cheats
Quick test that SP is not affected
Missions are correctly shown as completed as they progress
Metadata is correctly syncronized to clients at the end of the round

No issues found
Closing as completed
