### ISSUE TITLE
Mission description of salvageartifactabyss is identical to salvageartifactcave due to textidentifier

### ISSUE THREAD

**Issue by A2ur3** [FakeFishGames/Barotrauma#13586]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

I presume the description should be `missiondescription.salvageartifactabyss`
but it doesn't work if textidentifier is used
![wrongmissiondescription](https://github.com/FakeFishGames/Barotrauma/assets/64390906/46cd5b0a-6236-49ea-9833-529224d85620)

### Reproduction steps

1. unlock mission salvageartifactabyss
2. see the mission description

### Bug prevalence

Just once

### Single player or multiplayer?

Single player

### Version

v1.2.8.0 (Winter Update hotfix 2)

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment]
Fixed in https://github.com/FakeFishGames/Barotrauma-development/commit/9bfff8aec52cd2224cb1db0bd9681fec12fb8a79
