### ISSUE TITLE
Repeatedly entering the submarine with a mission logbook creates duplicate text on the mission screen 

### ISSUE THREAD

**Issue by Vykn** [FakeFishGames/Barotrauma#13588]
![image](https://github.com/FakeFishGames/Barotrauma/assets/37850646/0def83b4-663c-4f81-97a0-5ef7d7f874c7)

### Steps to reproduce
1. Start a salvage wreck mission with a logbook
2. obtain the logbook and bring it to the ship
3. leave the ship and re-enter with the logbook (the mission complete popup will show up again)
4. repeat as many times as you would like
5. observe that in the missions tab the text is duplicated for as many times as you re-entered the ship with the logbook

**Comment by Regalis11** [comment]
Fixed in https://github.com/FakeFishGames/Barotrauma-development/commit/3841a79a62adcd458ac563155f30758b4bfd4ef9

**Comment by Jasontti** [comment]
Tested in: https://github.com/FakeFishGames/Barotrauma-development/pull/5075/commits/3d1477dfcead4eb1e10a708ba904c32a148ad9d7

No issues found
