### ISSUE TITLE
Flaw in Russian localization of Load Campaign menu

### ISSUE THREAD

**Issue by Regalis11** [FakeFishGames/Barotrauma#13635]
### Discussed in https://github.com/FakeFishGames/Barotrauma/discussions/13634

<div type='discussions-op-text'>

<sup>Originally posted by **Goosegit11** March 21, 2024</sup>
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [X] My issue happened while using mods.

### What happened?

<details>

<summary> English current: </summary>

```xml
<campaignmode.incompatiblecontentpackage>The content package "[incompatiblecontentpackage]" was not in use when saving the campaign.</campaignmode.incompatiblecontentpackage>
<campaignmode.incompatiblecontentpackages>The content packages [incompatiblecontentpackages] were not in use when saving the campaign.</campaignmode.incompatiblecontentpackages>
```

</details>

<details>

<summary> Russian current: </summary>

```xml
<campaignmode.incompatiblecontentpackage>Набор контента "[incompatiblecontentpackage]" использовался при сохранении кампании.</campaignmode.incompatiblecontentpackage>
<campaignmode.incompatiblecontentpackages>Наборы контента "[incompatiblecontentpackages]" использовались при сохранении кампании.</campaignmode.incompatiblecontentpackages>
```

</details>

<details>

<summary> Russian proposal: </summary> 

```xml
<campaignmode.incompatiblecontentpackage>Набор контента "[incompatiblecontentpackage]" не использовался при сохранении кампании.</campaignmode.incompatiblecontentpackage>
<campaignmode.incompatiblecontentpackages>Наборы контента "[incompatiblecontentpackages]" не использовались при сохранении кампании.</campaignmode.incompatiblecontentpackages>
```

</details>

Потому что 'was not in use' == 'не использовался'

В нынешней локализации куда-то пропала 'не'. Очень путало меня, пока не посмотрел как оно в оригинале.

### Reproduction steps

*

### Bug prevalence

Happens every time I play

### Single player or multiplayer?

Single player

### Version

v1.2.8.0 (Winter Update hotfix 2)

### Which operating system did you encounter this bug on?

Linux

### Relevant error messages and crash reports

_No response_</div>

**Comment by Regalis11** [comment]
Fixed in the localization kit, let's wait for it to be imported and verify the issue is fixed.

**Comment by Goosegit11** [comment]
That was fast. Thank you.

**Comment by Regalis11** [comment]
Addressed, fix coming up in the next update!
