### ISSUE TITLE
[Unstable] Cannot use item orders on rum, ethanol, or cigars

### ISSUE THREAD

**Issue by Regalis11** [FakeFishGames/Barotrauma#13668]
### Discussed in https://github.com/FakeFishGames/Barotrauma/discussions/13666

<div type='discussions-op-text'>

<sup>Originally posted by **ReesesCups** March 25, 2024</sup>
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

You cannot use orders on rum, ethanol, or cigars, such as telling npcs to not interact. This may also be a problem for other items that recently received changes. The cigar sprite is different, and ethanol and rum received the ability to fight infections, so I believe there may have been an error created there. 

### Reproduction steps

1. Make a bottle of rum using raptorbane and ethanol (or cheat it into the game; you can't use additional cargo for rum for some reason).
2. Try to tell your profoundly stupid npc medics to not use your delicious alcoholic beverage by shift-middle mouse clicking on the bottle in a cabinet of your choice
3. cry as they refuse to hear your pleas
4. cry harder as the same applies as well to ethanol and cigars

### Bug prevalence

Just once

### Single player or multiplayer?

Single player

### Version

v1.2.13.0 (unstable)

### Which operating system did you encounter this bug on?

Windows

### Relevant error messages and crash reports

_No response_</div>

**Comment by Regalis11** [comment]
Fixed in https://github.com/FakeFishGames/Barotrauma-development/commit/464990dc86244a550d6b5e50073963854daa0c38

**Comment by Rokvach** [comment]
The items does have the ignore this order but they don't have the new deconstruct order, should they?

**Comment by Regalis11** [comment]
They aren't deconstructible, so they shouldn't have the deconstruct order.

**Comment by Rokvach** [comment]
No issues then,  can be merged and closed.
