### ISSUE TITLE
Human skin color applies to "Human_damage" and "Human_damageoverlay" sprites

### ISSUE THREAD

**Issue by Regalis11** [FakeFishGames/Barotrauma#13678]
### Discussed in https://github.com/FakeFishGames/Barotrauma/discussions/13648

<div type='discussions-op-text'>

<sup>Originally posted by **Dr-Psycho-SK** March 22, 2024</sup>
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

I was working in Sub editor when I took notice of the fact that the "Human_damage" and "Human_damageoverlay" was being affected by the selected skin color of the character.

Needless to say why but I think all the human characters are supposed to have the same blood color and so I assume it's a bug/oversight.

### Reproduction steps

For best results:
1. Find a white skinned character.
2. Find one or more darker skinned characters.
3. Injure them both enough to see the damage overlay clearly and compare the visuals.

![image_2024-03-21_211943856](https://github.com/FakeFishGames/Barotrauma/assets/135719646/26ff8438-e3aa-41d8-909a-04c29daba517)

### Bug prevalence

Happens every time I play

### Single player or multiplayer?

Happens in both single player and multiplayer

### Version

v1.2.8.0 (Winter Update hotfix 2)

### Which operating system did you encounter this bug on?

Windows

### Relevant error messages and crash reports

```shell
None.
```
</div>

**Comment by Regalis11** [comment]
Fixed in https://github.com/FakeFishGames/Barotrauma-development/commit/a35c927042e1f886242db75a453fcbe16521e61d

**Comment by kumilanka** [comment]
<img width="361" alt="bloody_leg_gallery" src="https://github.com/FakeFishGames/Barotrauma/assets/29928947/79a2c0b4-e088-440d-bc01-65e8a45db636">
Tested using explosions in sub editor. Fix seems to be working.

**Comment by kumilanka** [comment]
<img width="153" alt="blood_comparison" src="https://github.com/FakeFishGames/Barotrauma/assets/29928947/ba112863-55d0-47a0-bf68-b38c7f0869af">

Seems to work correctly.

**Comment by Regalis11** [comment]
Merged, closing
