### ISSUE TITLE
Tasty Target causes passive sonar to be able to see as far as active sonar without alerting enemies.

### ISSUE THREAD

**Issue by Regalis11** [FakeFishGames/Barotrauma#13676]
### Discussed in https://github.com/FakeFishGames/Barotrauma/discussions/13671

<div type='discussions-op-text'>

<sup>Originally posted by **BlackMoons** March 27, 2024</sup>
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

When an assistant gets tasty target, a huge noise appears on passive sonar where they are that lights up the entire sonar range with sonar reflections. 

Enemies don't seem to notice this noise either, allowing you to see enemies on passive sonar that can't see you at all. Makes the game a LOT easier as passive sonar works as well as active. 

Expected behavior: To not be able to see the level in passive sonar unless something is actually making a noise that attracts enemies. 

### Reproduction steps

Start campaign
Spawn assistant, Observe minimal noise on sonar in passive mode. 

give assistant enough EXP to reach tasty target and take the trait

Notice passive sonar mode showing a HUGE noise where the assistant is, as loud as a large engine at full throttle. Can see the level via noise reflection almost as well as active sonar, even with the ships engines/reactor/etc off. 

### Bug prevalence

Just once

### Single player or multiplayer?

Single player

### Version

v1.2.8.0 (Winter Update hotfix 2)

### Which operating system did you encounter this bug on?

Windows

### Relevant error messages and crash reports

_No response_</div>

**Comment by Rokvach** [comment]
Tested, working correctly. Can be merged and closed.

**Comment by Xardion495** [comment]
What works correctly?? Tasty Target still works as legal cheat and highlights all the rocks and enemies around
[tasty.webm](https://github.com/user-attachments/assets/e3e05692-7652-4dda-ac47-422cf43790e9)

**Comment by Xardion495** [comment]
@Regalis11 
Please note
