### ISSUE TITLE
Charybdis have some troubles attacking subs that are lying on the sea floor

### ISSUE THREAD

**Issue by itchyOwl** [FakeFishGames/Barotrauma#13689]
### Discussed in https://github.com/FakeFishGames/Barotrauma/discussions/13601

<div type='discussions-op-text'>

<sup>Originally posted by **SomeRandomNoobKekeke** March 17, 2024</sup>
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

When sub is lying on the sea floor Charybdis attack often gets canceled at the last moment
I guess it's caused by attackpattern="Circle" because with attackpattern="Straight" no such problem occurs

https://github.com/FakeFishGames/Barotrauma/assets/122838333/d1844f8f-cc81-4fbd-a4a9-9929307a0985

If it's already been addressed in upcoming "eating crew from the sub" update then excuse me
I guess it's not intended because it's stops Charybdis from eating the crew

### Reproduction steps

Teleport sub on the sea floor
You might want to godmode and lock it
spawn some Charybdises and watch

### Bug prevalence

Happens every time I play

### Single player or multiplayer?

Single player

### Version

v1.2.8.0 (Winter Update hotfix 2)

### Which operating system did you encounter this bug on?

Windows

### Relevant error messages and crash reports

_No response_</div>

**Comment by Jasontti** [comment]
Tested in: https://github.com/FakeFishGames/Barotrauma-development/pull/4663/commits/d273439767bce4182bae7a3c121f15a13433214d

Tested as a part of PR testing and no issues found.

Closing as completed
