### ISSUE TITLE
[Unstable] Crash when you grab a character that doesn't belong to any player and has money on them

### ISSUE THREAD

**Issue by Regalis11** [FakeFishGames/Barotrauma#13693]
### Discussed in https://github.com/FakeFishGames/Barotrauma/discussions/13692

<div type='discussions-op-text'>

<sup>Originally posted by **Regalis11** March 28, 2024</sup>
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

The game crash when you grab a character that doesn't belong to any player and has money on them in MP.
![image](https://github.com/FakeFishGames/Barotrauma/assets/14351070/c3b9cbc9-cb11-43ac-8e08-a3a15858ec12)

### Reproduction steps

1. Start a multiplayer campaign
2. Trigger a wreck salvage mission (e.g. `unlockmission salvagewreck1`)
3. Crash

### Bug prevalence

Happens regularly

### Single player or multiplayer?

Multiplayer hosted from the in-game menu (= using a listen server)

### Version

v1.4.0.0 (unstable)

### Which operating system did you encounter this bug on?

Windows

### Relevant error messages and crash reports

_No response_</div>

**Comment by Regalis11** [comment]
Fixed in https://github.com/FakeFishGames/Barotrauma-development/commit/f37ba4ab0a62b0cdd0ba0acacf0d97388077afe1

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
