### ISSUE TITLE
Downloading workshop mods when joining a server no longer works

### ISSUE THREAD

**Issue by Regalis11** [FakeFishGames/Barotrauma#13705]
### Discussed in https://github.com/FakeFishGames/Barotrauma/discussions/13695

<div type='discussions-op-text'>

<sup>Originally posted by **SquidingTin** March 29, 2024</sup>
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [X] My issue happened while using mods.

### What happened?

The game kicks you to the main menu when you try to download mods from workshop. This appears to have only started happening after today's update. The Epic Games patch update.

I can get multiple people to verify that this isn't an isolated issue either.

### Reproduction steps

1. Find a multiplayer server running mods you aren't currently subscribed to.
2. Press "Subscribe to all on workshop"
3. get kicked to main menu

https://github.com/FakeFishGames/Barotrauma/assets/33539475/8cbbece8-cb4c-4e43-a653-eed2f6babfa9

### Bug prevalence

Happens every time I play

### Single player or multiplayer?

Multiplayer hosted from the in-game menu (= using a listen server)

### Version

v1.3.0.0/v1.3.0.1

### Which operating system did you encounter this bug on?

Windows

### Relevant error messages and crash reports

```shell
WARNING: Tried to restore enabled packages multiple times/without performing a backup
```
</div>

**Comment by 0roxson0** [comment]
I'm experiencing the same problem as this guy. When I try to subscribe to all mods all it does is bring me to the main menu without subscribing to any mods.

**Comment by Lussitonic** [comment]
I would like to confirm that this issue is something preventing me from joining modded servers (under the name "kitten")

**Comment by Rokvach** [comment]
Tested, working correctly. Can be merged and closed. 

Tested by joining public modded servers through the PR and being able to download mods from the workshop upon joining and then compared it to the current Stable.

**Comment by Regalis11** [comment]
The fix should now be live in the public build. Sorry for the inconvenience!
