### ISSUE TITLE
Mission mode enemy vessel still called "pirate" mission

### ISSUE THREAD

**Issue by itchyOwl** [FakeFishGames/Barotrauma#13743]
### Discussed in https://github.com/FakeFishGames/Barotrauma/discussions/13742

<div type='discussions-op-text'>

<sup>Originally posted by **Vykn** April  8, 2024</sup>
### What happened?

![image](https://github.com/FakeFishGames/Barotrauma/assets/37850646/280f8836-16fb-4970-90ae-37e52115921d)

Pirates don't exist anymore. The mission should probably be renamed to "Enemy vessel" or something such.

### Reproduction steps

1. Start a server, select mission mode
2. Select Pirate mission
3. No pirates

### Version

v1.3.0.2</div>

**Comment by Regalis11** [comment]
This has already been fixed in the latest unstable, closing
