### ISSUE TITLE
[Unstable] Half of the crawlers are unable to board submarines from birth

### ISSUE THREAD

**Issue by Regalis11** [FakeFishGames/Barotrauma#13756]
### Discussed in https://github.com/FakeFishGames/Barotrauma/discussions/13755

<div type='discussions-op-text'>

<sup>Originally posted by **SomeRandomNoobKekeke** April  8, 2024</sup>
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

I was testing https://github.com/FakeFishGames/Barotrauma/discussions/13751 and found that it was a symptom of a bigger problem, so i made another report 

I was unable to reproduce it with mudraptors, husks, crawler husks, large crawlers ,threshers, hammerheadspawn
only with normal crawlers (and crawler hatchlings)

I don't understand why half is broken and half is normal, this seems random
They don't get stuck in stable

https://github.com/FakeFishGames/Barotrauma/assets/122838333/c8b30b66-405e-4a35-a051-1848e398105a

https://github.com/FakeFishGames/Barotrauma/assets/122838333/c9d9a0c6-6682-47c5-9cdb-e4a1257fa071

### Test 1
open some sub in editor, lock it and explode it
put some human bait inside and godmode it
spawn some crawlers outside and watch them get stuck in the walls

### Test 2
open some sub in editor, lock it and explode it
spawn crawler, control it, try to board the sub
kill it, repeat

### Bug prevalence

Happens every time I play

### Single player or multiplayer?

Single player

### Version

v1.4.0.0 (unstable)

### Which operating system did you encounter this bug on?

Windows

### Relevant error messages and crash reports

_No response_</div>

**Comment by Jasontti** [comment]
Tested in: https://github.com/FakeFishGames/Barotrauma-development/pull/5153/commits/79b1912e0035dcd9718bfcac19c91487b3128426

Tested in SP and MP
Spawned in all the crawlers and most of other enemies too, even big ones like charybdis
Observed their behaviour

Sidenote:
There is occasionally a single crawler that is unable to find their way inside the sub and chooses to attack already destroyed piece of hull, but that seems like not related to this ticket and hardly an issue. Usually when sub moves they reset their targeting and figure another way in.

No issues found
Closing ticket
