### ISSUE TITLE
[Unstable] Pre-defined name and description texts of missions always get displayed regardless of translation files.

### ISSUE THREAD

**Issue by Regalis11** [FakeFishGames/Barotrauma#13777]
### Discussed in https://github.com/FakeFishGames/Barotrauma/discussions/13772

<div type='discussions-op-text'>

<sup>Originally posted by **AzureNocte** April 12, 2024</sup>
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [X] My issue happened while using mods.

### What happened?

I noticed that when 1.4.3.0 comes out, translation of modded mission fails to shows up, it only shows the pre-defined name and description, which I think should not be like this. 
Because these pre-defined mission names and descriptions are for languages that does not have a matching translation file yet(unlike vanilla missions that always have translation available), not intended to replace them. 

Here is the mod I use, it used to work just fine. 
[Undersea Horrors Mission Edition.zip](https://github.com/FakeFishGames/Barotrauma/files/14961109/Undersea.Horrors.Mission.Edition.zip)

### Reproduction steps

1. start modded mission.
2. no translation displayed.

### Bug prevalence

Happens regularly

### Single player or multiplayer?

Happens in both single player and multiplayer

### Version

Other

### -

v1.4.3.0 (unstable)

### Which operating system did you encounter this bug on?

Windows

### Relevant error messages and crash reports

_No response_</div>

**Comment by Rokvach** [comment]
Tested by using the provided mod and running it with simplified chinese selected, translations are shown correctly on mission texts. Working correctly. Can be merged and closed.
