### ISSUE TITLE
Fractal guardians spawn in vents / other weird places in clear ruin mission

### ISSUE THREAD

**Issue by itchyOwl** [FakeFishGames/Barotrauma#13779]
### Discussed in https://github.com/FakeFishGames/Barotrauma/discussions/13770

<div type='discussions-op-text'>

<sup>Originally posted by **SomeRandomNoobKekeke** April 12, 2024</sup>
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

So they spawn stuck and helpless
Almost in every clear ruin mission in unstable at least one guardian is stuck
I couldn't reproduce in stable though, mb i'm just too lazy

![20240412110319_1](https://github.com/FakeFishGames/Barotrauma/assets/122838333/05144735-85c1-44df-8d8f-340685154d21)
![20240412121155_1](https://github.com/FakeFishGames/Barotrauma/assets/122838333/f2c19fec-d03b-4b17-a3a6-bdb7e2027824)
![20240412134339_1](https://github.com/FakeFishGames/Barotrauma/assets/122838333/c760bcf2-5388-439e-8679-0a4c2c5d8279)
![20240412134938_1](https://github.com/FakeFishGames/Barotrauma/assets/122838333/b030d8e6-cc68-46d3-9edf-b8bd3ad0e4cf)
![20240412135546_1](https://github.com/FakeFishGames/Barotrauma/assets/122838333/4b4fadde-88b3-4215-ab2d-4107e04e0ca2)
![20240412140428_1](https://github.com/FakeFishGames/Barotrauma/assets/122838333/20d1bcd6-3b7e-4bd1-b071-eac93a0b539e)
![20240412135953_1](https://github.com/FakeFishGames/Barotrauma/assets/122838333/45b305b4-f2c4-4018-9de5-438434df95dc)

### Reproduction steps

Start clear ruin mission on 100% difficulty
Find guards

### Bug prevalence

Happens every now and then

### Single player or multiplayer?

Single player

### Version

v1.4.0.0 (unstable)

### Which operating system did you encounter this bug on?

Windows

### Relevant error messages and crash reports

_No response_</div>

**Comment by Jasontti** [comment]
Tested in: https://github.com/FakeFishGames/Barotrauma-development/pull/5186/commits/16b36f891409b8fb7a7be5d8e2ac5fce70b3f70e

Started 20+ ruins mission in SP and MP in various difficulty levels and biomes
did not see guardian stuck in the vents

No issues found
Closing ticket
