### ISSUE TITLE
Bots don't crouch when attacking with knife

### ISSUE THREAD

**Issue by itchyOwl** [FakeFishGames/Barotrauma#13780]
### Discussed in https://github.com/FakeFishGames/Barotrauma/discussions/13776

<div type='discussions-op-text'>

<sup>Originally posted by **SomeRandomNoobKekeke** April 13, 2024</sup>
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

Also unstable 1.4.3.0 doesn't have watermark

https://github.com/FakeFishGames/Barotrauma/assets/122838333/4916945c-8edb-46b7-a3c0-185beb882216

### Reproduction steps

control one of the guards
giveaffliction "Husk infection" 100, unpause, kill
See how other guards deal with this situation

### Bug prevalence

Happens every time I play

### Single player or multiplayer?

Single player

### Version

v1.4.3.0 (unstable)

### Which operating system did you encounter this bug on?

Windows

### Relevant error messages and crash reports

_No response_</div>

**Comment by itchyOwl** [comment]
Managed to fix the issue, but still not sure what caused it. Still investigating, so that we can fix it without causing side effects.

**Comment by itchyOwl** [comment]
Fixed in FakeFishGames/Barotrauma-development#5188.

**Comment by Rokvach** [comment]
Tested, working correctly. Can be merged and closed.
