### ISSUE TITLE
No connection route from first biome to second biome

### ISSUE THREAD

**Issue by Regalis11** [FakeFishGames/Barotrauma#13797]
### Discussed in https://github.com/FakeFishGames/Barotrauma/discussions/13791

<div type='discussions-op-text'>

<sup>Originally posted by **kaedepon** April 19, 2024</sup>
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

Maybe it is again of #10047 
Start seed is ```b@@`cBj?```
The first biome has no traversable route connecting it to the second biome for the campaign.

----
![missingpath](https://github.com/FakeFishGames/Barotrauma/assets/47914478/50e4462e-7143-4410-9cbf-a02b63439140)

The save data is here.
[No_connection.zip](https://github.com/FakeFishGames/Barotrauma/files/15043071/No_connection.zip)

### Reproduction steps

1. Input Seed ```b@@`cBj?```
2. Start a campaign.
3. Watch generated map.

### Bug prevalence

Happens every time I play

### Single player or multiplayer?

Happens in both single player and multiplayer

### Version

v1.3.0.4

### Which operating system did you encounter this bug on?

Windows

### Relevant error messages and crash reports

_No response_</div>

**Comment by giists** [comment]
Closing as completed
