### ISSUE TITLE
Persistence between round restarts (dead bots stay dead, completed missions stay completed)

### ISSUE THREAD

**Issue by Regalis11** [FakeFishGames/Barotrauma#13820]
### Discussed in https://github.com/FakeFishGames/Barotrauma/discussions/13819

<div type='discussions-op-text'>

<sup>Originally posted by **bananaman6213** April 24, 2024</sup>
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

While doing a Hunting Grounds mission in multiplayer (unstable at the time but the bug seems to have made it to stable), our Sootman bot died. We continued to kill the abyssal, but were sunk to crush depth and returned to the server lobby. Upon retrying the round, Sootman was missing from the crew list and the Hunting Grounds mission was absent. Players had gained experience from the completed mission as well.

I believe the bug still occurs whether you let everyone die or end the round early

Restarting the round a second time seems to fix it

### Reproduction steps

1. Start a round with a mission completable mid-round (Hunting Grounds in our case, but a swarm or beacon may also work)
2. Let a bot die, and complete a mission
3. Either let the whole crew die or return to the server lobby early
4. When restarting, the bots should still be dead and the missions should be absent

### Bug prevalence

Happens every now and then

### Single player or multiplayer?

Multiplayer hosted from the in-game menu (= using a listen server)

### Version

v1.4.4.1 (Blood in the Water Update)

### Which operating system did you encounter this bug on?

Windows

### Relevant error messages and crash reports

_No response_</div>

**Comment by Regalis11** [comment]
Fixed in https://github.com/FakeFishGames/Barotrauma-development/commit/4535443ecf2dff12f5cfcad974227fe8529fa15b, closing. Will be included in the next hotfix.

**Comment by bananaman6213** [comment]
I can't confirm this personally but I have heard that the issue is still present in 1.4.5.0
Was unable to reproduce it though, so take this with a grain of salt. Mostly just posting this to put it back on your radar as a potential issue.
