### ISSUE TITLE
MustWalk and the animation-less scuba suit cause a walking animation lock.

### ISSUE THREAD

**Issue by HakureiReimu18** [FakeFishGames/Barotrauma#13849]
### Discussed in https://github.com/FakeFishGames/Barotrauma/discussions/13846

<div type='discussions-op-text'>

<sup>Originally posted by **HakureiReimu18** April 26, 2024</sup>
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [X] My issue happened while using mods.

### What happened?

 This is a bug related to MustWalk. In the game, I wrote a new Affliction that applies the MustWalk effect using AbilityFlag, which worked fine in previous versions. However, after the recent character skeleton animation update, if this Affliction is repeatedly applied, and then the character wears a scuba suit that does not change the character's animation, and waits for the effect to wear off before applying it again, the character's walking animation will still be the default Vanilla scuba suit walking animation, regardless of whether the scuba suit is worn or not. This is the link to my mod's Steam Workshop page:https://steamcommunity.com/sharedfiles/filedetails/?id=2941124988

### Reproduction steps

1.In my mod, there is an affliction associated with a character's clothing. Wearing it applies several afflictions, one of which restricts the character to walking only, utilizing MustWalk. In my mod, there are two pieces of equipment and a new skill level that, when their conditions are met, can remove this debuff.
2.I opened the submarine editor and prearranged items in it, then started testing. First, I had the character wear the "Patchouli's Outfit+" which grants an additional talent and continuously applies "The_Still_Library" affliction.
3.I entered the command "setskill Touhou_Magic max" in the F3 console to maximize the skill level of the new skill added by your mod. Then, I helped you equip the "Magic_Pouch" and "Magic_Veil" so that you can consistently obtain the "Touhou_Magic_Boost" effect. When this effect reaches its maximum value, your character will become immune to the affliction called "MustWalk," allowing them to regain their running ability.
4.The problem lies here. When the character becomes immune to "MustWalk," their animation is normal. However, if I remove the "Magic_Pouch" and the character loses the immunity to "MustWalk," and then apply the "MustWalk" effect again, the character's walking animation will change to the animation used when wearing a diving suit. This also happens when I remove the "Magic_Veil." Regardless of what actions I take, the walking animation remains the same, and only the walking animation changes in this manner.

https://github.com/FakeFishGames/Barotrauma/assets/140368777/0afad10a-7249-4683-a44d-016119a3bb34

### Bug prevalence

Happens every time I play

### Single player or multiplayer?

Happens in both single player and multiplayer

### Version

v1.4.4.1 (Blood in the Water Update)

### Which operating system did you encounter this bug on?

Windows

### Relevant error messages and crash reports

_No response_</div>

**Comment by Regalis11** [comment]
Thank you for the report! I gave the mod a test, but unfortunately I couldn't follow the repro steps: there doesn't seem to be an item called "Patchouli's Outfit+" nor an affliction called "MustWalk" in the mod.

**Comment by Regalis11** [comment]
Also, please do not create bug reports in the issue tracker yourself: they should now instead be created in the [Bug Reports section in Discussions](https://github.com/FakeFishGames/Barotrauma/issues/13590).
