### ISSUE TITLE
Travel menu appears at the start of "flipped" levels

### ISSUE THREAD

**Issue by Regalis11** [FakeFishGames/Barotrauma#13862]
### Discussed in https://github.com/FakeFishGames/Barotrauma/discussions/13809

<div type='discussions-op-text'>

<sup>Originally posted by **ubertpendragon** April 23, 2024</sup>
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [X] My issue happened while using mods.

### What happened?

If you travel from right to left on the map, the levels are "flipped", sometimes resulting in the submarine spawning on top of the starting point.

**1. This will open the map menu (happens when you reach a level exitpoint), which can be confusing/annoying**

**2. If the menu opens, this will cause a bug when reaching the destination: sometimes you won't be able to travel to the location and will have to pick another one.** 

Example:
I am travelling to this location, which can be entered by getting near (exitpoint)
However, the game will not let me enter the location if the map has been opened on round start

![image](https://github.com/FakeFishGames/Barotrauma/assets/73229309/b6042ec3-f6c8-4cb1-9ccf-d147bf01ac40)

### Reproduction steps

Download 
[#DELocalHuskModIntegrated.zip](https://github.com/FakeFishGames/Barotrauma/files/15079174/DELocalHuskModIntegrated.zip)

1. Start a campaign
2. togglecampaignteleport 
3. Teleport to an empty node near a lair
4. Map should open on start of level
5. Travel to the end of the level
6. You can't go to your destination

### Bug prevalence

Just once

### Single player or multiplayer?

Other

### Version

v1.4.3.0 (unstable)

### Which operating system did you encounter this bug on?

Windows

### Relevant error messages and crash reports

_No response_</div>

**Comment by Regalis11** [comment]
Fixed in https://github.com/FakeFishGames/Barotrauma-development/pull/5254/commits/7a930f84620d134ea8e3609e0b8532286dd9fcd8

**Comment by ubertpendragon** [comment]
Happens in vanilla just go further into biomes like Great Sea and travel backwards

The picture in the ticket is kind of a different issue

**Comment by Rokvach** [comment]
Tested, working correctly. Can be merged and closed.
