### ISSUE TITLE
Old and Duplicate Texts

### ISSUE THREAD

**Issue by Regalis11** [FakeFishGames/Barotrauma#13876]
### Discussed in https://github.com/FakeFishGames/Barotrauma/discussions/13870

<div type='discussions-op-text'>

<sup>Originally posted by **Vykn** April 28, 2024</sup>
### What happened?

There are several duplicate texts in the most recent update

- diving suit descriptions
- acid reaction name & description
- tonic liquid description
- cyanide & sufforin descriptions
- bandage, plastiseal & antibiotic glue descriptions
- saline description
- deusizine description
- broken diving suit name & description

and possibly more. I just checked most of the new stuff

### Reproduction steps

check any of the descriptions/names prior mentioned and observe that they switch between different lines</div>

**Comment by itchyOwl** [comment]
Read through the changes. Noticed that you removed the description of adrenaline gland and it was now missing. Reverted that in ec942c1.

**Comment by Vykn** [comment]
There are still duplicate texts. Version 1.4.6.0 Unstable

![image](https://github.com/FakeFishGames/Barotrauma/assets/37850646/257e81d4-de84-4b21-8989-c55b47a6274d)

**Comment by itchyOwl** [comment]
Thanks for pointing that out. But yeah we noticed there are still issues. Also some texts are missing. Some of the issues are old, though.
