### ISSUE TITLE
Bug - Art of War book doesn't stack and is bugged

### ISSUE THREAD

**Issue by Regalis11** [FakeFishGames/Barotrauma#13899]
### Discussed in https://github.com/FakeFishGames/Barotrauma/discussions/13857

<div type='discussions-op-text'>

<sup>Originally posted by **Myrik25** April 27, 2024</sup>
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [X] My issue happened while using mods.

### What happened?

Since last patch, the skill book Art of War doesn't stack and is bugged. 

### Reproduction steps

When I load up my single player game save the error has been there since the patch

### Bug prevalence

Happens every time I play

### Single player or multiplayer?

Single player

### Version

v1.4.5.0 (Blood in the Water Update, hotfix 1)

### Which operating system did you encounter this bug on?

Windows

### Relevant error messages and crash reports

_No response_</div>

**Comment by Regalis11** [comment]
Not sure if it's intentional it doesn't stack, but imo for consistency all the books should stack the same way.

**Comment by Regalis11** [comment]
Reopening, this still doesn't work that well. The issue seems to be that most of the time you get less than 1 skill from the book, which gives the impression the book does nothing.

**Comment by Jasontti** [comment]
Testing notes: https://github.com/FakeFishGames/Barotrauma-development/pull/5574#issuecomment-2312301653
Closing as completed

**Comment by Regalis11** [comment]
Reopening, this was still bugged https://github.com/FakeFishGames/Barotrauma-development/pull/5574#issuecomment-2312487289 and needs to be re-tested.

**Comment by Jasontti** [comment]
Testing notes: https://github.com/FakeFishGames/Barotrauma-development/pull/5574#issuecomment-2348278179
Closing ticket as completed for real this time :)
