### ISSUE TITLE
Team2 (hostile) NPC AI completely break if the location has a team/faction

### ISSUE THREAD

**Issue by itchyOwl** [FakeFishGames/Barotrauma#13892]
### Discussed in https://github.com/FakeFishGames/Barotrauma/discussions/13818

<div type='discussions-op-text'>

<sup>Originally posted by **ubertpendragon** April 24, 2024</sup>
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [X] My issue happened while using mods.

### What happened?

If the location doesn't have `outpostteam="None"` and is owned by I assume FriendlyNPC team or a faction, the AI of NPCs in team2 breaks: Enemies flee you without attacking. 

I assume this is to prevent Team2 from shooting at the outpost? But humans don't actually shoot handheld weapons at walls

![image](https://github.com/FakeFishGames/Barotrauma/assets/73229309/5bb7c864-1e1c-484a-a57a-b9be40f66f79)

# IF YOU SPAWN THE ENEMIES WITH FRIENDLY TEAM ID and THEN CHANGE THEIR TEAM, THE AI IS FINE FOR SOME REASON 

```xml
      <Character identifier="soldierseparatists" from="de_separatistscombat" teamid="FriendlyNpc" requirekill="true" />
      
    <ScriptedEvent identifier="takeoverteamtest" >
      <TagAction criteria="humanprefabidentifier:soldierseparatists" tag="defenders" ContinueIfNoTargetsFound="true" />
      <NPCChangeTeamAction npctag="defenders" teamtag="Team2" />
    </ScriptedEvent> 
```

# IF YOU SPAWN THE ENEMIES WITH teamid="Team2" OR LEAVE IT BLANK, THE AI BREAKS
    
This is a problem for any event/mission that uses Team2 to turn NPCs hostile. Otherwise you have to loop a combataction event to circumvent the problem

Example of  modded mission that is basically using the abandonedoutpostassassinate mission, but in a city 

https://github.com/FakeFishGames/Barotrauma/assets/73229309/acb81caf-8ec2-42f1-b0b1-352537ca73c3

```xml
  <OutpostDestroyMission name="Coalition Station-Takeover" identifier="cotakeover_separatistoutpost" tags="outposttakeovermission" type="OutpostDestroy" requireCorrectLocationType="true" locations="city" reward="5500" difficulty="4" commonness="0" allowretry="true" BlockLocationTypeChanges="true">
    <Reputation identifier="separatists" amount="-20" />
    <Reputation identifier="coalition" amount="10" />
    <Icon texture="Content/UI/MissionIcons.png" sourcerect="0,512,256,256" color="214,50,48" />
    <Characters>
      <Character identifier="soldierseparatists" from="de_separatistscombat" requirekill="true" />
      <Character identifier="soldierseparatists" from="de_separatistscombat" requirekill="true" />
      <Character identifier="soldierseparatists" from="de_separatistscombat" requirekill="true" />
      <Character identifier="soldierseparatists" from="de_separatistscombat" requirekill="true" />
      <Character identifier="soldierseparatists" from="de_separatistscombat" requirekill="true" />
      <Character identifier="soldierseparatists" from="de_separatistscombat" requirekill="true" />
      <Character identifier="soldierseparatists" from="de_separatistscombat" requirekill="true" />
      <Character identifier="soldierseparatists" from="de_separatistscombat" requirekill="true" />
      <Character identifier="soldierseparatists" from="de_separatistscombat" requirekill="true" />
      <Character identifier="soldierseparatists" from="de_separatistscombat" requirekill="true" multiplayeronly="true" />
      <Character identifier="soldierseparatists" from="de_separatistscombat" requirekill="true" multiplayeronly="true" />
      <Character identifier="soldierseparatists" from="de_separatistscombat" requirekill="true" multiplayeronly="true" />
    </Characters>
    <TriggerEvent state="0" delay="1" eventidentifier="cooutposttakeoverevent" campaignonly="true" />
    <LocationType identifier="city" />
    <message header="missionheader0.coalitiontakeover" text="missionmessage0.coalitiontakeover" />
  </OutpostDestroyMission>
```

### Reproduction steps

1. Delete `outpostteam="None"` from abandonedoutpost locationtype.xml
2. Start an abandoned outpost mission with human enemies
3. AI breaks

### Bug prevalence

Happens every time I play

_No response_

### Version

v1.4.4.1 (Blood in the Water Update)
</div>

**Comment by Regalis11** [comment]
Addressed in https://github.com/FakeFishGames/Barotrauma-development/commit/1a729305c160a0717376058f92d8118f88f2d839

**Comment by Regalis11** [comment]
Fixed in https://github.com/FakeFishGames/Barotrauma/issues/13892, closing
