### ISSUE TITLE
Zealot robes should benefit husked players, but not give husk immunity

### ISSUE THREAD

**Issue by JeroonBosch** [FakeFishGames/Barotrauma#13890]
### Discussed in https://github.com/FakeFishGames/Barotrauma/discussions/13812

<div type='discussions-op-text'>

<sup>Originally posted by **NotWendy** April 24, 2024</sup>
At the moment, zealot robes provide a very powerful effect for a clothes slot, combining the functionality of husk genes with passive healing and making husked enemies neutral to the wearer.

They are also very easily accessible through stealing and can be acquired very early in the campaign, which people generally point at as the biggest problem with the item.

I suggest removing the husk infection immunity stat from the robes, instead making them synergize with husk genes/symbiosis. They'll support husked players by giving them health regeneration, but will still require you to find a way to make husk infection not kill you.</div>

----

Main issues:
- Too easily available
- Too powerful for its availability

Note, cultist robe and zealot robe both have
```
    <Price baseprice="150" canbespecial="false" sold="false">
      <Price storeidentifier="merchanthusk" minavailable="1" maxavailable="4" sold="true">
        <Reputation faction="huskcult" min="70"/>
      </Price>
    </Price>
```
Which is probably an oversight, the effect of the Cultist robe is less powerful, yet they're both available at 70 rep and 150 mks.
Aside from buying these when reputation is high enough (reaching 70 rep actually seems quite hard to me for the husk cult), the robes are also worn by cultist leader, allowing it to be accessed earlier.

abandonedoutposthusks Mission f.e. has a cultist leader.
Abandoned outpost is already quite common by the 2nd biome.
commonnessperzone="1: 0, 2: 0.8, 3: 0.8, 4: 0.5, 5: 0.5, 6: 0"

---

**A couple of steps could be taken here:**
`<entitydescription.zealotrobes>A dark garment worn by esteemed members of the Church of Husk. Embedded with genetic technology and hormone injectors that give the wearer heightened regenerative capabilities of their symbiote, while keeping the symbiote docile.</entitydescription.zealotrobes>`

1. The technology and hormone injectors could require some upkeep (alien power cell, batteries, some medicine that needs refreshing?)
2. abandonedoutposthusks mission given a mindifficulty
3. huskcult merchants wearing cultist robe instead of zealot robe
4. Increase price of zealot robe, decrease regular cultist robe reputation cost
5. "They are also very easily accessible through stealing" - figure out where they can be stolen, according to XML they shouldn't pop up as random loot

**Comment by ubertpendragon** [comment]
On my mod I made it use ABX to prevent husk transformation


```xml
      <!-- only heals if husk infection is at 75% (when the husk appendage spawns) -->
      <StatusEffect target="Character,Contained" type="OnWearing" condition="-0.5" >
        <Conditional huskinfection="gt 75" />
        <RequiredItem items="antibiotics" type="Contained" />
        <ReduceAffliction type="damage" amount="0.25" />
        <ReduceAffliction type="bleeding" amount="0.1" />
        <Affliction identifier="husktransformimmunitytemporary" amount="50" />
      </StatusEffect>
      <!-- can't take ABX out because partials suck -->
      <StatusEffect target="Contained" type="OnContained" noninteractable="true" setvalue="true" >
        <RequiredItem items="antibiotics" type="Contained" />
        <Conditional condition="lt 100" />
      </StatusEffect> 
    </Wearable>    
    <ItemContainer capacity="1" maxstacksize="1">
      <SlotIcon slotindex="0" texture="Content/UI/StatusMonitorUI.png" sourcerect="384,448,64,64" origin="0.5,0.5" />
      <Containable items="antibiotics" />
    </ItemContainer>    
```

**Comment by dakkhuza** [comment]
"They are also very easily accessible through stealing" You can acquire them by killing the husk merchant through any number of means, my go to being overdosing them. You can then yoink the cloak and leave the outpost before anyone can react through either switching characters in singleplayer or having the captain ready to go in multiplayer. You'll lose maybe 1-2 rep and get a very powerful item very quickly.

Also as a side note, the rep requirements for the minor faction merchants is really bonkers and makes no sense imo. You might want to do a pass on the rep requirements and spread the items out more instead of having 3 or so break points where a bunch of items become available at the same time.

**Comment by Jasontti** [comment]
Tested changes to robes
- Cultist robes require less reputation to buy, Zealot robes more
- Zealot robes no longer block transformation, discord said it's strong enough with the regen properties already, husk infection will be kept risky this way unless the player gets high quality genes (which probably is more fun)

Feels like a good synergy with gene splicing mechanic and robes

Closing as completed
