### ISSUE TITLE
Alien blood and "Bloody Business"

### ISSUE THREAD

**Issue by Regalis11** [FakeFishGames/Barotrauma#13891]
### Discussed in https://github.com/FakeFishGames/Barotrauma/discussions/13885

<div type='discussions-op-text'>

<sup>Originally posted by **Instant2116** April 28, 2024</sup>
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

Alien blood now deal organ damage instead of psychosis, but Medic (doctor) has talent "Bloody Business" that decrease psychosis from Alien blood, which doesn't make sense now.

### Reproduction steps

1. Start any type of game
2. Spawn medic
3. Read  "Bloody Business" talent description
4. It doesn't make sense

### Bug prevalence

Happens every time I play

### Single player or multiplayer?

Single player

### Version

v1.4.5.0 (Blood in the Water Update, hotfix 1)

### Which operating system did you encounter this bug on?

Windows

### Relevant error messages and crash reports

_No response_</div>

**Comment by JeroonBosch** [comment]
Closing, inaccurate info, alien blood gives psychosis still (and thus the talent works as expected)
