### ISSUE TITLE
[Unstable] Some weapons shooting backwards sometimes

### ISSUE THREAD

**Issue by Regalis11** [FakeFishGames/Barotrauma#14016]
### Discussed in https://github.com/FakeFishGames/Barotrauma/discussions/14001

<div type='discussions-op-text'>

<sup>Originally posted by **HawkinsThe71st** May 25, 2024</sup>
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

While using the scrap cannon I noticed it would shoot backwards every now and then. Very inconsistent to reproduce but it might occur at specific angles more frequently.
![image](https://github.com/FakeFishGames/Barotrauma/assets/115734437/d8a74730-7d44-4a5d-b9e2-d0d868a0ae00)
Can also happen when using the RFA:
![image](https://github.com/FakeFishGames/Barotrauma/assets/115734437/1a176e95-5c9d-4152-8fab-59263bf93473)

### Reproduction steps

1. Shoot Scrap Cannon or RFA in random directions until the issue occurs

### Bug prevalence

Happens every now and then

### Single player or multiplayer?

Single player

### Version

v1.5.0.0 (unstable)

### Which operating system did you encounter this bug on?

Windows

### Relevant error messages and crash reports

_No response_</div>

**Comment by Regalis11** [comment]
Fixed in https://github.com/FakeFishGames/Barotrauma-development/commit/dacba3ae30ff7d5969552bf657050a75e8710d77

**Comment by Jasontti** [comment]
Tested in: https://github.com/FakeFishGames/Barotrauma-development/pull/5333/commits/dacba3ae30ff7d5969552bf657050a75e8710d77

Tested with steps provided
Tested grenade launcher, harpoon gun, shotgun and syringe gun
Turrets, railgun with shells and canisters, coilgun and flak
Shooted these in all directions
Flashlights are also pointing the right way

No issues found
Closing as completed
