### ISSUE TITLE
[Unstable] Scrap Savant error message

### ISSUE THREAD

**Issue by Regalis11** [FakeFishGames/Barotrauma#14020]
### Discussed in https://github.com/FakeFishGames/Barotrauma/discussions/14003

<div type='discussions-op-text'>

<sup>Originally posted by **ubertpendragon** May 25, 2024</sup>
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

![image](https://github.com/FakeFishGames/Barotrauma/assets/73229309/b45fdb86-35a4-4394-a71e-ccd4c58e0bd2)

### Reproduction steps

`givetalent "Scrap Savant"`

### Bug prevalence

Just once

### Single player or multiplayer?

Single player

### Version

v1.4.6.0 (Blood in the Water Update, hotfix 2)

### Which operating system did you encounter this bug on?

Windows

### Relevant error messages and crash reports

_No response_</div>

**Comment by Jasontti** [comment]
Testing notes: https://github.com/FakeFishGames/Barotrauma-development/pull/5331#issuecomment-2137235950
No issues found
Closing ticket
