### ISSUE TITLE
Strange Canister Shell crafting behaviour

### ISSUE THREAD

**Issue by Regalis11** [FakeFishGames/Barotrauma#14033]
### Discussed in https://github.com/FakeFishGames/Barotrauma/discussions/14012

<div type='discussions-op-text'>

<sup>Originally posted by **Kokhirus** May 26, 2024</sup>
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

Not sure, if it is a common problem, but this is not looking right. Maybe it is just a one time issue, so I will try to reproduce it later.
![image](https://github.com/FakeFishGames/Barotrauma/assets/91697233/5c78987b-f988-43a3-8d72-42cca78f8d5a)
UPD Have got a new strange behaviour while crafting Canister Shell (can be seen below). You can recraft Canister Shell using full Canister Shell for it:
![image](https://github.com/FakeFishGames/Barotrauma/assets/91697233/c99615f1-599e-46f2-bf84-460e500d4668)

### Reproduction steps

1. Approach fabricator to craft canister shell
2. Check resources
3. Get confused

### Bug prevalence

Just once

### Single player or multiplayer?

Multiplayer hosted from the in-game menu (= using a listen server)

### Version

v1.4.6.0 (Blood in the Water Update, hotfix 2)

### Which operating system did you encounter this bug on?

Windows

### Relevant error messages and crash reports

_No response_</div>

**Comment by Regalis11** [comment]
Fixed in https://github.com/FakeFishGames/Barotrauma-development/commit/6c7000e4fa0067d3e72c3142ab11b3aee6bbf44a (commit in our private repo)

**Comment by Jasontti** [comment]
Testing notes: https://github.com/FakeFishGames/Barotrauma-development/pull/5343#issuecomment-2146845840
No issues found, closing ticket.
