### ISSUE TITLE
Ironman trivialised by the round ending

### ISSUE THREAD

**Issue by Regalis11** [FakeFishGames/Barotrauma#14044]
### Discussed in https://github.com/FakeFishGames/Barotrauma/discussions/14042

<div type='discussions-op-text'>

<sup>Originally posted by **Vykn** May 28, 2024</sup>
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

The point of ironman mode is that if your character dies, then you're out of the game. One might imagine that if the entire crew dies, then that's just the end of the campaign. This is not the case. If everyone dies, the server goes back to lobby like normal, and then you can simply resume the save at the start of the level. All stakes have been lost, since even if the entire crew dies, you can just try again, which really goes against the spirit of an ironman feature.

### Reproduction steps

1. start an ironman campaign
2. get the entire crew to jump out the airlock
3. wait 60 seconds (or just press the "server lobby" button
4. continue your "ironman" save after everyone just died, and you will find that everyone is now alive and you can try again

### Bug prevalence

Happens every time I play

### Single player or multiplayer?

Single player

### Version

v1.5.0.0 (unstable)

### Which operating system did you encounter this bug on?

Windows

### Relevant error messages and crash reports

_No response_</div>

**Comment by Jasontti** [comment]
Testing notes: https://github.com/FakeFishGames/Barotrauma-development/pull/5362#issuecomment-2142164620
No issues found, closing ticket
