### ISSUE TITLE
Opened hatches/doors do not cast shadow when closed

### ISSUE THREAD

**Issue by Regalis11** [FakeFishGames/Barotrauma#14065]
### Discussed in https://github.com/FakeFishGames/Barotrauma/discussions/13811

<div type='discussions-op-text'>

<sup>Originally posted by **SomeRandomNoobKekeke** April 24, 2024</sup>
### Disclaimers  

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

If sub was saved with an opened hatch/door all nearby shadow casting lights will consider it open forever and it won't cast shadow
Yes, it can happen between rounds
Probably related https://github.com/FakeFishGames/Barotrauma/issues/12087 
It probably won't hurt performance to make it "unhidden" once per round

https://github.com/FakeFishGames/Barotrauma/assets/122838333/a23957d1-bd2b-4ed5-ab10-26586f7ae5e3

https://github.com/FakeFishGames/Barotrauma/assets/122838333/99da28a4-8e2a-40e4-882d-7ecbf0c60f4d

### Reproduction steps

Go to sub editor
Open Typhon
Open that hatch
Turn batteries on
Test

### Bug prevalence

Happens every time I play

### Single player or multiplayer?

Single player

### Version

v1.3.0.4

### Which operating system did you encounter this bug on?

Windows

### Relevant error messages and crash reports

_No response_</div>

**Comment by Regalis11** [comment]
Fixed in https://github.com/FakeFishGames/Barotrauma-development/commit/e4b0468c04440ace419264f66b031a5e610e79d3

**Comment by NilanthAnimosus** [comment]
Closing as fixed, tested and merged into the codebase for the next patch/unstable.
