### ISSUE TITLE
Detached components keep zapping, and you can reconnect the wire even though the component is detached

### ISSUE THREAD

**Issue by Regalis11** [FakeFishGames/Barotrauma#14084]
### Discussed in https://github.com/FakeFishGames/Barotrauma/discussions/14052

<div type='discussions-op-text'>

<sup>Originally posted by **SomeRandomNoobKekeke** May 29, 2024</sup>
### Disclaimers  

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

If you disconnect a wire on one side and detach the component then disconnected wire will still be attached to it and keep zapping, which is annoying

https://github.com/FakeFishGames/Barotrauma/assets/122838333/0a9b5925-f179-4ce3-9c63-64d56cd17474

### Reproduction steps

connect 2 components with wire
detach wire on one side, but don't remove it
detach that component
wire still connected to that component

### Bug prevalence

Happens every time I play

### Single player or multiplayer?

Single player

### Version

v1.4.6.0 (Blood in the Water Update, hotfix 2)

### Which operating system did you encounter this bug on?

Windows

### Relevant error messages and crash reports

_No response_</div>

**Comment by Regalis11** [comment]
Note: as mentioned in the discussion, it's intentional that the wire keeps hanging and zapping like this when the other end is not connected to anything. 

What is not intentional though is that the wire still shows up as a "loose wire" in the detached component's connection panel, and can be reattached there.

> Normally when you detach a component all connected wires drops, but if a wire was disconnected then it'll still be hanging on that component so you can place that component on the other sub, connect hanging wire back and it'll work

https://github.com/FakeFishGames/Barotrauma/assets/122838333/82dcc397-4699-4c01-9d7b-60d53119a90e

**Comment by Regalis11** [comment]
Fixed in https://github.com/FakeFishGames/Barotrauma-development/commit/9714eac1a76275fddd3bc84725f411d1a3a475d1

**Comment by Jasontti** [comment]
Tested in: https://github.com/FakeFishGames/Barotrauma-development/pull/5046/commits/04d55ffbe4d54bb2c7953d083d446255fbf1c3ef

Tested with other fixes to wire disconnection logic.
Used the steps above.
Tested different order of disconnections and not disconnecting wires at all before detaching

No issues found, closing ticket as completed
