### ISSUE TITLE
In the network campaign game, the bot deconstructs only one item from the stack.

### ISSUE THREAD

**Issue by Regalis11** [FakeFishGames/Barotrauma#14092]
### Discussed in https://github.com/FakeFishGames/Barotrauma/discussions/14089

<div type='discussions-op-text'>

<sup>Originally posted by **pavel4win** June  5, 2024</sup>
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

Although in a single player game the bot normally deconstructs any stack of items by dragging items into the deconstructor one at a time.
But in a network game, the bot only deconstructs the first item from the stack, ignoring the rest. 
I also noticed, in the next round, the remaining items in the stack lose the “deconstruct mark".
It seems like as if deconstruct one item, the mark is removed from the entire stack.

### Reproduction steps

1. create a server
2. start a new campaign game on the Orca sub with one bot.
3. collect 8 oxygen tanks in  your inventory and put them in the closet as one stacks of 8 items.
4. give to the bot "deconstruct" order.
5. Mark  the stack of tanks for deconstruction.
6. The bot will deconstruct one tank, after this the bot will stay inactive.
7. now save and restore the game. The "deconstruct mark" has disappeared from the stack of tanks.

### Bug prevalence

Happens every time I play

### Single player or multiplayer?

Multiplayer hosted from the in-game menu (= using a listen server)

### Version

v1.4.6.0 (Blood in the Water Update, hotfix 2)

### Which operating system did you encounter this bug on?

Windows

### Relevant error messages and crash reports

_No response_</div>

**Comment by Regalis11** [comment]
Fixed in https://github.com/FakeFishGames/Barotrauma-development/commit/f209adc342c0ddacb2f9a0e4b4b8bbbc755a33c8

**Comment by Rokvach** [comment]
Tested, working correctly. Can be merged and closed.
