### ISSUE TITLE
Some issues regarding a few of the new talents (Machine Maniac, Quickfixer, Junction Junkie)

### ISSUE THREAD

**Issue by Regalis11** [FakeFishGames/Barotrauma#14125]
### Discussed in https://github.com/FakeFishGames/Barotrauma/discussions/13710

<div type='discussions-op-text'>

<sup>Originally posted by **HawkinsThe71st** April  2, 2024</sup>
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

The skill book Art of Submarine Warfare does not grant any weapons skill unless directly created by the War Stories talent. It's also unclear how much skill is gained per kill as characters with a low weapons skill seem to gain more skill points than characters with a higher weapons skill.

Machine Maniac and Quickfixer don't work on deconstructors, medical fabricators and duct blocks.
`tags="fabricator,door,engine,oxygengenerator,pump,turretammosource"`
Missing the `deconstructor`, `medicalfabricator` and `ductblock` tags.

Very minor discrepancy between Junction Junkie and Better Than New, Junction Junkie uses tags `tags="junctionbox,supercapacitor,battery,reactor,sonarmonitor,statusmonitor,navterminal"` while Better Than New uses `category="Electrical"` which doesn't include the reactor as it is not categorized as an electrical item.

Junction Junkie description states 500 XP while the actual amount given is 600.
```
  Description tag="talentdescription.junctionjunkie.30">
  <Replace tag="[amount]" value="10" color="gui.green"/>
  <Replace tag="[skill]" value="stattypenames.electricalskillbonus" color="gui.orange"/>
  <Replace tag="[xpamount]" value="500" color="gui.green"/>
</Description>
```
`<CharacterAbilityGiveExperience amount="600"/>`

These lines are somewhat vague as to whether or not there would be any benefit if those they were already at level 1
"-50: Upgrades the submarine's junction boxes to level 1."
"-50: Upgrades the submarine's pumps to level 1."
Currently if the sub is tier 2 and the junctions are at 1/2 upgrades then reaching the 50 repair threshold works and upgrades the junctions to level 2.

### Reproduction steps

1. Use Art of Submarine Warfare without the War Stories talent
2. Repair deconstructor, medical fabricator or duct block with the Machine Maniac talent

### Bug prevalence

Happens regularly

### Single player or multiplayer?

Single player

### Version

v1.4.0.0 (unstable)

### Which operating system did you encounter this bug on?

Windows

### Relevant error messages and crash reports

_No response_</div>

**Comment by JeroonBosch** [comment]
Slight overlap with #5378

**Comment by Jasontti** [comment]
Testing notes: https://github.com/FakeFishGames/Barotrauma-development/pull/5451#issuecomment-2165658753
No issues found, closing ticket as completed.
