### ISSUE TITLE
[Unstable] Round ending too fast when falling unconscious

### ISSUE THREAD

**Issue by Regalis11** [FakeFishGames/Barotrauma#14122]
### Discussed in https://github.com/FakeFishGames/Barotrauma/discussions/14119

<div type='discussions-op-text'>

<sup>Originally posted by **Vykn** June 11, 2024</sup>
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

In multiplayer, if a player is the last (or only) player alive, and they fall unconscious, the round will immediately end. Since they technically never died, they are not considered "dead" for the purposes of an Ironman run, and so they can continue with the save even if everyone was unconscious.

Additionally, the round ends even if the player could have been healed (either by a bot or some other effect like meds or matriarch genes) back to consciousness. Which is slightly annoying if the injuries could have been healed, but the server takes everyone back to the lobby anyway. It would be better if there was a timer that started when everyone was unconscious, or just didn't go back to lobby until everyone is properly dead.

### Reproduction steps

1. Launch a multiplayer campaign and be the only player
2. get a medic bot to follow you and give sufficient meds such that they could heal you
3. give yourself just enough damage to knock you unconscious
4. Observe that the server takes you back to the lobby before you can be healed

And for the other issue
1. Launch an ironman multiplayer campaign and be the only player
2. Spawn a bunch of enemies near you and be attacked
3. Observe that the server takes you back to the lobby before you can die, and so you can reload the ironman save

### Bug prevalence

Happens every now and then

### Single player or multiplayer?

Multiplayer hosted from the in-game menu (= using a listen server)

### Version

v1.5.4.0 (unstable)

### Which operating system did you encounter this bug on?

Windows

### Relevant error messages and crash reports

_No response_</div>

**Comment by Jasontti** [comment]
Tested in: https://github.com/FakeFishGames/Barotrauma-development/commit/40d794d2c64791902cf5bee9cd5653106bac4514

Generally used giveaffliction "blood loss" 70 to incapacitate and "oxygen low" -100 to stay alive.
Permadeath (normal and ironman) game ended after 60 seconds of unconsiouness.
Normal campaign had same effect.
Mission mode game didn't end at all.
Quickly tested single player too, no issues there.

No issues found, closing ticket as completed

**Comment by Jasontti** [comment]
Noting that round ending from incapacitation does not make characters dead in save files, but usually this kind of stable death is not common.
