### ISSUE TITLE
The campaign rarely starts in the 2nd biome (Starter Outpost)

### ISSUE THREAD

**Issue by Regalis11** [FakeFishGames/Barotrauma#14146]
### Discussed in https://github.com/FakeFishGames/Barotrauma/discussions/14138

<div type='discussions-op-text'>

<sup>Originally posted by **ubertpendragon** June 15, 2024</sup>
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [X] My issue happened while using mods.

### What happened?

The game rarely fails to generate a basic "outpost" at the start of the first biome, and will start your campaign ahead on the map on the first outpost it finds

Example using Dynamic Europa, since we have many possible outpost types there's a non-zero chance this happens:

![image](https://github.com/FakeFishGames/Barotrauma/assets/73229309/01b38eaa-b1b8-460f-b832-c5d70eb7d324)

**Please force the tutorial outpost in both SP and MP. This also allows customizeable starter outposts**

----------

### Reproduction steps

1. Download Dynamic Europa
https://steamcommunity.com/sharedfiles/filedetails/?id=2532991202
2. Roll a new campaign a dozen of times (with tutorial disabled) until this happens

or use this save 
[Save 54.zip](https://github.com/user-attachments/files/15846339/Save.54.zip)

### Bug prevalence

Happens every now and then

### Version

v1.4.6.0 (Blood in the Water Update, hotfix 2)
</div>

**Comment by Regalis11** [comment]
Fixed in https://github.com/FakeFishGames/Barotrauma-development/commit/84a943b8f87aff5cb5d9b677219995a3b73e9fb0

**Comment by kaedepon** [comment]
For your information.
In the vanilla, these seeds are applicable to this report.

- `mrxto693`
- `mtgWo3M3`
- `mtrdo36M`

**Comment by ubertpendragon** [comment]
I must once again ask for a custom starter outpost (enforce tutorialoutpost)

**Comment by kaedepon** [comment]
I'm sorry I didn't make it clear enough. 
These are valid seeds for v1.5.8.0.
I just wanted to provide some test data for developers.

I can not check this commit but I believe it has been fixed.

**Comment by Regalis11** [comment]
@kaedepon Yep, I assumed so, thanks for the seeds! And yeah, we have implemented a fix, but haven't tested it internally yet so it isn't included in any public build yet.

**Comment by Jasontti** [comment]
Tested in: https://github.com/FakeFishGames/Barotrauma-development/pull/5471/commits/33c4e4010aebf6ca956c1a6b7a73a49ca3799c25

Quickly tested generating couple campaign starts in SP and MP
Tested with kaedepons seeds on MP with and without DE
Original test save is irreversibly corrupted and always have the same starting position
Loaded couple older saves

No issues found, closing ticket as completed.
