### ISSUE TITLE
Jovian radiation doesn't move in multiplayer at all

### ISSUE THREAD

**Issue by SomeRandomNoobKekeke** [FakeFishGames/Barotrauma#14148]
### Disclaimers  

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.
- [X] I have tried verifying game files

### What happened?
It ~either~ doesn't move ~or checkbox for enabling jovian radiation doesn't work~

### Reproduction steps

Start multiplayer campaign with radiation enabled
togglecampaignteleport
Jump around the map 4-6 times
No radiation...

In singleplayer you will see red radiation front

### Bug prevalence

Happens every time I play

### Single player or multiplayer?

Multi Player

### Version

v1.4.6.0 (Blood in the Water Update, hotfix 2)

### Which operating system did you encounter this bug on?

Windows

**Comment by SomeRandomNoobKekeke** [comment]
I decompressed my multiplayer saves, RadiationEnabled="True", very strange

**Comment by SomeRandomNoobKekeke** [comment]
I made myself a command
```
      DebugConsole.Commands.Add(new DebugConsole.Command("radstep", "", (string[] args) =>
      {
        GameMain.GameSession?.Map?.Radiation?.OnStep(1);
      }));
```
I can move radiation with it, but after start level / dock it gets reset back to -200

I'm out of ideas how to test it
![barodev small](https://github.com/FakeFishGames/Barotrauma/assets/122838333/fee85247-fae7-4b41-a3e2-09faa0417068)

**Comment by Vykn** [comment]
RadiationEnabled="" doesn't control the radiation. At the bottom of the gamesession.xml, there's a <Radiation> line which is how it's actually enabled/disabled.

Also, #13590

**Comment by SomeRandomNoobKekeke** [comment]
@Vykn 

> At the bottom of the gamesession.xml, there's a <Radiation> line which is how it's actually enabled/disabled.

i mentioned that, you didn't ever read it

> Radiation amount doesn't change :( `<Radiation Amount="-200" Enabled="True" />`

**Comment by Vykn** [comment]
I did read it, I just didn't recognise that part of it. I encountered this over a year ago and it seemed like the same issue. Sorry ¯\_(ツ)_/¯
