### ISSUE TITLE
Missions never go to natural formations/abandoned outposts

### ISSUE THREAD

**Issue by Regalis11** [FakeFishGames/Barotrauma#14145]
### Discussed in https://github.com/FakeFishGames/Barotrauma/discussions/14134

<div type='discussions-op-text'>

<sup>Originally posted by **Vykn** June 14, 2024</sup>
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

Missions from outposts never go to natural formations or abandoned outposts.

This makes sense for specific missions like escort or transport, but not for a bunch of other missions like killing or salvage.
This kinda sucks, because usually the natural formations are towards the deeper regions, and if there aren't missions there it disincentivises going in the direction that progresses the campaign, just because there aren't missions there. 

### Reproduction steps

1. Load up a campaign
2. teleport to the deeper regions, to an outpost that neighbours natural formations/abandoned outposts and at least one outpost
3. unlock missions either from the npc or using the `unlockmissions` command
4. observe that none of the missions go to the natural formations/abandoned outposts

### Bug prevalence

Happens every time I play

### Single player or multiplayer?

Single player

### Version

v1.5.4.0 (unstable)

### Which operating system did you encounter this bug on?

Windows

### Relevant error messages and crash reports

_No response_</div>

**Comment by Regalis11** [comment]
Fixed in https://github.com/FakeFishGames/Barotrauma-development/commit/4c9e6f46f453bde50487b40ea4543d62020e021a

**Comment by Rokvach** [comment]
Tested, working correctly. Can be merged and closed.

![image](https://github.com/FakeFishGames/Barotrauma/assets/7299826/a621ea95-1f49-4eef-b2ee-87966ea53ea0)
