### ISSUE TITLE
Sound triggered by Statuseffect/Event never stops playing in Multiplayer

### ISSUE THREAD

**Issue by Regalis11** [FakeFishGames/Barotrauma#14154]
### Discussed in https://github.com/FakeFishGames/Barotrauma/discussions/14009

<div type='discussions-op-text'>

<sup>Originally posted by **ubertpendragon** May 25, 2024</sup>
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

Sound triggered by Statuseffect/Event never stops playing in Multiplayer and loops forever

Example:
The sound plays for 3 seconds in SP just fine, but keeps playing in MP

Part of larger series of statuseffect MP desyincs  #14008

```xml
    <ScriptedEvent identifier="loopingsoundmpbug">
          <TagAction criteria="player" tag="player" />
          <StatusEffectAction targettag="player">
              <StatusEffect target="this" duration="3" >
                <Sound file="Content/Sounds/Radiostatic.ogg" range="4000" volume="2" loop="true" />
              </StatusEffect>
            </StatusEffectAction>            
    </ScriptedEvent >
```

### Reproduction steps

Use `triggerevent loopingsoundmpbug` in both SP and MP with the above event

### Bug prevalence

Just once

### Single player or multiplayer?

Single player

### Version

v1.4.6.0 (Blood in the Water Update, hotfix 2)

### Which operating system did you encounter this bug on?

Windows

### Relevant error messages and crash reports

_No response_</div>

**Comment by Regalis11** [comment]
Fixed in https://github.com/FakeFishGames/Barotrauma-development/pull/5482/commits/983655421f9499d8624f08a7eb21c03d6bc334e6

**Comment by Jasontti** [comment]
Tested in: https://github.com/FakeFishGames/Barotrauma-development/commit/41364a7aa39bf32a7d49e604ad9a5377f4dbcf41

Tested in SP and MP
Tested with example provided and other naturally occuring events

No issues found
