### ISSUE TITLE
NPCs turn hostile when healed

### ISSUE THREAD

**Issue by Regalis11** [FakeFishGames/Barotrauma#14159]
### Discussed in https://github.com/FakeFishGames/Barotrauma/discussions/14101

<div type='discussions-op-text'>

<sup>Originally posted by **Awec4** June  8, 2024</sup>
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

In a multiplayer game where we had a mission to escort NPCs
Our sub was attacked by Tiger Threshers while I was outside, when I arrived back inside I found one of the mission NPCs unconscious with low oxygen/bloodloss and an infected wound, so I gave him alien blood and CPR to revive him and applied some antibiotics to the infected wound. As I was inspecting the NPC to ensure the infected wound fully healed he suddenly turned hostile and he and the others attacked me.
Presumably some part of the healing did damage e.g psychosis from the alien blood or organ damage from antibiotics
Expected behaviour: Mission NPCs on the sub should not turn hostile when being healed

### Reproduction steps

1. Start a mission to escort NPCs
2. Have an NPC be injured/knocked unconscious by creatures
3. Heal the NPC

### Bug prevalence

Just once

### Single player or multiplayer?

Multiplayer hosted from the in-game menu (= using a listen server)

### Version

v1.4.6.0 (Blood in the Water Update, hotfix 2)

### Which operating system did you encounter this bug on?

Windows

### Relevant error messages and crash reports

_No response_</div>

**Comment by Vykn** [comment]
Also affects npcs in multiplayer mode, but not singleplayer. So you can give antibiotics to your crew in sp, but not in mp

**Comment by Regalis11** [comment]
Addressed in https://github.com/FakeFishGames/Barotrauma-development/pull/5600

**Comment by Regalis11** [comment]
Merged, closing
