### ISSUE TITLE
The side crew list in Multiplayer is complete chaos

### ISSUE THREAD

**Issue by Regalis11** [FakeFishGames/Barotrauma#14213]
### Discussed in https://github.com/FakeFishGames/Barotrauma/discussions/14152

<div type='discussions-op-text'>

<sup>Originally posted by **ubertpendragon** June 18, 2024</sup>
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

The crew list in MP is pure chaos.
It's sorted based on who spawned last and keeps rearranging itself based on who joins, and doesn't respect actual jobs
Manually sorting the list is a waste of time as it keeps moving around and resetting

![image](https://github.com/FakeFishGames/Barotrauma/assets/73229309/f496618d-9ce7-4380-ba18-b0803dae2590)

If it could respect a certain job "order" using a priority value (or at least always put the captain on top)

Captain
Security
Medic
Engineer
Mechanic
Assistant

Modded jobs would have to specify their priority or going at the bottom of the list by default

### Reproduction steps

Play in MP, drag names around to rearrange, a few minute later it's all scrambled

### Bug prevalence

Happens every time I play

### Single player or multiplayer?

Multiplayer hosted from the in-game menu (= using a listen server)

### Version

v1.4.6.0 (Blood in the Water Update, hotfix 2)

### Which operating system did you encounter this bug on?

Windows

### Relevant error messages and crash reports

_No response_</div>

**Comment by Regalis11** [comment]
Fixed in https://github.com/FakeFishGames/Barotrauma-development/commit/c240ffcdda836c8b629e0807dadecdc7c35ae5fa

**Comment by xDJxDeFaLtx** [comment]
Ты смог решить эту проблема? Как их отсортировать?

**Comment by Regalis11** [comment]
@xDJxDeFaLtx 

The fix only prevents the list from shuffling around constantly. Like in single player, the characters aren't sorted in any particular order, but they can be manually rearranged.
