### ISSUE TITLE
[Unstable] Loop sounds triggered by statuseffect cannot play correctly

### ISSUE THREAD

**Issue by Regalis11** [FakeFishGames/Barotrauma#14232]
### Discussed in https://github.com/FakeFishGames/Barotrauma/discussions/14230

<div type='discussions-op-text'>

<sup>Originally posted by **zhu-rengong** June 28, 2024</sup>
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

Loop sound will stop immediately after playing and keep cycling this.

https://github.com/FakeFishGames/Barotrauma/assets/73634685/236d4189-6f7c-472f-9074-cf2f0ded1e5f

### Reproduction steps

Equip respawn diving suit with less than 5% condition

### Bug prevalence

Happens every now and then

### Single player or multiplayer?

Single player

### Version

v1.6.100.0 (unstable)

### Which operating system did you encounter this bug on?

Windows

### Relevant error messages and crash reports

_No response_</div>

**Comment by Regalis11** [comment]
Fixed in https://github.com/FakeFishGames/Barotrauma-development/commit/e2b2c02c839edca59a06eb76adaf2e0e2c842222

**Comment by Rokvach** [comment]
Tested, working correctly. Can be merged and closed.
