### ISSUE TITLE
Censorship outpost event bug

### ISSUE THREAD

**Issue by Jasontti** [FakeFishGames/Barotrauma#14269]
### Discussed in https://github.com/FakeFishGames/Barotrauma/discussions/14268

<div type='discussions-op-text'>

<sup>Originally posted by **Jasontti** July  8, 2024</sup>
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

Clown outpost event censorship breaks down when selecting "better not" dialog option

### Reproduction steps

1. Go to clown allied outpost
2. `triggerevent censorship`
3. Progress the dialog until option "censorship.o1.o1.o2" "Better not" is available
4. Choose it
5. Dialog doesn't close and it's bugged now

### Bug prevalence

Happens regularly

### Single player or multiplayer?

Happens in both single player and multiplayer

### Version

v1.5.9.1 (Summer Update Hotfix 2)

### Which operating system did you encounter this bug on?

Linux

### Relevant error messages and crash reports

_No response_</div>

**Comment by JeroonBosch** [comment]
https://github.com/FakeFishGames/Barotrauma-development/pull/5543

**Comment by Jasontti** [comment]
Testing notes: https://github.com/FakeFishGames/Barotrauma-development/pull/5543#issuecomment-2328531244
Closing ticket as completed
