### ISSUE TITLE
AbilityConditionNearbyCharacterCount doesn't work properly(or I don't know how programming works)

### ISSUE THREAD

**Issue by cabegame** [FakeFishGames/Barotrauma#14279]
### Discussed in https://github.com/FakeFishGames/Barotrauma/discussions/14275

<div type='discussions-op-text'>

<sup>Originally posted by **cabegame** July 10, 2024</sup>
Hi everyone! Tried to make a talent that triggers when you are in the oceans of Europa and noone's around, but the talent triggers all the time, as if it ignores the AbilityConditionNearbyCharacterCount. Is it even supposed to work with AbilityGroupInterval?
Here's the test talent, you can check it out yourself(used an in-game affliction with an icon just to be sure conditions are met):
```
<AbilityGroupInterval>
		<Conditions>
			<AbilityConditionInWater/>
			<AbilityConditionInHull invert="true"/>
			<AbilityConditionNearbyCharacterCount distance="500" targettypes="Any" count="0"/>
		</Conditions>
		<Abilities>
			<CharacterAbilityApplyStatusEffects>
				<StatusEffects>
					<StatusEffect type="OnAbility" target="Character" disabledeltatime="true">
						<Affliction identifier="dashing" amount="1.0"/>
					</StatusEffect>
				</StatusEffects>
			</CharacterAbilityApplyStatusEffects>
		</Abilities>
	</AbilityGroupInterval>
```</div>

**Comment by Regalis11** [comment]
Please do not create bug reports in the issue tracker yourself: they should now instead be created in the https://github.com/FakeFishGames/Barotrauma/issues/13590.
