### ISSUE TITLE
Welding tool / Plasma cutter combat priority at 10, bots keep using them as weapons

### ISSUE THREAD

**Issue by JeroonBosch** [FakeFishGames/Barotrauma#14274]
### Discussed in https://github.com/FakeFishGames/Barotrauma/discussions/14271

<div type='discussions-op-text'>

<sup>Originally posted by **ubertpendragon** July  9, 2024</sup>
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

Bots keep using their welding tools and plasma cutters as weapons if an enemy is nearby instead of wrench/screwdrivers.

Combat priority for welder/cutter is at 10, combat priority for wrench/screwdriver is at 8/7

Welding tools deal very little damage and waste fuel, while mechanic and engineer respectively have talents to hit harder with their respective tools

### Reproduction steps

spawn a monster near mechanic/engineer bots

### Bug prevalence

Happens every now and then

### Single player or multiplayer?

Single player

### Version

v1.5.9.1 (Summer Update Hotfix 2)

### Which operating system did you encounter this bug on?

Windows

### Relevant error messages and crash reports

_No response_</div>

**Comment by JeroonBosch** [comment]
I guess we should at the very least lower the combat priority of welding tools. Plasma cutters wasting oxygen is less of an issue as they're easily refillable - but only makes sense if plasma cutters actually deal more damage than wrench / screwdriver.

I suppose we could also look into changing weapon priority for AI when they have a certain talent. F.e. the heavy wrench could have a much higher combatpriority if the mechanic has the wrench-related talents. -  but that would mean code additions

**Comment by itchyOwl** [comment]
Addressed in FakeFishGames/Barotrauma-development#5551 by just adjusting the priorities. The old values probably predated both nerfing the torches and the addition of the talents.

**Comment by Rokvach** [comment]
Tested, no issues. Can be merged and closed.
