### ISSUE TITLE
[Unstable] Performance issues in the debugdraw mode

### ISSUE THREAD

**Issue by itchyOwl** [FakeFishGames/Barotrauma#14335]
Performance in the debug draw mode is abyssmal especially if you zoom out and move the camera in the freecam mode. Seems to be (mainly?) caused by FakeFishGames/Barotrauma-development@f423e80d, which added an insertion sort in the `Submarine.CullEntities()` method.

See:
<img width="1422" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMDhSQmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--44b5ba1bb6a18be6ef07eac0b5bc227b4a3404ce/image%20%281%29.png" alt="image (1).png" />

Compare to, where I just reverted that commit:
<img width="1419" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMUVSQmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--24cd2913ea338eca0621b51d1eceded8112a14fb/image%20%282%29.png" alt="image (2).png" />

Repro steps:
Start any game mode (I used the profiling button), type `debugdraw` and `freecam`. Also had `devmode` enabled.

Version:
v1.6.1.0 (unstable)

**Comment by SomeRandomNoobKekeke** [comment]
https://github.com/FakeFishGames/Barotrauma/discussions/14253

**Comment by itchyOwl** [comment]
Here's some data from the VS profiler: 
![image](https://github.com/user-attachments/assets/dd0382cc-a162-4818-a9db-910f8742e748)
![image](https://github.com/user-attachments/assets/ded261f1-c6a9-41f0-9f99-da639dd70f8a)
![image](https://github.com/user-attachments/assets/4209e911-ad76-4a47-a14f-f2f965dcdc71)

**Comment by Regalis11** [comment]
Addressed in https://github.com/FakeFishGames/Barotrauma-development/commit/aa256f6fb54c15683ec6d5174b7bf723f1025213 and https://github.com/FakeFishGames/Barotrauma-development/commit/0b5342a06459dbec1627b357b2ca260e08932886

**Comment by Jasontti** [comment]
Testing notes: https://github.com/FakeFishGames/Barotrauma-development/pull/5569#issuecomment-2271121597
No issues found, closing ticket.
