### ISSUE TITLE
[Unstable] Some issues about MUX/DEMUX components

### ISSUE THREAD

**Issue by Regalis11** [FakeFishGames/Barotrauma#14347]
### Discussed in https://github.com/FakeFishGames/Barotrauma/discussions/14345

<div type='discussions-op-text'>

<sup>Originally posted by **jcx1991911** July 28, 2024</sup>
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

move_output pin of DEMUX component are not function inside circuit box
move_output and set_output(is this supposed to be move_input and set_input??) pin of MUX component are complete not function, whatever inside circuit box or no

### Reproduction steps

just test there pins

### Bug prevalence

Happens every time I play

### Single player or multiplayer?

Single player

### Version

v1.6.101.0 (unstable)

### Which operating system did you encounter this bug on?

Windows

### Relevant error messages and crash reports

_No response_</div>

**Comment by Rokvach** [comment]
Tested, working correctly. Can be merged and closed.

**Comment by Rokvach** [comment]
Nvm forgot that If found some visual issues with the components
![image](https://github.com/user-attachments/assets/a7fe0de4-03b1-4f1c-a956-479779ec6568)
