### ISSUE TITLE
[UNSTABLE] All players respawn to the coalition team in deathmatch

### ISSUE THREAD

**Issue by Regalis11** [FakeFishGames/Barotrauma#14349]
### Discussed in https://github.com/FakeFishGames/Barotrauma/discussions/14281

<div type='discussions-op-text'>

<sup>Originally posted by **WrillWasTaken** July 12, 2024</sup>
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

If a player respawns in deathmatch, they always respawn to the coalition team. Even if they died as part of the separatist team.

### Reproduction steps

1. Start outpost deathmatch on the separatist side
2. Die
3. Respawn
4. You dirty traitor.

### Bug prevalence

Happens every time I play

### Single player or multiplayer?

Multiplayer hosted using a dedicated server

### Version

v1.6.101.0 (unstable)

### Which operating system did you encounter this bug on?

Windows

### Relevant error messages and crash reports

_No response_</div>

**Comment by Regalis11** [comment]
Fixed in https://github.com/FakeFishGames/Barotrauma-development/commit/b1f23eee6269759935818fc6e2f3e64c20b32820

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
