### ISSUE TITLE
[UNSTABLE] Respawns in deathmatch (and KOTH?) happen on the docked submarine.

### ISSUE THREAD

**Issue by Regalis11** [FakeFishGames/Barotrauma#14352]
### Discussed in https://github.com/FakeFishGames/Barotrauma/discussions/14284

<div type='discussions-op-text'>

<sup>Originally posted by **WrillWasTaken** July 12, 2024</sup>
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

When respawning in deathmatch and KOTH, players will spawn on the docked submarine instead of the station.

### Reproduction steps

1. Start a game of deathmatch or KOTH
2. Die
3. Respawn
4. Welcome to the submarine.

### Bug prevalence

Happens every time I play

### Single player or multiplayer?

Multiplayer hosted using a dedicated server

### Version

v1.6.101.0 (unstable)

### Which operating system did you encounter this bug on?

Windows

### Relevant error messages and crash reports

_No response_</div>

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
