### ISSUE TITLE
[Unstable] The particles emitted from burning affliction gradually out of the correct position when the emitter source or the submarine moves

### ISSUE THREAD

**Issue by Regalis11** [FakeFishGames/Barotrauma#14355]
### Discussed in https://github.com/FakeFishGames/Barotrauma/discussions/14254

<div type='discussions-op-text'>

<sup>Originally posted by **zhu-rengong** July  5, 2024</sup>
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

The particles emitted by the burning affliction are very messy.

https://github.com/FakeFishGames/Barotrauma/assets/73634685/09b1461e-2932-4a04-88fd-f032a14d59ab

I think it would be better to bind particles to targets and smoothly follow their positions.
Of course, particles should not completely follow targets, but just adding an offset(from the position where the particle is created to the position of the targets) to their current position, because the rising of the flames also needs to be taken into account.
Not only that, they will also become more messier when the submarine is sinking in high velocity.

### Reproduction steps

1. give burning affliction to yourself
2. run and observe the flames
3. make the submarine sinking severly and keep observing

### Bug prevalence

Happens every now and then

### Single player or multiplayer?

Single player

### Version

v1.6.101.0 (unstable)

### Which operating system did you encounter this bug on?

Windows

### Relevant error messages and crash reports

_No response_</div>

**Comment by Regalis11** [comment]
Addressed in https://github.com/FakeFishGames/Barotrauma-development/commit/3f32c97b390fc6d5ea72ee044122de042f85fe85

**Comment by Jasontti** [comment]
Tested, no issues found.
Minor improvement idea could be adding a light source to actually illuminate surrounding area, but it might not possible currently and if there would be lot of fire, performance impact could be severe. This can be separate ticket though.
Closing ticket.
