### ISSUE TITLE
[UNSTABLE] KOTH is completely unplayable

### ISSUE THREAD

**Issue by Regalis11** [FakeFishGames/Barotrauma#14351]
### Discussed in https://github.com/FakeFishGames/Barotrauma/discussions/14283

<div type='discussions-op-text'>

<sup>Originally posted by **WrillWasTaken** July 12, 2024</sup>
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

It spawns an outpost as if it was outpost deathmatch. There is a beacon but good luck reaching it if you weren't the first to the sub.

### Reproduction steps

1. Start a game of KOTH
2. suffer

### Bug prevalence

Happens every time I play

### Single player or multiplayer?

Multiplayer hosted using a dedicated server

### Version

v1.6.101.0 (unstable)

### Which operating system did you encounter this bug on?

Windows

### Relevant error messages and crash reports

_No response_</div>

**Comment by Regalis11** [comment]
Fixed in https://github.com/FakeFishGames/Barotrauma-development/pull/5523/commits/d1447775a0f1a396280b4944deb7a396bfcb823b

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
