### ISSUE TITLE
[UNSTABLE] Submarines belonging to BOTH teams spawn in outpost deathmatch

### ISSUE THREAD

**Issue by Regalis11** [FakeFishGames/Barotrauma#14350]
### Discussed in https://github.com/FakeFishGames/Barotrauma/discussions/14282

<div type='discussions-op-text'>

<sup>Originally posted by **WrillWasTaken** July 12, 2024</sup>
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

Outpost deathmatch spawns 2 submarines, one docked. The docked sub spawns like a completely normal submarine... which is problematic because it has a fully autofilled medbay and armory, meaning the team that reaches it first generally wins.

### Reproduction steps

1. Start a game of outpost deathmatch
2. Observe.

### Bug prevalence

Happens every time I play

### Single player or multiplayer?

Multiplayer hosted using a dedicated server

### Version

v1.6.101.0 (unstable)

### Which operating system did you encounter this bug on?

Windows

### Relevant error messages and crash reports

_No response_</div>

**Comment by Regalis11** [comment]
Fixed in https://github.com/FakeFishGames/Barotrauma-development/pull/5480

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
