### ISSUE TITLE
[Unstable] Acid emitters spawned by the acid grenade will make loud noise when hit the structure.

### ISSUE THREAD

**Issue by Regalis11** [FakeFishGames/Barotrauma#14357]
### Discussed in https://github.com/FakeFishGames/Barotrauma/discussions/14229

<div type='discussions-op-text'>

<sup>Originally posted by **zhu-rengong** June 28, 2024</sup>
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

As the title saying, I think it's unreal.

### Reproduction steps

1. Detonator a acid grenade indoor
2. You will constantly hear the walls being hit hard

### Bug prevalence

Happens every now and then

### Single player or multiplayer?

Multiplayer hosted from the in-game menu (= using a listen server)

### Version

v1.6.100.0

### Which operating system did you encounter this bug on?

Windows

### Relevant error messages and crash reports

_No response_</div>

**Comment by Jasontti** [comment]
Testing notes: https://github.com/FakeFishGames/Barotrauma-development/pull/5568#issuecomment-2323887260
Closing issues as completed
