### ISSUE TITLE
Inconsistent display of color tagged text.

### ISSUE THREAD

**Issue by Regalis11** [FakeFishGames/Barotrauma#14361]
### Discussed in https://github.com/FakeFishGames/Barotrauma/discussions/14337

<div type='discussions-op-text'>

<sup>Originally posted by **lIllIIlI** July 27, 2024</sup>
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [X] My issue happened while using mods.

### What happened?

Some GUI displays proper color for items tagged with a specific color via translation xml, i.e: 
  <entityname.Patchouli_gear>‖color:120,75,100,255‖帕秋莉装束‖color:end‖</entityname.Patchouli_gear>
  <entityname.Patchouli_gear>‖color:120,75,100,255‖Patchouli's Outfit‖color:end‖</entityname.Patchouli_gear>
Appears correctly in tooltips, but not in crafting / shop menus.
![Barotrauma_HewB5xlmMx](https://github.com/user-attachments/assets/a713ef62-e227-40c3-aa01-c715f537e039)

Similarly, chat text popups do not adhere to the color tags while the chat window does.
![image](https://github.com/user-attachments/assets/ca7dc18a-7ef9-45a8-acac-70ab51aeccac)
![image](https://github.com/user-attachments/assets/7eacd612-1aa2-4089-a2d2-45e1dcdceff0)

I'd like the colors to be supported in all types of texts.

### Reproduction steps

1. Use localization text file to give item names color using ||color:###,###,###,###||<Item Name>||color:end||
2. color appears properly in tool tips, chat window, fabrication tooltip
3. color does not appear but the code itself appears in chat bubbbles and fab/shop menus

### Bug prevalence

Happens every time I play

### Single player or multiplayer?

Happens in both single player and multiplayer

### Version

v1.5.9.1 (Summer Update Hotfix 2)

### Which operating system did you encounter this bug on?

Windows

### Relevant error messages and crash reports

_No response_</div>

**Comment by Regalis11** [comment]
Fixed in https://github.com/FakeFishGames/Barotrauma-development/commit/e5d6ce72b2795349db55179ceae48215d88affd4

**Comment by Jasontti** [comment]
Testing notes:
Checked most of the menus and items that have colored text in descriptions ie. item quality and such
Tested chat messages with All leaks repaired in ‖color:gui.Blue‖command room‖end‖!
No issues found, closing ticket as resolved
