### ISSUE TITLE
Colored text does not work in speech bubble

### ISSUE THREAD

**Issue by Regalis11** [FakeFishGames/Barotrauma#14385]
### Discussed in https://github.com/FakeFishGames/Barotrauma/discussions/13936

<div type='discussions-op-text'>

<sup>Originally posted by **A2ur3** May  7, 2024</sup>
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

‖color:gui.Blue‖‖end‖ is not converted to colored text 

### Reproduction steps

1. send this message
All leaks repaired in ‖color:gui.Blue‖command room‖end‖!

### Bug prevalence

Happens every time I play

### Single player or multiplayer?

Happens in both single player and multiplayer

### Version

v1.4.6.0 (Blood in the Water Update, hotfix 2)

### Which operating system did you encounter this bug on?

Windows

### Relevant error messages and crash reports

_No response_</div>

**Comment by Regalis11** [comment]
Fixed in https://github.com/FakeFishGames/Barotrauma-development/commit/e5d6ce72b2795349db55179ceae48215d88affd4

**Comment by Jasontti** [comment]
Testing notes:
Checked most of the menus and items that have colored text in descriptions ie. item quality and such
Tested chat messages with All leaks repaired in ‖color:gui.Blue‖command room‖end‖!
No issues found, closing discussion as resolved
