### ISSUE TITLE
variables not accessible for xml conditionals

### ISSUE THREAD

**Issue by Master-Woof** [FakeFishGames/Barotrauma#14447]
these variables are not accessible for xml conditionals:

https://github.com/FakeFishGames/Barotrauma/blob/0aee53976202c7ea5c0bb3f26669a97c8dc2400c/Barotrauma/BarotraumaShared/SharedSource/Items/Components/Signal/SmokeDetector.cs#L11

https://github.com/FakeFishGames/Barotrauma/blob/0aee53976202c7ea5c0bb3f26669a97c8dc2400c/Barotrauma/BarotraumaShared/SharedSource/Items/Components/Signal/OxygenDetector.cs#L10

unlike similar variables:

https://github.com/FakeFishGames/Barotrauma/blob/0aee53976202c7ea5c0bb3f26669a97c8dc2400c/Barotrauma/BarotraumaShared/SharedSource/Items/Components/Signal/MotionSensor.cs#L27

https://github.com/FakeFishGames/Barotrauma/blob/0aee53976202c7ea5c0bb3f26669a97c8dc2400c/Barotrauma/BarotraumaShared/SharedSource/Items/Components/Signal/WaterDetector.cs#L61-L62

**Comment by SomeRandomNoobKekeke** [comment]
They are fields, not properties, and they are private
Devs hiding all the good stuff, as usual

**Comment by Master-Woof** [comment]
i just want the variables changed from private to public, as i see no reason to have them be private and i want to use them for my mod lol.

**Comment by Regalis11** [comment]
As SomeRandomNoobKekeke mentioned, these are fields, not properties. Changing them to public won't make them accessible for conditionals.

I changed them to public properties in https://github.com/FakeFishGames/Barotrauma-development/commit/b60f6038f6427fd2e046f6f440adea5846f6a2f9 though.
