### ISSUE TITLE
LAN Server Hosting doesn't authenticate, even with RequireAuthentication="false"

### ISSUE THREAD

**Issue by Regalis11** [FakeFishGames/Barotrauma#14457]
### Discussed in https://github.com/FakeFishGames/Barotrauma/discussions/14343

<div type='discussions-op-text'>

<sup>Originally posted by **Chromaphasia** July 28, 2024</sup>
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

I hosted a dedicated server on my machine, and attempted to connect with another machine on the same network. The connecting machine got "Connection Authentication Failed" in response. I have set RequireAuthentication to false in the server settings and saved the file, but it doesn't seem to have worked, or if it has, it hasn't worked correctly.

### Reproduction steps

1. Start a dedicated server with RequireAuthentication = "False" in the serverSettings.xml
2. Attempt to connect with another machine using 'Direct Join' and inputting the first machine's IP. (In my case, this second machine does not have access to Steam/Epic Games but does have LAN access to the first machine)
3. Connection Authentication Failed error, but first machine can connect to server without issue (First machine does have access to steam however.)

Host Machine is Windows, Connecting Machine is Linux (Arch).

### Bug prevalence

Happens every time I play

### Single player or multiplayer?

Multiplayer hosted using a dedicated server

### Version

v1.5.9.1 (Summer Update Hotfix 2)

### Which operating system did you encounter this bug on?

Linux

### Relevant error messages and crash reports

_No response_</div>

**Comment by Regalis11** [comment]
Fixed in https://github.com/FakeFishGames/Barotrauma-development/commit/12dcfcd5adacef2e121914e3fdcb7100aac30cd8

**Comment by Jasontti** [comment]
Testing notes: https://github.com/FakeFishGames/Barotrauma-development/pull/5989#issuecomment-2488488625
No issues found. Closing ticket as completed.
