### ISSUE TITLE
Monsters ignore handheld sonar beacons inside subs

### ISSUE THREAD

**Issue by Regalis11** [FakeFishGames/Barotrauma#14466]
### Discussed in https://github.com/FakeFishGames/Barotrauma/discussions/14453

<div type='discussions-op-text'>

<sup>Originally posted by **pavel4win** August 19, 2024</sup>
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

~~A handheld sonar beacon turned on inside a submarine pings the area almost as well as a submarine's sonar turned on.
This makes the use of a ship's sonar almost unnecessary.
It seems to me that a sonar beacon turned on inside a boat should not sound outside the boat at all.
Just as a handheld sonar (turned on inside the ship) shows nothing outside the boat.~~

Joonas edit: the issue here is not that the sonar beacon allows you to see outside. That's intentional: it makes a very loud noise, which the passive sonar can use. The problem is that (most?) monsters don't seem to be able to target the sonar beacon. This seems to happen because they attempt to target it using the "provocative" targeting parameters, which only work when targeting something in the same sub. If they targeted using the "sonar" targeting parameters, it'd work as intended.

### Reproduction steps

Start game session
Take a handheld sonar beacon and turn it on inside sub.
Open navigation terminal.
Navigate with shop's sonar turned off
Monsters do not react to a submarine outside of direct line of sight.

### Bug prevalence

Happens every time I play

### Single player or multiplayer?

Happens in both single player and multiplayer

### Version

v1.5.9.1 (Summer Update Hotfix 2)

### Which operating system did you encounter this bug on?

Windows

### Relevant error messages and crash reports

_No response_</div>

**Comment by Jasontti** [comment]
Closing as completed
