### ISSUE TITLE
Bug Report: Сustom circuit boxes for some reason get locked by lock default wiring options

### ISSUE THREAD

**Issue by Regalis11** [FakeFishGames/Barotrauma#14475]
### Discussed in https://github.com/FakeFishGames/Barotrauma/discussions/13979

<div type='discussions-op-text'>

<sup>Originally posted by **SerChiz** May 20, 2024</sup>
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

Сustom circuit boxes for some reason get locked by lock default wiring options and neither original nor custom circuit boxes actually unlock after removing loсk default wiring checkmark.

![screen](https://github.com/FakeFishGames/Barotrauma/assets/82869566/7531a033-a504-4d46-bfe9-071df1c27337)

### Reproduction steps

1 Multiplayer campaign.
2. Set settings options "lock default wiring" to true
2 Сraft new Circuit Box
3 Place the Circuit Box on wall
4 Created a schematic in it
5 Play level and restart server
6 Custom Circuit Box is lock!

### Bug prevalence

Happens regularly

### Single player or multiplayer?

Multiplayer hosted from the in-game menu (= using a listen server)

### Version

v1.4.6.0 (Blood in the Water Update, hotfix 2)

### Which operating system did you encounter this bug on?

Windows

### Relevant error messages and crash reports

_No response_</div>

**Comment by Regalis11** [comment]
Fixed in https://github.com/FakeFishGames/Barotrauma-development/pull/5652/commits/a5e847c3480045aeb3188bd7000d94eddbcff509

**Comment by Jasontti** [comment]
Testing notes: https://github.com/FakeFishGames/Barotrauma-development/pull/5652#issuecomment-2310245204
Closing as fixed

**Comment by dossy** [comment]
When will this fix land?  I just experienced this in a game running on:

Barotrauma Dedicated Server 1.5.9.2 (ReleaseLinux, branch release/summer-update-hotfix-2, revision 54bd6b29f7)

thanks!
