### ISSUE TITLE
WiFi Components inside Circuit Boxes cannot link to chat or communicate with Components outside Circuit Boxes, and vice versa.

### ISSUE THREAD

**Issue by Regalis11** [FakeFishGames/Barotrauma#14477]
### Discussed in https://github.com/FakeFishGames/Barotrauma/discussions/14465

<div type='discussions-op-text'>

<sup>Originally posted by **Sarynkia** August 21, 2024</sup>
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [X] My issue happened while using mods.

### What happened?

Disclaimer for the disclaimer: Only texture replacement mods were in use.

It appears that WiFi Components placed inside Circuit Boxes cannot link to chat (no output) even with "link to chat" enabled in the server settings. Placing the exact same WiFi Component (or combinations thereof) outside Circuit Boxes however works correctly.

This occurred in MP while I'm cleaning up the Sub myself, I have not tried replicating this issue in SP or doing so with other players in the server.

### Reproduction steps

1. Start a Multiplayer campaign.
2. Place a "link to chat"-enabled WiFi Component inside a Circuit Box.
3. (Connect the WiFi Component to a Signal Out pin in the Circuit Box, and the pin to a text display if desired to verify)
4. Send whatever message to the WiFi Component. Verify that no messages in chat appear in the corresponding channel.
5. Take the WiFi Component _out of_ the Circuit Box for comparison.
6. Send whatever message to it again.
7. Profit. Messages should appear normally in chat.

### Bug prevalence

Happens every time I play

### Single player or multiplayer?

Multiplayer hosted from the in-game menu (= using a listen server)

### Version

v1.5.9.1 (Summer Update Hotfix 2)

### Which operating system did you encounter this bug on?

Windows

### Relevant error messages and crash reports

_No response_</div>

**Comment by Regalis11** [comment]
Addresed in https://github.com/FakeFishGames/Barotrauma-development/pull/5653 (PR in our private repo)

**Comment by Jasontti** [comment]
Testing notes: https://github.com/FakeFishGames/Barotrauma-development/pull/5653#issuecomment-2402137607
Closing ticket as completed
