### ISSUE TITLE
Game crashed on OSX after last update (28 aug 2024, 1.5.9.2)

### ISSUE THREAD

**Issue by vse3211** [FakeFishGames/Barotrauma#14525]
### Discussed in https://github.com/FakeFishGames/Barotrauma/discussions/14524

<div type='discussions-op-text'>

<sup>Originally posted by **vse3211** August 28, 2024</sup>
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

Game crashed after update on OSX.
Launcher: Steam
App number: 602960
Build ID: 15504647
OS: MacOS 15 (Beta 7)
Crash log state: NOT FOUND (Not possible to save in root game fold
Apple crash log: [Barotrauma Crash Report 2808241640.txt](https://github.com/user-attachments/files/16782775/Barotrauma.Crash.Report.2808241640.txt)
er)

Game crashed on all available versions now.

Game folder from "Application Support" folder: [Download from iCloud (zip, 102.6mb)](https://www.icloud.com/iclouddrive/0a6Xac8ecNdJOW9Aib-OnIqzw#Barotrauma_crashsave_280824)

### Reproduction steps

Update and start game on MacBook Pro with M2

User game files: [Download from iCloud (zip, 102.6mb)](https://www.icloud.com/iclouddrive/0a6Xac8ecNdJOW9Aib-OnIqzw#Barotrauma_crashsave_280824)

### Bug prevalence

Happens every time I play

### Single player or multiplayer?

Other

### -

I cant start game!

### Version

v1.5.9.2 (Summer Update Hotfix 2)

### Which operating system did you encounter this bug on?

MacOS

### Relevant error messages and crash reports

_No response_</div>

**Comment by Regalis11** [comment]
https://github.com/FakeFishGames/Barotrauma/issues/13590
