### ISSUE TITLE
Mission Equality Check failure preventing players from joining

### ISSUE THREAD

**Issue by Regalis11** [FakeFishGames/Barotrauma#14526]
### Discussed in https://github.com/FakeFishGames/Barotrauma/discussions/13803

<div type='discussions-op-text'>

<sup>Originally posted by **bananaman6213** April 22, 2024</sup>
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

Players cannot join a lobby while missions are selected at an outpost, as described in #11469. This issue was marked as a duplicate of another mission equality check issue but i believe that the two were unrelated.

### Reproduction steps

1. Host lobby
2. In an outpost, select missions on the map screen without actually starting a round
3. Have someone else join
4. They should be kicked due to mission equality check failure
5. Deselect the missions
6. Watch as that second player can now join without issue

### Bug prevalence

Happens every now and then

### Single player or multiplayer?

Multiplayer hosted from the in-game menu (= using a listen server)

### Version

v1.3.0.4

### Which operating system did you encounter this bug on?

Windows

### Relevant error messages and crash reports

_No response_</div>

**Comment by Rokvach** [comment]
Tested, working correctly. Can be merged and closed.
