### ISSUE TITLE
Medical AI issues (test cases included)

### ISSUE THREAD

**Issue by Regalis11** [FakeFishGames/Barotrauma#14545]
### Discussed in https://github.com/FakeFishGames/Barotrauma/discussions/14411

<div type='discussions-op-text'>

<sup>Originally posted by **SomeRandomNoobKekeke** August  7, 2024</sup>
### Disclaimers  

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

Bots waste all med and OD whenever i look away
So i can't trust them anymore, i have to tell them to ignore med cabinet and only treat them myself

Examples:

- They constantly use T1 meds(bandages / opium / alien blood) for no good reason, and bleed out / OD / hallucinating
- They will also waste all the saline/ethanol on board whenever they see an infected wound before applying any real medicine
- They ignore security officer with heal order and higher skill, try to heal themselves and die
- They periodically just tell "there's nothing i can do" and watch someone die when there's clearly something they can do / Don't heal someone for no reason
- They don't heal FriendlyNPC at all
- They completely ignore people that was discovered unconscious
- They don't heal to full health people that fainted during healing
- They are often mesmerized by infection, if you have massive bleeding and suddenly get infection they will just stand and watch you bleed, if you have multiple doctors they will all come to stare
- They don't heal internal damage on opiate addicts, this is probably related to https://github.com/FakeFishGames/Barotrauma/discussions/14318 and solution depends on how you resolve that
- They don't do CPR, at least i've never seen them do it
- They ignore all skill requirements
- They don't heal husk infection, they don't think it's worth wasting medicine on
- They may sometimes heal husk infection if patient has more affliction, but not always
- They prefer to inject antibiotics one by one for husk infection, which is never enough
- They keep injecting antibiotics in terminal stage which is useless
- They will also waste all morphine / calyxanide on transforming patients

### Reproduction steps

Use [this](https://steamcommunity.com/sharedfiles/filedetails/?id=3286179963)

### Bug prevalence

Happens regularly

### Single player or multiplayer?

Single player

### Version

v1.5.9.1 (Summer Update Hotfix 2)

### Which operating system did you encounter this bug on?

Windows

### Relevant error messages and crash reports

_No response_</div>

**Comment by Jasontti** [comment]
Testing notes: https://github.com/FakeFishGames/Barotrauma-development/pull/5670#issuecomment-2343314405
Some of the issues were resolved, but closing this for making more specific tickets out of the original discussion.
