### ISSUE TITLE
Revert unintended docking port sprite change

### ISSUE THREAD

**Issue by JeroonBosch** [FakeFishGames/Barotrauma#14567]
### Discussed in https://github.com/FakeFishGames/Barotrauma/discussions/14565

<div type='discussions-op-text'>

<sup>Originally posted by **ubertpendragon** September  3, 2024</sup>
Just no

![image](https://github.com/user-attachments/assets/992e4841-fd4b-4830-9504-2b6d454af0cf)

![image](https://github.com/user-attachments/assets/ab4aa5ff-0685-45ee-9301-276e0eaba3ae)
</div>

**Comment by Regalis11** [comment]
Addressed in https://github.com/FakeFishGames/Barotrauma-development/pull/5678, closing
