### ISSUE TITLE
[Unstable] Endoutpost ruin walls fail to render behind submarine

### ISSUE THREAD

**Issue by Regalis11** [FakeFishGames/Barotrauma#14604]
### Discussed in https://github.com/FakeFishGames/Barotrauma/discussions/14595

<div type='discussions-op-text'>

<sup>Originally posted by **ubertpendragon** September  8, 2024</sup>
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

In the end outpost, you can see the ruin walls rendering in front of the wreck walls

I'm assuming `drawbehindsubs="true"` broke?

https://github.com/FakeFishGames/Barotrauma/blob/0e8fb6569d2810e2f8ad5fb17b4bba546cc5739a/Barotrauma/BarotraumaShared/SharedSource/Map/Outposts/OutpostGenerator.cs#L432-L439

![image](https://github.com/user-attachments/assets/84727cf9-73ad-4461-822b-84ce2151a184)

### Reproduction steps

.

### Bug prevalence

Just once

### Single player or multiplayer?

Single player

### Version

v1.5.9.2 (Summer Update Hotfix 2)

### Which operating system did you encounter this bug on?

Windows

### Relevant error messages and crash reports

_No response_</div>

**Comment by Regalis11** [comment]
Fixed in https://github.com/FakeFishGames/Barotrauma-development/commit/546f76b4fba7009d9cfa58ae6c19264ac56f974c

**Comment by Rokvach** [comment]
Tested, working correctly. Can be merged and closed.
