### ISSUE TITLE
ERROR Could not start voice capture; suitable capture device not found. (40964)

### ISSUE THREAD

**Issue by KvaKvax** [FakeFishGames/Barotrauma#14609]
### Discussed in https://github.com/FakeFishGames/Barotrauma/discussions/14602

<div type='discussions-op-text'>

<sup>Originally posted by **KvaKvax** September  9, 2024</sup>
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

The game has an issue connecting to the recording device.
I use a USB audio interface as the recording device.

The error message shows:
ERROR
Could not start voice capture; suitable capture device not found. (40964)

Debug console prints the following:
```
WASAPI capture open failed: HRESULT 0X80004005 (2)
alcCaptureOpenDevice failed: exception thrown (Device reset failed)
Alc.CaptureOpenDevice attempt 1 failed: error code 40964
WASAPI capture open failed: HRESULT 0X80004005 (2)
alcCaptureOpenDevice failed: exception thrown (Device reset failed)
Alc.CaptureOpenDevice attempt 2 failed: error code 40964
WASAPI capture open failed: HRESULT 0X80004005 (2)
alcCaptureOpenDevice failed: exception thrown (Device reset failed)
```

OS: Windows 10 21H2
This is NOT an issue caused by the device being named in non-Latin characters.
This is also NOT an issue caused by improper recording device setup.

I have tried the common fixes such as reinstalling the game, driver reinstalls, firewall exceptions, etc.,
so please refrain from those.

Any assistance is appreciated.

### Reproduction steps

1. boot the game
2. do anything requiring the game to apply voice settings (opening settings, connecting to a server)

### Bug prevalence

Happens every time I play

### Single player or multiplayer?

Happens outside single player or multiplayer game modes (e.g. game launches on startup, something broken in the main menu)

### Version

v1.5.9.2 (Summer Update Hotfix 2)

### Which operating system did you encounter this bug on?

Windows

### Relevant error messages and crash reports

```shell
WASAPI capture open failed: HRESULT 0X80004005 (2)
alcCaptureOpenDevice failed: exception thrown (Device reset failed)
Alc.CaptureOpenDevice attempt 1 failed: error code 40964
WASAPI capture open failed: HRESULT 0X80004005 (2)
alcCaptureOpenDevice failed: exception thrown (Device reset failed)
Alc.CaptureOpenDevice attempt 2 failed: error code 40964
WASAPI capture open failed: HRESULT 0X80004005 (2)
alcCaptureOpenDevice failed: exception thrown (Device reset failed)
```
</div>

**Comment by Regalis11** [comment]
Please use the [bug reports section](https://github.com/FakeFishGames/Barotrauma/discussions/categories/bug-reports) in the discussions for bug reports.
