### ISSUE TITLE
Bots will not heal husk infection unless the patient is damaged by other vitality reducing afflictions.

### ISSUE THREAD

**Issue by JeroonBosch** [FakeFishGames/Barotrauma#14615]
### Discussed in https://github.com/FakeFishGames/Barotrauma/discussions/14504

<div type='discussions-op-text'>

<sup>Originally posted by **Crazyjr20** August 25, 2024</sup>
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

Bots appear to only cure husk infection as an affliction if the target is deemed injured, as husk infection does not cause any vitality damage until it's too late and uncurable medics will ignore it unless you also recieved sufficient damage from other sources, this includes station medics, making guards not get healed after being bit by any husks (usually players intentionally cheesing to be honest) as the bite wounds was not high enough to trigger the doctor.

https://github.com/user-attachments/assets/4e954591-e35c-4ee5-9a1f-0fe37f902247

### Reproduction steps

1 - Start a game
2 - Spawn or hire a medic (For testing I did both, but quick method is _"spawn medicaldoctor cursor"_
3 - Give medic order to heal (or leave them to idly do it)
4 - Give yourself husk infection _"giveaffliction huskinfection 50"_
5 - They will tell you injuries are too minor
6 - Give yourself any type of vitality reducing affliction more than a tiny amount (for testing I used blunt force trauma) _"giveaffliction blunttrauma 20"_
7 - Now they will heal you as you are "Injured"

### Bug prevalence

Happens every time I play

### Single player or multiplayer?

Happens in both single player and multiplayer

### Version

v1.5.9.1 (Summer Update Hotfix 2)

### Which operating system did you encounter this bug on?

Windows

### Relevant error messages and crash reports

_No response_</div>

**Comment by JeroonBosch** [comment]
Somewhat related to #14545 (as that also handled some AI cases) but I don't think we addressed this case.

**Comment by JeroonBosch** [comment]
I think some afflictions like husk infection, infected wounds and poisons (since they only increase in strength) should be handled the moment they're spotted by AI as they will only get stronger. These afflictions should never be considered too minor.

**Comment by itchyOwl** [comment]
Actually this is intentional. If we'd make the bots to react to the husk infection, that'd reveal that you have an infection. And it's supposed to be something that can go unnoticed and therefore untreated. The same goes for poisons: if the bots immediately start healing them, they can't be stealthy.

We can control the thresholds for treating and the thresholds for displaying the affliction/treatments in the health interface. Here's a recap:

```
/// <summary>
/// How high the strength has to be for the affliction icon to be shown in the UI
/// </summary>
public readonly float ShowIconThreshold = 0.05f;

/// <summary>
/// How high the strength has to be for the affliction icon to be shown to others with a health scanner or via the health interface
/// </summary>
public readonly float ShowIconToOthersThreshold = 0.05f;

/// <summary>
/// How high the strength has to be for the affliction icon to be shown with a health scanner
/// </summary>
public readonly float ShowInHealthScannerThreshold;

/// <summary>
/// How strong the affliction needs to be before bots attempt to treat it.
/// Also effects when the affliction is shown in the suitable treatments list.
/// </summary>
public readonly float TreatmentThreshold = 10.0f;
```

For example, it's intentional that bots don't treat deliriumine poisoning at all, sufforin poisoning only when it gets serious, morbusine poisoning a bit earlier, and cyanide poisoning even a bit before that. The idea here is that they only start treating those when it's apparent what's happening. With cyanide, it's intentional that it's often too late.

Currently thresholds for treatment and for showing the suitable treatments are always the same, but [Fix/treatment suggestions not shown #5581](https://github.com/FakeFishGames/Barotrauma-development/pull/5581) will add an option to set them different by defining `TreatmentSuggestionThreshold`:

```
/// <summary>
/// How strong the affliction needs to be for treatment suggestions to be shown in the health interface.
/// Defaults to <see cref="TreatmentThreshold"/>.
/// </summary>
public readonly float TreatmentSuggestionThreshold;
```

Removing "bug", adding "design", if we want to address this somehow.

**Comment by itchyOwl** [comment]
Also moved to icebox, because I don't think we should address this. If you feel that there's something to address, feel free to move it in backlog.

**Comment by JeroonBosch** [comment]
> Actually this is intentional. If we'd make the bots to react to the husk infection, that'd reveal that you have an infection. And it's supposed to be something that can go unnoticed and therefore untreated. The same goes for poisons: if the bots immediately start healing them, they can't be stealthy.

Hm, but it looks to me like TreatmentThreshold defaults to 10 and it is not defined for husk infection?

To me the repro steps suggest a bug because it states:
- If a character has 50 husk infection and no other afflictions, the husk infection will not be cured by bots
- If a character has 50 husk infection and 20 blunt trauma, the husk infection will be cured by bots

Nothing in your comment addresses this?

**Comment by JeroonBosch** [comment]
I think we can also equalize some of the values here to match the dormantthreshold:
So from this
```
dormantthreshold="50"
showiconthreshold="40"
showinhealthscannerthreshold="20"
treatmentthreshold="10"
```

to new values:
```
dormantthreshold="50"
showiconthreshold="50"
showinhealthscannerthreshold="30"
treatmentthreshold="50"
```

**Comment by JeroonBosch** [comment]
Completed and merged
