### ISSUE TITLE
[Unstable] Error after downloading a sub from the server

### ISSUE THREAD

**Issue by Regalis11** [FakeFishGames/Barotrauma#14632]
### Discussed in https://github.com/FakeFishGames/Barotrauma/discussions/14631

<div type='discussions-op-text'>

<sup>Originally posted by **Regalis11** September 14, 2024</sup>
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

Clients disconnect with an error message after they finish downloading submarine from the server.

![image](https://github.com/user-attachments/assets/ef2f4532-1ff1-41c4-a52d-fb2c30a9daf5)

### Reproduction steps

1. Join a server that has submarines you don't have
2. Select one of those submarines to make the client download it

### Bug prevalence

Happens regularly

### Single player or multiplayer?

Multiplayer hosted from the in-game menu (= using a listen server)

### Version

v1.6.4.0 (unstable)

### Which operating system did you encounter this bug on?

Windows

### Relevant error messages and crash reports

_No response_</div>

**Comment by itchyOwl** [comment]
Fixed and merged. Closing
