### ISSUE TITLE
[Unstable] Multi-tool issues

### ISSUE THREAD

**Issue by Regalis11** [FakeFishGames/Barotrauma#14630]
### Discussed in https://github.com/FakeFishGames/Barotrauma/discussions/14624

<div type='discussions-op-text'>

<sup>Originally posted by **ubertpendragon** September 13, 2024</sup>
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

* still stackable to 8 in inventory, 32 in cabinets
* has quality property but no required skill for crafting
* not swingable as a melee weapon
* holdpos is weird

![image](https://github.com/user-attachments/assets/4dd601d5-d47f-456b-ac42-9590356f7a86)
![image](https://github.com/user-attachments/assets/08483c8d-263b-4ff1-a958-0b1c1bfa0419)

### Reproduction steps

.

### Bug prevalence

Just once

### Single player or multiplayer?

Single player

### Version

v1.5.9.2 (Summer Update Hotfix 2)

### Which operating system did you encounter this bug on?

Windows

### Relevant error messages and crash reports

_No response_</div>

**Comment by JeroonBosch** [comment]
A fix has been merged in [Multi-tool fixes](https://github.com/FakeFishGames/Barotrauma-development/pull/5717)
