### ISSUE TITLE
MP - Crewmember disappear after using the setclientcharacter command

### ISSUE THREAD

**Issue by OWazabi** [FakeFishGames/Barotrauma#14645]
How the bug happens (happened multiple times) :
- You use the setclientcharacter command to control another crew member on multiplayer (to craft for example)
- You go back to your own character, crew member is still there no problems.
- You undock or dock

Then the character randomly disappears.
Note that this happened to me a few times already, but sometimes I controlled the character and it didn't happened. Feels random.

This is a big issue for small groups of friends wanting to play multiplayer, like 2-3, where AI crew is mandatory and you need those crafts.

**Comment by Regalis11** [comment]
Please use the [bug reports section](https://github.com/FakeFishGames/Barotrauma/discussions/categories/bug-reports) in the discussions for bug reports.

Btw, are you aware that any character can craft items a bot has unlocked with a talent, so there's no need to switch to the bot?
