### ISSUE TITLE
Unhandled exception when removing fuel rod from beacon station reactor

### ISSUE THREAD

**Issue by itchyOwl** [FakeFishGames/Barotrauma#14696]
### Discussed in https://github.com/FakeFishGames/Barotrauma/discussions/14670

<div type='discussions-op-text'>

<sup>Originally posted by **Arctodites** September 21, 2024</sup>
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

After successfully activating a beacon station, I took the fuel rod back out of the station's reactor (thus deactivating the beacon), and the game threw an unhandled exception: "Result 'UnexpectedError' was not handled by 'UnlockAchievements'".
![BeaconStationError](https://github.com/user-attachments/assets/e85b2696-f7b2-408f-98de-bf349dbd86e2)

Playing the latest Windows unstable version of Barotrauma (v. 1.6.9.0) via Steam build 1726604483 on Windows 10 Home.

### Reproduction steps

1.) Repair a beacon station that has a reactor.
2.) Power the station's reactor with a normal fuel rod.
3.) Activate the beacon station's sonar beacon.
4.) Remove the fuel rod from the station's reactor, or simply deactivate the sonar.
5.) The dev console should pop up with an error message about an unhandled exception.

### Bug prevalence

Happens regularly

### Single player or multiplayer?

Single player

### Version

v1.6.4.0 (unstable)

### -

Barotrauma Unstable v. 1.6.9.0

### Which operating system did you encounter this bug on?

Windows

### Relevant error messages and crash reports

```shell
"Result 'UnexpectedError' was not handled by 'UnlockAchievements.'"
See attached image file (.jpg).
```
</div>

**Comment by Regalis11** [comment]
The achievement error seems to be unrelated to the beacon station, and there's [a separate ticket](https://github.com/FakeFishGames/Barotrauma/issues/14706) about that.

The error message about the beacon becoming inactive is intentional, clarified the message in https://github.com/FakeFishGames/Barotrauma-development/commit/22a264921f0a831d7b3f6328bbba70ef242b5c5e.
