### ISSUE TITLE
[Unstable] Golden Hammerhead Crashing Game When Shot

### ISSUE THREAD

**Issue by itchyOwl** [FakeFishGames/Barotrauma#14690]
### Discussed in https://github.com/FakeFishGames/Barotrauma/discussions/14676

<div type='discussions-op-text'>

<sup>Originally posted by **GreatBlueMoon** September 22, 2024</sup>
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

Enter the game, find a golden hammerhead in campaign mode. Shoot the golden hammerhead via coilgun or pulse laser. (current guns we're using on Barsuk).
[servercrashreport (35).log](https://github.com/user-attachments/
[servercrashreport (33).log](https://github.com/user-attachments/files/17086002/servercrashreport.33.log)
files/17085998/servercrashreport.35.log)
[servercrashreport (34).log](https://github.com/user-attachments/files/17086001/servercrashreport.34.log)
[servercrashreport (32).log](https://github.com/user-attachments/
[crashreport (26).log](https://github.com/user-attachments/files/17086004/crashreport.26.log)
files/17086003/servercrashreport.32.log)

### Reproduction steps

1. Start Multiplayer Campaign
2. Do missions until golden hammerhead is found.
3. Shoot with any Barsuk gun. (pulse seems to count? so this must mean other guns have issues.)

### Bug prevalence

Happens every time I play

### Single player or multiplayer?

Multiplayer hosted from the in-game menu (= using a listen server)

### Version

v1.6.4.0 (unstable)

### Which operating system did you encounter this bug on?

Windows

### Relevant error messages and crash reports

_No response_</div>

**Comment by Rokvach** [comment]
Tested, working correctly. Can be merged and closed.
