### ISSUE TITLE
[Unstable] Console Limb bug and Husks are Influenced by the Miracle Worker medic talent

### ISSUE THREAD

**Issue by itchyOwl** [FakeFishGames/Barotrauma#14699]
### Discussed in https://github.com/FakeFishGames/Barotrauma/discussions/14664

<div type='discussions-op-text'>

<sup>Originally posted by **Holneer** September 20, 2024</sup>
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

Whenever I get hit by husks (both new and old) I get console error pop-ups.
Miracle worker works on husks

### Reproduction steps

Issue 1: Randomly whenever I get hit by husks (both the new and the old).
![image](https://github.com/user-attachments/assets/a99ab2f4-a308-4701-9fcf-164f91f7bdaa)

Issue 2: Playing as a Medic and having the Miracle Worker talent prevents the Husks from dying (only tested while wearing Zealot Robes). I'm guessing I'm being flagged as part of their faction/team when I wear the cultist stuff so the talent starts afflicting them making it impossible for them to die for as long as I stay close.

![602960_20240920214735_1](https://github.com/user-attachments/assets/e2f2b983-b379-4a39-aae5-55f461859fde)

![602960_20240920214732_1](https://github.com/user-attachments/assets/253ffebd-357b-40d4-b6f1-5ab291a968d6)

Stood for several minutes next to them and they only died when I went into a different room (exceeded talent's range).

### Bug prevalence

Happens every time I play

### Single player or multiplayer?

Happens in both single player and multiplayer

### Version

v1.6.4.0 (unstable)

### Which operating system did you encounter this bug on?

Windows

### Relevant error messages and crash reports

_No response_</div>

**Comment by Regalis11** [comment]
Couldn't find a way to repro the 1st issue, 2nd one fixed in https://github.com/FakeFishGames/Barotrauma-development/pull/5755

**Comment by itchyOwl** [comment]
Had a bit of difficulties with reproducing the issue. Turned out https://github.com/FakeFishGames/Barotrauma-development/pull/5914 coincidentally fixed it for husks, because husks don't have character info.

However, confirmed the issue with human husks. Also confirmed the issue with husks in autumn-update. Is fixed in https://github.com/FakeFishGames/Barotrauma-development/pull/5755.

Steps used for reproducing:
1. "givetalent miracleworker"
2. equip cultist robes, spawned via a console command
3. spawned a husk/humanhusk near the character
4. "giveaffliction burn 1000" on the target

**Comment by Regalis11** [comment]
Merged, closing
