### ISSUE TITLE
[Unstable] Husks can stay permanently stunned if burned enough

### ISSUE THREAD

**Issue by itchyOwl** [FakeFishGames/Barotrauma#14693]
### Discussed in https://github.com/FakeFishGames/Barotrauma/discussions/14672

<div type='discussions-op-text'>

<sup>Originally posted by **ubertpendragon** September 21, 2024</sup>
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

Husks don't naturally heal burns so you can keep them unconscious forever if they have enough burns

Not sure if this is intentional, a 0.1 burn regen might help

### Reproduction steps

.

### Bug prevalence

Just once

### Single player or multiplayer?

Single player

### Version

v1.6.4.0 (unstable)

### Which operating system did you encounter this bug on?

Windows

### Relevant error messages and crash reports

_No response_</div>

**Comment by Jasontti** [comment]
Testing notes: https://github.com/FakeFishGames/Barotrauma-development/pull/5759#issuecomment-2378601224
No issues. Closing ticket.
