### ISSUE TITLE
[Localization Problem] Incorrect Mission Type Description

### ISSUE THREAD

**Issue by itchyOwl** [FakeFishGames/Barotrauma#14698]
### Discussed in https://github.com/FakeFishGames/Barotrauma/discussions/14665

<div type='discussions-op-text'>

<sup>Originally posted by **VeesTM** September 20, 2024</sup>
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

Mission type: Enemy submarine
English version description:
![image](https://github.com/user-attachments/assets/da9af913-acb0-42f9-ab0d-fe72bc2f0e86)

Russian version description:
![image](https://github.com/user-attachments/assets/b1f0b4df-fe5d-46e8-b124-ec89da0397bf)

In Russian version there is a mistake. Written "...уничтожьте есго вместе..." instead "...уничтожьте его вместе...".

### Reproduction steps

1. Switch the game to the Russian language pack
2. Host server
3. Switch game mode to mission
4. Look at description mission Enemy submarine

### Bug prevalence

Just once

### Single player or multiplayer?

Multiplayer hosted from the in-game menu (= using a listen server)

### Version

v1.5.9.2 (Summer Update Hotfix 2)

### Which operating system did you encounter this bug on?

Windows

### Relevant error messages and crash reports

_No response_</div>

**Comment by Regalis11** [comment]
Added to the issues tab in the localization kit

**Comment by Regalis11** [comment]
Fixed in https://github.com/FakeFishGames/Barotrauma-development/commit/8ef1017c1ce425ffb08c5d7137f1b826ebd725df (commit in our private repo), fix coming up in the next update.
