### ISSUE TITLE
[Unstable] Destroy alien terminal achievement broken?

### ISSUE THREAD

**Issue by itchyOwl** [FakeFishGames/Barotrauma#14702]
### Discussed in https://github.com/FakeFishGames/Barotrauma/discussions/14685

<div type='discussions-op-text'>

<sup>Originally posted by **Ek-Videogames** September 22, 2024</sup>
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

Destroying either variant (terminal1 type or terminal2 type) with any smallalienartifact, or alien curio specificially - doesn't trigger the achievement. Even though you said that they should be implemented on the unstable build now, so it's likely bugged somehow.

- Considering the only unstable achievement that seems to be showing up in activity is the cave mantis, its reasonable to assume that none of these other achievements are triggering right either. (such as king of the hull)

### Reproduction steps

![image](https://github.com/user-attachments/assets/45a8cfcf-b48f-4a59-b74b-4d94bad7d2eb)

### Bug prevalence

Just once

### Single player or multiplayer?

Single player

### Version

v1.6.4.0 (unstable)

### Which operating system did you encounter this bug on?

Windows

### Relevant error messages and crash reports

_No response_</div>

**Comment by Regalis11** [comment]
Fixed in https://github.com/FakeFishGames/Barotrauma-development/commit/ca21ae9528809f81881a675f76baae3d005b687c. Couldn't repro the bug with the king of the hull achievement, seemed to unlock with no issues:
![image](https://github.com/user-attachments/assets/8da60499-0e82-48e3-9245-d76a0d4e8f68)

**Comment by Jasontti** [comment]
Tested the fix for ancient novelty achievement. No issues found.
Leaving this on open still if we want to test for the other achievements too.

**Comment by Jasontti** [comment]
Achievements seem to unlock without problems.
Closing this ticket as completed.
