### ISSUE TITLE
[Unstable] Explosion will remove nearby explosives contained in detonators.

### ISSUE THREAD

**Issue by Regalis11** [FakeFishGames/Barotrauma#14703]
### Discussed in https://github.com/FakeFishGames/Barotrauma/discussions/14669

<div type='discussions-op-text'>

<sup>Originally posted by **zhu-rengong** September 21, 2024</sup>
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

As the title said.

https://github.com/user-attachments/assets/8e7dd549-e2ed-4218-962a-092d6595e0cc

### Reproduction steps

1. spawn a compound N and place it inside any type of detonator
2. destroy the detonator by any means

### Bug prevalence

Happens every now and then

### Single player or multiplayer?

Single player

### Version

Other

### -

v1.6.9.0

### Which operating system did you encounter this bug on?

Windows

### Relevant error messages and crash reports

_No response_</div>

**Comment by Jasontti** [comment]
Tested the fix for this. No issues found.
Now detonators only take damage from their own explosion.
Closing ticket.
