### ISSUE TITLE
UnlockAchievements UnexpectedError not handled

### ISSUE THREAD

**Issue by Regalis11** [FakeFishGames/Barotrauma#14706]
### Discussed in https://github.com/FakeFishGames/Barotrauma/discussions/14434

<div type='discussions-op-text'>

<sup>Originally posted by **rekterakathom** August 14, 2024</sup>
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

Multiple messages ``Result "UnexpectedError" was not handled by "UnlockAchievements"`` in console. Seemingly after every mission completed. Some people in the lobby unlocked achievements during the session.

![20240814214430_1](https://github.com/user-attachments/assets/fbc19da2-a5e8-4def-9632-c71404cd1d25)

### Reproduction steps

1. Finish a mission (during a session where somebody unlocked an achievement...?)
2. Open console
3. Check for UnexpectedError messages

### Bug prevalence

Just once

### Single player or multiplayer?

Multiplayer hosted from the in-game menu (= using a listen server)

### Version

v1.5.9.1 (Summer Update Hotfix 2)

### Which operating system did you encounter this bug on?

Windows

### Relevant error messages and crash reports

_No response_</div>

**Comment by Pancake8450** [comment]
Did you ever find a solution for this as I've been getting this bug all of yesterday and today.
For me it started when I subscribed to mods for the first time and played on my solo campaign (Without even having them on) and even after unsubscribing to them and starting multiple new campaigns the problem persists.
(I get the error at the end of each mission and when I launch the game)
