### ISSUE TITLE
[Unstable] Detonator's light is set to cast shadows.

### ISSUE THREAD

**Issue by Regalis11** [FakeFishGames/Barotrauma#14714]
### Discussed in https://github.com/FakeFishGames/Barotrauma/discussions/14710

<div type='discussions-op-text'>

<sup>Originally posted by **Ek-Videogames** September 24, 2024</sup>
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

Detonator & Timed-Detonator's light component is set to shadow casting, unintentional?

### Reproduction steps

![image](https://github.com/user-attachments/assets/a0d77be5-f4b2-453c-8ffa-5b3d3477c2fd)

### Bug prevalence

Happens every time I play

### Single player or multiplayer?

Other

### Version

v1.6.4.0 (unstable)

### Which operating system did you encounter this bug on?

Windows

### Relevant error messages and crash reports

_No response_</div>

**Comment by Jasontti** [comment]
Simple xml fix. No issues found.
Closing ticket.
