### ISSUE TITLE
Different creature behavior in Singleplayer and Multiplayer (Reverse)

### ISSUE THREAD

**Issue by Regalis11** [FakeFishGames/Barotrauma#14721]
### Discussed in https://github.com/FakeFishGames/Barotrauma/discussions/14719

<div type='discussions-op-text'>

<sup>Originally posted by **ubertpendragon** September 25, 2024</sup>
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

Creatures behave differently in SP and MP

Specifically in the case of attacks using `AfterAttack="ReverseUntilCanAttack"`, in singleplayer the creature will properly reverse, in multiplayer it will turn around. 
This might affect other aspects of creature behavior.

Examples with vanilla and modded creature:

https://github.com/user-attachments/assets/e05c7706-fb31-403e-bf18-9b1c3f390dea

https://github.com/user-attachments/assets/cffb4fde-bbdd-40a2-9313-81d1d3edc066

### Reproduction steps

Go in the abyss
Turn on sonar
Spawn latcher in SP
Host a game and do the same in MP

### Bug prevalence

Happens every time I play

### Single player or multiplayer?

Single player

### Version

v1.5.9.2 (Summer Update Hotfix 2)

### Which operating system did you encounter this bug on?

Windows

### Relevant error messages and crash reports

_No response_</div>

**Comment by Rokvach** [comment]
Tested, working correctly. Can be merged and closed.
