### ISSUE TITLE
[Unstable] Additional skill gain once every round

### ISSUE THREAD

**Issue by Regalis11** [FakeFishGames/Barotrauma#14740]
### Discussed in https://github.com/FakeFishGames/Barotrauma/discussions/14737

<div type='discussions-op-text'>

<sup>Originally posted by **HawkinsThe71st** September 26, 2024</sup>
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

If the player character has any bonus skill it will affect regular skill gain once per round.
For instance, a captain with the bonus +10 Helm from the hat will receive +10 Helm skill from piloting the sub instead of just +1.
Another example using The Sailor's Guide book with Picking Up the Slack and wearing a Researcher's Outfit:

https://github.com/user-attachments/assets/ab3b1aba-6a5d-4fea-b0d0-a6058b9241db

In this case the bonus skill gets added to the book's skill gain.

### Reproduction steps

1. Start a multiplayer mission/campaign
2. Use The Sailor's Guide book while wearing skill boosting clothes

### Bug prevalence

Happens regularly

### Single player or multiplayer?

Multiplayer hosted from the in-game menu (= using a listen server)

### Version

Other

### -

v1.6.9.0 (unstable)

### Which operating system did you encounter this bug on?

Windows

### Relevant error messages and crash reports

_No response_</div>

**Comment by Regalis11** [comment]
Fixed in https://github.com/FakeFishGames/Barotrauma-development/commit/66cbdc65a8e4abd1c28b84ef9b96ca204f32503b

**Comment by Jasontti** [comment]
Testing notes: https://github.com/FakeFishGames/Barotrauma-development/pull/5784#issuecomment-2382663766
No issues found
