### ISSUE TITLE
Weird exosuit sprite scaling inconsistency

### ISSUE THREAD

**Issue by dinhtuananhfakefish** [FakeFishGames/Barotrauma#14751]
### Discussed in https://github.com/FakeFishGames/Barotrauma/discussions/14666

<div type='discussions-op-text'>

<sup>Originally posted by **Tripodfish-the-sequal** September 21, 2024</sup>
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

For some reason, the exosuits changes the scale of its arms depending if it's on the ground or being worn. This problem is just visual but has been annoying me for some time. The arms are much smaller when worn making the exosuit look like a massive box with shrimpy arms

### Reproduction steps

Place one exosuit on ground
Wear one exosuit
Cry for hours

### Bug prevalence

Happens every time I play

### Single player or multiplayer?

Happens in both single player and multiplayer

### Version

v1.5.9.2 (Summer Update Hotfix 2)

### Which operating system did you encounter this bug on?

Windows

### Relevant error messages and crash reports

_No response_</div>

**Comment by Regalis11** [comment]
I tried to address this by scaling up the arms of the worn sprite to match the dropped sprite, but that makes holding items look weird (because the arms of the suit become longer than the character's actual arms). I think we should instead address this by scaling down the arms on the dropped sprite to match the worn sprite.

**Comment by dinhtuananhfakefish** [comment]
I will handle this

**Comment by dinhtuananhfakefish** [comment]
Just pushed the new changes to the exosuit dropped sprite

**Comment by Regalis11** [comment]
Merged, closing
