### ISSUE TITLE
Stackable items drop from Fabricator

### ISSUE THREAD

**Issue by Regalis11** [FakeFishGames/Barotrauma#14852]
### Discussed in https://github.com/FakeFishGames/Barotrauma/discussions/14847

<div type='discussions-op-text'>

<sup>Originally posted by **FlashORC** October 17, 2024</sup>
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

Some stackable items drop from Fabricator while crafting multiple instances. Noticed on Fuel Rods, Batteries, Fuel and Oxygen tanks with 100% chance of Excellent or Masterwork quality.
Not reproducible with revolver rounds, shotgun shells, etc.
Both outpost and ship Fabricators.
No errors in console.

### Reproduction steps

1. Start fabrication of 8 Fuel Rods with 100% chance of any quality.
2. First one stays in output slot
3. Other 7 drop on the floor

### Bug prevalence

Happens every time I play

### Single player or multiplayer?

Single player

### Version

v1.6.4.0 (unstable)

### -

v1.6.16.0

### Which operating system did you encounter this bug on?

Windows

### Relevant error messages and crash reports

_No response_</div>

**Comment by MJJJJN11** [comment]
It also happened in V1.6.17.0

**Comment by Regalis11** [comment]
This has now been fixed in out private repo, fix coming up in the next hotfix.
