### ISSUE TITLE
[Unstable] Interacting with fire extinguisher brackets and weapon holders no longer automatically picks up the item

### ISSUE THREAD

**Issue by Regalis11** [FakeFishGames/Barotrauma#14867]
### Discussed in https://github.com/FakeFishGames/Barotrauma/discussions/14864

<div type='discussions-op-text'>

<sup>Originally posted by **A2ur3** October 20, 2024</sup>
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

.

### Reproduction steps

1. interact with fire extinguisher brackets

### Bug prevalence

Just once

### Single player or multiplayer?

Single player

### Version

v1.6.17.0 (unstable)

### Which operating system did you encounter this bug on?

Windows

### Relevant error messages and crash reports

_No response_</div>

**Comment by Regalis11** [comment]
Fixed in https://github.com/FakeFishGames/Barotrauma-development/commit/5d05e780f3934e52e76f07bb5c1b59fa774c8ed1

**Comment by OverwatchVoice** [comment]
[Intended behavior(?)](https://github.com/FakeFishGames/Barotrauma/discussions/14425)

**Comment by Jasontti** [comment]
Testing notes: https://github.com/FakeFishGames/Barotrauma-development/pull/5910#issuecomment-2431828003
No issues found
