### ISSUE TITLE
Toggle Run

### ISSUE THREAD

**Issue by JeroonBosch** [FakeFishGames/Barotrauma#14883]
### Discussed in https://github.com/FakeFishGames/Barotrauma/discussions/5209

<div type='discussions-op-text'>

<sup>Originally posted by **Trigger-1** March 10, 2021</sup>
Let me preface by saying that I love this game. The chaos of playing with fandoms is hilarious, the co-op is fantastic, and the constant content updates keep me coming back.

However, as someone with arthritis, holding the Run button down constantly takes its toll. An option to toggle Run would be a fantastic quality of life upgrade, especially if tapping the button while moving activated Run, and automatically switched back to walking after releasing the movement keys.</div>

---

Design notes: A simple new keybinding (unbound by default) would do the trick. "Toggle run" could be bound to shift (or caps lock, depending on player preference) to replace default shift functionality.

**Comment by Regalis11** [comment]
Implemented in https://github.com/FakeFishGames/Barotrauma-development/pull/5922. Merged, closing.
