### ISSUE TITLE
Bots pick up live grenades

### ISSUE THREAD

**Issue by Regalis11** [FakeFishGames/Barotrauma#14907]
### Discussed in https://github.com/FakeFishGames/Barotrauma/discussions/14898

<div type='discussions-op-text'>

<sup>Originally posted by **4Hangar** October 22, 2024</sup>
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

Bots attempt to clean up dropped live grenades

### Reproduction steps

1. Arm Grenade
2. Drop the Grenade in front of the bot (Don't throw)
3. Laugh as they pick up the grenade and blow themselves up

### Bug prevalence

Just once

### Single player or multiplayer?

Happens in both single player and multiplayer

### Version

v1.6.17.0 (Unto the Breach Update)

### Which operating system did you encounter this bug on?

Windows

### Relevant error messages and crash reports

_No response_</div>

**Comment by Tsunder** [comment]
can you make them throw the grenades back?

**Comment by NilanthAnimosus** [comment]
Tested, fix works, closing as fixed and ready to merge.

as for the comment - that sounds more like a feature suggestion (and im not even sure if its a good idea myself, in terms of balance, enemy AI throwing them back, allied characters, etc. if they would run at grenades that couldn't be thrown in time, running across a submarine to some grenade or even just player thrown grenades towards enemies etc).

Its simpler for the AI to not clean up grenades in the first place at first then see if it makes sense for them to throw grenades back as a feature suggestion that can be discussed in the github discussions. Grenades can be held down and have the timer reduced, and it could make grenades less useful or more annoying if friendly characters got themselves killed more, or enemy characters simply threw them back. given just my thoughts on that, I recommend making a separate feature request instead for discussion while this is hotfixed.
