### ISSUE TITLE
Gravity sphere's base no longer rotates.

### ISSUE THREAD

**Issue by Regalis11** [FakeFishGames/Barotrauma#14906]
### Discussed in https://github.com/FakeFishGames/Barotrauma/discussions/14902

<div type='discussions-op-text'>

<sup>Originally posted by **inmanw** October 23, 2024</sup>
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [X] My issue happened while using mods.

### What happened?

Only the sphere rotates now with seems pointless. I like using them as decorations and can't anymore due to them not being adjustable.

### Reproduction steps

1 Load up sub editor.
2 spawn gravity sphere.
3 adjust rotation.

### Bug prevalence

Happens every time I play

### Single player or multiplayer?

Single player

### Version

v1.6.17.0 (Unto the Breach Update)

### Which operating system did you encounter this bug on?

Windows

### Relevant error messages and crash reports

_No response_</div>

**Comment by Regalis11** [comment]
Fixed in https://github.com/FakeFishGames/Barotrauma-development/commit/80df2418529308839a7cc5fd045eaec2cde38e8b

**Comment by Rokvach** [comment]
Tested, working correctly. Can be merged and closed.

**Comment by Rokvach** [comment]
Tested all the alien devices with a static collider, I was able to rotate all of them.
