### ISSUE TITLE
No spawnpoints for escorted characters (VIP, prisoner, commonner)

### ISSUE THREAD

**Issue by Regalis11** [FakeFishGames/Barotrauma#14909]
### Discussed in https://github.com/FakeFishGames/Barotrauma/discussions/14900

<div type='discussions-op-text'>

<sup>Originally posted by **KougamiYuriko** October 23, 2024</sup>
Every time I restart the game, the NPC will randomly appear at a spawn point, such as standing with the captain. Sometimes it will appear in a room without oxygen and die from lack of oxygen in a few minutes.</div>

**Comment by txzzgckq** [comment]
我也有一样的问题
I have the same problem

**Comment by NilanthAnimosus** [comment]
Closing as fixed and merged.
