### ISSUE TITLE
Kills not counted in Sub Vs Sub Combat

### ISSUE THREAD

**Issue by Regalis11** [FakeFishGames/Barotrauma#14924]
### Discussed in https://github.com/FakeFishGames/Barotrauma/discussions/14918

<div type='discussions-op-text'>

<sup>Originally posted by **4-S-H** October 23, 2024</sup>
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

Kills not counted in Sub Vs Sub Combat

### Reproduction steps

- Start a Sub vs Sub PVP round
- Shoot someone until they fall unconscious
- They die
- Kill and death not counted at the end

### Bug prevalence

Happens every time I play

### Single player or multiplayer?

Multiplayer hosted from the in-game menu (= using a listen server)

### Version

v1.6.17.0 (Unto the Breach Update)

### Which operating system did you encounter this bug on?

Windows

### Relevant error messages and crash reports

_No response_</div>

**Comment by Regalis11** [comment]
Fixed in https://github.com/FakeFishGames/Barotrauma-development/commit/43a595a9baf4f817ce432ced49bb3b6430c78b38

**Comment by Jasontti** [comment]
Testing notes: https://github.com/FakeFishGames/Barotrauma-development/pull/5940#issuecomment-2437222346
No issues found
