### ISSUE TITLE
Reduce required repair count of Machine Maniac talent

### ISSUE THREAD

**Issue by JeroonBosch** [FakeFishGames/Barotrauma#14949]
### Discussed in https://github.com/FakeFishGames/Barotrauma/discussions/14760

<div type='discussions-op-text'>

<sup>Originally posted by **BiffW** October  2, 2024</sup>
Through my experiences, it usually takes much more time to fully unlock this talent than an Engineer fully unlock Junction Junkie. As an early-game talent, it's bonus should not be delayed for so long. I suggest required count should be reduced by 40%~60%.</div>

**Comment by Regalis11** [comment]
Fixed, closing
