### ISSUE TITLE
[Unstable] Handheld Sonar & Artifact Container lights stuck on in subeditor

### ISSUE THREAD

**Issue by Regalis11** [FakeFishGames/Barotrauma#14948]
### Discussed in https://github.com/FakeFishGames/Barotrauma/discussions/14830

<div type='discussions-op-text'>

<sup>Originally posted by **Ek-Videogames** October 15, 2024</sup>
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

Handheld sonar & Artifact container now draw a light by default, and even when inside a container.

This causes unnecessary light rendering, especially with many manually-placed handheld sonars in a diving gear locker for example.

### Reproduction steps

- Artifact containers can be fixed by turning off their light component manually.

- Handheld sonars however cannot, and will for some reason *magically re-enable their light* upon exiting and reloading the save.

![image](https://github.com/user-attachments/assets/cb39baba-a6ef-4c42-a821-3b8ebc64a8f6)

### Bug prevalence

Happens every time I play

### Single player or multiplayer?

Happens outside single player or multiplayer game modes (e.g. game launches on startup, something broken in the main menu)

### Version

v1.6.4.0 (unstable)

### Which operating system did you encounter this bug on?

Windows

### Relevant error messages and crash reports

_No response_</div>

**Comment by Regalis11** [comment]
Fixed in https://github.com/FakeFishGames/Barotrauma-development/commit/3dbea0ddeb225a91598eec4ebd6cb38869366031

**Comment by michael-fakefish** [comment]
Testing notes: https://github.com/FakeFishGames/Barotrauma-development/pull/5949#issuecomment-2488328144
Closing as completed.
