### ISSUE TITLE
Server stun resistance setting does nothing

### ISSUE THREAD

**Issue by Regalis11** [FakeFishGames/Barotrauma#14978]
### Discussed in https://github.com/FakeFishGames/Barotrauma/discussions/14957

<div type='discussions-op-text'>

<sup>Originally posted by **Harry-Wang-dotcom** October 26, 2024</sup>
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

I set server stun resistance setting to 100%, can stun everybody the same time as I used to, and get stunned myself the same time as I used to.

### Reproduction steps

1. start multiplier server
2. set server setting to 100% stun resistance
3. set server setting to spawn some bots if you want
4. start game
5. throw stun grenade on self, see if works
6. use stun baton on a bot, see if works
7. shoot shotgun rubber shells on a bot, see if works

### Bug prevalence

Happens every time I play

### Single player or multiplayer?

Multiplayer hosted from the in-game menu (= using a listen server)

### Version

v1.6.17.0 (Unto the Breach Update)

### Which operating system did you encounter this bug on?

Linux

### Relevant error messages and crash reports

_No response_</div>

**Comment by Regalis11** [comment]
Fixed in https://github.com/FakeFishGames/Barotrauma-development/commit/4f94ca3fe8ca37ac8785b4c0e47494d1c87a0107

**Comment by Jasontti** [comment]
Tested with 0%, 50% and 100% stun reduction.

No issues found
