### ISSUE TITLE
PvP outposts spawn clipped into terrain (often)

### ISSUE THREAD

**Issue by Regalis11** [FakeFishGames/Barotrauma#14980]
### Discussed in https://github.com/FakeFishGames/Barotrauma/discussions/14955

<div type='discussions-op-text'>

<sup>Originally posted by **girlyguppy** October 25, 2024</sup>
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

![image](https://github.com/user-attachments/assets/3ee12ebc-a9a8-45d3-a908-00bb2b8f10ae)
![image](https://github.com/user-attachments/assets/6cf264c2-f13b-42d3-9399-70488e8af641)

It makes view movement and mouse movement all jittery, messes up spectator mode (massive shaking and teleporting), and if you have any moving parts such as elevators/shuttles, screws that up too

### Reproduction steps

1. start outpost deathmatch pvp with a big outpost
2. repeat until eventually it spawns inside terrain
3. may not be an issue with the TWO vanilla outposts, but certainly causes issues with custom ones

### Bug prevalence

Happens regularly

### Single player or multiplayer?

Multiplayer hosted from the in-game menu (= using a listen server)

### Version

v1.6.17.0 (Unto the Breach Update)

### Which operating system did you encounter this bug on?

Windows

### Relevant error messages and crash reports

_No response_</div>

**Comment by Regalis11** [comment]
Fixed in https://github.com/FakeFishGames/Barotrauma-development/commit/01a84af95ac9abf6ef98c1224f06a113a7ecefcf

**Comment by Jasontti** [comment]
Tested.
No issues found.
