### ISSUE TITLE
infinite levels due to mindwipe

### ISSUE THREAD

**Issue by JeroonBosch** [FakeFishGames/Barotrauma#14992]
### Discussed in https://github.com/FakeFishGames/Barotrauma/discussions/14988

<div type='discussions-op-text'>

<sup>Originally posted by **Banditism** October 29, 2024</sup>
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

if you use a mindwipe and a captain with atleast 8 skill points you can make a net neutral of skill points but positive for the rest of the crew, already stupid enough. after doing this for awhile i realized if you dont spend all your skills and leave the last one out before wiping again you actually dont lose a single skill.... so basically you can use a mindwipe and give everyone a free level including yourself..... this is really op and insanely hilarious

### Reproduction steps

captain with 8 skill points, tech into family
dont spend last point and mindwipe
captain with 9 skill points tech into family 
dont spend last point and mindwipe
captain with 10 skill points tech into family 
dont spend last point and mindwipe
captain with 11 skill points tech into family 
dont spend last point and mindwipe
captain with 12 skill points tech into family 
dont spend last point and mindwipe
captain with 13 skill points tech into family 
dont spend last point and mindwipe

you get the idea....

### Bug prevalence

Happens every time I play

### Single player or multiplayer?

Happens in both single player and multiplayer

### Version

v1.6.18.1 (Unto the Breach Update)

### Which operating system did you encounter this bug on?

Windows

### Relevant error messages and crash reports

_No response_</div>

**Comment by JeroonBosch** [comment]
I think this ticket has two parts to it:

> after doing this for awhile i realized if you dont spend all your skills and leave the last one out before wiping again you actually dont lose a single skill....

First is a bug, where if you don't spend all your talent points, you don't lose a single talent point.

Second is a design problem where mindwipe should probably penalize the user more on every consecutive use (which was it's original design but seemed more complex / perhaps overly harsh).

**Comment by Regalis11** [comment]
Addressed in https://github.com/FakeFishGames/Barotrauma-development/commit/b015f00444924caf580dbc284331d1ead09f3a89
