### ISSUE TITLE
Piezo Crystals facing the wrong way

### ISSUE THREAD

**Issue by Regalis11** [FakeFishGames/Barotrauma#15019]
### Discussed in https://github.com/FakeFishGames/Barotrauma/discussions/15012

<div type='discussions-op-text'>

<sup>Originally posted by **GracedTarkov** October 31, 2024</sup>
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

Piezo Crystals always face upwards instead of outwards from the surface they are sticking to.

![Screenshot 2024-10-31 120538](https://github.com/user-attachments/assets/929940d9-a54a-49f5-a079-0e95a6caa11c)

### Reproduction steps

Host a multiplayer or start a singleplayer game, go to the Great Sea, look for Piezo Crystals.

### Bug prevalence

Happens every time I play

### Single player or multiplayer?

Happens in both single player and multiplayer

### Version

v1.6.19.1 (Unto the Breach Update Hotfix 2)

### Which operating system did you encounter this bug on?

Windows

### Relevant error messages and crash reports

_No response_</div>

**Comment by Jasontti** [comment]
Testing notes: https://github.com/FakeFishGames/Barotrauma-development/pull/5992#issuecomment-2482994906
Closing ticket as completed
