### ISSUE TITLE
Multi-Tool doesn't function as a wrench properly

### ISSUE THREAD

**Issue by JeroonBosch** [FakeFishGames/Barotrauma#15119]
### Discussed in https://github.com/FakeFishGames/Barotrauma/discussions/15050

<div type='discussions-op-text'>

<sup>Originally posted by **mijukamidami22** November  3, 2024</sup>
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

When using the multitool anything that requires a wrench to be done (not repaired) will not be done.
The most clear example is detaching anything that was placed, such as buttons or components.
I think an easy fix is to add a toggle to the multitool for when it will act as a wrench and when as a screwdriver, perhaps with m1 and m2? or other keys as well.
I do want to reiterate repairing works fine, i have tested it on every part of the ship including but not limited to:
Gun loaders, pumps, turbine, fabricator, deconstructor, medical fabricator, electrical boxes, battery chargers, reactor, oxygen generator, supercapacitors.

### Reproduction steps

I Start any campaign or go into the sub editor,
II Spawn in a button or any component and the multi-tool
III Place said component or button and try to remove it with the multi tool

### Bug prevalence

Happens every time I play

### Single player or multiplayer?

Happens in both single player and multiplayer

### Version

v1.6.19.1 (Unto the Breach Update Hotfix 2)

### Which operating system did you encounter this bug on?

Windows

### Relevant error messages and crash reports

_No response_</div>

**Comment by Regalis11** [comment]
Merged, closing
