### ISSUE TITLE
Character teleporting out of the ship while driving

### ISSUE THREAD

**Issue by Regalis11** [FakeFishGames/Barotrauma#15138]
### Discussed in https://github.com/FakeFishGames/Barotrauma/discussions/14118

<div type='discussions-op-text'>

<sup>Originally posted by **Vykn** June 11, 2024</sup>
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

Occasionally, while driving, the character will briefly teleport out of the sub, in the same way that would sometimes happen when moving between hulls. It might not only occur while driving, but since I spent 90% of my recent campaign driving, it's the only time I remember experiencing it. It happened maybe once every 10-20 minutes or so.

I've only ever experienced this in this Unstable, but I've heard it has happened in previous versions too. Perhaps it only happens when hosting from one's own computer.

https://github.com/FakeFishGames/Barotrauma/assets/37850646/b9b94743-8cae-4244-9039-e5fe4fe05694

### Reproduction steps

1. Load unstable campaign (you can use the save file I uploaded [here](https://github.com/FakeFishGames/Barotrauma/discussions/14117) if you want
2. Drive around (try to go fast? I think it might have happened more often as I drove faster)
3. Observe your character going to a different dimension sometimes

### Bug prevalence

Happens regularly

### Single player or multiplayer?

Multiplayer (Hosted from in-game menu)

### Version

v1.5.4.0 (unstable)</div>

**Comment by Regalis11** [comment]
Fixed in https://github.com/FakeFishGames/Barotrauma-development/commit/48d82a57f32e9f48bd6ed3353e1888b6397ce994

**Comment by Jasontti** [comment]
Testing notes: https://github.com/FakeFishGames/Barotrauma-development/pull/6013#issuecomment-2476253041
Closing ticket as completed
