### ISSUE TITLE
Can't join the round - game keeps downloading save file from server

### ISSUE THREAD

**Issue by Regalis11** [FakeFishGames/Barotrauma#15143]
### Discussed in https://github.com/FakeFishGames/Barotrauma/discussions/14995

<div type='discussions-op-text'>

<sup>Originally posted by **A2ur3** October 30, 2024</sup>
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [X] My issue happened while using mods.

### What happened?

https://github.com/user-attachments/assets/2a2a71e3-79a1-4085-a04b-be1dc3e55624

It happens regularly when we join the heavy modded dedicated server
player numbers, mod numbers, network connection can contribute to this issue

### Reproduction steps

1. start a multiplayer campaign
2. let other players connect the server?

### Bug prevalence

Happens regularly

### Single player or multiplayer?

Multiplayer hosted using a dedicated server

### Version

v1.6.18.1 (Unto the Breach Update)

### Which operating system did you encounter this bug on?

Windows

### Relevant error messages and crash reports

```shell
Error in ClientRead. Owned submarine index was out of bounds (list of server submarines is empty).
```
</div>

**Comment by Jasontti** [comment]
Testing notes: https://github.com/FakeFishGames/Barotrauma-development/pull/6014#issuecomment-2485020877
No issues found, closing ticket as resolved.
