### ISSUE TITLE
Nested/child genetic material can be sold

### ISSUE THREAD

**Issue by Regalis11** [FakeFishGames/Barotrauma#15147]
### Discussed in https://github.com/FakeFishGames/Barotrauma/discussions/15146

<div type='discussions-op-text'>

<sup>Originally posted by **A2ur3** November 14, 2024</sup>
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

you can sell material inside combined genes

### Reproduction steps

1. get a combined genetic material
2. go to merchant and sell material inside

### Bug prevalence

Happens every time I play

### Single player or multiplayer?

Happens in both single player and multiplayer

### Version

v1.6.19.1 (Unto the Breach Update Hotfix 2)

### Which operating system did you encounter this bug on?

Windows

### Relevant error messages and crash reports

_No response_</div>

**Comment by DrBruhman** [comment]
merchant is so strong he can separate molecular bonds by hand

**Comment by Jasontti** [comment]
Testing notes: https://github.com/FakeFishGames/Barotrauma-development/pull/6015#issuecomment-2505978478
No issues found, closing ticket as completed
