### ISSUE TITLE
Server Ignores "HerpesThreshold" Setting

### ISSUE THREAD

**Issue by Regalis11** [FakeFishGames/Barotrauma#15181]
### Discussed in https://github.com/FakeFishGames/Barotrauma/discussions/15178

<div type='discussions-op-text'>

<sup>Originally posted by **CaptainDickard** November 17, 2024</sup>
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

When using custom Karma settings the "Space herpes threshold" is being ignored. Despite setting the threshold to 1 karma, players are receiving space herpes any time their karma is reduced below 40.

In trying to fix this issue, I deleted all files under common/barotrauma and reinstalled the game, validated files.

Karma settings from file (I did not manually edit this file)

name="Custom"
    ResetKarmaBetweenRounds="False"
    KarmaDecay="0.01"
    KarmaDecayThreshold="50"
    KarmaIncrease="0"
    KarmaIncreaseThreshold="50"
    StructureRepairKarmaIncrease="0.01"
    StructureDamageKarmaDecrease="1"
    MaxStructureDamageKarmaDecreasePerSecond="15"
    ItemRepairKarmaIncrease="0.01"
    ReactorOverheatKarmaDecrease="0.5"
    ReactorMeltdownKarmaDecrease="100"
    DamageEnemyKarmaIncrease="0"
    HealFriendlyKarmaIncrease="0.01"
    DamageFriendlyKarmaDecrease="1"
    StunFriendlyKarmaDecrease="1"
    StunFriendlyKarmaDecreaseThreshold="10"
    ExtinguishFireKarmaIncrease="0"
    DangerousItemStealKarmaDecrease="30"
    DangerousItemStealBots="True"
    BallastFloraKarmaIncrease="0.01"
    AllowedWireDisconnectionsPerMinute="0"
    WireDisconnectionKarmaDecrease="20"
    SteerSubKarmaIncrease="0.15"
    SpamFilterKarmaDecrease="1"
    HerpesThreshold="1"
    KickBanThreshold="1"
    KicksBeforeBan="1"
    KarmaNotificationInterval="15"
    AllowedRetaliationTime="120"
    DangerousItemContainKarmaDecrease="30"
    IsDangerousItemContainKarmaDecreaseIncremental="True"
    MaxDangerousItemContainKarmaDecrease="100"
    
    
### Reproduction steps

1. Start a multiplayer campaign.
2. Use my custom karma settings from the above section.
3. Use F3 to input the command "setkarma [playername] 39"
4. Observe the player getting herpes despite the threshold being 1.

### Bug prevalence

Happens every time I play

### Single player or multiplayer?

Multiplayer hosted from the in-game menu (= using a listen server)

### Version

v1.6.19.1 (Unto the Breach Update Hotfix 2)

### Which operating system did you encounter this bug on?

Windows

### Relevant error messages and crash reports

_No response_</div>

**Comment by Regalis11** [comment]
Fixed in https://github.com/FakeFishGames/Barotrauma-development/commit/8b978902117d42fc112a1b73f70d0b8da9bb77dd

**Comment by CaptainDickard** [comment]
You're awesome.
