### ISSUE TITLE
"At Wit's End" event issues

### ISSUE THREAD

**Issue by Regalis11** [FakeFishGames/Barotrauma#15186]
### Discussed in https://github.com/FakeFishGames/Barotrauma/discussions/15175

<div type='discussions-op-text'>

<sup>Originally posted by **A2ur3** November 17, 2024</sup>
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

"At Wit's End" event has two issues
1. you need to press E twice to start the conversation
2. artie keeps following you if you decline him

### Reproduction steps

1. triggerevent atwitsend
2. decline artie
3. artie keeps following you

### Bug prevalence

Just once

### Single player or multiplayer?

Happens in both single player and multiplayer

### Version

v1.6.19.1 (Unto the Breach Update Hotfix 2)

### Which operating system did you encounter this bug on?

Windows

### Relevant error messages and crash reports

_No response_</div>

**Comment by Regalis11** [comment]
Addressed in https://github.com/FakeFishGames/Barotrauma-development/commit/8474e8cd470ebe9e4bea4bd120cea567e16b41ed and https://github.com/FakeFishGames/Barotrauma-development/commit/cd310e3c6565407aeeb55bf674f6d0bff432a96f

**Comment by Jasontti** [comment]
Testing notes: https://github.com/FakeFishGames/Barotrauma-development/pull/6028#issuecomment-2503701059
No issues found, closing issue as completed
