### ISSUE TITLE
Secretly Tainted Genes

### ISSUE THREAD

**Issue by Regalis11** [FakeFishGames/Barotrauma#15223]
### Discussed in https://github.com/FakeFishGames/Barotrauma/discussions/15213

<div type='discussions-op-text'>

<sup>Originally posted by **Rat-Crusher** November 21, 2024</sup>
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

When you take a tainted gene and combine it with a pure, untainted gene that is not of the same variety (For instance: Tainted Crawler, and Pure Hammerhead), the output will appear as if it is not tainted. However, the gene is tainted still. Had issues purifying the secretly tainted gene as well afterwards.

### Reproduction steps

1: Acquire untainted gene, and a tainted gene of a different variety.
2: Combine them
3: Attempt to purify by adding pure genes into the gene which appears to be pure (despite it not being pure)

### Bug prevalence

Just once

### Single player or multiplayer?

Single player

### Version

v1.6.19.1 (Unto the Breach Update Hotfix 2)

### Which operating system did you encounter this bug on?

Windows

### Relevant error messages and crash reports

_No response_</div>

**Comment by Jasontti** [comment]
Testing notes: https://github.com/FakeFishGames/Barotrauma-development/pull/6049#issuecomment-2500525407
Tested fix commit: https://github.com/FakeFishGames/Barotrauma-development/commit/ef239ba6c1342ebb371fb825f2463405568701cd

No issues found when combining tainted genes with clean ones.
Closing ticket as completed.
