### ISSUE TITLE
Character variant that inherits creature in another mod will try to find its sprite from wrong mod

### ISSUE THREAD

**Issue by Regalis11** [FakeFishGames/Barotrauma#15243]
### Discussed in https://github.com/FakeFishGames/Barotrauma/discussions/15235

<div type='discussions-op-text'>

<sup>Originally posted by **A2ur3** November 23, 2024</sup>
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [X] My issue happened while using mods.

### What happened?

mod A creates a new character which sprite path uses %ModDir% 
mod B creates a variant of that character
game tries to find sprite in mod B instead of mod A

### Reproduction steps

1. download mod "Chimera Remake"
2. try to create a variant of Chimera_head in a separate mod

### Bug prevalence

Just once

### Single player or multiplayer?

Single player

### Version

v1.6.19.1 (Unto the Breach Update Hotfix 2)

### Which operating system did you encounter this bug on?

Windows

### Relevant error messages and crash reports

_No response_</div>

**Comment by itchyOwl** [comment]
Tested with this definition set in a custom mod:
<Charactervariant inherit="Chimera_head" speciesname="CustomChimeraHead">
</Charactervariant>

Before the fix throws this error:
![image](https://github.com/user-attachments/assets/4c3b0b76-d3e5-45ea-ae2d-577ef3f9fa47)

After the fix loads the character correctly.
