### ISSUE TITLE
Reopened: Inconsistent display of color tagged text.

### ISSUE THREAD

**Issue by Jasontti** [FakeFishGames/Barotrauma#15250]
## Original ticket:
<div type='discussions-op-text'>

<sup>Originally posted by **lIllIIlI** July 27, 2024</sup>
### What happened?

Some GUI displays proper color for items tagged with a specific color via translation xml, i.e: 
  <entityname.Patchouli_gear>‖color:120,75,100,255‖帕秋莉装束‖color:end‖</entityname.Patchouli_gear>
  <entityname.Patchouli_gear>‖color:120,75,100,255‖Patchouli's Outfit‖color:end‖</entityname.Patchouli_gear>
Appears correctly in tooltips, but not in crafting / shop menus.
![Barotrauma_HewB5xlmMx](https://github.com/user-attachments/assets/a713ef62-e227-40c3-aa01-c715f537e039)

Similarly, chat text popups do not adhere to the color tags while the chat window does.
![image](https://github.com/user-attachments/assets/ca7dc18a-7ef9-45a8-acac-70ab51aeccac)
![image](https://github.com/user-attachments/assets/7eacd612-1aa2-4089-a2d2-45e1dcdceff0)

I'd like the colors to be supported in all types of texts.

### Reproduction steps

1. Use localization text file to give item names color using ||color:###,###,###,###||<Item Name>||color:end||
2. color appears properly in tool tips, chat window, fabrication tooltip
3. color does not appear but the code itself appears in chat bubbbles and fab/shop menus

</div>

## Missed in testing

Sub editors menu doesn't properly show color tagged items

![image](https://github.com/user-attachments/assets/8b418665-9037-4cc2-8c64-1f65b821e822)

Steps:
Rename revolver in EnglishVanilla.xml
`<entityname.revolver>‖color:120,75,100,255‖revolver‖color:end‖</entityname.revolver>`

**Comment by Regalis11** [comment]
Fixed in https://github.com/FakeFishGames/Barotrauma-development/commit/f678dcbeba0f93a85a4bfdbe4136b444dfded464
