### ISSUE TITLE
Bug Report: Can't reach [name]!

### ISSUE THREAD

**Issue by Regalis11** [FakeFishGames/Barotrauma#15268]
### Discussed in https://github.com/FakeFishGames/Barotrauma/discussions/15266

<div type='discussions-op-text'>

<sup>Originally posted by **lewri** November 27, 2024</sup>
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

I noticed while having 3 people follow me around in single player the medic was unable to reach one. However, instead of using their name the radio text used the placeholder `[name]`. This did occur multiple times during 30 seconds.

![image](https://github.com/user-attachments/assets/19f0afd0-60ee-49dc-a35d-77bafc6f95d5)

### Reproduction steps

1. Have 3 people follow you in the sub
2. Somehow cause injuries to the party
3. Wait for the medic. Though I think mine occurred while moving around a bit still.

### Bug prevalence

Just once

### Single player or multiplayer?

Single player

### Version

v1.6.19.1 (Unto the Breach Update Hotfix 2)

### Which operating system did you encounter this bug on?

Windows

### Relevant error messages and crash reports

_No response_</div>

**Comment by Regalis11** [comment]
Fixed in https://github.com/FakeFishGames/Barotrauma-development/commit/82ca6967fbc7eccdb6b4f28728f32ea2070d7d59

**Comment by michael-fakefish** [comment]
Can be merged

Tested in fix/bot-dialog-'cant-reach-name' fd4344b6

Tested by trapping a medical doctor in a room with no exit, injured all crew members and had 3-5 crew members follow me around while ordering the medical doctor to heal and rescue. The names of bots were correctly displayed in the "Can't get to …!" messages.
