### ISSUE TITLE
Can't fabricate things with bot talents in MP

### ISSUE THREAD

**Issue by Regalis11** [FakeFishGames/Barotrauma#15278]
- [x] I have searched the issue tracker to check if the issue has already been reported.
- [ ] I'm using mods.

**Description**
Everyone should be able to fabricate things using a recipe unlocked by a bot, but this doesn't work properly in MP. A client sees the recipe being unlocked on the fabricator and is able to start the fabrication, but nothing happens.

**Steps To Reproduce**
1. Give a bot a talent that unlocks a recipe in MP (e.g. "Robotics")
2. Attempt to fabricate the item unlocked by the talent

**Version**
v1.7

**Comment by Regalis11** [comment]
Fixed in https://github.com/FakeFishGames/Barotrauma-development/commit/cbbf8a1258f78d1c1fdd6669e1c4f8a7ba4c9871

**Comment by Jasontti** [comment]
Testing notes: https://github.com/FakeFishGames/Barotrauma-development/pull/6092#issuecomment-2516677240
Closing as completed
