### ISSUE TITLE
Rapidly gaining on damage effects genes by pulling out gene splicer

### ISSUE THREAD

**Issue by Regalis11** [FakeFishGames/Barotrauma#15273]
### Discussed in https://github.com/FakeFishGames/Barotrauma/discussions/15270

<div type='discussions-op-text'>

<sup>Originally posted by **Xeavas** November 28, 2024</sup>
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

You can rapidly gain vigor/hyperactivity by inducing multiple instances of organ damage if you have multiple gene effects. 
ie pulling out an advanced gene splicer with 4 gene effects with skitter genes give 240 units of hyperactivity

### Reproduction steps

1. Have 2 Compound gene with at least one containing mollosc/skitter
2. Put them all in an advanced gene splicer
3. Equip into gene slot and rip gene splicer out

### Bug prevalence

Happens every time I play

### Single player or multiplayer?

Single player

### Version

v1.7.0.1 (Unstable)

### Which operating system did you encounter this bug on?

Windows

### Relevant error messages and crash reports

_No response_</div>

**Comment by Regalis11** [comment]
Fixed in https://github.com/FakeFishGames/Barotrauma-development/commit/022548c1e5c2f7637cdb178a1c2398398d6fd6ec

**Comment by Jasontti** [comment]
Last testing notes: https://github.com/FakeFishGames/Barotrauma-development/pull/6086#issuecomment-2530672587
No issues found, closing ticket as completed
