### ISSUE TITLE
Camaraderie affliction icon flickers in multiplayer after a crewmember has died

### ISSUE THREAD

**Issue by Regalis11** [FakeFishGames/Barotrauma#15277]
- [x] I have searched the issue tracker to check if the issue has already been reported.
- [ ] I'm using mods.

**Description**
Camaraderie (which gives buffs to the crew as long as no-one has died) affliction icon flickers in multiplayer after a crewmember has died

**Steps To Reproduce**
1. Give someone the Camaraderie talent in MP.
2. Kill some other character
3. The affliction icon should disappear, but keeps reappearing every second or so.

**Version**
v1.7

**Comment by Regalis11** [comment]
Fixed in https://github.com/FakeFishGames/Barotrauma-development/commit/cbbf8a1258f78d1c1fdd6669e1c4f8a7ba4c9871

**Comment by Jasontti** [comment]
Testing notes: https://github.com/FakeFishGames/Barotrauma-development/pull/6092#issuecomment-2516677240
Closing as completed
