### ISSUE TITLE
Attack damagemultiplier of character variant does not work

### ISSUE THREAD

**Issue by itchyOwl** [FakeFishGames/Barotrauma#15327]
### Discussed in https://github.com/FakeFishGames/Barotrauma/discussions/15321

<div type='discussions-op-text'>

<sup>Originally posted by **A2ur3** December  9, 2024</sup>
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

Mudraptor_unarmored WaterAttack 30% bitewounds
```xml
<attack context="Outside" cooldown="3" afterattack="FollowThrough" range="100" damagerange="100" duration="0.3" structuredamage="60" itemdamage="40" structuresoundtype="StructureSlash" targetforce="0" severlimbsprobability="0" torque="0" force="20" applyforceonlimbs="0, 2, 3, 4, 5" targettype="Any" hitdetectiontype="Distance" stun="0" onlyhumans="False" applyforcesonlyonce="True" targetimpulse="40" targetimpulseworld="0,40" targetforceworld="0,0" stickchance="0" priority="2" secondarycooldown="0" cooldownrandomfactor="0.25" reverse="False" targetlimbtype="None" afterattackdelay="0" retreat="False" rootforceworldstart="0,0" rootforceworldmiddle="0,0" rootforceworldend="0,0" roottransitioneasing="Linear" fullspeedafterattack="False" emitstructuredamageparticles="True" penetration="0" levelwalldamage="30" ranged="False" avoidfriendlyfire="False" requiredangle="20" submarineimpactmultiplier="1" blink="False">
  <Affliction identifier="bitewounds" strength="30" probability="1" />
  <Affliction identifier="bleeding" strength="20" probability="0.5" />
  <Affliction identifier="stun" strength="0.5" probability="1" />
</attack>
```
Control Mudraptor_unarmored outside and attack human head 22.5% bitewounds (Human head has default 25% bitewounds resistance)
```xml
<Charactervariant inherit="Mudraptor_unarmored" speciesname="Mudraptor_hatchling">
  <attack damagemultiplier="0.25" rangemultiplier="0.5" impactmultiplier="0.25" />
</Charactervariant>
```
Control Mudraptor_hatchling outside and attack human head still 22.5% bitewounds 

### Reproduction steps

.

### Bug prevalence

Just once

### Single player or multiplayer?

Single player

### Version

v1.6.19.1 (Unto the Breach Update Hotfix 2)

### Which operating system did you encounter this bug on?

Windows

### Relevant error messages and crash reports

_No response_</div>

**Comment by Jasontti** [comment]
Testing notes: https://github.com/FakeFishGames/Barotrauma-development/pull/6140#issuecomment-2531441913
No issues found, closing ticket as completed.
