### ISSUE TITLE
Brain dead characters can spawn duffel bag and cause item duplication

### ISSUE THREAD

**Issue by Regalis11** [FakeFishGames/Barotrauma#15343]
### Discussed in https://github.com/FakeFishGames/Barotrauma/discussions/15341

<div type='discussions-op-text'>

<sup>Originally posted by **A2ur3** December 11, 2024</sup>
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

I heard the issue from other players
sometimes all items of brain dead character will be duplicated and put inside duffel bag

### Reproduction steps

.

### Bug prevalence

Happens every now and then

### Single player or multiplayer?

Multiplayer hosted from the in-game menu (= using a listen server)

### Version

v1.6.19.1 (Unto the Breach Update Hotfix 2)

### Which operating system did you encounter this bug on?

Windows

### Relevant error messages and crash reports

_No response_</div>

**Comment by Regalis11** [comment]
Fixed in https://github.com/FakeFishGames/Barotrauma-development/commit/314e93b1ac3e2e98edcd73a8917dc16aba4c317b

**Comment by michael-fakefish** [comment]
Tested in fix/item-duplication-through-duffelbagged-braindead-players 314e93b1ac3e2e98edcd73a8917dc16aba4c317b

Tested by using multiclienttestmode with local dedicated server and disconnecting a character during a round, then joining after returning in the outpost.

The duffel bag was correctly no longer available for disconnect deaths, and correctly available for other (for example drowning) deaths, but **respawning at the outpost caused the items to be lost**, as the inventory was reset to the default one. When joining during the same round, the player respawned immediately with the items. A check was done with a granted talent to confirm that the character that lost the items in the outpost respawn scenario was the same as before disconnecting.

Moving back to "todo".

**Comment by Regalis11** [comment]
Merged, closing
