### ISSUE TITLE
Door sound effect muffled incorrectly

### ISSUE THREAD

**Issue by thegrb93** [FakeFishGames/Barotrauma#2476]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Opening a door from certain sides will muffle the sound effect when played from one side but not the other. This might be fault of the sub creator but not sure how it works exactly.

**Steps To Reproduce**
Once I get a video I'll update this with it.

**Version**
Windows 0.9.7.1

**Comment by Regalis11** [comment]
I unfortunately could not find a way to reproduce this. I'm suspecting it happens with some kind of unconventional hull/door setups. If you or anyone else finds a way to get this to occur, or a submarine where it happens consistently, please let us know!

**Comment by thegrb93** [comment]
Sorry, meant to get that info sooner.
Here's an easy to reproduce case of it I found using this ship: https://steamcommunity.com/sharedfiles/filedetails/?id=1768666616 .

I just started a dedicated server and it happens without anything special needed. https://streamable.com/a1px2

**Comment by Regalis11** [comment]
Repro steps and an explanation of the issue in https://github.com/FakeFishGames/Barotrauma/pull/13246
