### ISSUE TITLE
Numeric keys on mac keyboard in azerty not detected

### ISSUE THREAD

**Issue by razmigsarkissian** [FakeFishGames/Barotrauma#3133]
If on AZERTY keyboards on Mac, the numeric keys are not detected

To be able to use those shortcuts (the inventory ones), I need to switch my keyboard setting to a qwerty keyboard.

**Comment by Regalis11** [comment]
Addressed in https://github.com/FakeFishGames/Barotrauma-development/pull/4783 (PR in our private repo)
