### ISSUE TITLE
No audio output over usb headset

### ISSUE THREAD

**Issue by Otsdarva68** [FakeFishGames/Barotrauma#3865]
- [ X] I have searched the issue tracker to check if the issue has already been reported. This same issue was previously reported in https://github.com/Regalis11/Barotrauma/issues/3101

The issue had no troubleshooting steps but was closed, so I am opening a new issue.

**Description**
Barotrauma does not send audio to my usb headset. Works with the aux speakers just fine.

**Steps To Reproduce**
Using an amazon basics pro usb gaming headset, plugged into any usb port. All other audio immediately defaults to the headset, but there is no audio from barotrauma recognized in volume mixer when headset is selected.

**Version**
v0.10.4.0, running Windows

**Comment by Regalis11** [comment]
Closing in favor of the new "general audio device issues" ticket: https://github.com/FakeFishGames/Barotrauma/issues/13430
