### ISSUE TITLE
Issue when starting a campaign with friends (Source array was not long enough)

### ISSUE THREAD

**Issue by Sadmongoose** [FakeFishGames/Barotrauma#4091]
So when starting a Multiplayer game with my friends, one of them has the same issue that happens everytime. When we hit start for the campaign on the lobby screen he is instantly kick and presented with an error.

Error : Error while reading a message from the server. (Source array was not long enough.Check the Source index, length, and the arrays lower bounds. (Parameter 'source array') Void Copy System.Array, Int32, System.Array, Int32, Int32, boolean.))

The console opens up with more info.
Strangely when we start a multiplayer mission he loads in fine. When he is host and starts a campaign we are kicked and presented with this message instead, and he loads in with no issues.- [ ] I have searched the issue tracker to check if the issue has already been reported. We were starting a vanilla Campaign and the issues only occurred.

If there is more info I can provide let me know. Thank you!

**Comment by Regalis11** [comment]
Would it be possible to provide us a screenshot of the full error message in the console? Thanks and sorry for the trouble!

**Comment by Sadmongoose** [comment]
![20201003173535_1](https://user-images.githubusercontent.com/72960319/96321337-ac200980-0fda-11eb-9141-b9bdda8a4ac9.jpg)


Hopefully that worked.

**Comment by Sadmongoose** [comment]
I should have posted that in the first place, my bad.

**Comment by WharkOddity** [comment]
I have a similar problem, my friends/people are **disconnected from the server** when **we begin a mission from an outpost in the campaign**, it's like the server won't let them load the whole "current game/round".
Just to give more details it's often doing this with "big submarines", but well actually we don't need a big sub to make them disconnected, sometimes it's doing this with shuttles or small submarines... We often need to re-launch the current "round" (of the campaign) or to create a new server to try to make it work (if it works).

One of my friends sent me his errors, sorry but he didn't screenshot the console. Next time I'll ask him for the console too.

![image](https://user-images.githubusercontent.com/25408400/96333115-5b56f200-1068-11eb-8717-f410e71cbe1a.png)
![image](https://user-images.githubusercontent.com/25408400/96333121-60b43c80-1068-11eb-8ad6-83037c310613.png)


 **_I'm self-hosting the server and all of us are on the stable version by the way._**

**Comment by WharkOddity** [comment]
Just a little quite note on that, but this is more related to "when we already created and started a campaign", well I hope it will help...

With my friends we tried to play together without the problem of disconnecting in some ways... 

### We found out that the game was loading correctly without disconnecting anyone when:

**Lobby > campaign outpost
Lobby > campaign missions**

### _But_

**Campaign outpost > mission 
Campaign missions > outpost**

cause everyone to be kicked by an error like this. 
The game is like disconnecting them before loading anything or because the load will be too long.


_So each time someone or everyone get disconnected, I have to go back in the lobby, wait for them to rejoin the server and start from the lobby to load the campaign missions/or outposts map._

**Comment by WharkOddity** [comment]
^_Probably related to #4183 but I don't think becausewe have this problem since the many updates of barotrauma._

**Comment by seyrenk** [comment]
I'm having the same problem, and it kicks me out of the multiplayer lobby whenever I join one.
If I'm lucky enough to join the lobby, then the game will kick me out on the loading screen.
It happens on ALL occasion, I have reinstalled Barotrauma thrice, and verified integrity of game files on steam.
Any advise?

![image](https://user-images.githubusercontent.com/51757250/103168219-41a60800-486c-11eb-8016-9940b78bb4ee.png)
![image](https://user-images.githubusercontent.com/51757250/103168224-5a162280-486c-11eb-998b-f47dbb47c1e9.png)

**Comment by Kyleffox96** [comment]
Has there been any movement with this bug? I am having the same issue as "seyrenk" as soon as I launch click launch Campaign it kicks anyone else in the lobby and gives them the "source array error". I have tried posting about it on the steam forums but have not gotten a reply. This is the first time I have seen someone else mention the issue so I guess it us not widespread.

**Comment by Kyleffox96** [comment]
So I managed to find a fix to this issue. For me it was being caused by a program called Gamefirst VI that comes pre installed with ASUS. When ever you start a game the program tried to optimise the network with a pop up, removing the software fixed the issue for me.

**Comment by Regalis11** [comment]
I added some more info to the error message in https://github.com/Regalis11/Barotrauma-development/commit/501920495517ab48a4da37904b986e792b44c75f to hopefully help us get to the bottom of this.

**Comment by cshingle** [comment]
> I recently helped diagnose a similar error on another person's computer, and the solution was to remove Gamefirst VI, as with Kyleffox96's solution. Due to the error message and the nature of the program causing the error, it seems likely that the cause of the issue is a network optimization program improperly setting MTU too low for Barotrauma, or setting it lower after Barotrauma has already cached the MTU at startup (if that even occurs).

@flarespeed Good god, what kind of monster would create a program that changed the MTU and then trick people into installing it on their computer? Did they charge crypto to remove it?

**Comment by flarespeed** [comment]
> @flarespeed Good god, what kind of monster would create a program that changed the MTU and then trick people into installing it on their computer? Did they charge crypto to remove it?

It's called manufacturer installed bloatware, AKA "software we developed that we couldn't find a way to sell, so we'll shovel it into an unsuspecting customer's new computer"

**Comment by Regalis11** [comment]
Related ticket: https://github.com/Regalis11/Barotrauma-development/issues/4335
