### ISSUE TITLE
Microphone isn't working 

### ISSUE THREAD

**Issue by mshebatin** [FakeFishGames/Barotrauma#5650]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
micro isnt working mac os mojave 

**Steps To Reproduce**
The green line of volume is full all the time 

**Additional information**
<img width="1280" alt="Снимок экрана 2021-04-29 в 23 07 25" src="https://user-images.githubusercontent.com/56454169/116612353-1d545800-a940-11eb-958b-ebe49f8c304a.png">

**Comment by mshebatin** [comment]
i try all, what i can, i turn on/off micro, barotrauma, steam, mac

**Comment by BurykinNikolay** [comment]
same problem

**Comment by vladplasmius** [comment]
Same issue, tried following the instructions from another post (disabling permissions, uninstalling then reinstalling and giving permission access to mic again) and mic still does not work, shows the same green line

**Comment by ciriousjoker** [comment]
Reinstalling seems to have fixed the issue for me

**Comment by itchyOwl** [comment]
Seems to have been fixed. Closing.
