### ISSUE TITLE
[Modding] Overriding submarine features reset their parameter values to default

### ISSUE THREAD

**Issue by Alca-teia** [FakeFishGames/Barotrauma#5893]
Hi. I'm a mod developer, and I'm currently facing major issues in my mod, [Sounds of Europa](https://steamcommunity.com/sharedfiles/filedetails/?id=2347002377l). When I override the submarine nav terminals, fabricators, junction boxes, etc, their custom parameters are reset to default, creating an amalgamate of issues in most custom submarines. Also facing similar issue from this #4214 and this #2355. Any known workaround to this issue?

**Game version 0.13.3.11**

**Comment by Regalis11** [comment]
Hello and thank you for the report!

Some properties of the items are intentionally reset to default - it would be difficult to modify items if overriding them still kept all the properties unchanged. There's most likely still some properties that we shouldn't change though: the buttons in the nav terminal are a good example and should now be fixed. I took a quick look at overriding the nav terminals, fabricators and junction boxes using the Trick or Trauma mod as a test case, but I couldn't spot any obvious problems with them.

Could you give some examples of the properties that you'd expect to be kept unchanged? Thank you in advance, and sorry for the inconvenience!

**Comment by Alca-teia** [comment]
> Hello and thank you for the report!
> 
> Some properties of the items are intentionally reset to default - it would be difficult to modify items if overriding them still kept all the properties unchanged. There's most likely still some properties that we shouldn't change though: the buttons in the nav terminal are a good example and should now be fixed (see #4214). I took a quick look at overriding the nav terminals, fabricators and junction boxes using the Trick or Trauma mod as a test case, but I couldn't spot any obvious problems with them.
> 
> Could you give some examples of the properties that you'd expect to be kept unchanged? Thank you in advance, and sorry for the inconvenience!

Have you tried out my mod?? The nav terminal labels still break from overriding apparently. I've seen it happen to different submarines before. Did a short test on the Dugong early this morning. There are a lot of issues to point out and I don't have time to do a diligent rundown for now. People's comments on my mod page can give insight on other issues in detail too, so you can get more info from there. With all that said, here's the most obvious issues I've been able to point out this morning.

![signallabelsbug](https://user-images.githubusercontent.com/51012337/119866167-e481b180-bef2-11eb-879e-131505d983d5.gif)
Tested on vanilla Dugong.
![Untitled01_000000](https://user-images.githubusercontent.com/51012337/119866837-9caf5a00-bef3-11eb-99be-9f7c6b3a9ed8.png)
![image](https://user-images.githubusercontent.com/51012337/119867030-cec0bc00-bef3-11eb-8f89-9bbbab3f8d35.png)
Tested on RainDreamer's [Nova VX](https://steamcommunity.com/sharedfiles/filedetails/?id=2259833357&searchtext=nova+vx). Basically, override resets custom scale values to default (0.5 to most objects).
