### ISSUE TITLE
Terminal input length hardcoded to 200 characters.

### ISSUE THREAD

**Issue by UzricRash** [FakeFishGames/Barotrauma#6410]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Unlike other electrical components, the terminal's input is limited to 200 characters and there is no GUI options to change that.

**Steps To Reproduce**
Open the editor, connect a signal component with an output bigger than 200 characters to the terminal and trigger that with a button or something. The output in the terminal will be cut even if the signal component is edited to output the full length.

**Version**
Windows 0.14.6.0

**Additional information**
*https://github.com/Regalis11/Barotrauma/blob/master/Barotrauma/BarotraumaShared/SharedSource/Items/Components/Signal/Terminal.cs*, lines 10 and 64.

**Comment by mygamingaccount** [comment]
Seems like a reasonable limit?

**Comment by PaladynMinak** [comment]
Please, add option to set terminal max output length. Also for relay, delay, wifi and others if they have hidden limit too. 
I wish to create terminal similar to command prompt, with few commands for switching or setting things and few commands providing informations, namely HELP for list of commands with short descriptions, GUIDE for descriptions of mechanisms and maybe few more. I could make it with multiple regexs for each, but that would cause stupid looking formatting.
