### ISSUE TITLE
can't alt tab out of game in loading screen

### ISSUE THREAD

**Issue by Tsunder** [FakeFishGames/Barotrauma#6512]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Can't alt tab out of the game focus for part of the start-up sequence of baro, and sometimes other screens (loading round?)

**Steps To Reproduce**
1. start baro
2. try to alt tab

**Version**
0.14.9

**Additional information**

**Comment by itchyOwl** [comment]
Seems to work properly now in win 11: I'm able to alt+tab to switch to another window. Works the same during the splash screens, loading, and in the main menu after the loading.

Moving to candidates for removal, because I think this has been solved.
