### ISSUE TITLE
[Modding] Conditional sprites on certain limbs do not use the specified texture path

### ISSUE THREAD

**Issue by Working-Joe** [FakeFishGames/Barotrauma#7043]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
If one adds a ConditionalSprite to Limbs that use gender or race specific sprites, specifying a texture path for the ConditionalSprite's Sprite does nothing. Instead, the texture path specified on the sprite for the limb is used.

**Steps To Reproduce**
The problem at least occurs when one adds a conditional sprite to a Human limb that has gender or race related sprite. 

For instance, if one adds
```xml
<conditionalsprite target="Character">
	<conditional affliction="gt 0"/>
	<sprite name="spritename" texture="Mods/Mod Name/Characters/Human/ConditionalSprite.png" sourcerect="0,0,128,128" depth="0.4"/>
</conditionalsprite>
```
to the head Limb in Human.xml to get

![image](https://user-images.githubusercontent.com/50582661/139121198-de85e4b3-6e3e-4fcf-864e-e412fdaa7755.png)

the specified texture is not used. Instead, the texture path in the main sprite is used: 

![image](https://user-images.githubusercontent.com/50582661/139119734-fa99d56f-057f-4b54-a03e-8ff873978d34.png)
_what are you looking at?_

**Additional Information**
I have not extensively tested this on other (non-)humanoid characters or limbs. I suspect it is jsut a side effect of how (or more specifically when) Limb.cs parses texture paths human Characters with different sprites for different races and genders.

**Version**
Windows v0.15.12.0

**Comment by Regalis11** [comment]
It seems this method has been completely rewritten since the ticket was created, need to test and check if this is still an issue.

**Comment by Regalis11** [comment]
Seems to still be an issue. Fixed in https://github.com/Regalis11/Barotrauma-development/commit/07b3cb8aedbb5beeb97d23c170c299f82342e2a4

**Comment by Regalis11** [comment]
Merged, closing
