### ISSUE TITLE
Map does not generate based on shuttle 

### ISSUE THREAD

**Issue by Yowbaby** [FakeFishGames/Barotrauma#7046]
Some map does not generate based on shuttle that is docked to the side (docking port) of the main submarine. 
![BF39D29F-BECB-46BC-A5A3-F03DAC3AE98C](https://user-images.githubusercontent.com/93289071/139140795-24075d70-f0c5-41e8-af83-cc52bc70e6db.png)
In some cases, the shuttle is clipped inside the walls of the map.

**Comment by Regalis11** [comment]
This seems to have been fixed by the changes in https://github.com/FakeFishGames/Barotrauma-development/pull/4495 (PR in our private repo which improved the outpost placement logic)
