### ISSUE TITLE
no living players left connected  dedi server stys in limbo, round never ends. "("Ending round (entire crew dead)" 

### ISSUE THREAD

**Issue by JoneKone** [FakeFishGames/Barotrauma#7121]
- [X] I have searched the issue tracker to check if the issue has already been reported.

**Description**
If a dedicated server is configured to have unlimited re spawn shuttle time and it is meant to never have a second re spawn shuttle, ppl disconnect and the round is never ended by the last alive person. The server will get caught in limbo, round never ends and no normal player can vote end round. You need an admin to manually end the round.

**Steps To Reproduce**
![20211101164347_1](https://user-images.githubusercontent.com/1114115/139695936-4bba74b9-2663-4167-a0b4-463a4d970c26.jpg)

configure your server like this.
Re spawn 10 sec, Unlimited time for re spawn shuttle. Then kill your self 2 times. You are now in limbo.

**Version**
0.15.12.0

**Additional information**

![Screenshot from 2021-11-01 16-27-37](https://user-images.githubusercontent.com/1114115/139695028-8027c520-169a-4e15-806f-5872dfd88a16.png)
This round never ended on the server as the ppl disconnected and when a new guy connects he can't have end round button as he was never alive.

Referring to this https://github.com/Regalis11/Barotrauma/issues/1319

**Comment by Rokvach** [comment]
Tested, working correctly. Can be merged and closed.
