### ISSUE TITLE
Issues with overrided characters' animations when enabling and disabling a mod

### ISSUE THREAD

**Issue by Emanthealmighty** [FakeFishGames/Barotrauma#7467]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
When disabling a mod which overrides a character, said character will keep using the animations from the now disabled mod when tested in the character editor or spawned in game (both singleplayer and multiplayer).

If the character is loaded in-game or in the character editor prior to enabling the mod, then, after enabling the mod, the character will keep using the unmodded animations.
The outcome seems to vary depending on whether the character is a humanoid or not.

**Version**
0.15.13.0 Windows

**Additional information**
[This](https://drive.google.com/drive/folders/14ySVcYJvvdFn6tIgJwa9BCKNBjjYHwOA?usp=sharing) is the mod I've used to test this issue. It contains an overrided human and crawler which have the same ragdolls as normal but have modified walking and running animations.

**Comment by Danielkaas94** [comment]
I think I have the same problem, it is very noticeable when walking with a flashlight without aiming it or using ladders 🔦

**Comment by itchyOwl** [comment]
Might have been fixed by the latest changes to the animation loading and caching. Moving to QA.

**Comment by NilanthAnimosus** [comment]
Tested against release/summer-update commit https://github.com/FakeFishGames/Barotrauma-development/commit/61e5eeddabf6ffcfa9e4e8ad54d7d086b0640d7f on Release build. no issues found.

overriding characters and their animation files appears to work perfectly fine now, before or after using the character editor with that character, and when enabling or disabling the mod when looking in the character editor. same should occur in game too.

Overrides with mods when enabling and disabling content does not appear to cause any lingering effects anymore.
