### ISSUE TITLE
Escort/transport missions may have empty node as a destination

### ISSUE THREAD

**Issue by ghost** [FakeFishGames/Barotrauma#7497]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Occasionally, escort / transport / haul people missions might end up having empty node as a destination.
Which looks borderline silly: the sub arrives, the captain dumps passengers from the hatch, the sub swims away like a boss.
Had it reproduced at once with both usual and triggerable-by-conversation (i. e. mudraptor boy) quests.
The former's description states that the destination is 'nearest station' - yet the station in question is nowhere to be seen. . .

**Steps To Reproduce**
Synthetic steps to reproduce:
1. Generate a world map at which the only outgoing route from sub's starting position is an empty, outpost-less node.
2. Force only escort/people hauling quests availability.
3. Load the save, schmooze with outpost dwellers, grab quests.
4. Set sail on a quest of hauling people to nowhere. . .

**Version**
Latest Steam release.

**Additional information**
Do note that Tectamus Linea is an empty node (1st screenie) yet both hauling quests have it as a destination (2nd screenie).
![20211126195351_1](https://user-images.githubusercontent.com/81986452/143619200-20d1ca7b-da8b-401f-a9dd-e0c602261235.jpg)
![20211126195457_1](https://user-images.githubusercontent.com/81986452/143619211-b625a634-e6bf-49ef-98bf-2a9d8a37c05c.jpg)
Due to a series of rather outrageous brain farts, I forgot to write the seed down. . .

**Comment by StruggleDuck** [comment]
I can confirm this bug does still exist, as I have recently experienced this exact issue, but I unfortunately also have forgotten to save the seed.

**Comment by Regalis11** [comment]
Related ticket: https://github.com/Regalis11/Barotrauma/issues/3425

**Comment by ubertpendragon** [comment]
![image](https://user-images.githubusercontent.com/73229309/218220031-6ebe2701-3360-4565-b76e-107c0caac5bc.png)

**Comment by Regalis11** [comment]
The missions can also end up choosing an outpost belonging to the opposing faction as the destination: https://github.com/Regalis11/Barotrauma/issues/11338

**Comment by itchyOwl** [comment]
Moved to backlog for re-evaluating. I think we should address this somehow.

**Comment by Regalis11** [comment]
Addressed in https://github.com/FakeFishGames/Barotrauma-development/commit/665800bf841e3733ea0c9f0df1799ecb5c1c6a11

> Finally fixed escort and cargo missions that lead to locations with no outpost. It seems that we had a field called requiredDestinationTypes in scripted events, which we can use to prevent the mission events from triggering if there's no adjacent outposts. https://github.com/FakeFishGames/Barotrauma/issues/7497
> 
> Also added support for configuring the required destination as "anyoutpost", and to make things easier for modders, location types with an outpost can be marked as being excluded from "any outpost" (so if you want to have lets say husk cult locations, you can disable cargo/escort missions into those).
