### ISSUE TITLE
Bots - Crew members does not ignore Prisoners that are in a hull that they can't get into

### ISSUE THREAD

**Issue by Kaillera** [FakeFishGames/Barotrauma#7729]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
![Capture](https://user-images.githubusercontent.com/5086682/145692026-31eca66c-9dd1-49f1-b4cd-a09e3fc0bf2e.PNG)

Crew members does not ignore Prisoners that are in a hull that they can't get into. Fight Intruder orders will keep on trying to get to these prisoners by continuously walking into the door. These prisoner cells have buttons that are a bit far from the door, so they won't be able to open it.

**Steps To Reproduce**
1. Prisoner Transport Mission.
2. Have crew members on Fight Intruder
3. Put Prisoners into cells
4. Wait until Prisoners takes their handcuffs off
5. Observe

**Version**
~0.15.20.0

**Comment by itchyOwl** [comment]
I tested it on Humpback, welding a door shut, but I can't repro the issue: instead the guard stays still and tells that he can't reach the target (as expected).

Do you have a save or the sub file? The guards probably think they can go through the doors, but somehow fail if the button is far.

![image.png](https://images.zenhubusercontent.com/5c93b12055cf186934fc0a03/1c751f8b-89f0-4540-8cdc-15a229118ae5)

**Comment by Kaillera** [comment]
> I tested it on Humpback, welding a door shut, but I can't repro the issue: instead the guard stays still and tells that he can't reach the target (as expected).
> 
> Do you have a save or the sub file? The guards probably think they can pass the doors, but somehow fail if the button is far.
> 
> ![image.png](https://camo.githubusercontent.com/74ad29cd0e900a8afb5531205e934b4615d81c3bead63b0f1fef58f64eb563f3/68747470733a2f2f696d616765732e7a656e68756275736572636f6e74656e742e636f6d2f3563393362313230353563663138363933346663306130332f31633735316638622d383966302d343534302d386364632d313561323239313138616535)

Yep the buttons are intentionally far in this sub: https://steamcommunity.com/sharedfiles/filedetails/?id=2683155573

**Comment by Regalis11** [comment]
I was able to repro this by replacing the door to Humpack's armory with a buttonless one and wiring it to a button in another room.

**Comment by Regalis11** [comment]
The problem I had in Humpback seemed to be that the waypoint wasn't linked to the door, fixing that go rid of the issue. I was able to repro this in 50L1-TUD3 though: there the button is in the same room, but too far for the bot to reach when they're standing by the door. We only mark the path as unreachable if there's something blocking the way to the button, which doesn't happen in this case, so the bot'll get stuck walking against the door and trying to find a button to press.

Need to think about how to address this: we could maybe make the bot navigate to the button, but that's not trivial to implement. We could also make the bots mark the path as unreachable if the button is too far to interact with, but ideally I think the bots should be able to figure out how to use doors like this.

![image](https://user-images.githubusercontent.com/14351070/153173577-2d33f517-cc06-4be0-8808-b84dbc103def.png)

**Comment by Kaillera** [comment]
The actual intention of the buttons being too far in this case was to keep bots interaction away from it. If otherwise can we set whether or not buttons are ignored by AI?

**Comment by itchyOwl** [comment]
Here's a related issue: the bots think they can open those doors, but can't use those buttons, as they are too far.

![image](https://user-images.githubusercontent.com/5370738/219429098-1bdae348-2937-46a4-b3a9-4c16fa0ad84d.png)

![image](https://user-images.githubusercontent.com/5370738/219429247-2a7ab26e-3717-446f-b63f-7c387ba3be59.png)
