### ISSUE TITLE
Creatures can charge through terrain and become stuck

### ISSUE THREAD

**Issue by Jaco909** [FakeFishGames/Barotrauma#7923]
- [Yes] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Crawlers (or potentially other small creatures) can clip into terrain and become stuck, forcing you to restart missions.

**Steps To Reproduce**
Unknown, though I believe it was from the creature moving at high speed towards the terrain (see below).

**Version**
v0.15.22.1 Windows

**Additional information**
While trying to get it un-stuck, it would sometimes try to charge at me (or the submarine). This charge would move it slightly through the terrain. It could be that while running away from railgun fire, it charged directly into the terrain below it and became stuck.
![in_terrain](https://user-images.githubusercontent.com/4472340/147338044-84744156-a918-46c8-8ddb-46bb82f90c58.jpg)
![sonar](https://user-images.githubusercontent.com/4472340/147338239-82b5e3f9-05e7-4b9c-9ece-5a55ad7b5174.jpg)

**Comment by MaaiG** [comment]
> I believe it was from the creature moving at high speed towards the terrain (see below).

Yeeea! Very high speed https://github.com/Regalis11/Barotrauma/issues/7635  :)

But maybe its still something like that https://github.com/Regalis11/Barotrauma/issues/4875

**Comment by WrillWasTaken** [comment]
Experienced possibly the same issue just now with a tiger thresher:
![image](https://github.com/Regalis11/Barotrauma/assets/86113712/1693c9b1-795e-461d-9afd-92e0b4f800fd)
Occured in missions mode on the following seed:
![image](https://github.com/Regalis11/Barotrauma/assets/86113712/3c14fbc6-460d-4dcd-abd8-3498f5bee3e7)

**Comment by itchyOwl** [comment]
In single player, I've noticed that at least limbs can get stuck in the walls when they are moved with high velocities. This can be solved case by case by reducing the forces. But that shouldn't cause the entire creature to get stuck inside the walls, which is the case here. There shouldn't be high enough forces applied on monsters to make them get stuck in the walls like that. I've also occasionally seen creatures getting spawned inside the walls, but that hasn't happened for a while now.

Moving this in QA investigates. We need better repro steps to be able to fix this. And if it's extremely rare, we could just as well close the ticket.

**Comment by Jasontti** [comment]
Tried to reproduce this with tiger threshers and hammerheads in different levels.
Main hunch was these types of sharp inwards corners where hitbox could clip in terrain.
![2024-11-27_11-30](https://github.com/user-attachments/assets/938b9cc9-2dac-4dd0-b1b9-ac442f8e6644)

As @itchyOwl said, this might be so rare case that needs some really specific level and spawning requirements.
Closing this for now.
