### ISSUE TITLE
Texture for Shell A 18 Degrees cutoff and as such doesnt fit to other shell parts

### ISSUE THREAD

**Issue by Zetabite** [FakeFishGames/Barotrauma#8695]
- [X] I have searched the issue tracker to check if the issue has already been reported.

**Description**
The texture for "Shell A 18 Degrees" is cutoff, meaning, at its bottom/top (depending on Y Mirror), its missing parts of its texture, so that it doesnt correctly fit to other shell parts.

**Steps To Reproduce**
1. Open Submarine Editor
2. Build Shell A 18 Degrees
3. Add another Shell and fit it to it
4. See that Shell A 18 Degrees doesnt fit to them

**Version**
0.16.7.0 Linux

**Files**
Shell 18 A Degrees on the right:
![image](https://user-images.githubusercontent.com/25250463/161296316-e22c4806-0d35-4d2d-95ce-f020ae7d2d25.png)

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/4a1c28c2be77449eac8bc94c44515d1b6d413d67

**Comment by Rokvach** [comment]
Tested, no issues. Closing.

**Comment by itchyOwl** [comment]
Is this fixed or not?

**Comment by Regalis11** [comment]
No, based on the commit history I reverted the change because adjusting the dimensions of the structure caused issues in existing subs.
