### ISSUE TITLE
Game freezes when Initializing GameAnalytics

### ISSUE THREAD

**Issue by Jade-Harleyy** [FakeFishGames/Barotrauma#8754]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
About 1 minute after opening the game, the game freezes for 2-3 minutes while GameAnalytics is initializing.

**Version**
Windows v0.16.7.0

**Additional information**
I still receive this issue in all of these situations:
- GameAnalytics is turned ON
- GameAnalytics is turned OFF
- GameAnalytics.NetStandard.dll is deleted

**Comment by Jade-Harleyy** [comment]
Another note - this has been happening to me ever since GameAnalytics was added to Barotrauma.

**Comment by itchyOwl** [comment]
Old ticket with not much info. Might still happen, but could also be stale. Moving to candidates for removal.
