### ISSUE TITLE
Game hates when headphones are unplugged 

### ISSUE THREAD

**Issue by Dbat2** [FakeFishGames/Barotrauma#8796]
**Description**
If headphones are unplugged and then plugged back in anytime when the game is running, then the game will refuse to play audio   until Barotrauma is shutdown and re-launched. The audio settings claim that the headphones are indeed reconnected, but no matter what there is no sound and it cannot pick up the mic. 
![image](https://user-images.githubusercontent.com/91236493/163025621-12c034c6-2765-441a-994a-151c178387d6.png)

**Steps To Reproduce**
Launch Barotrauma, and then unplug your headset/headphones. Plug your headphones back in and then you shouldn't be able to hear audio again until the game is re-launched. It may help if you change your computer's sound settings to only input and output through the headset.

**Version**
Unstable V0.17.9.0

**Additional information**
Found an additional report about this on Steam forums, so it likely isn't an issue exclusive to unstable. https://steamcommunity.com/app/602960/discussions/0/3279191623123162823/

**Comment by Damjdu** [comment]
I have the same problem but you must not relaunch the game necessarily.
If you unplug and then plugin your headset
You can temporary solve it by:

- Going to settings
- Audio & Voice Chat.
- Change to your default output.
- Change back to Headset output.
- Apply
![For issue 1](https://github.com/Regalis11/Barotrauma/assets/88905360/309d7aee-60ac-4a62-a8a3-442e6ae34608)
![For issue 2](https://github.com/Regalis11/Barotrauma/assets/88905360/fcf9315b-f46a-492c-a440-1a9124401431)
![For issue 3](https://github.com/Regalis11/Barotrauma/assets/88905360/2fdc1258-9beb-4461-8156-12786486a5d2)
