### ISSUE TITLE
Need better way to retrieve harpoons stuck to mobs.

### ISSUE THREAD

**Issue by CurePindal** [FakeFishGames/Barotrauma#9493]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

When shooting harpoons at mobs they stick into the (dead) mob. And theres no solid way to retrieve them until they drop off after a while? Also they dangle around a lot and create more, unneeded physics interactions.

Expected behaviour: Being able to retrieve harpoons stuck in (dead) mobs in a better way (maybe make stuck harpoons show up in the monster mobs inventory?)

### Reproduction steps

1. shoot harpoon at mob, mob dead.
2. harpoon sticks to the mob
3. How do I retrieve it now manually?

### Bug prevalence

Happens every now and then

### Version

Other

### -

any.

### Which operating system did you encounter this bug on?

Windows

**Comment by deltanedas** [comment]
also very hard to retrieve from the floor if you miss, due to tiny hitbox and already being hard to spot.

this is even worse if you have high latency, then the harpoons will fly around and you have to really spam click to have a chance of picking them up

**Comment by Ek-Videogames** [comment]
If this is with "Improved Keybinds" too there is a high chance of accidentally grabbing the creature instead of the harpoon.

**Comment by Regalis11** [comment]
I would say the new "interaction labels" added in the unstable branch solve this issue.
