### ISSUE TITLE
Overridden character variants don't properly reflect their multipliers.

### ISSUE THREAD

**Issue by Emanthealmighty** [FakeFishGames/Barotrauma#9651]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [X] My issue happened while using mods.

### What happened?

When overriding a variant of a character, its various multipliers such as ragdoll scale and attack multipliers won't have an effect on it.
``` xml
<Override>
  <Charactervariant inherit="Crawler" speciesname="Crawler_large" speciestranslationoverride="Crawler" usebosshealthbar="true">
    <health vitality="1000"/>
    <ai combatstrength="160" avoidgunfire="False">
      <!--Disables latching-->
      <chooserandom>
        <clear/>
      </chooserandom>
    </ai>
    <ragdoll scalemultiplier="1.3"/>
    <attack damagemultiplier="25" rangemultiplier="1.3" impactmultiplier="1.3" />
  </Charactervariant>
</Override>
```
For example, everything defined in this overridden variant of the crawler (crawler_large) will work as expected, except for the ragdoll and attack multipliers. The crawler will properly have a lot more health, and also present a boss health bar, but its damage and scale will simply remain the same as its inherited's.
[Testcrawl.zip](https://github.com/Regalis11/Barotrauma/files/9201019/Testcrawl.zip)

### Bug prevalence

Happens every time I play

### Version

0.18.15.0

### Which operating system did you encounter this bug on?

Windows

**Comment by shangjiaxuan** [comment]
This is because of `Barotrauma/BarotraumaShared/SharedSource/Characters/Params/Ragdoll/RagdollParams.cs` line 393-407 in master branch:
```
        public void ApplyVariantScale(XDocument variantFile)
        {
            if (variantScaleApplied) { return; }
            if (variantFile == null) { return; }
            var scaleMultiplier = variantFile.Root.GetChildElement("ragdoll")?.GetAttributeFloat("scalemultiplier", 1f);
            if (scaleMultiplier.HasValue)
            {
                JointScale *= scaleMultiplier.Value;
                LimbScale *= scaleMultiplier.Value;
            }
            variantScaleApplied = true;
        }
```
The scale and others directly work with the xml document, assuming root element is the character, but for override variants the root element is an <override/>. I would suggest changing the parameter to ContentXElement, but will likely result in multiple files changed.
