### ISSUE TITLE
Crew list is shown in reverse team order for spectators

### ISSUE THREAD

**Issue by Tsunder** [FakeFishGames/Barotrauma#9793]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

the [C]rew list (left side) is shown in reverse team order for spectators in PVP

expected is that the order matches the tab/server info menu order, so coalition first/ top to bottom. instead, it shows renegade first, from bottom towards top.

### Reproduction steps

1. start pvp with like 4 or more people (2 per team)
2. spectate
3. open C crew list

### Bug prevalence

Happens every time I play

### Version

0.18.15.1 / 0.18.15.2 on macOS

### Which operating system did you encounter this bug on?

Windows

**Comment by Tsunder** [comment]
Example: (spectating from start of round, not mid-round joining)
![image](https://user-images.githubusercontent.com/5103517/188244895-7ca9590b-fa83-402b-9208-678f0f54eb86.png)

![image](https://user-images.githubusercontent.com/5103517/188244917-eaad0371-2da3-4cad-8ef8-6ad008b74ee0.png)

**Comment by Regalis11** [comment]
Fixed in https://github.com/FakeFishGames/Barotrauma-development/commit/c240ffcdda836c8b629e0807dadecdc7c35ae5fa
